BETA: Register laman .is-a.dev
is-a-dev/register pull request #10229
Opened 2023-12-20 20:15 UTC by Derogater

Added `laman .is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-12-20 20:21 UTC, Derogater commented
Testing a dev website.

2023-12-20 23:10 UTC, DEV-DIBSTER requested changes

2023-12-20 23:10 UTC, DEV-DIBSTER commented on domains/laman .json
No space allowed in domain name.

2023-12-20 23:10 UTC, DEV-DIBSTER commented on domains/laman .json
> +        "TXT": "laman"
TXT record alone doesn't do anything.

2023-12-21 04:07 UTC, Derogater commented on domains/laman .json
> +        "TXT": "laman"
What should be done then?

2023-12-25 01:28 UTC, closed without merging