Create norkart1.json
is-a-dev/register pull request #10308
Opened 2023-12-23 08:03 UTC by norkart1

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-12-23 08:06 UTC, norkart1 reviewed
H

2023-12-25 01:22 UTC, DEV-DIBSTER requested changes

2023-12-25 01:22 UTC, DEV-DIBSTER commented on domains/norkart1.json
> +        "CNAME": "personal-website-26y.pages.dev",
CNAME cannot be used in conjunction with other records and vice versa.

2023-12-26 05:04 UTC, closed without merging

2023-12-26 09:44 UTC, norkart1 commented
G