BETA: Register samdev.is-a.dev
is-a-dev/register pull request #10337
Opened 2023-12-24 00:33 UTC by sam-shot

Added `samdev.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-12-25 01:23 UTC, DEV-DIBSTER requested changes

2023-12-25 01:23 UTC, DEV-DIBSTER commented on domains/samdev.json
> +        "CNAME": "s"
Invalid CNAME, must be a valid hostname.

2023-12-25 09:39 UTC, sam-shot commented
Please i dont understand what should be there

2023-12-26 05:09 UTC, DEV-DIBSTER commented
> Please i dont understand what should be there

Should be a hostname. Like dibster.dev. Example is if I wanted dibster.is-a.dev to display the content from dibster.dev, I can set a CNAME to dibster.dev, dibster.is-a.dev will display the dibster.dev.

2023-12-29 23:54 UTC, closed without merging