BETA: Register nah.is-a.dev
is-a-dev/register pull request #10351
Opened 2023-12-24 11:24 UTC by HoaQuyingVN

Added `nah.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-12-24 11:32 UTC, HoaQuyingVN commented
Wait

2023-12-24 12:09 UTC, HoaQuyingVN reviewed
I changed

2023-12-25 01:19 UTC, DEV-DIBSTER requested changes

2023-12-25 01:19 UTC, DEV-DIBSTER commented on domains/share.nazi.json
Yeah.... absolutely not.

2023-12-25 01:21 UTC, DEV-DIBSTER commented
@phenax Requesting a ban from the repository due to anti-semitic domain name request.

2023-12-25 01:26 UTC, WilliamDavidHarrison requested changes

2023-12-25 01:26 UTC, WilliamDavidHarrison commented on domains/slag.json
This is a no as well.

2023-12-25 05:38 UTC, phenax commented
User has been banned

2023-12-25 05:38 UTC, closed without merging