BETA: Register smartcloud.is-a.dev
is-a-dev/register pull request #10364
Opened 2023-12-24 22:22 UTC by Smartlinuxcoder

Added `smartcloud.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-12-25 01:25 UTC, DEV-DIBSTER requested changes

2023-12-25 01:25 UTC, DEV-DIBSTER commented on package-lock.json
This file should not be touched.

2023-12-25 01:25 UTC, DEV-DIBSTER commented on .vscode/settings.json
This file should not be touched.

2023-12-26 19:44 UTC, Smartlinuxcoder commented on .vscode/settings.json
Ah, I see, my vscode created that file

2024-01-01 20:56 UTC, DEV-DIBSTER requested changes

2024-01-01 20:56 UTC, DEV-DIBSTER commented on package-lock.json
This file still needs to be restored.

2024-01-02 04:34 UTC, closed without merging