Create codwizer.json
is-a-dev/register pull request #10382
Opened 2023-12-25 09:06 UTC by Codwizer

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-12-25 16:04 UTC, DEV-DIBSTER requested changes

2023-12-25 16:04 UTC, DEV-DIBSTER commented on domains/codwizer.json
> +        "CNAME": "codwizer.github.io"
404 CNAME record.

2023-12-25 21:44 UTC, Codwizer commented on domains/codwizer.json
> +        "CNAME": "codwizer.github.io"
I'm only writing it so far.

2023-12-26 05:05 UTC, DEV-DIBSTER submitted a review, later dismissed

2023-12-26 05:07 UTC, DEV-DIBSTER approved these changes

2023-12-26 05:07 UTC, merged