Register mrjbadshah.is-a.dev
is-a-dev/register pull request #10391
Opened 2023-12-25 14:56 UTC by MRJ-Badshah

Added `mrjbadshah.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

2023-12-25 16:01 UTC, DEV-DIBSTER requested changes

2023-12-25 16:01 UTC, DEV-DIBSTER commented on domains/mrjbadshah.json
> +        "A": ["1.1.1.1"]
That's a DNS resolver. Invalid A record.

2023-12-25 16:01 UTC, DEV-DIBSTER commented on domains/ytdl.mrj.json
> +        "TXT": ""
TXT record alone doesn't do anything. It also has no value provided.

2023-12-26 12:55 UTC, MRJ-Badshah reviewed
updated

2023-12-27 06:00 UTC, closed without merging