Register Nithin.is-a.dev
is-a-dev/register pull request #10455
Opened 2023-12-27 13:06 UTC by nithinlycanz

Register Nithin.is-a.dev with CNAME record pointing to My personal website.

2023-12-28 02:22 UTC, hackermondev submitted a review, later dismissed
Invalid CNAME & you don't need a file in the root directory

2023-12-31 04:53 UTC, DEV-DIBSTER requested changes

2023-12-31 04:53 UTC, DEV-DIBSTER commented on domains/nithin.json
> +            "CNAME": "nithinlycanz.github.io/nithinlycanz"
Invalid CNAME, must be a valid hostname without /.

2024-01-01 17:28 UTC, DEV-DIBSTER approved these changes

2024-01-01 17:29 UTC, merged

2024-01-04 16:06 UTC, nithinlycanz commented
Thank you guys 😄.