Update almaz.json
is-a-dev/register pull request #10497
Opened 2023-12-29 09:50 UTC by AlmaziikDev

Add correct repo

2023-12-29 23:51 UTC, DEV-DIBSTER requested changes

2023-12-29 23:51 UTC, DEV-DIBSTER commented on domains/almaz.json
> +        "CNAME": "almaziikdev.github.io"
404 CNAME record.

2023-12-29 23:51 UTC, DEV-DIBSTER commented on domains/almaz.json
> +        "email": "almazgamer228@gmail.com",
Comma at the end is invalid.

2023-12-30 18:15 UTC, mtgsquad approved these changes, later dismissed

2023-12-31 04:54 UTC, DEV-DIBSTER commented on domains/almaz.json
> +        "CNAME": "almaziikdev.github.io"
Site is still unreachable.

2023-12-31 10:16 UTC, closed without merging