BETA: Register wade-cheng.is-a.dev
is-a-dev/register pull request #10525
Opened 2023-12-30 06:23 UTC by wade-cheng

Added `wade-cheng.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-12-31 04:46 UTC, DEV-DIBSTER requested changes

2023-12-31 04:46 UTC, DEV-DIBSTER commented on domains/wade-cheng.json
> +        "CNAME": "wade-cheng.is-a.dev"
Same hostname as the one being requested, invalid record.

2024-01-03 18:26 UTC, wade-cheng commented
Sorry about that. Hopefully this functions now?

2024-01-04 02:57 UTC, DEV-DIBSTER approved these changes

2024-01-04 02:57 UTC, merged