added: syofyanzuhad
is-a-dev/register pull request #1056
Opened 2021-08-21 15:26 UTC by syofyanzuhad

2021-08-21 16:45 UTC, TheBotlyNoob approved these changes

2021-08-21 16:46 UTC, TheBotlyNoob requested changes
We don't support `TXT` records

2021-08-22 13:22 UTC, hackermondev requested changes
CNAME cannot contain ``https://`` since it cannot be a link.

2021-08-25 19:07 UTC, hackermondev approved these changes

2021-08-27 11:04 UTC, TheBotlyNoob approved these changes

2021-08-27 11:04 UTC, merged