BETA: Register almaz.is-a.dev
is-a-dev/register pull request #10635
Opened 2024-01-02 11:29 UTC by AlmaziikDev

Added `almaz.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-01-02 21:18 UTC, DEV-DIBSTER requested changes, later dismissed

2024-01-02 21:18 UTC, DEV-DIBSTER commented on domains/almaz.json
> +        "CNAME": "almaziikdev.github.io"
Inaccessible website.

2024-01-02 21:35 UTC, DEV-DIBSTER commented on domains/almaz.json
> +        "CNAME": "almaziikdev.github.io"
Website is still inaccessible. Conversation is unresolved until the site is reachable.

2024-01-02 23:22 UTC, mtgsquad submitted a review, later dismissed
Port number cannot be added to the end of CNAME. Please use a proxy host in order to do so, this is possible by using Nginx Proxy Manager, and if your website is pure HTML, CSS, and JS files, you can use Hosting by is-a-dev, or for JavaScript Frameworks, use Cloudflare Pages.

2024-01-04 06:34 UTC, wdhdev approved these changes

2024-01-04 06:34 UTC, merged