Create parshnt
is-a-dev/register pull request #108
Opened 2020-10-09 07:15 UTC by parshnt

added me :)

2020-10-09 16:38 UTC, phenax approved these changes

2020-10-09 16:41 UTC, phenax requested changes

2020-10-09 19:55 UTC, parshnt commented
Hi @phenax 
I've renamed the file, kindly have a look :)

2020-10-12 12:20 UTC, phenax approved these changes

2020-10-12 12:20 UTC, merged