Register tr1xem.is-a.dev
is-a-dev/register pull request #10812
Opened 2024-01-06 16:37 UTC by tr1xem

Register tr1xem.is-a.dev with TXT record pointing to 7bf3c01b64e04e87d52e935076aa7a.

2024-01-07 03:44 UTC, DEV-DIBSTER requested changes

2024-01-07 03:44 UTC, DEV-DIBSTER commented on domains/tr1xem.json
> +            "TXT": "7bf3c01b64e04e87d52e935076aa7a"
TXT record alone doesn't do anything.

2024-01-07 04:46 UTC, tr1xem commented on domains/tr1xem.json
> +            "TXT": "7bf3c01b64e04e87d52e935076aa7a"
Can you delete it?

2024-01-08 08:58 UTC, SX-9 requested changes
invalid format

2024-01-08 08:58 UTC, SX-9 commented on domains/it.json
> +             "TXT": [
invalid txt record (txt can only be string) and txt alone isnt enough

2024-01-08 09:39 UTC, SX-9 commented
closing this as it is the same as #10877

2024-01-08 09:39 UTC, closed without merging