Register pratham-gupta.is-a.dev
is-a-dev/register pull request #10949
Opened 2024-01-09 18:15 UTC by shygamer123

Register pratham-gupta.is-a.dev with CNAME record pointing to 69.30.249.53.

2024-01-09 18:24 UTC, CuteDog5695 requested changes

2024-01-09 18:24 UTC, CuteDog5695 commented on domains/pratham-gupta.json
> +            "CNAME": "69.30.249.53"
wrong record, change CNAME to A

2024-01-09 18:28 UTC, shygamer123 commented on domains/pratham-gupta.json
> +            "CNAME": "69.30.249.53"
okay

2024-01-09 18:38 UTC, CuteDog5695 approved these changes
seems good to me now, wait for a maintainer to merge it then you have the domain

2024-01-09 18:43 UTC, CuteDog5695 requested changes
wait nvm add [] to the numbers, sorry. forgot about that

2024-01-10 09:31 UTC, SukiPlayz commented
@shygamer123  your json file should look like this:
```json
{
    "owner": {
            "username": "shygamer123",
            "email": "gpratham522@gmail.com",
            "discord": "840244590870003762"
        },
        "record": {
            "A": ["69.30.249.53"]
        }
    }
```

update to that^^

2024-01-10 09:56 UTC, SukiPlayz approved these changes

2024-01-10 12:44 UTC, iostpa approved these changes
looks good to me now

2024-01-11 21:08 UTC, DEV-DIBSTER approved these changes

2024-01-11 21:08 UTC, merged