BETA: Register khaidev.is-a.dev
is-a-dev/register pull request #11070
Opened 2024-01-13 11:41 UTC by TruongDuyKhai

Added `khaidev.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-01-13 17:31 UTC, CuteDog5695 requested changes

2024-01-13 17:31 UTC, CuteDog5695 commented on domains/khaidev.json
> +        "email": "truongduykhai1012@gmail.com",
Remove the comma after email

2024-01-13 18:24 UTC, VaibhavSys commented on domains/khaidev.json
> +        "email": "truongduykhai1012@gmail.com",
```suggestion
        "email": "truongduykhai1012@gmail.com"
```

2024-01-14 05:00 UTC, DEV-DIBSTER approved these changes

2024-01-14 05:01 UTC, merged