BETA: Register alf.is-a.dev
is-a-dev/register pull request #11086
Opened 2024-01-14 04:11 UTC by alfonsop123

Added `alf.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-01-14 05:10 UTC, DEV-DIBSTER requested changes

2024-01-14 05:10 UTC, DEV-DIBSTER commented on domains/alf.json
> +        "CNAME": "gv-gybmprmm6adobi.dv.googlehosted.com"
No site content. Unable to reach.

2024-01-14 05:10 UTC, DEV-DIBSTER commented on domains/asddsadasads.json
> +        "TXT": "google-site-verification=wwoshgzb1e_med696nh0rsnw8pzzmbkmor-94rscdr0"
TXT record alone doesn't do anything.

2024-01-14 05:10 UTC, DEV-DIBSTER commented on domains/test.json
Domain will not be released due to abuse risk.

2024-01-14 05:10 UTC, closed without merging

2024-01-23 01:55 UTC, alfonsop123 commented on domains/test.json
bro what this is for myself but it said i had to verify it on google sites and the dashboard never loaded the alf.is-a.dev

2024-04-22 02:28 UTC, alfonsop123 commented
Hello