Create discusser.json
is-a-dev/register pull request #11110
Opened 2024-01-14 11:32 UTC by Discusser

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://discusser.github.io/ (the website is subject to change soon)

2024-01-14 12:37 UTC, CuteDog5695 requested changes

2024-01-14 12:37 UTC, CuteDog5695 commented on domains/discusser.json
> +        "email": "noobly321growing@gmail.com",
remove comma line after email

2024-01-14 12:40 UTC, CuteDog5695 approved these changes
its good now

2024-01-15 01:51 UTC, DEV-DIBSTER approved these changes

2024-01-15 01:51 UTC, merged