Add MX, TXT Records
is-a-dev/register pull request #11156
Opened 2024-01-15 06:16 UTC by ukrioo

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-01-16 13:58 UTC, SX-9 approved these changes

2024-01-16 13:58 UTC, SX-9 commented on domains/email.json
> +        "URL": "https://ukrioo.github.io/"
note: we are having issues with url record so if its not working as expected contact on discord

2024-01-17 00:25 UTC, DEV-DIBSTER requested changes

2024-01-17 00:25 UTC, DEV-DIBSTER commented on domains/email.json
Will not release this domain as it has the potential for abuse.

2024-01-17 00:25 UTC, DEV-DIBSTER commented on domains/secret.json
Will not release this domain as it has the potential for abuse.

2024-01-17 00:25 UTC, DEV-DIBSTER commented on domains/uk.json
Will not release this domain as it has the potential for abuse.

2024-01-17 00:25 UTC, closed without merging