Add my subdomain
is-a-dev/register pull request #1118
Opened 2021-09-07 20:48 UTC by uh-Sid

2021-09-08 02:17 UTC, mtgsquad submitted a review, later dismissed

2021-09-08 14:01 UTC, TheBotlyNoob approved these changes

2021-09-08 14:01 UTC, TheBotlyNoob requested changes
The filename cannot be `sid_.json`, sorry!

2021-09-11 22:17 UTC, uh-Sid commented
I changed the file name :)

2021-09-11 23:45 UTC, TheBotlyNoob approved these changes

2021-09-12 14:33 UTC, mtgsquad approved these changes

2021-09-12 14:33 UTC, merged