BETA: Register thunderarch.is-a.dev
is-a-dev/register pull request #11317
Opened 2024-01-20 15:03 UTC by thunderarch

Added `thunderarch.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-01-20 15:07 UTC, CuteDog5695 requested changes

2024-01-20 15:07 UTC, CuteDog5695 commented on domains/thunderarch.json
> +        "CNAME": "1"
invalid CNAME record

2024-01-21 10:46 UTC, thunderarch commented on domains/thunderarch.json
> +        "CNAME": "1"
I changed it to url

2024-01-21 13:43 UTC, CuteDog5695 approved these changes
think its fine now

2024-01-22 00:02 UTC, DEV-DIBSTER approved these changes

2024-01-22 00:02 UTC, merged