BETA: Register rizwan.is-a.dev
is-a-dev/register pull request #11341
Opened 2024-01-21 11:04 UTC by mrizwan2260

Added `rizwan.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-01-21 11:05 UTC, mrizwan2260 commented
my name is rizwan

2024-01-22 01:16 UTC, wdhdev requested changes

2024-01-22 01:16 UTC, wdhdev commented on domains/rizwan.json
> +        "URL": "www.rizwan.is-a.dev"
Please use a valid record.

2024-01-22 07:05 UTC, wdhdev requested changes
You seem to be merging an out of date branch into our main branch. Please rebase the branch and open a new PR.

2024-01-22 07:05 UTC, closed without merging