Update thunderarch.json
is-a-dev/register pull request #11412
Opened 2024-01-24 03:57 UTC by thunderarch

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-01-24 16:48 UTC, VaibhavSys requested changes, later dismissed

2024-01-24 16:48 UTC, VaibhavSys commented on domains/thunderarch.json
> +        "CNAME": "https://thunderarch.github.io"
```suggestion
        "CNAME": "thunderarch.github.io"
```
Invalid CNAME

2024-01-27 08:52 UTC, wdhdev approved these changes

2024-01-27 08:54 UTC, merged

2024-01-27 14:48 UTC, thunderarch commented
😅