Register shoumik.is-a.dev
is-a-dev/register pull request #11532
Opened 2024-01-27 16:01 UTC by mixmaker

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview
mixmaker.github.io

2024-01-27 19:40 UTC, Stef-00012 requested changes

2024-01-27 19:40 UTC, Stef-00012 commented on domains/shoumik.json
> +        "email": shoumikskdev@gmail.com",
missing a " in the mail

2024-01-28 02:37 UTC, mixmaker commented on domains/shoumik.json
> +        "email": shoumikskdev@gmail.com",
uh oh 🤦‍♂️

2024-01-28 02:39 UTC, DEV-DIBSTER approved these changes

2024-01-28 02:39 UTC, mixmaker reviewed
added " before the email

2024-01-28 02:41 UTC, merged