added tih.json using cname
is-a-dev/register pull request #11536
Opened 2024-01-27 17:03 UTC by FatihArridho

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-01-27 19:25 UTC, Stef-00012 requested changes

2024-01-27 19:25 UTC, Stef-00012 commented on domains/tih.json
> +        "CNAME": "https://tih-9t0.pages.dev"
Invalid CNAME record

2024-01-27 23:48 UTC, FatihArridho reviewed
remove https://

2024-01-28 00:03 UTC, FatihArridho commented
@Stef-00012 Thank you for reminding me, can you accept this PR?

2024-01-28 02:43 UTC, DEV-DIBSTER approved these changes

2024-01-28 02:44 UTC, merged