BETA: Register aliwoto.is-a.dev
is-a-dev/register pull request #11637
Opened 2024-01-30 08:47 UTC by ALiwoto

Added `aliwoto.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-01-30 09:43 UTC, Stef-00012 requested changes

2024-01-30 09:43 UTC, Stef-00012 commented on domains/aliwoto.json
> +        "A": ["176.9.175.107"]
I cannot reach your site
"176.9.175.107 refused to connect."

2024-01-30 23:38 UTC, ALiwoto commented
@DEV-DIBSTER Can I re-open this pr? I am fixing the issue on my host rn.

2024-01-30 23:39 UTC, DEV-DIBSTER commented
@ALiwoto Yes absolutely, I only end up closing these due to almost every single one going inactive in the first 24 hours gets no response.

2024-01-30 23:39 UTC, DEV-DIBSTER commented
Just re-opened for ya.

2024-01-31 00:02 UTC, ALiwoto commented
Thanks a lot! I got my site up (port 80).

2024-02-01 01:14 UTC, wdhdev approved these changes
Finally someone who responds to requested changes! Thank you for your quick co-operation!

2024-02-01 01:14 UTC, merged