BETA: Register mohdjariullah.is-a.dev
is-a-dev/register pull request #11686
Opened 2024-01-31 16:22 UTC by Mohdjariullah

Added `mohdjariullah.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-01-31 18:31 UTC, Stef-00012 requested changes

2024-01-31 18:31 UTC, Stef-00012 commented on domains/mohdjariullah.json
> +        "TXT": "vc-domain-verify=mohdjariullah.is-a.dev,b3a36b427835806db9b2"
Vercel is not supported

2024-01-31 18:46 UTC, Mohdjariullah commented on domains/mohdjariullah.json
> +        "TXT": "vc-domain-verify=mohdjariullah.is-a.dev,b3a36b427835806db9b2"
what Hosting provider i shall use then?

2024-02-01 01:17 UTC, closed without merging

2024-02-01 01:18 UTC, wdhdev commented on domains/mohdjariullah.json
> +        "TXT": "vc-domain-verify=mohdjariullah.is-a.dev,b3a36b427835806db9b2"
GitHub Pages, Cloudflare Pages, etc.