dimanet.is-a.dev
is-a-dev/register pull request #11785
Opened 2024-02-03 20:48 UTC by dimalmfao

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-02-03 20:51 UTC, dimalmfao commented
Sorry, I updated the code because I used a file from another user as a template.

2024-02-05 14:32 UTC, SX-9 requested changes

2024-02-05 14:32 UTC, SX-9 commented on domains/dimanet.json
> +    "CNAME": "dimaonline.fr/dimanet"
invalid value (expected hostname)

2024-02-06 21:04 UTC, dimalmfao commented
changed `dimaonline.fr/dimanet` to `dimanet.dimaonline.fr`

2024-02-11 11:31 UTC, SX-9 approved these changes

2024-02-11 11:31 UTC, merged