BETA: Register me.is-a.dev
is-a-dev/register pull request #11809
Opened 2024-02-04 11:42 UTC by cloudcap10

Added `me.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-04 13:49 UTC, Stef-00012 requested changes

2024-02-06 10:30 UTC, cloudcap10 commented on domains/me.json
> +        "CNAME": "cloudcap10.github.io"
@Stef-00012 already reconfigured to Github page first https://cloudcap10.github.io/me/. Thanks

2024-02-06 21:22 UTC, Stef-00012 commented on domains/me.json
> +        "CNAME": "cloudcap10.github.io"
ah sorry, removed the inaccessible website label (I usually check if the person has the site on some other repo but in your case had 142 repositories to check xD)

2024-02-12 13:14 UTC, VaibhavSys approved these changes

2024-02-12 13:15 UTC, merged