BETA: Register infinotiver.is-a.dev
is-a-dev/register pull request #11812
Opened 2024-02-04 12:10 UTC by prakarsh17

Added `infinotiver.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-05 04:29 UTC, DEV-DIBSTER requested changes

2024-02-05 04:29 UTC, DEV-DIBSTER commented on domains/infinotiver.json
> +        "CNAME": "prakarsh17.github.io"
404 GitHub page.

2024-02-05 14:36 UTC, prakarsh17 commented
I am not able to update branch... can you help me [ i am little new to prs, ]

2024-02-06 13:34 UTC, prakarsh17 commented
I think i will just close and open a new PR (sorry for this mess)

2024-02-06 13:34 UTC, closed without merging