BETA: Register rl.is-a.dev
is-a-dev/register pull request #11819
Opened 2024-02-04 14:26 UTC by Rylazius

Added `rl.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-04 14:26 UTC, Rylazius commented
i want to use this as my bio domain

2024-02-05 14:37 UTC, SX-9 requested changes

2024-02-05 14:37 UTC, SX-9 commented on domains/rl.json
> +        "TXT": "8232e838f145c8ffd79d7c4958111c"
txt alone does nothing

2024-02-06 01:24 UTC, Rylazius commented on domains/rl.json
> +        "TXT": "8232e838f145c8ffd79d7c4958111c"
i forgor wait me a lil bit

2024-02-06 01:31 UTC, Rylazius commented
ive changed the txt record to cname

2024-02-07 09:24 UTC, satr14washere approved these changes

2024-02-07 09:25 UTC, merged