BETA: Register nullyih.is-a.dev
is-a-dev/register pull request #11834
Opened 2024-02-04 21:22 UTC by NullyIsHere

Added `nullyih.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-04 21:23 UTC, NullyIsHere commented
PD: Previewing will not work, the ip is a nginx proxy

2024-02-05 04:28 UTC, DEV-DIBSTER requested changes

2024-02-05 04:28 UTC, DEV-DIBSTER commented on domains/itsasheer.json
> +        "CNAME": "nullyishere.github.io"
404 GitHub page.

2024-02-10 00:51 UTC, wdhdev commented
@NullyIsHere You need to delete the file from your fork.

2024-02-12 01:34 UTC, closed without merging