Register infinotiver.is-a.dev and delete prakarsh.is-a.dev
is-a-dev/register pull request #11891
Opened 2024-02-06 14:01 UTC by prakarsh17

## Requirements

- [x ] The file is in the `domains` folder and is in the JSON format.
- [ x] You have completed your website. 
- [ x] The website is reachable.  
- [ x] You're not using Vercel or Netlify.  
- [x ] There is sufficient information at the `owner` field.  

## Website Link/Preview
![image](https://github.com/is-a-dev/register/assets/88645086/c2599249-8e16-4688-ab6d-42f7584cfac4)

## Delete prakarsh.is-a.dev
Pls refer to https://github.com/is-a-dev/register/issues/11369

2024-02-06 21:11 UTC, Stef-00012 requested changes

2024-02-06 21:11 UTC, Stef-00012 commented on domains/infinotiver.json
> +        "CNAME": "https://prakarsh17.github.io/profile/"
Invalid CNAME record (can not have `https://` or `/`)

2024-02-08 13:42 UTC, prakarsh17 reviewed
Updated website record (removed // and /)

2024-02-08 13:43 UTC, prakarsh17 commented
Fixed and merged "main" into main (updated branch)..
All issues must be solved now??!

2024-02-08 13:53 UTC, infinotiver reviewed
Updated my username - changed info in infinotiver.json

2024-02-08 15:29 UTC, Stef-00012 approved these changes
seems good now

2024-02-08 15:30 UTC, CuteDog5695 approved these changes
seems fine to me

2024-02-08 15:31 UTC, merged