BETA: Register shamil.is-a.dev
is-a-dev/register pull request #11893
Opened 2024-02-06 15:15 UTC by shamxl

Added `shamil.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-06 21:13 UTC, Stef-00012 requested changes

2024-02-08 15:33 UTC, Stef-00012 approved these changes
seems good now

2024-02-08 15:38 UTC, Stef-00012 requested changes

2024-02-08 15:38 UTC, Stef-00012 commented on domains/shamil.json
> +           "email": "103837170+shamxl@users.noreply.github.com",
You cannot use a noreply mail in the mial field

2024-02-09 18:48 UTC, Stef-00012 approved these changes
seems good now

2024-02-11 07:14 UTC, CuteDog5695 approved these changes
seems good to me

2024-02-11 07:14 UTC, merged