BETA: Register darvingaba.is-a.dev
is-a-dev/register pull request #11920
Opened 2024-02-07 16:34 UTC by darvingaba

Added `darvingaba.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-08 16:03 UTC, Stef-DP requested changes

2024-02-08 16:03 UTC, Stef-00012 commented on domains/darvingaba.json
> +        "URL": "https://portfolio-lac-psi-77.vercel.app/"
I cannot reach your website, vercel says
> 404: NOT_FOUND
> Code: DEPLOYMENT_NOT_FOUND
> ID: fra1::lm9t4-1707408132681-de49b9a1f423
> 
> [This deployment cannot be found. For more information and troubleshooting, see our documentation.](https://vercel.com/docs/errors/platform-error-codes#deployment_not_found)

2024-02-08 19:52 UTC, darvingaba commented
added website link

2024-02-09 18:43 UTC, Stef-00012 requested changes

2024-02-09 18:43 UTC, Stef-00012 commented on package-lock.json
You can't add files to the root folder

2024-02-10 07:35 UTC, Stef-00012 commented
seems good now

2024-02-12 18:09 UTC, CuteDog5695 approved these changes
seems good to me

2024-02-12 18:11 UTC, merged