BETA: Register coderzen.is-a.dev
is-a-dev/register pull request #12008
Opened 2024-02-11 10:39 UTC by Realtrickz

Added `coderzen.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-11 10:40 UTC, Realtrickz commented
Name: _vercel

2024-02-12 02:13 UTC, DEV-DIBSTER requested changes

2024-02-12 02:13 UTC, DEV-DIBSTER commented on domains/coderzen.json
> +        "TXT": "vc-domain-verify=coderzen.is-a.dev,47bacd4c08fa05bd0544"
We do not support Vercel.

2024-02-12 02:13 UTC, closed without merging

2024-02-12 06:07 UTC, Realtrickz commented on domains/coderzen.json
> +        "TXT": "vc-domain-verify=coderzen.is-a.dev,47bacd4c08fa05bd0544"
coderzen CNAME coderzen.netlify.app.