BETA: Register r_akash.is-a.dev
is-a-dev/register pull request #12063
Opened 2024-02-13 11:56 UTC by CruxCoder7

Added `r_akash.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-13 17:16 UTC, Stef-00012 requested changes

2024-02-13 17:16 UTC, Stef-00012 commented on domains/akash.json
> +        "CNAME": "akash"
Invalid CNAME reocrd

2024-02-13 17:16 UTC, Stef-00012 commented on domains/akashr.json
> +        "CNAME": "akashr.vercel.app"
Vercel is not supported

2024-02-13 23:25 UTC, closed without merging

2024-02-14 05:21 UTC, CruxCoder7 commented
Is my 3rd commit valid?
CNAME=cruxoder7.github.io