Update axd.json
is-a-dev/register pull request #12078
Opened 2024-02-13 21:15 UTC by alexdhg

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-02-15 07:18 UTC, Stef-00012 requested changes

2024-02-15 07:18 UTC, Stef-00012 commented on domains/axd.json
> +    "CNAME": "https://axxd.me"
Invalid CNAME record (can not have `https://`)

2024-02-15 22:17 UTC, alexdhg reviewed
done

2024-02-16 12:54 UTC, Stef-00012 commented
seems good now

2024-02-16 13:06 UTC, CuteDog5695 approved these changes
seems good to me

2024-02-16 13:06 UTC, merged