BETA: Register aymouwu.is-a.dev
is-a-dev/register pull request #12076
Opened 2024-02-13 21:02 UTC by NotAymo

Added `aymouwu.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-13 21:03 UTC, NotAymo commented
please remove the other domains, let only aymouwu.is-a.dev, thanks in advance

2024-02-15 07:17 UTC, Stef-00012 requested changes

2024-02-15 07:17 UTC, Stef-00012 commented on domains/cdn.untendo.json
> +        "CNAME": "untendo.github.io"
I cannot reach your website (404 page)

2024-02-15 20:54 UTC, NotAymo commented on domains/cdn.untendo.json
> +        "CNAME": "untendo.github.io"
done

2024-02-15 22:00 UTC, Stef-00012 commented
seems good now


> please remove the other domains, let only aymouwu.is-a.dev, thanks in advance

I didn't even notice this comment 💀

2024-02-22 13:27 UTC, CuteDog5695 approved these changes
seems good to me

2024-02-22 13:27 UTC, merged