Akashr
is-a-dev/register pull request #12087
Opened 2024-02-14 05:29 UTC by CruxCoder7

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://cruxcoder7.github.io

2024-02-21 15:13 UTC, CruxCoder7 commented
.

2024-02-23 12:30 UTC, Omxpro approved these changes

2024-02-26 05:45 UTC, wdhdev requested changes

2024-02-26 05:45 UTC, wdhdev commented on domains/r_akash.json
We don't support domains with underscores in them.

2024-02-28 00:04 UTC, closed without merging