Update thecashewtrader.json
is-a-dev/register pull request #1212
Opened 2021-09-26 16:38 UTC by thecashewtrader

This is needed to verify the domain for gitlab pages.

2021-09-26 18:49 UTC, hackermondev approved these changes

2021-09-26 18:52 UTC, hackermondev requested changes, later dismissed
If I remember correctly, you cannot have a ``CNAME`` + ``TXT`` record at the same time. If you can change the ``CNAME`` record to a ``A`` record if you have the IP of your gitlab ``CNAME``.

2021-09-27 13:59 UTC, TheBotlyNoob approved these changes

2021-09-27 17:26 UTC, mtgsquad approved these changes

2021-09-27 17:26 UTC, mtgsquad approved these changes

2021-09-27 17:51 UTC, merged