Register jay.is-a.dev
is-a-dev/register pull request #12125
Opened 2024-02-16 01:51 UTC by Jay-Dodhiawala

Register jay.is-a.dev with CNAME record pointing to Aspiring Developer.

2024-02-16 01:56 UTC, DEV-DIBSTER requested changes

2024-02-16 01:56 UTC, DEV-DIBSTER commented on domains/jay.json
> +            "CNAME": "aspiring developer"
Invalid CNAME record.

2024-02-16 01:56 UTC, omsenjalia requested changes
Invalid CNAME

2024-02-16 02:02 UTC, Jay-Dodhiawala commented on domains/jay.json
> +            "CNAME": "aspiring developer"
what it should be

2024-02-16 12:10 UTC, omsenjalia approved these changes
ye this works

2024-02-23 14:38 UTC, CuteDog5695 requested changes

2024-02-23 14:38 UTC, CuteDog5695 commented on domains/jay.json
> +    "CNAME": "jaydodhiawala.github.io"
site gives 404 error

2024-02-26 12:13 UTC, closed without merging