BETA: Register codecloak.jigar.is-a.dev
is-a-dev/register pull request #12147
Opened 2024-02-17 03:37 UTC by drone911

Added `codecloak.jigar.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-17 03:41 UTC, drone911 commented
I am sorry, I did the temporary.is-a.dev as a test. I just want codecloak.jigar.is-a.dev.

2024-02-23 12:08 UTC, Omxpro requested changes

2024-02-23 12:08 UTC, Omxpro commented on domains/codecloak.jigar.json
> +        "URL": "codecloak.onrender.com"
URL records must have https:// and your other domain should be deleted

2024-02-26 12:15 UTC, Omxpro approved these changes

2024-02-26 12:17 UTC, CuteDog5695 requested changes
jigar.is-a.dev doesnt exist, so you cant make a nested domain with it

2024-02-27 23:49 UTC, drone911 commented
I added the domain jigar.is-a.dev. I hope that is okay.

2024-02-28 12:31 UTC, Omxpro approved these changes

2024-02-28 12:59 UTC, CuteDog5695 approved these changes

2024-02-28 13:00 UTC, merged