BETA: Register billy.is-a.dev
is-a-dev/register pull request #12179
Opened 2024-02-18 06:15 UTC by billyeatcookies

Added `billy.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-18 07:10 UTC, CuteDog5695 requested changes

2024-02-18 07:10 UTC, CuteDog5695 commented on domains/billy.json
> +        "URL": "billyeatcookies.github.io"
URL doesnt have protocol

2024-02-18 08:14 UTC, billyeatcookies commented
@CuteDog5695 fixed the issue, please review again.

2024-02-23 08:00 UTC, CuteDog5695 approved these changes
seems good to me now

2024-02-23 08:03 UTC, merged