BETA: Register mayank.is-a.dev
is-a-dev/register pull request #12184
Opened 2024-02-18 08:34 UTC by MayankServers

Added `mayank.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-20 13:19 UTC, MayankServers commented
@wdhdev

2024-02-20 13:33 UTC, CuteDog5695 requested changes

2024-02-20 13:33 UTC, CuteDog5695 commented on domains/mayank.json
> +        "CNAME": "mayankserver.github.io"
site gives 404 page

2024-02-21 04:28 UTC, MayankServers commented on domains/mayank.json
> +        "CNAME": "mayankserver.github.io"
> site gives 404 page

Sorry wrong url

2024-02-21 04:29 UTC, MayankServers commented on domains/mayank.json
> +        "CNAME": "mayankserver.github.io"
@CuteDog5695 recheck it

2024-02-23 08:06 UTC, CuteDog5695 approved these changes
seems good to me now

2024-02-23 08:06 UTC, merged