BETA: Register scythemedia.is-a.dev
is-a-dev/register pull request #12227
Opened 2024-02-19 12:54 UTC by ScytheMediaTheDev

Added `scythemedia.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-20 08:50 UTC, Stef-00012 requested changes

2024-02-20 08:50 UTC, Stef-00012 commented on domains/media.json
> +        "MX": ["10"]
Invalid MX record

2024-02-20 08:50 UTC, Stef-00012 commented on domains/scythe.json
> +        "URL": "https://www.scythe.is-a.dev"
That domain doesn't exist in the is-a.dev repo

2024-02-20 08:50 UTC, Stef-00012 commented on domains/scythemail.json
> +        "MX": ["scythemail.is-a.dev"]
You can't set the domain itself as MX record

2024-02-20 08:50 UTC, Stef-00012 commented
> how do i delete other domains @wdhdev @phenax

i saw that only after the review, just delete the file from your fork

2024-02-21 19:59 UTC, ScytheMediaTheDev commented
you never actually accepted my pr for scythemedia.is-a.dev @Stef-00012 @wdhdev @phenax

2024-02-21 20:11 UTC, Stef-00012 commented
> you never actually accepted my pr for scythemedia.is-a.dev @Stef-00012 @wdhdev @phenax

the pr can't be merged as it contains other invalid domains, if you want only the `scythemedia.is-a.dev` domain to be merged, you need to first fix or remove the other invalid ones

2024-02-21 20:18 UTC, ScytheMediaTheDev commented
ok

2024-02-22 13:01 UTC, ScytheMediaTheDev commented
I know but i copied the code from it so its not lost @Stef-00012 , do i just paste the code into a file called (scythemedia.json)

2024-02-22 13:01 UTC, ScytheMediaTheDev commented
is there a way to undo that commit of deleting the scythemedia.is-a.dev file?

2024-02-22 19:20 UTC, Stef-00012 commented
delete media.json and create scythemedia.json with the correct json & records

2024-02-22 20:32 UTC, ScytheMediaTheDev commented
@Stef-00012 is that good now?
I made the json file and uploaded it
also deleted media.json

2024-02-23 22:26 UTC, ScytheMediaTheDev commented
@wdhdev @phenax @Stef-00012 @is-a-dev/maintainers

2024-02-24 19:07 UTC, ScytheMediaTheDev commented
Yo this system is messed up, @wdhdev @Stef-00012 @phenax

2024-02-24 22:01 UTC, wdhdev commented
@ScytheMediaTheDev Please stop mentioning maintainers, we will get to your PR when we can.

2024-02-25 17:26 UTC, ScytheMediaTheDev commented
ok

2024-02-25 17:27 UTC, ScytheMediaTheDev commented
srry my bad, just waited at least a week or two to even get a reply

2024-02-26 05:43 UTC, wdhdev approved these changes

2024-02-26 05:44 UTC, merged

2024-02-26 12:38 UTC, ScytheMediaTheDev commented
Thanks!
    On Monday, February 26, 2024 at 12:45:11 AM EST, reviewmate[bot] ***@***.***> wrote:  
 
 


Pull Request Merged

 

What's next?

Just follow the steps below and you can start using your domain!

GitHub Pages
   
   - Go to your GitHub repository that you use for your is-a.dev domain.
   - Click on the Settings tab.
   - Click on the Pages link in the sidebar.
   - In the custom domain option, enter the domain you registered.
   - Check the Enforce HTTPS checkbox.
   - Give your domain some time (~24 hours) for the changes to propagate.
   - Enjoy your domain!

Server Owners

If your domain points to a server you own, add your-domain.is-a.dev to your domain configuration. For HTTPS, you will have to configure an SSL certificate to allow the new subdomain to work (here's why).

Need help with your domain? If you have troubles setting up your domain, please create an issue and we will try and help you as soon as possible!

Made a mistake in the records? Don't worry, you can create a new pull request with the corrections.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>