BETA: Register kamolgks.is-a.dev
is-a-dev/register pull request #12239
Opened 2024-02-20 01:49 UTC by kamolgks

Added `kamolgks.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-20 20:26 UTC, Stef-00012 requested changes

2024-02-27 17:53 UTC, kamolgks commented on domains/kamolgks.json
> +        "CNAME": "kamolgks.github.io"
everything is fixed.

2024-02-27 20:08 UTC, Stef-00012 commented
seems good now

2024-02-27 20:15 UTC, CuteDog5695 approved these changes

2024-02-27 20:15 UTC, merged