BETA: Register imsoumyaneel.is-a.dev
is-a-dev/register pull request #12237
Opened 2024-02-19 21:07 UTC by A-Little-Hat

Added `imsoumyaneel.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-20 20:24 UTC, Stef-DP requested changes

2024-02-20 20:24 UTC, Stef-00012 commented on domains/imsoumyaneel.json
> +        "CNAME": "https://test-3e8b2.web.app/"
Invalid CNAME record (can not contain `https://` or `/`)

2024-02-22 12:35 UTC, Stef-00012 approved these changes
Seems good now

2024-02-22 19:22 UTC, Stef-00012 requested changes

2024-02-22 19:22 UTC, Stef-00012 commented on domains/imsoumyaneel.json
> +        "CNAME": "test-3e8b2.web.app/"
nevermind i just rechecked and your CNAME record is invalid, can not contain `/`

2024-02-24 05:20 UTC, A-Little-Hat commented
I updated the repo. Please review it.

2024-02-24 09:36 UTC, Stef-00012 commented
Now seems good

2024-02-25 07:00 UTC, CuteDog5695 approved these changes

2024-02-25 07:02 UTC, merged