BETA: Register berkehazar.is-a.dev
is-a-dev/register pull request #12234
Opened 2024-02-19 18:37 UTC by BerkeHazar

Added `berkehazar.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-20 20:23 UTC, Stef-00012 requested changes

2024-02-21 15:24 UTC, CuteDog5695 commented on domains/berkehazar.json
> +        "TXT": "google-site-verification=ll4q7mdujdndaoemsfcof7svndjgdhg11khr48i0q6e"
theres Github Pages and Cloudflare Pages

2024-02-21 20:08 UTC, Stef-DP requested changes

2024-02-26 10:34 UTC, Omxpro approved these changes
works but fix your other domains

2024-02-26 12:23 UTC, closed without merging