BETA: Register alimehdi.is-a.dev
is-a-dev/register pull request #12263
Opened 2024-02-21 19:09 UTC by DeadMan30

Added `alimehdi.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-21 20:26 UTC, Stef-00012 requested changes

2024-02-21 20:26 UTC, Stef-00012 commented on domains/alimehdi.json
> +        "TXT": "vc-domain-verify=alimehdi.is-a.dev,73a902df9c7b76caf4a3"
Vercel is not supported

2024-02-21 20:51 UTC, DeadMan30 commented on domains/alimehdi.json
> +        "TXT": "vc-domain-verify=alimehdi.is-a.dev,73a902df9c7b76caf4a3"
Changed the record to CNAME

2024-02-23 09:25 UTC, Omxpro approved these changes

2024-02-23 11:51 UTC, CuteDog5695 approved these changes

2024-02-23 11:52 UTC, merged