BETA: Register omairr.is-a.dev
is-a-dev/register pull request #12326
Opened 2024-02-23 20:12 UTC by omaiirr

Added `omairr.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-24 00:08 UTC, Omxpro requested changes

2024-02-24 00:08 UTC, Omxpro commented on domains/omairr.json
> +        "CNAME": "omairr"
Invalid CNAME record. please look at https://is-a.dev/docs and fix it!

2024-02-25 13:13 UTC, raphael-as commented
Normally, it's correct

2024-02-25 13:43 UTC, CuteDog5695 approved these changes
seems good to me now

2024-02-25 13:44 UTC, merged