Register anna.is-a.dev
is-a-dev/register pull request #12323
Opened 2024-02-23 18:57 UTC by annanas271

Register anna.is-a.dev with CNAME record pointing to annanas271.github.io.

2024-02-23 19:05 UTC, Stef-00012 requested changes

2024-02-23 19:05 UTC, Stef-00012 commented on domains/anna.json
> +            "CNAME": "annanas271.github.io"
I cannot reach your website
`annanas271.github.io` redirects me to `miaroschi.rocks` with returns
> This site can’t be reached
> Check if there is a typo in miaroshi.rocks.
> DNS_PROBE_FINISHED_NXDOMAIN

2024-02-26 10:30 UTC, Omxpro approved these changes

2024-02-26 11:40 UTC, iostpa approved these changes
site is accessible now

2024-02-26 11:42 UTC, merged