Change the CNAME records for cfp domains
is-a-dev/register pull request #12321
Opened 2024-02-23 18:44 UTC by cfpwastaken

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

I only changed the CNAME to another domain on another host which doesn't have as much suction as noip.

2024-02-23 19:03 UTC, Stef-00012 requested changes

2024-02-23 19:03 UTC, Stef-00012 commented on domains/cfp.json
> +	  "CNAME": "dyn.picoscratch.de"
I cannot reach your website
"404 page not found"

2024-02-23 19:03 UTC, Stef-00012 commented on domains/pic.cfp.json
> +	  "CNAME": "dyn.picoscratch.de"
I cannot reach your website
"404 page not found"

2024-02-23 19:03 UTC, Stef-00012 commented on domains/scfp.json
> +	  "CNAME": "dyn.picoscratch.de"
I cannot reach your website
"404 page not found"

2024-02-23 19:03 UTC, Stef-00012 commented on domains/status.cfp.json
> +		"CNAME": "dyn.picoscratch.de"
I cannot reach your website
"404 page not found"

2024-02-23 19:16 UTC, cfpwastaken commented
@Stef-00012 First of all, thanks for the quick review!
That domain is actually just used for my dynamic DNS and it points to a webserver that hosts multiple domains' websites at once and it can't guess which one you are trying to see when you just enter dyn.picoscratch.de. Please try entering the IP with domain into your hosts file and navigate directly to the domain. Since the current records point to the same IP in the end you can also check the current pages. They won't change.
Thanks!

2024-02-23 22:45 UTC, Stef-00012 commented
> @Stef-00012 First of all, thanks for the quick review! That domain is actually just used for my dynamic DNS and it points to a webserver that hosts multiple domains' websites at once and it can't guess which one you are trying to see when you just enter dyn.picoscratch.de. Please try entering the IP with domain into your hosts file and navigate directly to the domain. Since the current records point to the same IP in the end you can also check the current pages. They won't change. Thanks!

I see, after adding it to my hosts file, I'm still unable to access `scfp.is-a.dev` (nginx 502 bad gateway) and `status.cfp.is-a.dev` (The connection is not private, and since `.dev` domains require https I can't access it)

2024-02-25 16:11 UTC, cfpwastaken commented
I have fixed the 2 pages now. Please check them again.
Take note that my IP address has changed by now to `87.150.220.123` (25.02.2024)

2024-02-26 11:43 UTC, CuteDog5695 approved these changes
website accessible now

2024-02-26 11:43 UTC, merged