BETA: Register @p2.is-a.dev
is-a-dev/register pull request #12355
Opened 2024-02-24 16:20 UTC by code-hunt-in

Added `@p2.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-24 18:52 UTC, Stef-00012 requested changes

2024-02-24 18:52 UTC, Stef-00012 commented on domains/ap2.json
> +        "TXT": "aishwary pandore"
TXT records alone do nothing

2024-02-24 18:52 UTC, Stef-00012 commented on domains/app.json
> +    "TXT": "Aishwary Pandore"
TXT records alone do nothing

2024-02-24 18:52 UTC, Stef-00012 commented on domains/app.json
> +    "email": "<aishwary.pandore@somaiya.edu>"
Username and email shouldn't not have the `<>`

2024-02-24 18:52 UTC, Stef-00012 commented on domains/@p2.json
File name non not contain `@`

2024-02-25 13:08 UTC, code-hunt-in reviewed
Thank you for guidance

2024-02-25 13:37 UTC, Stef-00012 requested changes

2024-02-25 13:37 UTC, Stef-00012 commented on domains/@p2.json
File name non not contain `@`

2024-02-25 13:48 UTC, code-hunt-in commented on domains/@p2.json
is aish ok?

2024-02-25 19:38 UTC, CuteDog5695 approved these changes
seems good to me

2024-02-25 19:39 UTC, merged