BETA: Register googledrivedirect.is-a.dev
is-a-dev/register pull request #12411
Opened 2024-02-26 07:38 UTC by c-23404

Added `googledrivedirect.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-26 08:25 UTC, Omxpro requested changes
invalid CNAME record

2024-02-26 12:37 UTC, CuteDog5695 requested changes

2024-02-26 12:37 UTC, CuteDog5695 commented on domains/googledrivedirect.json
> +        "CNAME": "c-23404.github.io."
remove the . in "c-23404.github.io."

2024-02-28 12:36 UTC, Omxpro approved these changes

2024-02-28 12:37 UTC, Omxpro commented
cannot access website

2024-02-28 14:09 UTC, c-23404 commented
> cannot access website

what i do?

2024-03-03 15:25 UTC, closed without merging