BETA: Register sashank.is-a.dev
is-a-dev/register pull request #12418
Opened 2024-02-26 12:03 UTC by shankypedia

Added `sashank.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-26 12:09 UTC, CuteDog5695 requested changes, later dismissed

2024-02-26 12:09 UTC, CuteDog5695 commented on domains/sashank.json
> +        "URL": "https://sashank.wiki"
Site can't be reached

2024-02-26 12:09 UTC, Omxpro requested changes
cannot access your website

2024-03-01 03:42 UTC, shankypedia commented
The website was never down, it's still online, please check with this hyperlink: https://sashank.wiki/

2024-03-01 04:15 UTC, Omxpro commented
> The website was never down, it's still online, please check with this hyperlink: https://sashank.wiki/

great

2024-03-03 20:21 UTC, DEV-DIBSTER approved these changes

2024-03-03 20:22 UTC, merged