BETA: Register hecker40.is-a.dev
is-a-dev/register pull request #12430
Opened 2024-02-27 07:22 UTC by hecker40

Added `hecker40.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-27 07:44 UTC, Omxpro requested changes

2024-02-27 07:44 UTC, Omxpro commented on domains/hecker40.json
> +        "URL": "hecker40.com"
URL records must contain https://

2024-03-03 21:49 UTC, Stef-00012 requested changes

2024-03-03 21:49 UTC, Stef-00012 commented on domains/hecker40.json
> +            "192.168.1.8"
I cannot reach your website, keeps on loading

2024-03-11 01:31 UTC, closed without merging