BETA: Register gabriela.is-a.dev
is-a-dev/register pull request #12448
Opened 2024-02-27 23:09 UTC by gabriela4152

Added `gabriela.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-02-28 00:04 UTC, Omxpro requested changes
web gives 404 error. please give us your website link

2024-02-29 19:39 UTC, gabriela4152 commented
https://gabriela4152.github.io/

2024-03-03 21:53 UTC, Stef-00012 commented
seems good now

2024-03-12 16:55 UTC, CuteDog5695 approved these changes

2024-03-12 17:00 UTC, merged