BETA: Register nthduc.is-a.dev
is-a-dev/register pull request #12456
Opened 2024-02-28 14:55 UTC by nthduc

Added `nthduc.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-03 21:48 UTC, Stef-00012 requested changes

2024-03-03 21:48 UTC, Stef-00012 commented on domains/nthduc.json
> +        "CNAME": "xb00925c3.custom.b4a.run"
I cannot reach your webiste, "not found"

2024-03-04 09:09 UTC, Stef-00012 commented on domains/nthduc.json
> +        "CNAME": "xb00925c3.custom.b4a.run"
oh ok, this works

2024-03-05 03:21 UTC, DEV-DIBSTER approved these changes

2024-03-05 03:21 UTC, merged