Register joltz.is-a.dev
is-a-dev/register pull request #12489
Opened 2024-02-29 22:36 UTC by joltz1234

Register joltz.is-a.dev with CNAME record pointing to https://joltz1234.github.io.

2024-03-01 03:06 UTC, Omxpro approved these changes

2024-03-01 03:07 UTC, wdhdev approved these changes

2024-03-01 03:07 UTC, wdhdev commented on domains/mystic titans.json
> +        "URL": "https://discord.gg/nxnsdjb4wm"
Invalid URL, 404

2024-03-01 03:07 UTC, wdhdev commented on domains/joltz.json
> +           "email": "75178291+joltz1234@users.noreply.github.com",
Invalid email

2024-03-01 03:08 UTC, wdhdev requested changes
Sorry not approved, please fix the comments above.

2024-03-03 21:58 UTC, Stef-00012 commented
seems good now

2024-03-11 01:33 UTC, DEV-DIBSTER approved these changes

2024-03-11 01:33 UTC, merged