BETA: Register heyavi.is-a.dev
is-a-dev/register pull request #12490
Opened 2024-02-29 23:34 UTC by Akhileshrangani4

Added `heyavi.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-03 21:54 UTC, Stef-00012 requested changes

2024-03-03 21:54 UTC, Stef-00012 commented on domains/akhileshh.json
> +        "TXT": "google-site-verification=mxvu1et47munvjqueyoocxtlg8u1ikizyueuxntqtka"
Google site verification through TXT records is not supported, use the HTTPS method

2024-03-03 21:54 UTC, Stef-00012 commented on domains/akhilesh.json
> +        "TXT": "google-site-verification=jr4pbfhu2ujqjmfocyc-ukbxokjugvn8oit17d-qhia"
Google site verification through TXT records is not supported, use the HTTPS method

2024-03-12 17:31 UTC, Akhileshrangani4 commented
prevent

2024-03-17 03:33 UTC, DEV-DIBSTER commented
Closing for inactivity.

2024-03-17 03:33 UTC, closed without merging