BETA: Register tgnick.is-a.dev
is-a-dev/register pull request #12502
Opened 2024-03-01 23:49 UTC by TGNick

Added `tgnick.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-02 22:58 UTC, Stef-00012 requested changes

2024-03-02 22:58 UTC, Stef-00012 commented on domains/echo.json
> +        "CNAME": "192.0.2"
Invalid CNAME record (must be a domain)

2024-03-02 22:58 UTC, Stef-00012 commented on domains/tgnick.json
> +        "URL": "discord.com"
invalid URL record, missing protocol

2024-03-05 13:19 UTC, TGNick commented on domains/echo.json
> +        "CNAME": "192.0.2"
Oh

2024-03-05 13:19 UTC, TGNick commented on domains/tgnick.json
> +        "URL": "discord.com"
Ok

2024-03-11 12:00 UTC, Stef-00012 requested changes

2024-03-11 12:00 UTC, Stef-00012 commented on domains/echo.json
> +        "CNAME": "https://echomp.github.io/Echodownload.github.io/"
Invalid CNAME record
can nout contain `https://` or `/`

2024-03-21 11:38 UTC, closed without merging