BETA: Register riddim_glitch.is-a.dev
is-a-dev/register pull request #12559
Opened 2024-03-04 09:45 UTC by Riddim-GLiTCH

Added `riddim_glitch.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-11 20:45 UTC, Riddim-GLiTCH commented
Bump

2024-03-12 17:01 UTC, CuteDog5695 requested changes

2024-03-12 17:01 UTC, CuteDog5695 commented on domains/riddim_glitch.json
i dont think we allow domains with underscores

2024-03-12 17:02 UTC, CuteDog5695 commented
> Should probably explain the funny screenshot, I previously registered for a domain which now no longer is under my list of domains, this PR is just me trying to re-add it. Though I think I originally had it registered as "riddim-glitch" instead of "riddim_glitch".

checked and i see that you originally registered riddim-glitch.is-a.dev

2024-03-12 21:53 UTC, Riddim-GLiTCH commented
> > Should probably explain the funny screenshot, I previously registered for a domain which now no longer is under my list of domains, this PR is just me trying to re-add it. Though I think I originally had it registered as "riddim-glitch" instead of "riddim_glitch".
> 
> checked and i see that you originally registered riddim-glitch.is-a.dev

Indeed, however it does not appear on my dashboard, and visiting it takes you to your homepage. this is why I registered again.

2024-03-13 18:31 UTC, CuteDog5695 commented
> > > Should probably explain the funny screenshot, I previously registered for a domain which now no longer is under my list of domains, this PR is just me trying to re-add it. Though I think I originally had it registered as "riddim-glitch" instead of "riddim_glitch".
> > 
> > 
> > checked and i see that you originally registered riddim-glitch.is-a.dev
> 
> Indeed, however it does not appear on my dashboard, and visiting it takes you to your homepage. this is why I registered again.

think it got caught in cleanup, btw rename riddim_glitch.json with riddim-glitch.json and then i can merge PR

2024-03-15 15:12 UTC, Riddim-GLiTCH commented
Renamed the files. My old domain was still present so I had to remove it in order to be able to save the file.

2024-03-16 06:10 UTC, CuteDog5695 submitted a review, later dismissed
seems fine to me now

2024-03-19 15:55 UTC, CuteDog5695 commented
i dont know if you noticed but this PR has a merge conflict, reason why i didnt merge PR. please fix the merge conflict problem and then ill merge it

2024-03-19 18:56 UTC, CuteDog5695 commented
> I have noticed but I'm not sure which file is conflicting. I'm also not sure where to start looking, to be honest.

you can try and google it

2024-03-24 13:23 UTC, Riddim-GLiTCH commented
Hi, apologies for the long delay in response. I was dealing with family matters and it consumed most of my free time, resulting in me not being able to check my github.

I just looked up the issue, but unless im misunderstanding the actual issue, it should already be solved?
All I could find was a potential lack of entries in the record file, Which should be mitigated with at least one entry, which *should* be present in the form of a CNAME. Unless the issue is the mismatching email compared the email in the record for my website, which I just updated.

2024-03-24 13:27 UTC, CuteDog5695 commented
> Hi, apologies for the long delay in response. I was dealing with family matters and it consumed most of my free time, resulting in me not being able to check my github.
> 
> I just looked up the issue, but unless im misunderstanding the actual issue, it should already be solved? All I could find was a potential lack of entries in the record file, Which should be mitigated with at least one entry, which _should_ be present in the form of a CNAME. Unless the issue is the mismatching email compared the email in the record for my website, which I just updated.

merge conflict seems to still be here, ill list a couple tutorials here:
https://www.freecodecamp.org/news/how-to-fix-merge-conflicts-in-git/
https://www.youtube.com/watch?v=mSfq1SoMocg
https://stackoverflow.com/questions/161813/how-do-i-resolve-merge-conflicts-in-a-git-repository

2024-03-24 21:55 UTC, Riddim-GLiTCH commented
Thanks, I will check these out tomorrow when I am done with work.

2024-03-25 11:19 UTC, 21Z commented
Your fork is outdated, `random-glitch.json` doesnt exist on this repo, but ur fork does...
Sync your fork and create a new file `random-glitch.json`

2024-03-26 13:29 UTC, TerraPlayz commented
Updates??

2024-03-28 08:53 UTC, Riddim-GLiTCH commented
> > My old domain was still present so I had to remove it
> 
> Your fork is outdated, Sync your fork and create a new file `random-glitch.json`

Done this

2024-03-28 14:43 UTC, Stef-00012 approved these changes
seems good to me now

2024-03-28 14:43 UTC, merged