BETA: Register jake0001.is-a.dev
is-a-dev/register pull request #12564
Opened 2024-03-04 16:11 UTC by jake0001-dev

Added `jake0001.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-18 07:05 UTC, 21Z requested changes
website can't be reached

2024-03-19 14:36 UTC, CuteDog5695 requested changes

2024-03-19 14:36 UTC, CuteDog5695 commented on domains/jake0001.json
> +        "A": ["95.214.180.29"]
404 not found

2024-03-26 13:28 UTC, TerraPlayz commented
Inactive

2024-03-26 13:28 UTC, closed without merging