BETA: Register shree.is-a.dev
is-a-dev/register pull request #12576
Opened 2024-03-05 10:53 UTC by shreekrishnalamichhane

Added `shree.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-19 14:40 UTC, CuteDog5695 requested changes

2024-03-19 14:40 UTC, CuteDog5695 commented on domains/shree.json
> +        "CNAME": "shreekrishnalamichhhane.com.np"
site cant be reached

2024-03-21 08:12 UTC, shreekrishnalamichhane reviewed
Cname record now has been fixed

2024-03-21 11:43 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-03-21 11:43 UTC, merged