Create Kacem.json
is-a-dev/register pull request #1261
Opened 2021-10-09 13:08 UTC by LordKacem

2021-10-09 23:58 UTC, hackermondev approved these changes

2021-10-10 00:01 UTC, hackermondev submitted a review, later dismissed
You need a valid ``username`` and ``email`` or ``twitter`` in the owner object.

2021-10-13 20:05 UTC, TheBotlyNoob approved these changes

2021-11-17 20:41 UTC, TheBotlyNoob approved these changes

2021-11-17 20:42 UTC, TheBotlyNoob requested changes
please change the file name to `kacem.json`, we do not allow capitals in the file name

2021-11-26 14:47 UTC, TheBotlyNoob commented
Closing because of inactivity

2021-11-26 14:47 UTC, closed without merging