BETA: Register gawaxine.exe.is-a.dev
is-a-dev/register pull request #12614
Opened 2024-03-07 18:14 UTC by galaxine-senpai

Added `gawaxine.exe.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-07 20:16 UTC, galaxine-senpai commented
The sub-domain I set it to point to may not be active yet as I only added it shortly before making this PR.

2024-03-19 16:01 UTC, CuteDog5695 requested changes

2024-03-19 16:01 UTC, CuteDog5695 commented on domains/gawaxine.exe.json
> +        "CNAME": "https://portfolio.microwavebot.com"
remove the https:// part pls (also site cant be reached)

2024-03-26 13:28 UTC, TerraPlayz commented
Inactive

2024-03-26 13:28 UTC, closed without merging