BETA: Register zero-stats.is-a.dev
is-a-dev/register pull request #12622
Opened 2024-03-08 08:44 UTC by Zero-Kurosaki

Added `zero-stats.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-11 01:37 UTC, DEV-DIBSTER requested changes

2024-03-11 01:37 UTC, DEV-DIBSTER commented on domains/zero-kurosaki.json
> +        "CNAME": "1"
Invalid CNAME record, must be valid hostname.

2024-03-21 07:29 UTC, 21Z requested changes

2024-03-21 07:29 UTC, 21Z commented on domains/zero_kurosaki.json
> +        "CNAME": "zero-kurosaki.github.io"
404 Site not found

2024-03-21 19:26 UTC, CuteDog5695 commented
since PR is stale and no response has been given, im closing the PR

2024-03-21 19:26 UTC, closed without merging