BETA: Register statusnodes.is-a.dev
is-a-dev/register pull request #12628
Opened 2024-03-08 16:47 UTC by roksito

Added `statusnodes.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-19 16:07 UTC, CuteDog5695 requested changes

2024-03-19 16:07 UTC, CuteDog5695 commented on domains/statusnodes,.json
a comma cant be in the .json file

2024-03-19 16:07 UTC, CuteDog5695 commented on domains/statusnodes.json
> +        "CNAME": "69.30.249.53"
invalid CNAME record

2024-03-26 13:26 UTC, TerraPlayz commented
Inactive

2024-03-26 13:26 UTC, closed without merging