BETA: Register riddle.is-a.dev
is-a-dev/register pull request #12645
Opened 2024-03-09 19:41 UTC by r-ddle

Added `riddle.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-10 21:09 UTC, PinkLittleKitty commented
Netlify is not supported.

2024-03-10 21:11 UTC, PinkLittleKitty requested changes
Netlify is not supported

2024-03-16 01:04 UTC, r-ddle commented
> Netlify is not supported

oh, what are the hostings that you support?

2024-03-16 01:10 UTC, PinkLittleKitty commented
I recommend using github pages, but you can also use Railway or Cloudfare.

2024-03-21 07:18 UTC, 21Z requested changes

2024-03-21 07:18 UTC, 21Z commented on domains/riddle.json
> +        "CNAME": "riddle cname r-ddle.netlify.app."
1. Invalid `CNAME` record
2. Netlify is not supported

2024-03-26 13:25 UTC, TerraPlayz commented
Inactive

2024-03-26 13:25 UTC, closed without merging