BETA: Register fud.is-a.dev
is-a-dev/register pull request #12648
Opened 2024-03-09 23:55 UTC by DevMHOne

Added `fud.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-09 23:57 UTC, DevMHOne commented
For biolink

2024-03-10 21:10 UTC, PinkLittleKitty commented
Vercel is not supported.

2024-03-10 21:12 UTC, PinkLittleKitty requested changes
Vercel is not supported.

2024-03-10 22:27 UTC, DevMHOne commented
Check again, I've updated it

2024-03-16 01:13 UTC, PinkLittleKitty approved these changes

2024-03-19 16:08 UTC, CuteDog5695 requested changes

2024-03-19 16:08 UTC, CuteDog5695 commented on domains/fud.json
> +        "A": "178.128.96.69"
IP should be in an array

2024-03-19 16:08 UTC, CuteDog5695 commented on domains/voucher .json
there shouldnt be a space in the .json file

2024-03-26 13:25 UTC, TerraPlayz commented
Inactive

2024-03-26 13:25 UTC, closed without merging