BETA: Register ztrdiamond .is-a.dev
is-a-dev/register pull request #12659
Opened 2024-03-10 09:52 UTC by ZTRdiamond

Added `ztrdiamond .is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-21 07:15 UTC, 21Z requested changes

2024-03-21 07:15 UTC, 21Z commented on domains/ztrdiamond .json
JSON file name should not contain space

2024-03-21 19:27 UTC, CuteDog5695 submitted a review, later dismissed

2024-03-21 19:27 UTC, CuteDog5695 commented on domains/ztrdiamond .json
.json file cant have a space in it

2024-03-22 10:13 UTC, ZTRdiamond commented on domains/ztrdiamond .json
done
https://github.com/is-a-dev/register/pull/12659/commits/08703750249da2dca6c138628563b925e8686580

2024-03-23 09:41 UTC, VaibhavSys approved these changes

2024-03-23 09:43 UTC, merged