Add new records to yunexiz.is-a.dev (Im not 100% sure if i did this correctly)
is-a-dev/register pull request #12670
Opened 2024-03-10 15:19 UTC by Yunexiz

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-03-10 17:09 UTC, VaibhavSys requested changes, later dismissed
Invalid Syntax and Error in MX

2024-03-10 17:09 UTC, VaibhavSys commented on domains/yunexiz.json
> +        "TXT": ["v=spf1 include:spf.improvmx.com ~all"]
```suggestion
        "TXT": ["v=spf1 include:spf.improvmx.com ~all"],
```

2024-03-10 17:09 UTC, VaibhavSys commented on domains/yunexiz.json
>          "A": ["109.71.252.37"]
```suggestion
        "A": ["109.71.252.37"],
```

2024-03-10 17:09 UTC, VaibhavSys commented on domains/yunexiz.json
> +        "MX": ["mx1.improvmx.com.", "mx2.improvmx.com."]
```suggestion
        "MX": ["mx1.improvmx.com", "mx2.improvmx.com"]
```

2024-03-11 10:44 UTC, wdhdev approved these changes

2024-03-11 10:45 UTC, merged