BETA: Register frogiee1stuff.is-a.dev
is-a-dev/register pull request #12674
Opened 2024-03-10 22:21 UTC by FrogiesArcade

Added `frogiee1stuff.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-21 07:12 UTC, 21Z requested changes

2024-03-21 07:12 UTC, 21Z commented on domains/frogiee1.json
> +    "username": "frogiee1",
Invalid username
```suggestion
    "username": "FrogiesArcade",
```

2024-03-21 07:12 UTC, 21Z commented on domains/frogiee1.json
> +  "repo": "https://github.com/frogiesarcade",
Invalid repo link
```suggestion
```

2024-03-26 13:39 UTC, TerraPlayz commented
Inactive

2024-03-26 13:39 UTC, closed without merging