BETA: Register webcubed.is-a.dev
is-a-dev/register pull request #12694
Opened 2024-03-12 00:25 UTC by webcubed

Added `webcubed.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-19 19:26 UTC, webcubed commented
woohoo?

2024-03-19 19:28 UTC, CuteDog5695 requested changes

2024-03-19 19:28 UTC, CuteDog5695 commented on domains/webcubed.json
> +        "CNAME": "https://webcubed.vercel.app/"
we dont support vercel (also for CNAME you need to remove https:// and /)

2024-03-26 13:38 UTC, TerraPlayz commented
Inactive

2024-03-26 13:38 UTC, closed without merging