BETA: Register mwa.is-a.dev
is-a-dev/register pull request #12724
Opened 2024-03-13 20:17 UTC by Totallynotmwa

Added `mwa.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-13 21:21 UTC, Totallynotmwa commented
Figuring out how to make a redirect bro☠️

2024-03-17 12:23 UTC, CuteDog5695 requested changes

2024-03-17 12:23 UTC, CuteDog5695 commented on domains/totallynotmwa.json
> +        "A": ["192.0.2.1"]
put an actual IP, not a local IP

2024-03-17 12:23 UTC, CuteDog5695 commented on domains/mwanothere.json
> +        "A": ["192.0.2.1"]
put an actual IP, not a local IP

2024-03-17 12:23 UTC, CuteDog5695 commented on domains/mwa.json
> +        "A": ["192.0.2.1"]
put an actual IP, not a local IP

2024-03-17 12:33 UTC, Totallynotmwa commented on domains/totallynotmwa.json
> +        "A": ["192.0.2.1"]
There i changed it all

2024-03-17 12:35 UTC, CuteDog5695 requested changes

2024-03-17 12:35 UTC, CuteDog5695 commented on domains/totallynotmwa.json
> +        "URL": "mwa.lol"
doesnt have protocol

2024-03-17 12:35 UTC, CuteDog5695 commented on domains/mwanothere.json
> +        "URL": "mwa.lol"
doesnt have protocol

2024-03-17 12:35 UTC, CuteDog5695 commented on domains/mwa.json
> +        "URL": "mwa.lol"
doesnt have protocol

2024-03-19 13:21 UTC, CuteDog5695 approved these changes
seems fine to me now

2024-03-19 13:23 UTC, merged