BETA: Register giocoliere.is-a.dev
is-a-dev/register pull request #12722
Opened 2024-03-13 16:48 UTC by giocoliere

Added `blog.gioco.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-23 09:50 UTC, VaibhavSys requested changes
_atproto is currently not supported.

2024-03-25 16:40 UTC, CuteDog5695 requested changes

2024-03-25 16:40 UTC, CuteDog5695 commented on domains/giocoliere.json
> +        "CNAME": "exquisite-paprenjak-917b5f.netlify.app"
we dont support netlify

2024-03-25 16:40 UTC, CuteDog5695 commented on domains/_atproto.gioco.json
delete this file please since we dont support _atproto

2024-03-26 13:41 UTC, TerraPlayz requested changes
cannot reach web

2024-03-27 12:56 UTC, closed without merging