Register lucia.is-a.dev
is-a-dev/register pull request #12764
Opened 2024-03-15 18:24 UTC by Max87153

Register lucia.is-a.dev with CNAME record pointing to fastidious-phoenix-f62ded.netlify.app.

2024-03-16 17:23 UTC, 21Z reviewed
Netlify is not supported.

2024-03-19 06:37 UTC, 21Z requested changes

2024-03-19 06:37 UTC, 21Z commented on domains/lucia.json
> +            "CNAME": "fastidious-phoenix-f62ded.netlify.app"
Netlify isn't supported

2024-03-26 13:31 UTC, TerraPlayz commented
Inactive

2024-03-26 13:31 UTC, closed without merging