New domain: chaprnks.json
is-a-dev/register pull request #12803
Opened 2024-03-17 04:23 UTC by Chaprnks

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [✔] The file is in the `domains` folder and is in the JSON format.
- [✔] You have completed your website. 
- [✔] The website is reachable.  
- [✔] You're not using Vercel or Netlify.  
- [✔] The CNAME record doesn't contain `https://` or `/`.  
- [✔] There is sufficient information at the `owner` field.  

## Website Link/Preview
http://chaprnks.me

2024-03-19 07:13 UTC, 21Z requested changes

2024-03-19 07:13 UTC, 21Z commented on domains/chaprnks.json
> +    "URL": "https://chaprnks.me"
site refused to connect.

2024-03-25 15:44 UTC, SX-9 requested changes

2024-03-25 15:44 UTC, SX-9 commented on domains/chaprnks.json
> +    "URL": "https://chaprnks.me"
as @21Z said it refused to cennect

2024-03-28 14:46 UTC, closed without merging