BETA: Register cheesedev.is-a.dev
is-a-dev/register pull request #12815
Opened 2024-03-17 22:06 UTC by CallenDV

Added `cheesedev.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-19 09:32 UTC, 21Z approved these changes
Are you sure you want to use `URL` and not `CNAME`?

2024-03-19 09:36 UTC, 21Z requested changes

2024-03-25 15:47 UTC, SX-9 requested changes
look at @21Z 's review

2024-03-26 10:23 UTC, Stef-00012 requested changes

2024-03-26 10:23 UTC, Stef-00012 commented on domains/cheesedev.json
> +        "URL": "callendv.github.io"
As 21Z pointed, URL record must have the protocol

2024-03-28 14:52 UTC, closed without merging