Register Mr.Unknown_74.is-a.dev
is-a-dev/register pull request #12820
Opened 2024-03-18 17:20 UTC by Mr-Unknown-74

Register Mr.Unknown_74.is-a.dev with CNAME record pointing to mr-unknown-74.github.io.

2024-03-25 11:43 UTC, 21Z requested changes

2024-03-25 11:43 UTC, 21Z commented on domains/mr.unknown_74.json
Domain cannot contain underscore

2024-03-26 10:29 UTC, Stef-00012 commented on domains/mr.unknown_74.json
they can contain underscores if they're in the middle

2024-03-26 10:34 UTC, Stef-00012 requested changes
seems good to me

2024-03-26 10:34 UTC, Stef-00012 commented on domains/mr.unknown_74.json
the domain `unknown_74` doesn't exist so you can't create a subdomain of it

2024-03-26 10:35 UTC, Stef-00012 requested changes

2024-03-26 10:35 UTC, Stef-00012 commented on domains/mr.unknown_74.json
the domain `unknown_74` doesn't exist so you can't create a subdomain of it (`mr`)

2024-03-27 20:55 UTC, closed without merging