Register canaan.is-a.dev
is-a-dev/register pull request #12822
Opened 2024-03-18 21:16 UTC by iiCanaanDev

Register canaan.is-a.dev with TXT record pointing to is-a.dev.

2024-03-19 07:07 UTC, 21Z requested changes

2024-03-19 07:07 UTC, 21Z commented on domains/canaan.json
> +            "TXT": "is-a.dev"
TXT records alone do nothing.

2024-03-26 10:37 UTC, Stef-00012 requested changes

2024-03-26 10:37 UTC, Stef-00012 commented on domains/canaan.json
> +            "TXT": "is-a.dev"
As 21Z said, TXT records alone do nothing

2024-03-26 10:40 UTC, closed without merging