add wlodekm
is-a-dev/register pull request #12843
Opened 2024-03-20 10:40 UTC by WlodekM

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [ x There is sufficient information at the `owner` field.  

## Website Link/Preview

![image](https://github.com/is-a-dev/register/assets/75479945/6f488e23-4151-49a3-8111-ebabc27ae22a)

2024-03-20 10:43 UTC, 21Z commented
eh this domains for developers to have a personal website

2024-03-28 14:58 UTC, TerraPlayz requested changes, later dismissed
a has to be renamed to A

2024-03-28 15:00 UTC, VaibhavSys requested changes, later dismissed

2024-03-28 15:00 UTC, VaibhavSys commented on domains/wlodekm.json
> +    "a": ["159.224.173.169"]
```suggestion
    "A": ["159.224.173.169"]
```

2024-03-31 03:28 UTC, DEV-DIBSTER approved these changes

2024-03-31 03:28 UTC, merged