BETA: Register fisch.is-a.dev
is-a-dev/register pull request #12847
Opened 2024-03-20 12:53 UTC by Fischss

Added `fisch.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-21 19:30 UTC, 21Z requested changes

2024-03-21 19:30 UTC, 21Z commented on domains/fisch.json
> +        "URL": "fish.is-a.dev"
Avoids redirects
```suggestion
        "URL": "https://github.com/fischss"
```

2024-03-28 14:18 UTC, VaibhavSys requested changes

2024-03-28 14:18 UTC, VaibhavSys commented on domains/fisch.json
> +        "URL": "fish.is-a.dev"
Invalid URL

2024-04-02 03:36 UTC, closed without merging