Update anshbhimani.json
is-a-dev/register pull request #12856
Opened 2024-03-20 16:45 UTC by AnshBhimani

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-03-20 19:13 UTC, 21Z requested changes

2024-03-20 19:13 UTC, 21Z commented on domains/anshbhimani.json
> +        "CNAME": "anshbhimani.github.io"
404 site not found

2024-03-23 13:31 UTC, anshbhimani commented
i want to remake the website from github pages can you delete the existing one

2024-03-23 15:38 UTC, 21Z commented
> i want to remake the website from github pages can you delete the existing one

Delete it in your fork

2024-03-25 16:53 UTC, closed without merging

2024-03-25 17:00 UTC, anshbhimani commented
Deleted in my fork

2024-03-25 17:00 UTC, anshbhimani commented
Deleted in my fork