BETA: Register mudee.is-a.dev
is-a-dev/register pull request #12898
Opened 2024-03-22 10:45 UTC by IMMudeeG

Added `mudee.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-25 17:49 UTC, 21Z requested changes

2024-03-25 17:49 UTC, 21Z commented on domains/mudee.json
> +        "A": ["131.123.747.5"]
Invalid IP

2024-03-26 10:59 UTC, Stef-00012 requested changes

2024-03-26 10:59 UTC, Stef-00012 commented on domains/mudee.json
> +        "A": ["131.123.747.5"]
As 21Z said, invalid IP address

2024-03-30 08:16 UTC, closed without merging