BETA: Register zwu.is-a.dev
is-a-dev/register pull request #12908
Opened 2024-03-22 15:27 UTC by wu000168

Added `zwu.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-23 11:56 UTC, tmasikt commented
hi, i am not an admin but you set it up wrongly. If you want a redirect to your github link, change record to this:
```json
"record": {
  "URL": "<your github profile link>"
}
```

2024-03-25 01:56 UTC, 21Z requested changes

2024-03-25 01:56 UTC, 21Z commented on domains/zwu.json
> +        "CNAME": "https://github.com/wu000168"
`CNAME` should not contain protocol
```suggestion
        "URL": "https://github.com/wu000168"
```

2024-03-26 15:27 UTC, Stef-00012 requested changes

2024-03-26 15:27 UTC, Stef-00012 commented on domains/zwu.json
> +        "CNAME": "https://github.com/wu000168"
as 21Z said, CNAME can not contain the protocol

2024-03-30 08:20 UTC, closed without merging