BETA: Register soulfulkrishna.is-a.dev
is-a-dev/register pull request #12927
Opened 2024-03-23 09:17 UTC by ecstaticsoul

Added `soulfulkrishna.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-23 10:07 UTC, 21Z requested changes

2024-03-23 10:07 UTC, 21Z commented on domains/soulfulkrishna.json
> +        "URL": "www.soulfulkrishna.is-a.dev"
- `URL` must contain protocol
- You can't set the same domain as `URL`

2024-03-25 01:54 UTC, 21Z requested changes

2024-03-25 01:54 UTC, 21Z commented on domains/kaybee.json
> +        "URL": "https://kaybee.is-a.dev"
You can't put the same domain for `URL`, put the link of the website you want the to redirect to.

2024-03-25 01:54 UTC, 21Z commented on domains/krish.json
> +        "URL": "https://krish.is-a.dev"
You can't put the same domain for `URL`

2024-03-25 01:54 UTC, 21Z commented on domains/soulfulkrishna.json
> +        "URL": "https://www.soulfulkrishna.is-a.dev"
You can't put the same domain for `URL`

2024-03-25 02:50 UTC, ecstaticsoul reviewed
Updated two pages. URL redirected to a GitHub page

2024-03-25 02:58 UTC, closed without merging