BETA: Register luther.is-a.dev
is-a-dev/register pull request #12925
Opened 2024-03-23 07:57 UTC by SeizedForge

Added `luther.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-23 10:08 UTC, 21Z requested changes

2024-03-23 10:08 UTC, 21Z commented on domains/luther.json
> +        "URL": "lutherkorsan.mooo.com"
`URL` doesn't have protocol

2024-03-26 13:17 UTC, Stef-00012 requested changes

2024-03-26 13:17 UTC, Stef-00012 commented on domains/luther.json
> +        "URL": "lutherkorsan.mooo.com"
As 21Z said, URL record must have a protocol

2024-03-26 13:17 UTC, Stef-00012 requested changes

2024-03-26 13:17 UTC, Stef-00012 commented on domains/luther.json
> +        "URL": "lutherkorsan.mooo.com"
As 21Z said, URL record must have a protocol

2024-03-30 08:17 UTC, closed without merging