Create hk
is-a-dev/register pull request #12933
Opened 2024-03-23 15:21 UTC by ericsia

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-03-23 16:48 UTC, tmasikt commented
nice website

2024-03-24 12:04 UTC, 21Z requested changes

2024-03-24 12:04 UTC, 21Z commented on domains/hk
delete this file

2024-03-25 01:52 UTC, 21Z requested changes

2024-03-25 01:52 UTC, 21Z commented on domains/hk.json
> +        "A": "185.27.134.137"
IP should be in an array
```suggestion
        "A": ["185.27.134.137"]
```

2024-03-26 15:28 UTC, Stef-00012 requested changes

2024-03-26 15:28 UTC, Stef-00012 commented on domains/hk.json
> +        "A": ["185.27.134.137"]
I cannot reach your website
> 185.27.134.137 didn’t send any data.

2024-03-26 17:08 UTC, Stef-00012 commented on domains/hk.json
> +        "A": ["185.27.134.137"]
> > I cannot reach your website
> > > 185.27.134.137 didn’t send any data.
> 
> You can't browse it directly using web browser. But the A record is correct

what will you use the domain for?

2024-03-26 17:28 UTC, Stef-00012 commented on domains/hk.json
> +        "A": ["185.27.134.137"]
then seems good

2024-03-26 17:28 UTC, Stef-00012 approved these changes

2024-03-26 17:29 UTC, merged

2024-03-26 19:52 UTC, Stef-00012 commented on domains/hk.json
> +        "A": ["185.27.134.137"]
no