BETA: Register dickerpopo.is-a.dev
is-a-dev/register pull request #12939
Opened 2024-03-23 20:41 UTC by DeveloperPopo

Added `dickerpopo.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-24 11:59 UTC, 21Z requested changes

2024-03-24 11:59 UTC, 21Z commented on domains/dickerpopo.json
> +        "CNAME": "dickerpopo.github.io"
404 Site not found

2024-03-26 15:22 UTC, Stef-00012 requested changes

2024-03-26 15:22 UTC, Stef-00012 commented on domains/dickerpopo.json
> +        "CNAME": "dickerpopo.github.io"
As 21Z said, 404 page

2024-03-30 08:19 UTC, closed without merging