Create ishh.json
is-a-dev/register pull request #12951
Opened 2024-03-24 08:40 UTC by ishh-xd

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-03-24 08:50 UTC, ishh-xd commented
The website is almost complete. I've to just fix few bugs. (Currently the github.io domain redirects to old link, as soon as CNAME is added it'll be fixed.)

2024-03-24 11:47 UTC, 21Z requested changes

2024-03-24 11:47 UTC, 21Z commented on domains/ishh.json
> +    "username": "Ishh",
```suggestion
    "username": "ishh-xd",
```

2024-03-24 15:32 UTC, ishh-xd commented
Was closed by mistake!
# Preview: (Mobile)
![Web Preview](https://github.com/is-a-dev/register/assets/88816438/2bea2916-b5f0-47c1-95eb-de212a63b5ac)

2024-03-25 17:45 UTC, iostpa approved these changes

2024-03-25 17:45 UTC, merged