BETA: Register niksne .is-a.dev
is-a-dev/register pull request #12968
Opened 2024-03-25 00:48 UTC by NikSneMC

Added `niksne .is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-26 15:33 UTC, Stef-DP requested changes

2024-03-26 18:11 UTC, NikSneMC commented on domains/niksne.json
> +        "CNAME": "www.niksne.ru"
> I cannot reach your website
> 
> > [www.niksne.ru](http://www.niksne.ru) redirected you too many times.

Yup, my website is WIP now

2024-03-30 08:21 UTC, closed without merging

2024-04-07 19:11 UTC, NikSneMC commented
The site is reacheble now

2024-04-08 12:54 UTC, VaibhavSys commented
> The site is reacheble now

You should reopen the PR

2024-04-08 14:09 UTC, NikSneMC commented
> > The site is reacheble now
> 
> You should reopen the PR

#13245