BETA: Register anton.is-a.dev
is-a-dev/register pull request #12971
Opened 2024-03-25 06:27 UTC by rorosin

Added `anton.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-26 15:35 UTC, Stef-00012 requested changes

2024-03-26 15:35 UTC, Stef-00012 commented on domains/rorosin.json
> +        "CNAME": "ru.ardev.tk."
Invalid CNAME record, remove the last `.`

2024-03-26 15:35 UTC, Stef-00012 commented on domains/anton.json
> +        "URL": "https://rorosin.ru/"
I cannot reach your website, keeps on loading

2024-03-26 17:36 UTC, rorosin commented
@Stef-00012 I`ve fixed those problems

2024-03-30 08:22 UTC, Stef-00012 approved these changes

2024-03-30 08:22 UTC, merged