Create zffu.json
is-a-dev/register pull request #13013
Opened 2024-03-26 22:01 UTC by Zffu

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

Here is my website hosted on Github Pages https://zffu.github.io

2024-03-26 23:25 UTC, Stef-00012 requested changes

2024-03-27 07:02 UTC, YouFoundAlpha commented on domains/zffu.json
> +    "URL": "zffumc.github.io"
User has updated the URL record and it is reachable

2024-03-27 07:03 UTC, YouFoundAlpha approved these changes
Looks good
Now you'll just have to wait until a maintainer to merge it

2024-03-27 07:05 UTC, YouFoundAlpha requested changes
Please add https:// to the beginning of the record to make it redirect to zffu.github.io

2024-03-27 13:12 UTC, Stef-00012 approved these changes

2024-03-27 13:12 UTC, Stef-00012 commented on domains/zffu.json
> +    "URL": "zffu.github.io"
URL record must have a protocol (`https://`)

2024-03-27 13:12 UTC, Stef-00012 requested changes

2024-03-27 13:12 UTC, Stef-00012 commented on domains/zffu.json
> +    "URL": "zffu.github.io"
URL record must have a protocol (https://)

2024-03-27 13:12 UTC, Stef-00012 commented on domains/zffu.json
> +    "URL": "zffu.github.io"
(approved for error before)

2024-03-27 14:20 UTC, 21Z requested changes

2024-03-27 14:20 UTC, 21Z commented on domains/zffu.json
> +    "URL": "zffu.github.io"
```suggestion
    "CNAME": "zffu.github.io"
```

2024-03-27 16:08 UTC, Stef-00012 requested changes

2024-03-27 16:08 UTC, Stef-00012 commented on domains/zffu.json
> +    "CNAME": "https://zffu.github.io"
CNAME can not contain `https://`

2024-03-27 17:46 UTC, Stef-00012 approved these changes
seems good to me

2024-03-27 17:46 UTC, merged