BETA: Register socials.chiragnahata.is-a.dev
is-a-dev/register pull request #13062
Opened 2024-03-29 17:16 UTC by chiragnahata

Added `socials.chiragnahata.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-03-29 22:06 UTC, Stef-00012 requested changes

2024-03-29 22:06 UTC, Stef-00012 commented on domains/socials.chiragnahata.json
you can't make a subdomain of `chiragnahata` because the it doesn't exist

2024-03-30 04:35 UTC, chiragnahata commented
Already opened one previously : https://github.com/is-a-dev/register/pull/7940

Opened new : https://github.com/is-a-dev/register/pull/13071

2024-03-30 07:38 UTC, chiragnahata commented on domains/socials.chiragnahata.json
Already opened one previously : https://github.com/is-a-dev/register/pull/7940

Opened new : https://github.com/is-a-dev/register/pull/13071

2024-03-30 12:23 UTC, closed without merging