Delete domains/ishan.json
is-a-dev/register pull request #13099
Opened 2024-03-31 07:10 UTC by quackduck

I'm trying to delete this domain.

2024-03-31 12:48 UTC, Stef-00012 approved these changes

2024-03-31 12:49 UTC, Stef-00012 requested changes
merge conflicts, fix them

2024-04-02 22:31 UTC, quackduck commented
I'm not sure how to resolve the conflict when the conflict is that the file is deleted and the whole point of the PR is to delete the file

2024-04-03 10:26 UTC, DEV-DIBSTER commented
I think your files might have not been updated with the latest branch. Recommend closing this PR, deleting your fork, reforking, and then make your changes to make sure there's no conflicts whatsoever.

2024-04-04 04:42 UTC, closed without merging