Create opott.json
is-a-dev/register pull request #13107
Opened 2024-03-31 13:54 UTC by opott

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview
opott.github.io
still under development

2024-03-31 17:42 UTC, CuteDog5695 approved these changes
seems good to me

2024-03-31 17:43 UTC, CuteDog5695 requested changes, later dismissed

2024-03-31 17:43 UTC, CuteDog5695 commented on domains/opott.json
> +        "URL": "opott.github.io",
oh nvm, URL doesnt have protocol

2024-04-03 10:29 UTC, DEV-DIBSTER approved these changes

2024-04-03 10:30 UTC, merged