BETA: Register safaa-mammed.is-a.dev
is-a-dev/register pull request #13108
Opened 2024-03-31 14:20 UTC by safaa-mammed

Added `safaa-mammed.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-02 08:18 UTC, TerraPlayz requested changes
what is this

2024-04-02 13:56 UTC, safaa-mammed commented
> what is this

hi there, it's a web portfolio that i'm deploying.

2024-04-03 18:46 UTC, CuteDog5695 requested changes

2024-04-03 18:46 UTC, CuteDog5695 commented on domains/safaa-mammed.json
> +        "CNAME": "0120762dd104775365bb3aac447cd87b.safaa-mammed.is.a.dev. cname _82de621132b5bcbb7855a38498d4e51e.mhbtsbpdnt.acm-validations.aws."
this seems to be txt verification, can you like point the domain to your website?

2024-04-07 14:17 UTC, closed without merging