Updated record for youfoundalpha.json
is-a-dev/register pull request #13175
Opened 2024-04-03 19:41 UTC by YouFoundAlpha

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-04-03 19:42 UTC, YouFoundAlpha commented
If any of you are wondering why they are changes made to the validations.test.js file
https://github.com/is-a-dev/register/issues/13174

2024-04-09 01:07 UTC, DEV-DIBSTER requested changes

2024-04-09 01:07 UTC, DEV-DIBSTER commented on domains/youfoundalpha.json
> +   "URL": "https://ap.yfadev.pw",
Error 1013.

2024-04-09 05:41 UTC, YouFoundAlpha commented
Fixed

2024-04-10 06:21 UTC, closed without merging