Register lnk.is-a.dev
is-a-dev/register pull request #13193
Opened 2024-04-04 15:46 UTC by littletheworld

Register lnk.is-a.dev with CNAME record pointing to cname.short.io.

2024-04-07 17:13 UTC, Stef-00012 requested changes, later dismissed

2024-04-07 17:13 UTC, Stef-00012 commented on domains/lnk.json
> +           "email": "79756355+littletheworld@users.noreply.github.com",
you can't use a noreply email

2024-04-07 17:32 UTC, littletheworld commented
I've edited my email.

On Mon, Apr 8, 2024, 12:14 AM Stef_DP ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In domains/lnk.json
> <https://github.com/is-a-dev/register/pull/13193#discussion_r1555013282>:
>
> > @@ -0,0 +1,12 @@
> +{
> +        "owner": {
> +           "username": "littletheworld",
> +           "email": ***@***.***",
>
> you can't use a noreply email
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/13193#pullrequestreview-1985134615>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATAPYQZ2MTYS6VBDOLJTJ3TY4F5GTAVCNFSM6AAAAABFXRH36CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSOBVGEZTINRRGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-09 01:05 UTC, DEV-DIBSTER approved these changes

2024-04-09 01:06 UTC, merged