BETA: Register nikyisme.is-a.dev
is-a-dev/register pull request #13205
Opened 2024-04-05 05:37 UTC by nikytap1n

Added `nikyisme.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-05 08:55 UTC, Stef-00012 requested changes

2024-04-05 08:55 UTC, Stef-00012 commented on domains/nikyisme.json
> +        "CNAME": "nikytest.github.io"
I cannot reach your website

2024-04-05 08:55 UTC, Stef-00012 commented on domains/nikytest.json
> +        "CNAME": "https://nikytap1n.github.io/"
CNAME can not contian / or https://

2024-04-10 15:07 UTC, CuteDog5695 requested changes
all of the CNAME records cant be visited (also how many domains do you need because this is a lot lmao)

2024-04-11 09:08 UTC, closed without merging