Register namuenpitayakom.is-a.dev
is-a-dev/register pull request #13219
Opened 2024-04-05 16:02 UTC by Pooh3133

Register namuenpitayakom.is-a.dev with TXT record pointing to test.

2024-04-06 01:43 UTC, 21Z requested changes

2024-04-06 01:43 UTC, 21Z commented on domains/namuenpitayakom.json
> +            "TXT": "test"
TXT records don't do anything.

2024-04-07 09:46 UTC, CuteDog5695 requested changes

2024-04-07 09:46 UTC, CuteDog5695 commented on domains/namuenpitayakom.json
> +            "TXT": "test"
txt doesnt do shit

2024-04-11 09:08 UTC, closed without merging