BETA: Register devendrakanojiya.is-a.dev
is-a-dev/register pull request #13221
Opened 2024-04-06 00:08 UTC by devendrakanojiya

Added `devendrakanojiya.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-06 01:42 UTC, 21Z requested changes

2024-04-06 01:42 UTC, 21Z commented on domains/devendrakanojiya.json
> +        "CNAME": "devenkanojiya.netlify.app"
Netlify isn't supported atm

2024-04-07 17:14 UTC, Stef-00012 requested changes

2024-04-07 17:14 UTC, Stef-00012 commented on domains/devendrakanojiya.json
> +        "CNAME": "devenkanojiya.netlify.app"
as @21Z said, netlify is not supported

2024-04-08 18:31 UTC, closed without merging