BETA: Register lipi.is-a.dev
is-a-dev/register pull request #13258
Opened 2024-04-08 14:08 UTC by ReticentFacade

Added `lipi.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-08 14:14 UTC, 21Z requested changes

2024-04-08 14:14 UTC, 21Z commented on domains/lipi.json
> +        "URL": "lipi.is-a.dev"
`URL` should contain protocol
`URL` can't be the same domain

2024-04-09 09:40 UTC, 21Z requested changes

2024-04-09 09:40 UTC, 21Z commented on domains/lipi.json
> +        "URL": "https://lipi.is-a.dev"
`URL` has to be a different website and not the same domain

2024-04-10 15:24 UTC, CuteDog5695 requested changes
what 21Z said

2024-04-14 01:23 UTC, closed without merging