BETA: Register palekiox.is-a.dev
is-a-dev/register pull request #13276
Opened 2024-04-09 08:18 UTC by palekiox

Added `palekiox.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-10 15:36 UTC, CuteDog5695 requested changes, later dismissed
can you add a bit more stuff on your site?

2024-04-10 20:34 UTC, palekiox commented
> can you add a bit more stuff on your site?

ya

2024-04-11 08:28 UTC, palekiox commented
> can you add a bit more stuff on your site?

done

2024-04-14 01:25 UTC, DEV-DIBSTER approved these changes

2024-04-14 01:25 UTC, merged