Updates
is-a-dev/register pull request #13277
Opened 2024-04-09 09:04 UTC by tylerdotnet

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-04-09 09:44 UTC, 21Z requested changes

2024-04-09 09:44 UTC, 21Z commented on domains/tyler.json
> +        "CNAME": "https://tylerdotnet.github.io/TylerDotNet-Portfolio/"
`CNAME` can't contain protocol or `/`

2024-04-10 16:02 UTC, CuteDog5695 requested changes

2024-04-10 16:02 UTC, CuteDog5695 commented on domains/domains/_github-pages-challenge-tylerdotnet.tyler.json
you made another domain folder and putted it in the new one, move this .json file to the other domain file (which your tyler.json is located)

2024-04-14 01:25 UTC, closed without merging