Update youfoundalpha.json
is-a-dev/register pull request #13296
Opened 2024-04-10 06:23 UTC by YouFoundAlpha

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-04-10 15:48 UTC, CuteDog5695 requested changes

2024-04-10 15:48 UTC, CuteDog5695 commented on domains/youfoundalpha.json
>      "TXT": "v=spf1 include:spf.improvmx.com ~all"
you cant use CNAME with any other record (also you cant have https:// on CNAME)

2024-04-10 19:55 UTC, YouFoundAlpha reviewed
Fixed

2024-04-11 04:23 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-04-11 04:23 UTC, merged

2024-04-11 07:40 UTC, YouFoundAlpha commented
Thank you