Create textodeejemplo.json and _deta.json
is-a-dev/register pull request #13319
Opened 2024-04-10 23:49 UTC by VSeryi

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] You have completed your website. 
- [X] The website is reachable.  
- [X] You're not using Vercel or Netlify.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.  

## Website Link/Preview
Link: https://textodeejemplo-1-b4120513.deta.app/

## Extra Info
I’m using [deta.space](https://deta.space/ ) to host the website.

To add the domain, they require both an A record (textodeejemplo.json) and a TXT record in _deta (_deta.json).

As indicated in ‘[Other Services](https://www.is-a.dev/docs/other/)’, I’ve set it up exactly as stated, but I’m not sure if it should be _deta.textodeejemplo.json

[More information](https://deta.space/docs/en/use/space-apps/domains#custom-domains) about use custom domains in Deta.

Thank you!

2024-04-11 08:47 UTC, omsenjalia requested changes
hey i understand your concern. and yes you will have to make `_deta.yoursubdomain.json`

2024-04-11 22:19 UTC, VSeryi reviewed
> hey i understand your concern. and yes you will have to make `_deta.yoursubdomain.json`

Thanks for your help! Changes done!

2024-04-12 17:26 UTC, CuteDog5695 requested changes

2024-04-12 17:26 UTC, CuteDog5695 commented on domains/_deta.textodeejemplo.json
we dont support underscores in domains (also you cant use _deta.subdomain.json since we dont support that atm i think)

2024-04-12 17:26 UTC, CuteDog5695 commented on domains/textodeejemplo.json
> +      "A": "76.223.55.44"
IP needs to be in an array

2024-04-12 18:33 UTC, VSeryi commented on domains/textodeejemplo.json
> +      "A": "76.223.55.44"
Fixed!

2024-04-12 18:36 UTC, VSeryi commented on domains/_deta.textodeejemplo.json
I only need it for the same process as _discord or _github.

I need it to verify domain ownership.

Couldn't it be used in the same way as the other verification domains?

If not, you can close the Pull Request :S

Thanks!

2024-04-13 13:12 UTC, VSeryi commented
Answered by Discord.

If you want support for _deta you have to open a request to discuss whether to add it or not.

Thank you very much!

2024-04-13 13:12 UTC, closed without merging