BETA: Register nikywelcome.is-a.dev
is-a-dev/register pull request #13338
Opened 2024-04-12 03:55 UTC by nikyy2

Added `nikywelcome.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-12 03:56 UTC, nikyy2 commented
## github link here: https://nikytap1n.github.io/28nikywelcome03.github.io/

2024-04-12 17:21 UTC, CuteDog5695 requested changes

2024-04-12 17:21 UTC, CuteDog5695 commented on domains/nikywelcome.json
> +        "CNAME": "28nikywelcome03.github.io"
to link the site you would need to use nikytap1n.github.io instead of this CNAME (since the link starts with the domain im suggesting you to add)

2024-04-13 13:11 UTC, CuteDog5695 approved these changes
seems good to me now

2024-04-13 13:11 UTC, merged