Create heroprotagonist.json
is-a-dev/register pull request #13370
Opened 2024-04-14 06:33 UTC by carafelix

# I plan on using it for all my Github Pages deploys. Thanks in advance. Great Work
## requirements

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://carafelix.github.io/codenames-coop/

2024-04-14 13:49 UTC, Stef-00012 requested changes

2024-04-14 13:49 UTC, Stef-00012 commented on domains/heroprotagonist.json
you can't add an empty file

2024-04-14 16:31 UTC, carafelix commented on domains/heroprotagonist.json
im sorry, i'll update now

2024-04-15 17:58 UTC, carafelix commented
Should be ok now

2024-04-20 09:14 UTC, Stef-00012 approved these changes

2024-04-20 09:15 UTC, merged