merge my domain
is-a-dev/register pull request #13379
Opened 2024-04-14 16:14 UTC by educationalgamer

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://portfolio-educationalgamer.vercel.app/

2024-04-19 13:10 UTC, 21Z requested changes

2024-04-19 13:10 UTC, 21Z commented on domains/anshu.json
> +      "CNAME": "https://portfolio-educationalgamer.vercel.app/"
`CNAME` can't contain protocol or `/`

2024-04-20 09:54 UTC, Stef-00012 requested changes

2024-04-20 09:54 UTC, Stef-00012 commented on domains/anshu.json
> +      "CNAME": "https://portfolio-educationalgamer.vercel.app/"
see @21Z comment, also vercel is not supported yet (might be soon)

2024-04-25 10:54 UTC, closed without merging