Create jinix6.is-a.dev
is-a-dev/register pull request #13388
Opened 2024-04-14 22:15 UTC by jinix6

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://jinix6.github.io/

2024-04-20 09:03 UTC, Stef-00012 approved these changes

2024-04-20 09:12 UTC, Stef-00012 requested changes

2024-04-20 09:12 UTC, Stef-00012 commented on domains/jinix6.is-a.dev
File should be a JSON file

2024-04-25 10:56 UTC, orxngc commented
Inactive

2024-04-25 10:56 UTC, closed without merging