BETA: Register danielmoore.is-a.dev
is-a-dev/register pull request #13386
Opened 2024-04-14 20:46 UTC by danieljemoore

Added `danielmoore.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-19 13:23 UTC, 21Z requested changes

2024-04-19 13:23 UTC, 21Z commented on domains/danielmoore.json
> +        "URL": "danieljemoore.com"
`URL` should contain protocol

2024-04-20 09:56 UTC, Stef-00012 requested changes

2024-04-20 09:56 UTC, Stef-00012 commented on domains/danielmoore.json
> +        "URL": "danieljemoore.com"
see @21Z comment

2024-04-25 10:55 UTC, closed without merging