Update ajay.json website link
is-a-dev/register pull request #13384
Opened 2024-04-14 19:24 UTC by Aj-Cdr

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-04-19 13:19 UTC, 21Z commented
Duplicate #13383

2024-04-19 13:19 UTC, 21Z requested changes

2024-04-20 09:55 UTC, Stef-00012 requested changes

2024-04-20 09:55 UTC, Stef-00012 commented on domains/ajay.json
> +        "URL": "ajay.framer.ai"
see @21Z comment

2024-04-25 10:54 UTC, closed without merging