Create sailesh.json
is-a-dev/register pull request #134
Opened 2020-10-09 13:29 UTC by saileshbro

2020-10-09 13:58 UTC, abhinavdalal requested changes

2020-10-09 13:58 UTC, abhinavdalal commented on domains/sailesh.json
> +    "CNAME": "https://saileshbro.github.io/saileshbro/",
@saileshbro 
CNAME needs to be saileshbro.github.io
you may want to add it as URL
```suggestion
    "URL": "https://saileshbro.github.io/saileshbro/",
```

2020-10-11 07:46 UTC, saileshbro commented
Can anyone review this?

2020-10-12 12:09 UTC, phenax requested changes

2020-10-12 12:09 UTC, phenax commented on domains/sailesh.json
> +    "URL": "https://saileshbro.github.io/saileshbro/"
You cannot have a cname and url redirection together this way. It should either be a cname record to your github pages link or a url redirection.

```suggestion
    "CNAME": "saileshbro.github.io"
```

2020-10-12 13:58 UTC, saileshbro commented
@phenax Is it okay now?

2020-10-12 18:58 UTC, phenax approved these changes

2020-10-12 18:59 UTC, merged