BETA: Register chrivav.is-a.dev
is-a-dev/register pull request #13407
Opened 2024-04-15 14:12 UTC by FiloClient

Added `chrivav.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-19 14:42 UTC, 21Z requested changes

2024-04-19 14:42 UTC, 21Z commented on domains/chrivav.json
> +        "URL": "is-a.dev"
Invalid URL record

2024-04-20 10:02 UTC, Stef-DP requested changes

2024-04-20 10:02 UTC, Stef-00012 commented on domains/chrivav.json
> +        "URL": "is-a.dev"
see @21Z comment

2024-04-20 15:46 UTC, Stef-00012 requested changes

2024-04-20 15:46 UTC, Stef-00012 commented on domains/chrivav.json
> +        "URL": "chrivav.is-a.dev"
- Missing protocol
- website can not reidrect to itself

2024-04-25 10:58 UTC, closed without merging