Created mihai.json!
is-a-dev/register pull request #1340
Opened 2021-11-03 20:27 UTC by 8xu

2021-11-19 13:25 UTC, 8xu commented
Is there anyone here? 😸

2022-01-17 13:45 UTC, phenax requested changes, later dismissed
Sorry for the delayed response. The json file needs to contain a single record. You can look at existing records for reference.

2022-01-17 13:48 UTC, 8xu commented
> Sorry for the delayed response. The json file needs to contain a single record. You can look at existing records for reference.

Can I link it on Cloudflare?

2022-01-20 17:09 UTC, phenax commented
I'm unfamiliar with the setup process but I think it should be possible

2022-03-11 17:38 UTC, 8xu commented
Fixed it, should be good now to be honest! :)

2022-03-12 13:27 UTC, TheBotlyNoob requested changes, later dismissed

2022-03-12 13:27 UTC, TheBotlyNoob commented on domains/mihai.json
> +    "CNAME": "https://8xu.github.io/web/"
a `CNAME` cannot have a `/`. You can rename the repository to `8xu.github.io`, and then change the `CNAME` to `8xu.github.io`, or if you really want to keep that repository, you can change it to a `URL` record.

2022-03-18 07:43 UTC, MaskDuck approved these changes

2022-03-18 07:46 UTC, merged

2022-03-18 07:46 UTC, MaskDuck commented
@8xu sorry for the delay but your domain is now accepted!

2022-03-18 10:08 UTC, 8xu commented
Thanks!