register akshya.is-a.dev domain
is-a-dev/register pull request #13404
Opened 2024-04-15 12:55 UTC by LowkeyGUY4444

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://lowkeyguy4444.github.io/

2024-04-17 11:24 UTC, LowkeyGUY4444 commented
what is wrong with my request.

2024-04-20 09:44 UTC, Stef-00012 requested changes, later dismissed

2024-04-20 09:44 UTC, Stef-00012 commented on domains/_github-pages-challenge-LowkeyGUY4444.akshya.json
`akshya` doesn't exist so you can't add a subdomain of it

2024-04-20 09:44 UTC, Stef-00012 commented on domains/akshya.is-a.dev.json
file name can not contain `.is-a.dev`

2024-04-20 16:22 UTC, LowkeyGUY4444 commented
now file renamed
can you check again

2024-04-24 14:05 UTC, LowkeyGUY4444 commented
can you check again

2024-04-25 10:57 UTC, orxngc approved these changes
Looks fine now.

2024-04-27 02:13 UTC, DEV-DIBSTER approved these changes

2024-04-27 02:15 UTC, merged