BETA: Register zeus-sec.is-a.dev
is-a-dev/register pull request #13417
Opened 2024-04-15 20:15 UTC by l33t1

Added `zeus-sec.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-20 09:17 UTC, Stef-00012 requested changes

2024-04-20 09:17 UTC, Stef-00012 commented on domains/x1337.json
> +        "A": ["178.33.36.88"]
I cannot reach your website, 404

2024-04-20 09:17 UTC, Stef-00012 commented on domains/x1337.pw.json
> +        "A": ["185.234.67.28"]
I cannot reach your website, 404

2024-04-20 09:17 UTC, Stef-00012 commented on domains/zeusapi.json
> +        "A": ["185.234.67.28"]
I cannot reach your website, 404

2024-04-20 09:17 UTC, Stef-00012 commented on domains/legit.json
> +        "URL": "https://zeusapi.ch"
I cannot reach your website, Connection timed out Error code 522

2024-04-25 11:00 UTC, closed without merging

2024-04-26 05:00 UTC, l33t1 reviewed
{
    "description": "Describe the use of this subdomain",
    "repo": "https://github.com/l33t1/l33t1.github.io",
    "owner": {
        "username": "l33t1",
        "email": "yassineonet@gmail.com",
        "twitter": "<twitter-username>"
    },
    "record": {
        "CNAME": "l33t1.github.io"
    }
}

2024-04-26 05:01 UTC, triach-rold commented
Website is still unreachable, btw. (Seems like the repo has been deleted too.)