BETA: Register jagad .is-a.dev
is-a-dev/register pull request #13419
Opened 2024-04-15 21:28 UTC by Jagadoye

Added `jagad .is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-20 09:27 UTC, Stef-00012 requested changes

2024-04-20 09:27 UTC, Stef-00012 commented on domains/jagad .json
Invalid file name, can not contain spaces

2024-04-20 09:27 UTC, Stef-00012 commented on domains/jagad-r.json
> +        "A": ["147.56.097.097"]
Invalid IP address

2024-04-20 09:27 UTC, Stef-00012 commented on domains/jgd.json
> +        "URL": "github.com/jagadoye/jagadoye.github.io"
Missing protocol (https://)

2024-04-20 09:27 UTC, Stef-00012 commented on domains/my-domain.json
> +        "CNAME": "github.com/jagadoye/jagadoye.github.io"
CNAME can not contain /

2024-04-25 11:01 UTC, orxngc commented
Inactive

2024-04-25 11:01 UTC, closed without merging