BETA: Register nycrp.is-a.dev
is-a-dev/register pull request #13411
Opened 2024-04-15 16:21 UTC by savageemote1

Added `nycrp.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-19 14:43 UTC, 21Z requested changes

2024-04-19 14:44 UTC, savageemote1 commented on domains/nycrp.json
> +        "URL": "nycrp.is-a.dev/"
what's that exactly, 



> You can't redirect to your own domain `URL` should contain protocol

2024-04-20 10:03 UTC, Stef-00012 requested changes

2024-04-20 10:03 UTC, Stef-00012 commented on domains/nycrp.json
> +        "URL": "nycrp.is-a.dev/"
> what's that exactly,
> 
> > You can't redirect to your own domain `URL` should contain protocol

`https://`

2024-04-20 10:03 UTC, Stef-00012 commented on domains/nycrp.json
> +        "URL": "nycrp.is-a.dev/"
you can't redirect the site to itself

2024-04-20 10:04 UTC, Stef-00012 commented on domains/nycrp.json
> +        "URL": "nycrp.is-a.dev/"
> what's that exactly,
> 
> > You can't redirect to your own domain `URL` should contain protocol

`https://`

2024-04-25 10:59 UTC, orxngc commented
Inactive

2024-04-25 10:59 UTC, closed without merging