BETA: Register jagad-r.is-a.dev
is-a-dev/register pull request #13461
Opened 2024-04-18 11:37 UTC by LM-xio

Added `jagad-r.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-24 04:05 UTC, 21Z requested changes

2024-04-24 04:05 UTC, 21Z commented on domains/jagad-renata.json
> +        "CNAME": "lm-xio.github.io"
this is mergable ig but you cant have more than one custom domain on a repo

2024-04-24 04:05 UTC, 21Z commented on domains/xio-develpment.json
> +        "CNAME": "lm-xio.github.io"
you cant have more than one custom domain on a repo

2024-04-25 11:08 UTC, orxngc commented
You cannot have multiple CNAMEs pointing toward one domain.

2024-04-25 11:08 UTC, closed without merging