Register robonamari.is-a.dev
is-a-dev/register pull request #13465
Opened 2024-04-18 13:11 UTC by robonamari

Register robonamari.is-a.dev with TXT record pointing to _discord.robonamari.is-a.dev.

2024-04-19 12:57 UTC, 21Z requested changes

2024-04-19 12:57 UTC, 21Z commented on domains/robonamari.json
> +            "TXT": "_discord.robonamari.is-a.dev"
`TXT` records does nothing to your website, also for discord's TXT verification you need to make another domain `_discord.robonamari.is-a.dev` with TXT record (content) given by discord

2024-04-20 09:52 UTC, Stef-00012 requested changes

2024-04-20 09:52 UTC, Stef-00012 commented on domains/robonamari.json
see https://www.is-a.dev/docs/discord_verification/

2024-04-27 02:15 UTC, closed without merging