Create eagler.json
is-a-dev/register pull request #13509
Opened 2024-04-20 19:11 UTC by stpv221

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x ] The website is reachable.  
- x[ ] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x ] There is sufficient information at the `owner` field.  

## Website Link/Preview

eagler.is-a.dev

2024-04-20 19:39 UTC, stpv221 commented
When the server is running the wep page should look like You are viewing the physical websocket of `domain`

2024-04-21 12:14 UTC, Stef-DP requested changes

2024-04-21 12:15 UTC, Stef-00012 commented on domains/eagler.json
> +    "CNAME": "remarkably-active-mammoth.ngrok-free.app"
"Tunnel remarkably-active-mammoth.ngrok-free.app not found"

2024-04-21 16:09 UTC, stpv221 commented
Ye I still have to set it up I'm working on it.

2024-04-27 02:17 UTC, closed without merging