Add domain
is-a-dev/register pull request #13510
Opened 2024-04-20 19:59 UTC by dntluchini

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-04-21 12:32 UTC, Stef-00012 commented
your domain has no records

2024-04-21 15:38 UTC, dntluchini reviewed
Added record and github page url

2024-04-22 02:58 UTC, DEV-DIBSTER requested changes

2024-04-22 02:58 UTC, DEV-DIBSTER commented on domains/dnt-luchini.json
> +        "URL": "https://dntluchini.github.io/Portfolio/",
Cannot have CNAME and URL together.

2024-04-22 02:58 UTC, DEV-DIBSTER commented on domains/dntluchini.json
> +    }
There's no records here.

2024-04-24 12:18 UTC, dntluchini commented
Any news?

2024-04-27 02:17 UTC, closed without merging