BETA: Register kota.is-a.dev
is-a-dev/register pull request #13529
Opened 2024-04-21 14:02 UTC by sharkota

Added `kota.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-23 08:26 UTC, Stef-00012 requested changes

2024-04-23 08:26 UTC, Stef-00012 commented on domains/kota.json
> +        "CNAME": "sharkota.github.io"
I cannot reach your website, 404 page

2024-04-23 08:26 UTC, Stef-00012 submitted a review, later dismissed

2024-04-23 08:26 UTC, Stef-00012 commented on domains/kota.json
> +        "CNAME": "sharkota.github.io"
I cannot reach your website, 404 page

2024-04-23 19:33 UTC, sharkota commented on domains/kota.json
> +        "CNAME": "sharkota.github.io"
Should be fixed now

2024-04-27 02:25 UTC, DEV-DIBSTER approved these changes

2024-04-27 02:26 UTC, merged