BETA: Register sohil.is-a.dev
is-a-dev/register pull request #13558
Opened 2024-04-23 08:53 UTC by EndingPencil

Added `sohil.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-25 10:16 UTC, orxngc approved these changes

2024-04-25 10:21 UTC, omsenjalia approved these changes

2024-04-26 18:55 UTC, CuteDog5695 requested changes

2024-04-26 18:55 UTC, CuteDog5695 commented on domains/f1rogman.json
invalid json file

2024-04-26 18:55 UTC, CuteDog5695 commented on domains/f1rogman.json
> +        "twitter": "<twitter-username>",
if you dont have twitter then remove the twitter line

2024-04-27 21:09 UTC, closed without merging