BETA: Register la.is-a.dev
is-a-dev/register pull request #13557
Opened 2024-04-23 06:23 UTC by Mrlabani

Added `la.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-23 08:22 UTC, Stef-00012 requested changes

2024-04-23 08:22 UTC, Stef-00012 commented on domains/labanii.json
> +    "CNAME": "lbni.github.io"
I cannot reach your website, 404 page

2024-04-27 03:36 UTC, triach-rold commented
I can see that the [repo](https://github.com/Mrlabani/lbni.github.io) exists but the website is still unreachable. I would suggest making a simple index.html page with some basic information for it to be considered "complete". Besides, since the name of the website is different from your github username, the website's link would be Mrlabani.github.io/lbni.github.io.

2024-04-27 03:37 UTC, triach-rold requested changes
^

2024-05-01 01:28 UTC, closed without merging