BETA: Register statuscheck.is-a.dev
is-a-dev/register pull request #13583
Opened 2024-04-24 06:41 UTC by digitallamp

Added `statuscheck.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-25 11:15 UTC, orxngc submitted a review, later dismissed

2024-04-27 02:20 UTC, DEV-DIBSTER approved these changes, later dismissed

2024-04-27 02:23 UTC, DEV-DIBSTER approved these changes

2024-04-27 03:33 UTC, triach-rold requested changes
Website exists and is reachable but is incomplete.

2024-04-27 08:30 UTC, Stef-00012 requested changes
You should complete your website

2024-05-01 01:29 UTC, closed without merging