ADD odi.is-a.dev
is-a-dev/register pull request #13590
Opened 2024-04-24 13:55 UTC by Vauth

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-04-25 11:23 UTC, orxngc requested changes, later dismissed
Error 404 when trying to access site.

2024-04-25 14:19 UTC, Vauth commented
> Error 404 when trying to access site.

The webpage is on vauth.github.io/hueco, but you way CNAME should not contain '/', Any solution?

2024-04-27 21:08 UTC, DEV-DIBSTER requested changes

2024-04-27 21:08 UTC, DEV-DIBSTER commented on domains/odi.json
> +    "CNAME": "vauth.github.io"
404 GitHub page.

2024-04-27 21:08 UTC, DEV-DIBSTER approved these changes

2024-04-27 21:09 UTC, merged