Register API to. my domain (Zoom). DISCORD & GITHUB verification system.
is-a-dev/register pull request #13607
Opened 2024-04-25 05:00 UTC by TheOldZoom

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-04-25 17:45 UTC, 21Z requested changes

2024-04-25 17:45 UTC, 21Z commented on domains/api.zoom.json
> +        "CNAME": "theoldzoom.github.io/api/"
`CNAME` can't contain `/`

2024-04-26 16:57 UTC, orxngc submitted a review, later dismissed

2024-04-26 16:58 UTC, triach-rold approved these changes

2024-04-26 17:34 UTC, CuteDog5695 requested changes

2024-04-26 17:34 UTC, CuteDog5695 commented on domains/_discord.zoom.is-a.dev.json
remove .is-a.dev from the json file please

2024-04-26 17:38 UTC, CuteDog5695 approved these changes
should be fine now

2024-04-26 17:39 UTC, merged

2024-04-27 00:30 UTC, TheOldZoom commented
Thanks you @CuteDog5695