BETA: Register zymi.is-a.dev
is-a-dev/register pull request #13639
Opened 2024-04-27 10:58 UTC by Zyminotfound

Added `zymi.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-27 11:09 UTC, triach-rold approved these changes

2024-04-27 11:12 UTC, triach-rold commented
Oops. I accidentally approved the wrong PR. mb, had multiple PRs open on my monitor.

2024-04-27 11:15 UTC, CuteDog5695 requested changes

2024-04-27 11:15 UTC, CuteDog5695 commented on domains/Zymi.json
> +        "email": "notzymi0@gmail.com",
remove the comma at the end in email line

2024-04-27 11:15 UTC, CuteDog5695 commented on domains/Zymi.json
> +        "CNAME": "Zymi.github.io"
404 page

2024-04-27 11:15 UTC, CuteDog5695 commented on domains/zymi.json
> +        "CNAME": "zymi.github.io"
404 page

2024-04-27 11:15 UTC, CuteDog5695 commented on domains/Zymi.json
all letters need to be lower case here, but since you have another json file thats almost the same name delete one of them

2024-04-27 11:24 UTC, Zyminotfound commented on domains/zymi.json
> +        "CNAME": "zymi.github.io"
how do i fix it?

2024-04-27 21:07 UTC, DEV-DIBSTER submitted a review, later dismissed

2024-04-27 21:07 UTC, DEV-DIBSTER commented on domains/zymi.json
> +        "CNAME": "zyminotfound.github.io"
404 GitHub page.

2024-04-28 08:18 UTC, CuteDog5695 approved these changes
its fine now, website is not hosted on zyminotfound.github.io so thats why it gives a 404 error

2024-04-28 08:19 UTC, merged