BETA: Register dtech.is-a.dev
is-a-dev/register pull request #13719
Opened 2024-04-30 13:40 UTC by pgwiz

Added `dtech.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-30 14:12 UTC, orxngc requested changes
Your CNAME should point somewhere, not be the domain you want.

2024-05-01 18:33 UTC, pgwiz reviewed
Changed record to TXT

2024-05-02 06:19 UTC, CuteDog5695 requested changes

2024-05-02 06:19 UTC, CuteDog5695 commented on domains/dtech.json
> +        "TXT": "_github-pages-challenge-pgwiz.dtech"
yea no this wont work, refer to here on how to connect a github page https://www.is-a.dev/docs/github_pages/

2024-05-03 04:42 UTC, pgwiz reviewed
What if i temporarily connect it to my panel at that IP address

2024-05-03 10:08 UTC, CuteDog5695 requested changes

2024-05-03 10:08 UTC, CuteDog5695 commented on domains/dtech.json
> +        "A": "128.204.223.70"
IP needs to be in an array

2024-05-03 10:09 UTC, CuteDog5695 commented on domains/dtech.json
> +        "A": "128.204.223.70"
also gives error, probably because it isnt connect to a domain. if you want to connect it there then please give us a preview of your website

2024-05-03 17:45 UTC, pgwiz commented
I

2024-05-03 17:50 UTC, pgwiz commented
1. That is the dns zone settings on my panel automatically created.

![Screenshot_20240503_071441_WhatsApp](https://github.com/is-a-dev/register/assets/75813303/2d4bd965-5d7d-4537-b60f-0c0bcdde7f58)


2. And the website preview at https://wiptechg.69.mu 

![Screenshot_20240503_204815_Chrome](https://github.com/is-a-dev/register/assets/75813303/649d9d1b-2e5d-429d-9f80-08948b0fa10e)

2024-05-06 05:20 UTC, orxngc requested changes
Your site is inaccessible. "Error: unknown domain"
And your preview is incomplete.

2024-05-09 15:15 UTC, DEV-DIBSTER approved these changes, later dismissed

2024-05-11 03:40 UTC, closed without merging

2024-05-11 03:40 UTC, orxngc commented
Stale