BETA: Register paypay.is-a.dev
is-a-dev/register pull request #13720
Opened 2024-04-30 14:01 UTC by s0u7a

Added `paypay.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-30 14:13 UTC, orxngc requested changes
Could you provide a preview version of your site that I can check?

2024-04-30 15:27 UTC, triach-rold requested changes
Default sakura webpage. Reachable but incomplete.

_デフォルトのさくらウェブページ。アクセス可能ですが、不完全です。_

2024-05-01 13:15 UTC, s0u7a commented
Hi I am currently creating a site that looks like an IP logger and need a domain for it

2024-05-01 15:43 UTC, closed without merging

2024-05-01 15:45 UTC, CuteDog5695 commented
> Hi I am currently creating a site that looks like an IP logger and need a domain for it

instant reject, well played