BETA: Register slainbot.is-a.dev
is-a-dev/register pull request #13726
Opened 2024-04-30 17:25 UTC by KhongPhaiHoangQuangHuy

Added `slainbot.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-04-30 17:34 UTC, triach-rold reviewed
Why'd you delete the changed file ?

2024-04-30 18:41 UTC, CuteDog5695 requested changes

2024-04-30 18:41 UTC, CuteDog5695 commented on domains/slainbot.json
> +        "CNAME": "us.pylex.me:8778"
you cant use ports with CNAME

2024-04-30 18:59 UTC, CuteDog5695 commented
Yes, you can use IPv4 addresses under A record

2024-04-30 19:04 UTC, CuteDog5695 requested changes, later dismissed

2024-05-01 03:43 UTC, MaskDuck requested changes

2024-05-01 17:31 UTC, MaskDuck approved these changes

2024-05-01 17:32 UTC, merged