BETA: Register kisi.is-a.dev
is-a-dev/register pull request #13743
Opened 2024-05-01 06:15 UTC by kisi-dev

Added `kisi.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-05-01 07:11 UTC, MaskDuck requested changes

2024-05-01 07:19 UTC, triach-rold requested changes
Redirects to the wikipage.

2024-05-01 15:36 UTC, MaskDuck requested changes

2024-05-03 02:00 UTC, kisi-dev commented on domains/kisi.json
> +        "CNAME": "kisi-dev.github.io"
I fixed it

2024-05-03 13:39 UTC, MaskDuck approved these changes

2024-05-03 13:39 UTC, merged