Update sharanvasoya.json
is-a-dev/register pull request #13747
Opened 2024-05-01 09:38 UTC by Vasoyasharan

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-05-01 09:40 UTC, triach-rold approved these changes
Website is reachable and complete. Nice job.

2024-05-01 15:30 UTC, MaskDuck submitted a review, later dismissed

2024-05-02 03:34 UTC, Vasoyasharan commented on domains/sharanvasoya.json
> +    "CNAME": "https://vasoyasharan.github.io/MyPortfolio/"
is CNAME ok now?

2024-05-03 10:14 UTC, iostpa requested changes

2024-05-03 11:04 UTC, Vasoyasharan commented on domains/sharanvasoya.json
> +    "CNAME": "Vasoyasharan.in"
is it reachable now?

2024-05-03 11:20 UTC, CuteDog5695 approved these changes
seems fine to me now

2024-05-03 11:20 UTC, merged