BETA: Register undefined.is-a.dev
is-a-dev/register pull request #13756
Opened 2024-05-01 16:22 UTC by predefine

Added `undefined.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-05-01 17:04 UTC, triach-rold reviewed
Either this is an excellent website, or this is a redirect. I honestly can't tell.

2024-05-01 22:14 UTC, Stef-00012 requested changes

2024-05-01 22:14 UTC, Stef-00012 commented on domains/undefined.json
> +        "CNAME": "http://147.185.221.19:36279/"
CNAME can not contain `http://` or `/`

2024-05-02 05:06 UTC, predefine commented on domains/undefined.json
> +        "CNAME": "http://147.185.221.19:36279/"
> CNAME can not contain `http://` or `/`
fixed

2024-05-04 21:08 UTC, closed without merging