Create tay.json
is-a-dev/register pull request #13765
Opened 2024-05-01 19:31 UTC by tayrp

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [No ] You have completed your website. 
- [Yes, It should be. ] The website is reachable.  
- [I am using github pages.] You're not using Vercel or Netlify.  
- [ It does not contain https:// or a /] The CNAME record doesn't contain `https://` or `/`.  
- [ Email is listed] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://tayrp.github.io - it is not currently in the works, I just want to reserve this domain/subdomain for when I do decide to work on it.

2024-05-01 20:06 UTC, triach-rold requested changes
Website is reachable, but you need to add content in order for it to qualify as "complete".

2024-05-01 22:20 UTC, Stef-00012 requested changes
you should complete your website first

2024-05-02 03:23 UTC, 21Z requested changes

2024-05-02 03:23 UTC, 21Z commented on domains/tay.json
> +},
Invalid JSON file
```suggestion
},
```

2024-05-04 21:07 UTC, closed without merging