BETA: Register ashokalis.is-a.dev
is-a-dev/register pull request #13777
Opened 2024-05-02 10:40 UTC by Ashokali

Added `ashokalis.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2024-05-02 10:55 UTC, triach-rold requested changes
Provide a URL to your website.

2024-05-03 09:59 UTC, CuteDog5695 requested changes

2024-05-03 09:59 UTC, CuteDog5695 commented on domains/ash.json
> +        "CNAME": "ash.is-a.dev"
you cant use the domain you are requesting as CNAME

2024-05-03 09:59 UTC, CuteDog5695 commented on domains/ashok.json
> +        "CNAME": "ashok.is-a.dev"
you cant use the domain you are requesting as CNAME

2024-05-03 09:59 UTC, CuteDog5695 commented on domains/ashokalis.json
> +        "CNAME": "ashokalis.is.a.dev"
you cant use the domain you are requesting as CNAME

2024-05-03 10:32 UTC, closed without merging