Updated push.is-a.dev
is-a-dev/register pull request #13813
Opened 2024-05-04 08:52 UTC by pushingcc

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

[https://pushingcc.github.io/](url)

2024-05-04 09:19 UTC, Stef-00012 requested changes, later dismissed

2024-05-04 09:19 UTC, Stef-00012 commented on domains/push.is-a.dev.json
you should remove `.is-a.dev` from file name

2024-05-04 09:19 UTC, Stef-00012 commented on domains/_discord.push.is-a.dev.json
you should remove `.is-a.dev` from file name

2024-05-04 09:20 UTC, Stef-00012 commented on domains/push.is-a.dev.json
> +        "twitter": "<N/A>"
remove twitter field if you don't have it

2024-05-04 09:42 UTC, pushingcc commented
Changes have been added and submitted.

2024-05-05 04:52 UTC, MaskDuck approved these changes

2024-05-05 04:52 UTC, merged