Register sonom.is-a.dev
is-a-dev/register pull request #13825
Opened 2024-05-04 21:48 UTC by getSono

Register sonom.is-a.dev with CNAME record pointing to getsono.github.io.

2024-05-04 22:46 UTC, DEV-DIBSTER requested changes

2024-05-04 22:46 UTC, DEV-DIBSTER commented on domains/sonom.json
> +            "CNAME": "getsono.github.io"
404 GitHub page.

2024-05-05 04:34 UTC, triach-rold requested changes
Website is unreachable. (Github pages 404).

2024-05-05 12:09 UTC, getSono commented
> Website is unreachable. (Github pages 404).

I fixed it

2024-05-05 16:52 UTC, getSono commented
And please register status.sono.is-a.dev too

2024-05-06 15:33 UTC, orxngc approved these changes

2024-05-06 15:34 UTC, orxngc requested changes
You can't point your domain toward someone else's site.

2024-05-06 19:38 UTC, closed without merging