Create _github-pages-challenge-crischutu07.crischutu07.is-a.dev.json
is-a-dev/register pull request #13832
Opened 2024-05-05 02:39 UTC by crischutu07

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-05-05 10:27 UTC, Stef-00012 requested changes

2024-05-05 10:27 UTC, Stef-00012 commented on _github-pages-challenge-crischutu07.crischutu07.is-a.dev.json
remove `.is-a.dev` from the file name
also the file should be inside the `domains` folder

2024-05-05 21:25 UTC, Stef-00012 approved these changes

2024-05-06 00:07 UTC, DEV-DIBSTER approved these changes

2024-05-06 00:08 UTC, merged