Register ukcai.is-a.dev
is-a-dev/register pull request #13843
Opened 2024-05-05 23:50 UTC by ukcai696969

Register ukcai.is-a.dev with CNAME record pointing to countdown.ukcai.me.

2024-05-06 05:06 UTC, 21Z requested changes

2024-05-06 05:06 UTC, 21Z commented on domains/ukcai.json
> +            "CNAME": "countdown.ukcai.me"
Can't reach website
DNS_PROBE_FINISHED_NXDOMAIN

2024-05-06 07:38 UTC, CuteDog5695 requested changes

2024-05-06 07:38 UTC, CuteDog5695 commented on domains/ukcai.json
> +           "email": "111254389+ukcai696969@users.noreply.github.com",
please either use your email or leave it blank

2024-05-06 10:47 UTC, triach-rold requested changes
Website unreachable.

2024-05-12 04:53 UTC, orxngc commented
Stale PR, closing.

2024-05-12 04:53 UTC, closed without merging