Register Kiuoz.is-a.dev
is-a-dev/register pull request #13854
Opened 2024-05-06 09:19 UTC by Kiuoz

Register Kiuoz.is-a.dev with CNAME record pointing to Kiuoz.github.io.

2024-05-06 10:43 UTC, CuteDog5695 requested changes

2024-05-06 10:43 UTC, CuteDog5695 commented on domains/Kiuoz
file isnt .json (but since theres another file with the same name you can delete this one)

2024-05-06 10:45 UTC, triach-rold requested changes
Syntax is incorrect, website is unreachable.

2024-05-08 14:40 UTC, MaskDuck requested changes

2024-05-12 18:03 UTC, closed without merging