chore: Add MX record and update contact info for nova.is-a.dev
is-a-dev/register pull request #13868
Opened 2024-05-07 07:08 UTC by LunarN0v4

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

![image](https://github.com/is-a-dev/register/assets/71067215/cf6fc1bb-12d6-49d5-9563-cdf45888692b)

2024-05-07 07:49 UTC, CuteDog5695 requested changes, later dismissed

2024-05-07 07:49 UTC, CuteDog5695 commented on domains/nova.json
> +        "MX": "mail.zeusteam.dev"
CNAME cant be used with other records

2024-05-08 20:59 UTC, LunarN0v4 commented
Changes were made

2024-05-09 03:20 UTC, DEV-DIBSTER approved these changes

2024-05-09 03:20 UTC, merged