Register komaruJ7.is-a.dev
is-a-dev/register pull request #13917
Opened 2024-05-10 14:13 UTC by savvacorgi

Register komaruJ7.is-a.dev with TXT record pointing to 46.248.190.217.

2024-05-10 14:56 UTC, CuteDog5695 requested changes

2024-05-11 07:52 UTC, savvacorgi commented on domains/komaruj7.json
> +            "TXT": "46.248.190.217"
domen not for site

2024-05-11 07:52 UTC, savvacorgi commented on domains/komaruj7.json
> +            "TXT": "46.248.190.217"
domen for minecraft server

2024-05-13 20:14 UTC, TobezDev commented
@savvacorgi:
To my knowledge you can't use forwarding links to host Minecraft IPs. Pretty sure this is a Minecraft restriction rather than from an issue like DNS traffic. I would suggest going to a domain registrar like Squarespace and buying a cheap one from there where you can directly edit the DNS records for the domain.
[Please correct me if I am wrong with this one - it's been a while since I did domains for Minecraft servers.]

2024-05-15 03:46 UTC, orxngc commented
> @TobezDev : To my knowledge you can't use forwarding links to host Minecraft IPs. Pretty sure this is a Minecraft restriction rather than from an issue like DNS traffic. I would suggest going to a domain registrar like Squarespace and buying a cheap one from there where you can directly edit the DNS records for the domain. [Please correct me if I am wrong with this one - it's been a while since I did domains for Minecraft servers.]

You can, but it requires an SRV record or an A record.
We don't support SRV records.
I recently added a page about this to the [documentation](is-a.dev/docs/minecraft).
The issue here @savvacorgi is that you used a TXT record instead of an A record; also, if you want to use an is-a.dev domain for Minecraft, it must be a nested subdomain i.e. owo.uwu.is-a.dev is fine (if you own uwu.is-a.dev) however you can't use uwu.is-a.dev directly, which you are trying to do here.
I'm closing this PR as stale. <3

2024-05-15 03:46 UTC, closed without merging

2024-05-15 15:46 UTC, savvacorgi commented
> @savvacorgi: To my knowledge you can't use forwarding links to host Minecraft IPs. Pretty sure this is a Minecraft restriction rather than from an issue like DNS traffic. I would suggest going to a domain registrar like Squarespace and buying a cheap one from there where you can directly edit the DNS records for the domain. [Please correct me if I am wrong with this one - it's been a while since I did domains for Minecraft servers.]

Ok, Do you confirm the NS protocol? I want to add a domain to cloudns.com

2024-05-15 16:07 UTC, CuteDog5695 commented
We dont have NS records

2024-05-15 16:10 UTC, savvacorgi commented
> We dont have NS records

Don't you know free dns?

2024-05-15 16:10 UTC, savvacorgi commented
which supports Check on txt or a