Add files via upload
is-a-dev/register pull request #1394
Opened 2021-11-21 15:52 UTC by slowwdev

2021-11-28 16:52 UTC, slowwdev commented
PLS

2021-11-28 17:45 UTC, TheBotlyNoob requested changes

2021-11-28 17:45 UTC, TheBotlyNoob commented on domains/slow.json
> +    "repo": "https://github.com/slowwdev/slow",
you probably want to rename this repo to `slowdev.github.io`

2021-11-28 17:45 UTC, TheBotlyNoob commented on domains/slow.json
> +      "CNAME": "slow.github.io"
and change this to `slowdev.github.io`

2021-11-28 17:48 UTC, slowwdev commented
i changed

2021-11-28 17:50 UTC, slowwdev commented
@TheBotlyNoob

2022-01-17 13:54 UTC, phenax approved these changes

2022-01-17 13:54 UTC, merged