Create mrstickypiston.json
is-a-dev/register pull request #13952
Opened 2024-05-13 07:22 UTC by MrStickyPiston

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

![screenshot of my amazing material design website](https://github.com/is-a-dev/register/assets/97804691/f8c5bb36-c494-4271-97d3-c1662b2382a9)

2024-05-13 10:00 UTC, Stef-00012 requested changes, later dismissed

2024-05-13 10:00 UTC, Stef-00012 commented on domains/mrstickypiston.json
> +        "email": "email@gmail.com"
You should put your own mail

2024-05-13 10:57 UTC, MrStickyPiston commented
Fixed it

2024-05-13 20:11 UTC, TobezDev commented
Can I just add here that the site is incomplete.
Most of the text content is just a placeholder which can be generated from sites such as https://loremipsum.io.

[Suggestion: add tag: `reason: incomplete`]

2024-05-16 16:57 UTC, orxngc commented
@tobezdev Yah a lot of it is lorem ipsum, but all you really need to be considered complete is your name and mayhaps contact info, both of which are present.

2024-05-16 16:57 UTC, orxngc approved these changes

2024-05-16 16:58 UTC, merged