Register wojtekgame.is-a.dev
is-a-dev/register pull request #13951
Opened 2024-05-12 19:41 UTC by WojtekCodesToday

Register wojtekgame.is-a.dev with CNAME record pointing to https://wojtekcodestoday.github.io/.

2024-05-13 02:01 UTC, DEV-DIBSTER requested changes, later dismissed

2024-05-13 02:01 UTC, DEV-DIBSTER commented on domains/wojtekgame.json
> +            "CNAME": "https://wojtekcodestoday.github.io/"
Redirects back to the domain which you are requesting, invalid.

2024-05-13 05:04 UTC, triach-rold requested changes
Unreachable. Website must be your own and must have enough content to be considered as complete.

2024-05-13 05:19 UTC, wdhdev approved these changes

2024-05-13 05:19 UTC, merged

2026-04-13 15:30 UTC, WojtekCodesToday commented
@wdhdev is there a way to remove (unmerge?) the domain? i'll soon just use a domain i bought a few weeks ago (wjgm.pl), thanks.