Create dscbmr.json
is-a-dev/register pull request #13960
Opened 2024-05-14 06:25 UTC by RAYXSTYDIOZ

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-05-14 07:10 UTC, Stef-00012 requested changes

2024-05-14 07:10 UTC, Stef-00012 commented on domains/dscbmr.json
> +        "TXT": "dh=af0561dc7d2f7eb0ef153cb3a270c0b98fe5c36e"
TXT records alone do nothing

2024-05-14 07:15 UTC, RAYXSTYDIOZ commented
Wanted to add it in discord custom domain

On Tue, 14 May 2024, 12:41 Stef_DP, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In domains/dscbmr.json
> <https://github.com/is-a-dev/register/pull/13960#discussion_r1599492433>:
>
> > @@ -0,0 +1,9 @@
> +{
> +    "owner": {
> +        "username": "Rayxstydioz",
> +        "email": ***@***.***"
> +    },
> +    "record": {
> +        "TXT": "dh=af0561dc7d2f7eb0ef153cb3a270c0b98fe5c36e"
>
> TXT records alone do nothing
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/13960#pullrequestreview-2054464557>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAU6SD3KDQ5AUBX6BKGF5KTZCG2JPAVCNFSM6AAAAABHVQJEXKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANJUGQ3DINJVG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-16 17:00 UTC, orxngc commented
@RAYXSTYDIOZ is-a.dev/docs/discord_verification
You must first own dscbmr.is-a.dev with a complete & accessible site, *then* you can register a Discord connection following the instructions here.

2024-05-16 17:00 UTC, closed without merging