Confirm untitled.is-a.dev for GitHub and Discord
is-a-dev/register pull request #13989
Opened 2024-05-15 14:53 UTC by VihaanAnand

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
[https://untitled.is-a.dev/](https://untitled.is-a.dev/)

2024-05-15 15:39 UTC, Stef-00012 requested changes

2024-05-15 15:39 UTC, Stef-00012 commented on domains/_discord.untitled.is-a.dev.json
file name can't contain .is-a.dev

2024-05-15 15:39 UTC, Stef-00012 commented on domains/_github-pages-challenge-VihaanAnand.untitled.json
file name should be all lowercase, including your github username

2024-05-16 01:23 UTC, VihaanAnand commented on domains/_discord.untitled.is-a.dev.json
Completed.

2024-05-16 01:23 UTC, VihaanAnand commented on domains/_github-pages-challenge-VihaanAnand.untitled.json
Completed.

2024-05-16 12:59 UTC, CuteDog5695 requested changes

2024-05-18 18:03 UTC, closed without merging