Create fishy.json
is-a-dev/register pull request #14029
Opened 2024-05-18 14:16 UTC by skibidiloser

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-05-18 14:28 UTC, CuteDog5695 requested changes

2024-05-18 14:28 UTC, CuteDog5695 commented on domains/fishy.json
Json file literally doesn't have anything

2024-05-19 05:36 UTC, CuteDog5695 requested changes

2024-05-19 05:36 UTC, CuteDog5695 commented on domains/fishy.json
> +    "email": "<auroralindgren23@gmail.com>"
```suggestion
    "username": "skibidiloser",
    "email": "auroralindgren23@gmail.com"
```

2024-05-19 05:36 UTC, CuteDog5695 commented on domains/fishy.json
> +    "CNAME": "<skibidiloser>.github.io"
```suggestion
    "CNAME": "skibidiloser.github.io"
```

2024-05-19 05:36 UTC, CuteDog5695 commented on domains/fishy.json
> +    "CNAME": "<skibidiloser>.github.io"
Also site gives 404 error, if you have the site hosted then please send a preview of the website

2024-05-24 05:20 UTC, orxngc reviewed
Your site returns a Github 404, we need a complete and accessible site.

2024-05-26 20:07 UTC, closed without merging