E-mail change to business email, and add subdomains for monitoring sites
is-a-dev/register pull request #14021
Opened 2024-05-17 21:51 UTC by AcronicalYT

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [✅] The file is in the `domains` folder and is in the JSON format.
- [✅] You have completed your website.
- [🟠 - It is sometimes down due to the hosting] The website is reachable.  
- [✅] You're not using Vercel or Netlify.  
- [✅] The CNAME record doesn't contain `https://` or `/`.  
- [✅] There is sufficient information at the `owner` field.  

## Website Link/Preview
![image](https://github.com/is-a-dev/register/assets/85801752/de9de994-b02a-4376-b041-ab2c6b29f7d3)
Same for both pages, but slightly different when there is no error

2024-05-18 06:54 UTC, CuteDog5695 requested changes

2024-05-18 06:54 UTC, CuteDog5695 commented on domains/nocwarebot.acronical.json
> +        "CNAME": "59893.site.bot-hosting.net"
Site seems to be down. Also the preview listed on the PR seems to just show the error instead of the actual website, would like that to get fixed.

2024-05-18 06:54 UTC, CuteDog5695 commented on domains/yrrahbot.acronical.json
> +        "CNAME": "9595.site.bot-hosting.net"
Site seems to be down. Also the preview listed on the PR seems to just show the error instead of the actual website, would like that to get fixed.

2024-05-20 19:41 UTC, AcronicalYT commented
Both sites are now accessible with the content there

2024-05-21 14:24 UTC, iostpa approved these changes
Seems fine now

2024-05-21 14:24 UTC, merged