Register seldom.is-a.dev
is-a-dev/register pull request #14031
Opened 2024-05-18 17:02 UTC by seldomgreeen

Register seldom.is-a.dev with CNAME record pointing to seldomgreen.me.

2024-05-18 18:13 UTC, DEV-DIBSTER requested changes

2024-05-18 18:13 UTC, DEV-DIBSTER commented on domains/seldomgreen.json
> +            "CNAME": "is-a.dev"
Could you provide the reason as to why you want this domain to point to our homepage?

2024-05-18 18:13 UTC, DEV-DIBSTER commented on domains/seldomgreen.json
> +           "email": "72107155+seldomgreeen@users.noreply.github.com",
Invalid email, we need a email that we are able to contact you, not a no reply email.

2024-05-18 18:13 UTC, DEV-DIBSTER commented on domains/seldom.json
> +           "email": "72107155+seldomgreeen@users.noreply.github.com",
Invalid email, we need a email that we are able to contact you, not a no reply email.

2024-05-19 15:47 UTC, seldomgreeen reviewed
I want the email to be seldom@seldomgreen.me

2024-05-24 20:19 UTC, closed without merging