Register seen.is-a.dev
is-a-dev/register pull request #14058
Opened 2024-05-20 05:38 UTC by Seendator

Register seen.is-a.dev with A record pointing to 45.8.22.48.

2024-05-20 12:43 UTC, orxngc requested changes, later dismissed
We need a complete & accessible site to approve a domain.

2024-05-20 15:09 UTC, CuteDog5695 requested changes

2024-05-20 15:09 UTC, CuteDog5695 commented on domains/seen.json
> +           "email": "101656813+Seendator@users.noreply.github.com",
Please replace the email with your own one or leave it blank

2024-05-21 14:22 UTC, CuteDog5695 approved these changes
Seems good to me

2024-05-21 15:01 UTC, merged