Create daily-stars-explorer.json
is-a-dev/register pull request #14070
Opened 2024-05-20 20:55 UTC by emanuelef

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x ] The file is in the `domains` folder and is in the JSON format.
- [x ] You have completed your website. 
- [x ] The website is reachable.  
- [ x] You're not using Vercel or Netlify.  
- [x ] The CNAME record doesn't contain `https://` or `/`.  
- [x ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-05-20 20:57 UTC, emanuelef commented
Hi, not sure about the CNAME. 
The GH page is https://emanuelef.github.io/daily-stars-explorer, repo is https://github.com/emanuelef/daily-stars-explorer.
And I guess ideally the is-a-dev url should be daily-stars-explorer.is-a.dev.
Thanks.

2024-05-20 22:58 UTC, DEV-DIBSTER approved these changes

2024-05-20 22:58 UTC, DEV-DIBSTER requested changes

2024-05-20 22:58 UTC, DEV-DIBSTER commented on domains/daily-stars-explorer.json
> +        "username": "emanuelef"
No email is present.

2024-05-21 20:59 UTC, emanuelef commented
Not very happy to add my email to a public repo. Also I wanted to understand more if this is going to work for one repo in my GH account with a different name then my account name.

2024-05-25 07:09 UTC, closed without merging