Register tukdanai-book.is-a.dev
is-a-dev/register pull request #14074
Opened 2024-05-21 13:10 UTC by BookIILoy

Register tukdanai-book.is-a.dev with TXT record pointing to _vercel.

2024-05-21 13:33 UTC, CuteDog5695 requested changes

2024-05-21 13:33 UTC, CuteDog5695 commented on domains/tukdanai-book.json
> +            "TXT": "_vercel"
TXT doesn't do anything (Also as far as I know we don't support Vercel at the moment)

2024-05-21 13:58 UTC, triach-rold requested changes
No links.

2024-05-24 07:35 UTC, orxngc commented
Closing as inactive

2024-05-24 07:35 UTC, closed without merging