Register alphacoder.is-a.dev
is-a-dev/register pull request #14129
Opened 2024-05-25 09:52 UTC by XZeipher

Register alphacoder.is-a.dev with CNAME record pointing to alphacoder.is-a.dev.

2024-05-25 09:52 UTC, XZeipher commented
Hehe

2024-05-25 16:12 UTC, CuteDog5695 requested changes

2024-05-25 16:12 UTC, CuteDog5695 commented on domains/alphacoder.json
> +            "CNAME": "alphacoder.is-a.dev"
You can't point CNAME record to the subdomain you are trying to get.

2024-05-25 16:13 UTC, CuteDog5695 commented
> Hehe

?

2024-05-30 07:18 UTC, orxngc commented
Closing as stale

2024-05-30 07:18 UTC, closed without merging