Create mumble.sono.json
is-a-dev/register pull request #14123
Opened 2024-05-25 07:40 UTC by getSono

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-05-25 10:43 UTC, 21Z commented
checks failing

2024-05-25 10:45 UTC, 21Z requested changes

2024-05-25 10:45 UTC, 21Z commented on domains/sono.json
>          "TXT": [
```suggestion
        "TXT": "v=spf1 include:spf.improvmx.com ~all",
```

2024-05-25 10:45 UTC, 21Z commented on domains/sono.json
> +
```suggestion
```

2024-05-25 16:07 UTC, CuteDog5695 requested changes

2024-05-25 16:07 UTC, CuteDog5695 commented on domains/sono.json
> +        "URL": "getsono.is-a.dev"
```suggestion
        "URL": "https://getsono.is-a.dev"
```

2024-05-25 16:08 UTC, 21Z approved these changes

2024-05-25 16:08 UTC, 21Z commented on domains/sono.json
> +        "URL": "getsono.is-a.dev"
Missing protocol
```suggestion
        "URL": "https://getsono.is-a.dev"
```

2024-05-25 16:12 UTC, 21Z commented
watrado

2024-05-27 15:07 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-05-27 15:07 UTC, merged