Domain add
is-a-dev/register pull request #14138
Opened 2024-05-26 03:08 UTC by WarpedEntrance

Github pages

2024-05-26 06:46 UTC, CuteDog5695 requested changes

2024-05-26 06:46 UTC, CuteDog5695 commented on domains/scpfabyssal.json
> +        "CNAME": "scpfabyssal.github.io/"
```suggestion
        "CNAME": "scpfabyssal.github.io"
```

2024-05-26 15:10 UTC, WarpedEntrance commented
Fixed

2024-05-30 07:19 UTC, orxngc approved these changes, later dismissed

2024-06-06 01:14 UTC, closed without merging