Discord domain verify (again xD)
is-a-dev/register pull request #14134
Opened 2024-05-25 16:28 UTC by xzonix

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-05-25 16:31 UTC, 21Z requested changes

2024-05-25 16:31 UTC, 21Z commented on _discord.fran.is-a.dev.json
Again, remove is-a.dev from the file name

2024-05-25 16:32 UTC, CuteDog5695 requested changes

2024-05-25 16:32 UTC, CuteDog5695 commented on _discord.fran.is-a.dev.json
File isn't in domains directory. (Also do what 21Z said)

2024-05-26 17:05 UTC, 21Z commented
bruh

2024-05-26 17:05 UTC, 21Z commented
Now create the _discord.fran.json with the txt record discord gave for fran.is-a.dev

2024-05-26 17:29 UTC, 21Z commented
done in #14136, close this

2024-05-26 17:38 UTC, closed without merging