Register kem.is-a.dev
is-a-dev/register pull request #14143
Opened 2024-05-26 11:52 UTC by JustKemForFun

Register kem.is-a.dev with A record pointing to 103.169.35.190.

2024-05-26 16:00 UTC, CuteDog5695 requested changes

2024-05-26 16:00 UTC, CuteDog5695 commented on domains/kem.json
> +            "A": ["103.169.35.190"]
Gives an error page

2024-05-26 16:00 UTC, CuteDog5695 commented on domains/kem.json
> +           "email": "136668112+JustKemForFun@users.noreply.github.com",
Either replace the noreply email with your own or leave it blank

2024-05-27 08:48 UTC, MaskDuck requested changes
wdym "Kiểm Tra Tài Khoản Sống Hay Chết (Dùng , Để Check Nhiều UID Cùng 1 Lúc)"? 
btw is FB token extractor from cookie allowed? (pretty sure not)

and wtf why would you have sexy girl and uhh sixpack boys in your api
this is a weird api tbh, have to double check if I can allow those thing

2024-05-27 14:59 UTC, DEV-DIBSTER submitted a review, later dismissed

2024-05-27 16:05 UTC, closed without merging