Register maine.is-a.dev
is-a-dev/register pull request #14162
Opened 2024-05-27 16:25 UTC by Codemaine

Register maine.is-a.dev with TXT record pointing to vc-domain-verify=maine.is-a.dev,8d16f8af14c09f846ccf.

2024-05-27 16:31 UTC, MaskDuck submitted a review, later dismissed
We do not support vercel

2024-05-27 16:39 UTC, 21Z requested changes

2024-05-27 16:39 UTC, 21Z commented on domains/jermaine.json
> +        "TXT": "vc-domain-verify=jay.is-a.dev,ab97cfe7fecbf105ee2c"
TXT records alone does nothing to your website... You need a working web page.

2024-05-27 16:39 UTC, 21Z commented on domains/maine.json
> +            "TXT": "vc-domain-verify=maine.is-a.dev,8d16f8af14c09f846ccf"
TXT records alone does nothing to your website... You need a working web page.

2024-05-27 16:42 UTC, 21Z commented
> Which hosting providers do you support?

Almost all except vercel and netlify.. You can use Github Pages or Cloudflare Pages

2024-05-27 16:47 UTC, Codemaine commented
Alright

2024-05-27 17:00 UTC, Codemaine commented
CNAME record pointing to codemaine.github.io

2024-05-27 19:07 UTC, 21Z commented
> CNAME record pointing to codemaine.github.io

You can edit the JSON file accordingly

2024-05-27 20:20 UTC, Codemaine commented
Which JSON file sorry?

2024-05-28 01:19 UTC, 21Z commented
> Which JSON file sorry?

The domain files (jermaine.json and maine.json)

2024-05-28 01:27 UTC, Codemaine commented
I've made the necessary changes

2024-05-28 04:01 UTC, 21Z requested changes

2024-05-28 04:01 UTC, 21Z commented on domains/maine.json
> +            "TXT": "vc-domain-verify=maine.is-a.dev,8d16f8af14c09f846ccf",
Remove the TXT record
```suggestion
```

2024-05-28 04:01 UTC, 21Z commented on domains/jermaine.json
> +        "TXT": "vc-domain-verify=jay.is-a.dev,ab97cfe7fecbf105ee2c",
Remove the TXT record
```suggestion
```

2024-05-28 09:15 UTC, omsenjalia submitted a review, later dismissed
Cannot access your website

2024-05-28 12:28 UTC, Codemaine commented
Fixed: [https://codemaine.github.io](https://codemaine.github.io)

2024-05-28 16:59 UTC, 21Z approved these changes

2024-05-28 17:30 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-05-28 17:31 UTC, merged