EMAIL
is-a-dev/register pull request #14166
Opened 2024-05-27 19:51 UTC by zvdxc

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] You're not using Vercel or Netlify.  
- [X] There is sufficient information at the `owner` field.  
(Some lines deleted, domain is for E-Mails)

2024-05-27 19:54 UTC, zvdxc commented on domains/mail.zvdxc.json
> +}
Dont know why the check failed

2024-05-28 01:22 UTC, 21Z requested changes

2024-05-28 01:22 UTC, 21Z commented on domains/mail.zvdxc.json
> +        "email": "zvdxc11@gmail.com",
```suggestion
        "email": "zvdxc11@gmail.com"
```

2024-05-28 04:23 UTC, MaskDuck approved these changes

2024-05-28 04:23 UTC, merged