Register ttt.talinsharma.is-a.dev
is-a-dev/register pull request #14165
Opened 2024-05-27 18:46 UTC by TalinTheDev

Register ttt.talinsharma.is-a.dev with CNAME record pointing to tic-tac-toe-talinsharma.web.app.

2024-05-27 19:06 UTC, 21Z requested changes

2024-05-27 19:06 UTC, 21Z commented on domains/ttt.talinsharma.json
> +            "CNAME": "tic-tac-toe-talinsharma.web.app"
Can't reach website.
`Site not found`

2024-05-27 21:55 UTC, TalinTheDev commented on domains/ttt.talinsharma.json
> +            "CNAME": "tic-tac-toe-talinsharma.web.app"
Sorry! Updated CNAME record now!

2024-05-28 01:20 UTC, 21Z approved these changes

2024-05-28 08:55 UTC, omsenjalia approved these changes

2024-05-28 08:55 UTC, merged