Create steeldev.json
is-a-dev/register pull request #14164
Opened 2024-05-27 18:13 UTC by steeldev0

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-05-27 19:05 UTC, 21Z requested changes

2024-05-27 19:05 UTC, 21Z commented on domains/steeldev.json
Empty file... ?

2024-05-28 07:10 UTC, kernal32dll commented
nice

2024-05-28 09:12 UTC, omsenjalia requested changes
Empty file

2024-05-28 17:15 UTC, closed without merging