Create lucid.is-a.dev.json
is-a-dev/register pull request #14195
Opened 2024-05-29 23:08 UTC by oShinyMew

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website.  ( I am registering for emails, however this is good for my website too. )
- [ ] The website is reachable.   ( It is reachable. )
- [ ] You're not using Vercel or Netlify.   ( I'm not using Vercel or Netlify. )
- [ ] The CNAME record doesn't contain `https://` or `/`.   ( I'm not using a CNAME record. )
- [ ] There is sufficient information at the `owner` field.   
## Website Link/Preview

https://oshinymew.github.io

2024-05-29 23:58 UTC, DEV-DIBSTER submitted a review, later dismissed

2024-05-30 03:53 UTC, CuteDog5695 requested changes

2024-05-30 03:53 UTC, CuteDog5695 commented on domains/peroxide.is-a.dev.json
Remove .is-a.dev from the json name

2024-05-30 12:58 UTC, iostpa approved these changes

2024-05-30 12:59 UTC, merged