Create preview.shan.json
is-a-dev/register pull request #14215
Opened 2024-05-31 04:12 UTC by Adwaith-Shan-Pk

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [Yes] The file is in the `domains` folder and is in the JSON format.
- [Yes] The file's name is all lowercased and alphanumeric. 
- [Yes] You have completed your website. 
- [Yes] The website is reachable.  
- [Yes] You're not using Vercel or Netlify.  
- [Yes] The CNAME record doesn't contain `https://` or `/`.  
- [Yes] There is sufficient information at the `owner` field.  

## Website Link/Preview
http://45.90.12.122:6941 (Will Be Up At 11:00 IST)

2024-05-31 06:02 UTC, Adwaith-Shan-Pk commented
The Website Is Up.

2024-05-31 10:40 UTC, 21Z requested changes

2024-05-31 10:40 UTC, 21Z commented on domains/preview.shan.json
> +        "A": ["45.90.12.122"],
```suggestion
        "A": ["45.90.12.122"]
```

2024-05-31 12:39 UTC, 21Z approved these changes

2024-06-02 15:46 UTC, CuteDog5695 approved these changes

2024-06-02 15:46 UTC, merged