Register theprofessionalbinbag.is-a.dev
is-a-dev/register pull request #14220
Opened 2024-05-31 09:47 UTC by Soapiexoxoxo

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://free-5118674.webadorsite.com/

2024-06-02 09:50 UTC, orxngc submitted a review, later dismissed

2024-06-02 10:30 UTC, Stef-00012 requested changes, later dismissed

2024-06-02 10:30 UTC, Stef-00012 commented on domains/theprofessionalbinbag.json
- Add a `,` on line 5
- Remove line 6 and 7

2024-06-02 11:04 UTC, Soapiexoxoxo commented on domains/theprofessionalbinbag.json
done :))

2024-06-05 06:13 UTC, MaskDuck approved these changes
why are you selling binbag

2024-06-05 06:13 UTC, merged