Create _discord.tay.json
is-a-dev/register pull request #14285
Opened 2024-06-04 17:26 UTC by tayrp

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-06-04 19:18 UTC, CuteDog5695 requested changes, later dismissed

2024-06-04 19:18 UTC, CuteDog5695 commented on domains/_github-pages-challenge-tayrp.tay.json
> +        "email": "mystixmew@gmail.com"
```suggestion
        "email": "mystixmew@gmail.com",
```

2024-06-04 19:18 UTC, CuteDog5695 commented on domains/tayrp/_discord.tay.json
File needs to be in domains directory, not domains/tayrp

2024-06-07 05:48 UTC, MaskDuck approved these changes

2024-06-07 05:48 UTC, merged