Update getsono and sono
is-a-dev/register pull request #14335
Opened 2024-06-07 12:05 UTC by getSono

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] The file's name is all lowercased and alphanumeric. 
- [X] You have completed your website. 
- [X] The website is reachable.  
- [X] You're not using Vercel or Netlify.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://getsono.is-a.dev
https://sono.is-a.dev

2024-06-07 12:07 UTC, CuteDog5695 requested changes

2024-06-07 12:07 UTC, CuteDog5695 commented on domains/getsono.json
> +            "TXT": "google-site-verification=MFPLEonkdLiPBmou5SY2mk4qJQ2HC3jZC9cQ8poP3_o"
You can't use CNAME with other records. (also for google site verification can't you do via html?)

2024-06-08 07:14 UTC, getSono reviewed
Changed CNAME to A records

2024-06-08 15:12 UTC, CuteDog5695 approved these changes
Seems fine to me I guess

2024-06-08 15:12 UTC, merged