Register brook.is-a.dev
is-a-dev/register pull request #14343
Opened 2024-06-07 20:52 UTC by bbrooklyn

Register brook.is-a.dev with A record pointing to 57.128.172.101.

2024-06-08 04:39 UTC, Stef-00012 requested changes

2024-06-08 04:39 UTC, Stef-00012 commented on domains/brook.json
> +            "A": ["57.128.172.101"]
I can not reach your website

2024-06-08 04:40 UTC, Stef-00012 commented on domains/brook.json
> +            "A": ["57.128.172.101"]
(404 Not Found)

2024-06-13 12:40 UTC, orxngc commented
Closing as stale

2024-06-13 12:40 UTC, closed without merging