Register p61s.is-a.dev
is-a-dev/register pull request #14351
Opened 2024-06-08 10:59 UTC by Samhey-debug

Register p61s.is-a.dev with CNAME record pointing to https://samhey-debug.github.io/rog/.

2024-06-08 15:21 UTC, CuteDog5695 requested changes

2024-06-08 15:21 UTC, CuteDog5695 commented on domains/p61s.json
> +            "CNAME": "https://samhey-debug.github.io/rog/"
```suggestion
            "CNAME": "samhey-debug.github.io"
```

2024-06-09 13:22 UTC, Samhey-debug reviewed
oooo fixed!!!

2024-06-12 12:46 UTC, CuteDog5695 requested changes
Previous CNAME record (which I assume is where the site is hosted) is redirecting to a js.org domain, can you give me a preview of your website?

2024-06-14 00:42 UTC, closed without merging