Register jogar.is-a.dev
is-a-dev/register pull request #14359
Opened 2024-06-08 21:16 UTC by Henzogabriel954

Register jogar.is-a.dev with A record pointing to 144.22.224.131.

2024-06-09 08:11 UTC, 21Z requested changes

2024-06-09 08:11 UTC, 21Z commented on domains/jogar.json
> +            "A": ["144.22.224.131"]
Can't reach the website, if this is the correct record, could you provide a preview of your website?

2024-06-09 11:28 UTC, Stef-00012 requested changes
what @21Z said

2024-06-13 12:40 UTC, orxngc commented
Closing as stale

2024-06-13 12:40 UTC, closed without merging