thisisram.github.io
is-a-dev/register pull request #14404
Opened 2024-06-11 16:26 UTC by thisisramhere

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [Yes ] The file is in the `domains` folder and is in the JSON format.
- [Yes ] The file's name is all lowercased and alphanumeric. 
- [ Yes] You have completed your website. 
- [Yes ] The website is reachable.  
- [Yes ] You're not using Vercel or Netlify.  
- [Yes ] The CNAME record doesn't contain `https://` or `/`.  
- [Yes ] There is sufficient information at the `owner` field.  

## Website Link/Preview

                            thisisram.github.io

2024-06-12 01:05 UTC, MaskDuck submitted a review, later dismissed
404 page on gh

2024-06-13 11:17 UTC, CuteDog5695 requested changes

2024-06-13 11:17 UTC, CuteDog5695 commented on domains/ram.json
> +        "CNAME": "thisisram.github.io"
You added the wrong CNAME for github pages (its usually your username and then github.io)
```suggestion
        "CNAME": "thisisramhere.github.io"
```

2024-06-14 13:40 UTC, CuteDog5695 approved these changes
now it seems fine to me

2024-06-14 13:40 UTC, merged