Domain register request
is-a-dev/register pull request #14432
Opened 2024-06-14 09:28 UTC by OchotaDariusz

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-06-14 15:57 UTC, 21Z requested changes

2024-06-14 15:57 UTC, 21Z commented on domains/domains/this-guy.json
Invalid file. You created another folder inside the domains folder.
\+ this is just a copy of the other file but without CNAME?

2024-06-14 15:57 UTC, 21Z commented on domains/this-guy.json
> +    "TXT": "e8fdea5df81baf689fe00bb6d833d8"
You can't use any other records with CNAME

2024-06-14 21:29 UTC, DariuszO commented on domains/domains/this-guy.json
It's config from https://www.is-a.dev/docs/github-pages-verification/

2024-06-15 11:33 UTC, MaskDuck approved these changes

2024-06-15 11:34 UTC, merged