Register befaci.is-a.dev
is-a-dev/register pull request #14460
Opened 2024-06-16 18:51 UTC by Ylian1512

Register befaci.is-a.dev with CNAME record pointing to ylian1512.github.io.

2024-06-17 02:50 UTC, DEV-DIBSTER requested changes

2024-06-17 02:50 UTC, DEV-DIBSTER commented on domains/befaci.json
> +            "CNAME": "ylian1512.github.io"
Redirects back to this domain, invalid.

2024-06-17 04:36 UTC, MaskDuck requested changes

2024-06-17 15:18 UTC, Ylian1512 commented
okay i will work on my website, so the json file is invalid ????

2024-06-19 14:05 UTC, Ylian1512 commented
> your json file is fine

so why record is invalid
and my website is block at befaci.is-a.dev (ylian1512.github.io)

2024-06-19 15:31 UTC, CuteDog5695 commented
> ylian1512.github.io

I think you have to add more content to your website, I checked the website and I don't really see much stuff (plus the buttons don't work) so please add more stuff to your website

2024-06-19 18:08 UTC, Ylian1512 commented
> > ylian1512.github.io
> 
> I think you have to add more content to your website, I checked the website and I don't really see much stuff (plus the buttons don't work) so please add more stuff to your website

okay, i will continue my website

2024-06-19 20:21 UTC, Ylian1512 commented
@CuteDog5695 my website redirect again to befaci.is-a.dev :(

2024-06-19 21:09 UTC, CuteDog5695 commented
> @CuteDog5695 my website redirect again to befaci.is-a.dev :(

Remove the domain from your Github repo or just delete the CNAME file

2024-06-19 21:57 UTC, Ylian1512 commented
> > @CuteDog5695 my website redirect again to befaci.is-a.dev :(
> 
> Remove the domain from your Github repo or just delete the CNAME file

Thx vert much!

2024-06-19 22:06 UTC, Ylian1512 commented
Don't work :'(

2024-06-19 22:14 UTC, Ylian1512 commented
Oh yes, I don't view the remove befaci.json

2024-06-19 22:17 UTC, Ylian1512 commented
Don't work anyway 😭😭😭😭😭😭😭😭😭😭

2024-06-20 05:40 UTC, Ylian1512 commented
> wdym don't work? if it's because befaci.is-a.dev is inaccessible then it's because we haven't merged it yet, we will merge it when your wbesite is completed

oh! okay!

2024-06-23 15:14 UTC, closed without merging