Register mcstatus.is-a.dev
is-a-dev/register pull request #14477
Opened 2024-06-17 15:09 UTC by EducatedSuddenBucket

Register mcstatus.is-a.dev with CNAME record pointing to mcstatus-is-a-dev.onrender.com.

2024-06-17 18:11 UTC, 21Z requested changes

2024-06-17 18:11 UTC, 21Z commented on domains/mcstatus.json
> +            "CNAME": "mcstatus-is-a-dev.onrender.com"
Could you provide a preview of your website?

2024-06-17 20:42 UTC, DEV-DIBSTER requested changes, later dismissed

2024-06-17 20:42 UTC, DEV-DIBSTER commented on domains/mcstatus.json
> +           "email": "149485703+EducatedSuddenBucket@users.noreply.github.com",
Cannot use a no reply email address.

2024-06-18 02:00 UTC, MaskDuck requested changes

2024-06-18 02:18 UTC, GlitchingPhantom commented on domains/mcstatus.json
> +            "CNAME": "mcstatus-is-a-dev.onrender.com"
it will load , render is not 24/7, you need to wait about 50 seonds so the sie can deploy

2024-06-18 02:21 UTC, GlitchingPhantom commented on domains/mcstatus.json
> +            "CNAME": "mcstatus-is-a-dev.onrender.com"
also dont reload the page while its loading unless it stops loading

2024-06-18 02:22 UTC, MaskDuck approved these changes

2024-06-18 02:22 UTC, merged