Register timmy.is-a.dev
is-a-dev/register pull request #14480
Opened 2024-06-17 19:04 UTC by BunkDev5674

Register timmy.is-a.dev with A record pointing to 188.93.139.120.

2024-06-17 20:43 UTC, DEV-DIBSTER requested changes

2024-06-17 20:43 UTC, DEV-DIBSTER commented on domains/timmy.json
> +           "email": "79503178+BunkDev5674@users.noreply.github.com",
Cannot use a no reply email address.

2024-06-19 11:20 UTC, BunkDev5674 commented on domains/timmy.json
> +           "email": "79503178+BunkDev5674@users.noreply.github.com",
i edited it

2024-06-19 15:33 UTC, CuteDog5695 requested changes

2024-06-19 15:33 UTC, CuteDog5695 commented on domains/timmy.json
> +            "A": ["188.93.139.120"]
404 not found, please give a preview of your website

2024-06-19 15:33 UTC, CuteDog5695 commented on domains/timtim.json
> +            "A": ["188.93.139.120"]
404 not found, please give a preview of your website

2024-06-23 03:21 UTC, closed without merging