add domain
is-a-dev/register pull request #14504
Opened 2024-06-19 04:05 UTC by yoeldesdev

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-06-19 06:13 UTC, 21Z requested changes

2024-06-19 06:13 UTC, 21Z commented on domains/yoeldesdev.json
> + "description": "yoeldesdev web",
Invalid JSON
```suggestion
{
 "description": "yoeldesdev web",
```

2024-06-19 07:11 UTC, Stef-00012 requested changes

2024-06-19 07:11 UTC, Stef-00012 commented on domains/yoeldesdev.json
> + "description": "yoeldesdev web",
accept @21Z's suggestion

2024-06-19 07:11 UTC, Stef-00012 commented on domains/yoeldesdev.json
> +        "email": "yoeldesdev@gmail.com",
remove the `,` here

2024-06-20 07:19 UTC, yoeldesdev commented on domains/yoeldesdev.json
> +        "email": "yoeldesdev@gmail.com",
ok

2024-06-22 18:29 UTC, Real-Yash approved these changes

2024-06-23 08:22 UTC, CuteDog5695 requested changes

2024-06-23 08:22 UTC, CuteDog5695 commented on domains/yoeldesdev.json
> +        "email": "yoeldesdev@gmail.com",
```suggestion
        "email": "yoeldesdev@gmail.com"
```

2024-06-26 02:25 UTC, closed without merging