Update midlaj.json
is-a-dev/register pull request #14525
Opened 2024-06-21 05:33 UTC by whoismidlaj

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-06-21 06:04 UTC, CuteDog5695 requested changes

2024-06-21 06:04 UTC, CuteDog5695 commented on domains/midlaj.json
> +    "TXT": ["_vercel", "vc-domain-verify=midlaj.is-a.dev,241ff5d3a4a7e0403ed6"]
You can't use CNAME with TXT (also we don't support Vercel currently)

2024-06-22 21:52 UTC, whoismidlaj commented
fixed all and using cloudflare pages now

2024-06-23 08:20 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-06-23 08:20 UTC, merged