Create aerocyber.json
is-a-dev/register pull request #14539
Opened 2024-06-22 05:43 UTC by aerocyber

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-06-22 16:54 UTC, CuteDog5695 requested changes

2024-06-22 16:54 UTC, CuteDog5695 commented on domains/aerocyber.json
> +  "repo": "https://github.com/aerocyber",
```suggestion
  "repo": "https://github.com/aerocyber"
```

2024-06-22 18:31 UTC, Real-Yash approved these changes

2024-06-23 08:20 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-06-23 08:20 UTC, merged

2024-06-23 08:31 UTC, aerocyber commented
Cool. Thanks!