register sharecrypt.is-a.dev
is-a-dev/register pull request #14593
Opened 2024-06-25 21:21 UTC by eli32-vlc

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://filesharing.eason.cloud

![image](https://github.com/is-a-dev/register/assets/84105075/cda2b347-218b-4c2f-8137-28045636bf4b)

2024-06-25 21:23 UTC, eli32-vlc commented
Personal project if you need any proof ask me.

2024-06-26 02:31 UTC, DEV-DIBSTER requested changes

2024-06-26 02:31 UTC, DEV-DIBSTER commented on domains/_acme-challenge.sharecrypt.is-a.dev.json
We do not do ACME records.

2024-06-26 02:55 UTC, eli32-vlc commented on domains/_acme-challenge.sharecrypt.is-a.dev.json
How do I verify aceme?![image](https://github.com/is-a-dev/register/assets/84105075/c179752e-de0b-48da-950d-85896b883845)

2024-06-26 08:23 UTC, CuteDog5695 commented on domains/_acme-challenge.sharecrypt.is-a.dev.json
We actually allow ACME records, he got some misinformation by another maintainer

2024-06-26 08:25 UTC, CuteDog5695 commented on domains/_acme-challenge.sharecrypt.is-a.dev.json
Though you have to remove .is-a.dev from the name since it would repeat is-a.dev twice if merged

2024-06-29 01:50 UTC, closed without merging