I want to host my personal portfolio.
is-a-dev/register pull request #14608
Opened 2024-06-27 13:32 UTC by Debaleena84

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://debaleena84.github.io/DIV-personal-portfolio-website/

2024-06-27 16:52 UTC, CuteDog5695 requested changes

2024-06-27 16:52 UTC, CuteDog5695 commented on domains/debaleena.json
File is empty.

2024-06-27 16:54 UTC, Debaleena84 commented
check debaleenabasu.json please

On Thu, 27 Jun, 2024, 22:23 CuteDog5695, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On domains/debaleena.json
> <https://github.com/is-a-dev/register/pull/14608#discussion_r1657473458>:
>
> File is empty.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/14608#pullrequestreview-2145964165>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUOFFO3HPZBAHQW2IR3QDETZJQ7P5AVCNFSM6AAAAABJ76LHRCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNBVHE3DIMJWGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-28 06:29 UTC, Debaleena84 commented on domains/debaleena.json
please check debaleenabasu.json

2024-06-28 11:52 UTC, closed without merging