Register evablog.is-a.dev
is-a-dev/register pull request #14612
Opened 2024-06-27 19:28 UTC by Evavmm

Register evablog.is-a.dev with CNAME record pointing to www.evablog.com.

2024-06-27 22:05 UTC, DEV-DIBSTER requested changes

2024-06-27 22:05 UTC, DEV-DIBSTER commented on domains/blogeve.json
Empty file.

2024-06-27 22:05 UTC, DEV-DIBSTER commented on domains/evablog.json
> +            "CNAME": "www.evablog.com"
Leads to a buy site.

2024-06-30 12:24 UTC, orxngc commented
Closing as stale.

2024-06-30 12:24 UTC, closed without merging