[shockbs.json] Pls Merge This When _domainkey is supported
is-a-dev/register pull request #14645
Opened 2024-06-30 06:05 UTC by shockbs

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

 thank you, this is for mail

2024-06-30 07:47 UTC, CuteDog5695 requested changes, later dismissed

2024-06-30 07:47 UTC, CuteDog5695 commented on domains/shockbs.json
> +    "TXT": "v=spf1 include:mailgun.org ~all"
You can't use CNAME with other records

2024-06-30 16:35 UTC, shockbs commented on domains/shockbs.json
> +    "TXT": "v=spf1 include:mailgun.org ~all"
i've changed to A records, thanks!

2024-06-30 16:37 UTC, DEV-DIBSTER requested changes, later dismissed

2024-06-30 16:37 UTC, DEV-DIBSTER commented on domains/mx._domainkey.shockbs.json
I believe we do not support this kid of record.

2024-07-01 05:40 UTC, shockbs commented on domains/mx._domainkey.shockbs.json
pls support dkim

2024-07-01 06:47 UTC, wdhdev approved these changes

2024-07-01 06:48 UTC, merged