Create Karttikeya
is-a-dev/register pull request #14659
Opened 2024-06-30 18:20 UTC by KartKernel

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-06-30 20:24 UTC, DEV-DIBSTER requested changes, later dismissed

2024-06-30 20:24 UTC, DEV-DIBSTER commented on domains/Karttikeya
File doesn't end in .json.

2024-06-30 20:24 UTC, DEV-DIBSTER commented on domains/Karttikeya
> +    "CNAME": "KartKernel.github.io"
Cannot seem to access your site.

2024-07-05 00:28 UTC, orxngc commented on domains/Karttikeya
user changed file name

2024-07-05 00:29 UTC, orxngc commented on domains/Karttikeya
> +    "CNAME": "KartKernel.github.io"
site is now accessible

2024-07-05 00:30 UTC, orxngc submitted a review, later dismissed

2024-07-05 00:38 UTC, orxngc requested changes
The filename must be all lowercase. That is, `karttikeya.json` instead of `Karttikeya.json`. Change that and then I can merge it, thank you!

2024-07-05 09:02 UTC, KartKernel commented
> The filename must be all lowercase. That is, `karttikeya.json` instead of `Karttikeya.json`. Change that and then I can merge it, thank you!

Hi, I have changed the name, thank you

2024-07-05 12:18 UTC, orxngc approved these changes

2024-07-05 12:18 UTC, merged