Create to-zeeshan.json
is-a-dev/register pull request #14675
Opened 2024-07-02 10:17 UTC by m-zeeshan42

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-07-02 11:54 UTC, CuteDog5695 requested changes

2024-07-02 11:54 UTC, CuteDog5695 commented on domains/to-zeeshan.json
> +  },
you need to add username line (username line is your Github username)

2024-07-02 18:50 UTC, m-zeeshan42 reviewed
Username added

2024-07-02 19:01 UTC, CuteDog5695 requested changes

2024-07-02 19:01 UTC, CuteDog5695 commented on domains/to-zeeshan.json
> +    "email": "zeeshanashraf424@gmail.com"
```suggestion
    "username": "m-zeeshan42",
    "email": "zeeshanashraf424@gmail.com"
```

2024-07-02 19:24 UTC, m-zeeshan42 reviewed
I am sorry for these small mistakes. Now i have double checked everything.

2024-07-03 10:17 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-07-03 10:17 UTC, merged