Register alcantara.is-a.dev
is-a-dev/register pull request #14703
Opened 2024-07-04 15:19 UTC by Aalcantaraxxx

Register alcantara.is-a.dev with CNAME record pointing to aalcantara-is-a-dev.web.app.

2024-07-04 15:42 UTC, Aalcantaraxxx commented
Hi, sorry. I accidentally created 2 pull requests one on github and one on discord.

I just need a subdomain (aalcantara.is-a.dev) please

Website preview (developing):     https://aalcantara-is-a-dev.web.app/

2024-07-05 02:29 UTC, 21Z requested changes

2024-07-05 02:29 UTC, 21Z commented on domains/aalcantara.json
> +  {
Invalid JSON
```suggestion
```

2024-07-05 02:43 UTC, Aalcantaraxxx commented on domains/aalcantara.json
> +  {
Thanks, I fixed it now :)

2024-07-05 03:30 UTC, orxngc approved these changes

2024-07-05 03:30 UTC, merged