Discord domain verification thingy
is-a-dev/register pull request #14727
Opened 2024-07-06 05:18 UTC by KeiranScript

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [/] The file is in the `domains` folder and is in the JSON format.
- [/] The file's name is all lowercased and alphanumeric. 
- [/] You have completed your website. 
- [/] The website is reachable.  
- [/] You're not using Vercel.  
- [/] The CNAME record doesn't contain `https://` or `/`.  
- [/] There is sufficient information at the `owner` field.  

## Website Link/Preview

![image](https://github.com/is-a-dev/register/assets/159267417/36a3b3bd-fe81-4d67-b723-589f0a54509b)

2024-07-06 06:23 UTC, CuteDog5695 requested changes

2024-07-06 06:23 UTC, CuteDog5695 commented on CNAME
> +keiran-is-a.dev
Delete this file please

2024-07-06 06:23 UTC, CuteDog5695 commented on domains/_discord.keiran.is-a.dev
> +{
Replace .is-a.dev with .json

2024-07-06 15:59 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-07-06 15:59 UTC, merged

2024-08-13 20:54 UTC, Sxinar commented
Hello, I want to use freeflarum now because netlify has frozen my account :/ I will use freeflarum cname: cname.freeflarum.com site link: sxinar.flarum.cloud