Register gicorada.is-a.dev
is-a-dev/register pull request #14751
Opened 2024-07-07 16:41 UTC by gicorada

Register gicorada.is-a.dev with CNAME record pointing to gicorada CNAME gicorada.netlify.app..

2024-07-07 19:24 UTC, triach-rold reviewed
typo in CNAME?

2024-07-07 19:30 UTC, gicorada commented
The dot at the end of the url is in the Netlify record, if it only needs to be included in the complete CNAME record and not in the url provided in the json file I can remove it

![image](https://github.com/is-a-dev/register/assets/51818710/a51beb05-1740-49bc-9cc5-f32747ad3e4c)

2024-07-08 18:09 UTC, DEV-DIBSTER requested changes

2024-07-08 18:09 UTC, DEV-DIBSTER approved these changes

2024-07-08 18:09 UTC, merged