Create ronak.json
is-a-dev/register pull request #14760
Opened 2024-07-08 11:45 UTC by RonakDutta

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://ronakdutta.github.io/portfolio/

2024-07-08 14:15 UTC, DEV-DIBSTER requested changes

2024-07-08 14:15 UTC, DEV-DIBSTER commented on domains/ronak.json
> +            "CNAME": "ronakdutta.github.io/portfolio"
Cannot have URL paths in CNAME.

2024-07-11 07:59 UTC, CuteDog5695 requested changes

2024-07-11 07:59 UTC, CuteDog5695 commented on domains/ronak.json
> +            "CNAME": "ronakdutta.github.io/portfolio"
```suggestion
            "CNAME": "ronakdutta.github.io"
```

2024-07-11 08:00 UTC, CuteDog5695 commented
Wait, this domain already has been merged in #14761. I'll close this PR now

2024-07-11 08:00 UTC, closed without merging