Create Hardik.json
is-a-dev/register pull request #14793
Opened 2024-07-10 10:13 UTC by Hardik-Vanani

Wanna Add my CNAME

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-07-10 10:43 UTC, saxophone-guy commented
Your subdomain cannot have capital letters. Presuming the CNAME given in your json file is your website, it is unreachable (at least for me). Try adding a screenshot to the PR if you prefer not to make it public just yet.

2024-07-10 13:45 UTC, CuteDog5695 requested changes

2024-07-10 13:45 UTC, CuteDog5695 commented on domains/Hardik.json
Domain needs to be all lower case, but someone already took hardik.is-a.dev. Please choose another subdomain name

2024-07-10 13:46 UTC, CuteDog5695 commented
> Your subdomain cannot have capital letters. Presuming the CNAME given in your json file is your website, it is unreachable (at least for me). Try adding a screenshot to the PR if you prefer not to make it public just yet.

He gave his repo in the files, so I could visit the page from that (since its username.github.io/reponame if repo isnt the github.io domain)

2024-07-12 11:52 UTC, Hardik-Vanani commented on domains/Hardik.json
ok i have changed the file name to "vhardik".

2024-07-12 20:07 UTC, CuteDog5695 commented
You need to change the json file name so that you actually change the domain you want, not by the name of the PR

2024-07-13 12:42 UTC, CuteDog5695 submitted a review, later dismissed

2024-07-13 12:42 UTC, CuteDog5695 commented on vhardik
File needs to be in domains directory and be json file. While you do that please delete the Hardik.json file

2024-07-14 13:16 UTC, orxngc approved these changes

2024-07-14 13:16 UTC, merged