Register slainbot.is-a.dev
is-a-dev/register pull request #14811
Opened 2024-07-11 00:11 UTC by KhongPhaiHoangQuangHuy

Register slainbot.is-a.dev with CNAME record pointing to https://khongphaihoangquanghuy.github.io/dashboard-Slain-BOT/.

2024-07-11 03:47 UTC, DEV-DIBSTER requested changes

2024-07-11 03:47 UTC, DEV-DIBSTER commented on domains/slainbot.json
> +            "CNAME": "https://khongphaihoangquanghuy.github.io/dashboard-slain-bot/"
Invalid CNAME, it must be a hostname, contain no protocols, url paths.

2024-07-12 03:12 UTC, CuteDog5695 requested changes, later dismissed

2024-07-12 03:12 UTC, CuteDog5695 commented on domains/slainbot.json
> +            "CNAME": "https://khongphaihoangquanghuy.github.io"
```suggestion
            "CNAME": "khongphaihoangquanghuy.github.io"
```

2024-07-12 21:18 UTC, DEV-DIBSTER requested changes

2024-07-12 21:18 UTC, DEV-DIBSTER commented on domains/slainbot.json
> +            "CNAME": "khongphaihoangquanghuy.github.io"
I don't see any content on this or the original URL you sent. Are you able to send a preview?

2024-07-13 02:49 UTC, DEV-DIBSTER approved these changes

2024-07-13 02:49 UTC, merged