Create _discord.crzy.is-a.dev
is-a-dev/register pull request #14827
Opened 2024-07-11 17:22 UTC by creativeblocker

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-07-11 19:25 UTC, DEV-DIBSTER requested changes

2024-07-11 19:25 UTC, DEV-DIBSTER commented on domains/_discord.crzy.is-a.dev
File needs to end in .json.

2024-07-12 00:25 UTC, orxngc requested changes
As Dibster said, the file needs to end in .json. Also, you must own crzy.is-a.dev to have a nested domain under it.

2024-07-14 13:05 UTC, orxngc commented
Closing as stale.

2024-07-14 13:05 UTC, closed without merging