Discord domain verification
is-a-dev/register pull request #14828
Opened 2024-07-11 17:28 UTC by creativeblocker

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-07-11 17:32 UTC, Stef-00012 requested changes

2024-07-11 17:32 UTC, Stef-00012 commented on domains/_discord.cvzy.is-a.dev.json
> +        "username": "EasyNebula",
username should be your github username

2024-07-11 17:32 UTC, Stef-00012 commented on domains/_discord.cvzy.is-a.dev.json
remove `.is-a.dev` from the filename

2024-07-11 17:32 UTC, Stef-00012 commented on domains/_discord.cvzy.is-a.dev.json
`cvzy` doesn't exist as is-a.dev domain

2024-07-12 00:26 UTC, orxngc requested changes
Closing as a duplicate of #14827.

2024-07-12 00:26 UTC, closed without merging