Update hirako.json
is-a-dev/register pull request #14845
Opened 2024-07-12 14:21 UTC by hirakoisdead

added other contact options and removed the email and added mx and txt record

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://hirako.is-a.dev/

2024-07-12 20:08 UTC, CuteDog5695 requested changes

2024-07-12 20:08 UTC, CuteDog5695 commented on domains/hirako.json
> +    "TXT": "v=spf1 include:spf.improvmx.com ~all"
You cannot use CNAME with MX and TXT.

2024-07-12 21:39 UTC, hirakoisdead commented on domains/hirako.json
> +    "TXT": "v=spf1 include:spf.improvmx.com ~all"
Done, removed the MX and TXT records

2024-07-13 12:37 UTC, CuteDog5695 submitted a review, later dismissed

2024-07-13 12:37 UTC, CuteDog5695 commented on domains/hirako.json
> +    "email": ""
```suggestion
    "email": "",
```

2024-07-13 16:31 UTC, MaskDuck approved these changes

2024-07-13 16:31 UTC, merged