Register MavisHost.is-a.dev
is-a-dev/register pull request #14888
Opened 2024-07-14 09:05 UTC by neklayd

Register MavisHost.is-a.dev with A record pointing to 172.18.1.235.

2024-07-14 09:16 UTC, MaskDuck requested changes

2024-07-14 11:10 UTC, CuteDog5695 commented
Is this domain supposed to be for a hosting service by any chance?

2024-07-16 22:35 UTC, orxngc commented
Closing as stale.

2024-07-16 22:35 UTC, closed without merging

2024-07-28 21:15 UTC, neklayd commented
No, this is not hosting, this is my hosting documentation