Create free.json
is-a-dev/register pull request #1489
Opened 2021-12-19 03:15 UTC by freegocrazy

2022-01-18 17:25 UTC, phenax requested changes
This seems like an incorrect use of the service. Please go through the docs or create an issue if you need any help.

2022-02-28 00:38 UTC, MaskDuck requested changes

2022-02-28 00:38 UTC, MaskDuck commented on domains/free.json
> +    "TXT": "whats poppin!"
I would like to see an actual DNS record, not a random string here.

2022-04-02 14:38 UTC, closed without merging

2022-04-03 01:51 UTC, SX-9 commented
He/she is probaply new to this kind of stuff

2022-04-03 01:55 UTC, MaskDuck commented
mm