Register pc.is-a.dev
is-a-dev/register pull request #14913
Opened 2024-07-15 00:18 UTC by MCPE-PC

Register pc.is-a.dev with CNAME record pointing to r.forwarddomain.net.

2024-07-15 09:49 UTC, CuteDog5695 requested changes

2024-07-15 09:49 UTC, CuteDog5695 commented on domains/_.pc.json
File name is invalid.

2024-07-15 22:23 UTC, MCPE-PC commented on domains/_.pc.json
I am trying to register `_.pc.is-a.dev` and the Discord bot generated that file name.

2024-07-16 09:10 UTC, CuteDog5695 commented on domains/_.pc.json
Checks are failing because of the file name

2024-07-16 22:39 UTC, closed without merging