Register daisuu.is-a.dev
is-a-dev/register pull request #14938
Opened 2024-07-16 06:43 UTC by DaisuKiee

Register daisuu.is-a.dev with CNAME record pointing to c6571a19-e974-48d0-848f-fff7f971c3b3.id.repl.co.

2024-07-16 06:46 UTC, DaisuKiee commented
how can i do this?

2024-07-16 09:21 UTC, CuteDog5695 requested changes

2024-07-16 09:21 UTC, CuteDog5695 commented on domains/daisukie.json
> +            "A": ["68.65.123.44"]
403 forbidden, please give a preview of your website.

2024-07-16 18:42 UTC, triach-rold reviewed
Website is unreachable.

2024-07-18 02:24 UTC, orxngc commented
Closing as stale.

2024-07-18 02:24 UTC, closed without merging