I make 38middle.json
is-a-dev/register pull request #14958
Opened 2024-07-17 09:20 UTC by SoftOSDev

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

huaxihao.eu.org

2024-07-17 10:30 UTC, CuteDog5695 requested changes

2024-07-17 10:30 UTC, CuteDog5695 commented on domains/38middle.json
> +    ]
You cannot use CNAME with A records (just pick one of them and remove the other one)

2024-07-17 10:30 UTC, CuteDog5695 commented on domains/38middle.json
> +    "CNAME": "softosdev.github.io",
404 page, please give a preview of your website

2024-07-18 23:05 UTC, orxngc commented
Closing as stale.

2024-07-18 23:05 UTC, closed without merging