Register xkotelek.is-a.dev
is-a-dev/register pull request #14954
Opened 2024-07-17 07:13 UTC by xKotelek

Register xkotelek.is-a.dev with CNAME record pointing to xkotelek.github.io.

2024-07-17 08:13 UTC, CuteDog5695 requested changes

2024-07-17 08:13 UTC, CuteDog5695 commented on CNAME
Delete this file please

2024-07-17 08:14 UTC, xKotelek commented on CNAME
what file?

2024-07-17 08:16 UTC, xKotelek commented on CNAME
kotelek.json was deleted

2024-07-17 08:22 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-07-17 08:22 UTC, merged

2024-08-09 21:10 UTC, xKotelek commented
Still can't enforce HTTPS 
![image](https://github.com/user-attachments/assets/a8d086bb-43b5-4af1-b549-c4d2af84e3de)
And an error:
![image](https://github.com/user-attachments/assets/ab941d10-ef1c-4f34-b65c-a8c2bb42b7b2)
Connection is not private
Attackers may be trying to steal your information from xkotelek.is-a.dev (such as passwords, messages, or credit card information). More information
net::ERR_CERT_COMMON_NAME_INVALID
xkotelek.is-a.dev typically uses encryption to protect your information. When Brave tried to connect to xkotelek.is-a.dev this time, it sent back unusual and incorrect login information. This can happen when an attacker is impersonating xkotelek.is-a.dev or when the Wi-Fi login screen interrupts the connection. Your information is still safe because the connection in Brave ended before any data was exchanged.

You can't visit xkotelek.is-a.dev right now because it uses HSTS. Network errors and attacks are usually temporary, so the site will likely be available later.