Create _discord.lumix.json
is-a-dev/register pull request #14981
Opened 2024-07-18 17:42 UTC by o-lumix

2024-07-18 23:01 UTC, orxngc requested changes, later dismissed
Invalid file name, change the .is-a.dev to .json. Also I see that your website is a literal copy of my website, that's wild my guy. 🔥

2024-07-20 13:45 UTC, CuteDog5695 requested changes

2024-07-20 13:45 UTC, CuteDog5695 commented on domains/_discord.lumix.is-a.dev
Replace .is-a.dev with .json

2024-07-20 14:29 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-07-20 14:30 UTC, merged