add catro.is-a.dev
is-a-dev/register pull request #15029
Opened 2024-07-21 07:17 UTC by catrophie

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

![image](https://github.com/user-attachments/assets/cd1571a7-9fe1-40bd-999c-be052c761ec9)

2024-07-21 07:21 UTC, MaskDuck requested changes

2024-07-21 07:22 UTC, catrophie commented on domains/catro.json
> +        "CNAME": "catrophie.github.io"
it broke it self and it is refusing to fix what do i do

2024-07-21 07:25 UTC, catrophie commented on domains/catro.json
> +        "CNAME": "catrophie.github.io"
https://catrophie.github.io/catro.is-a.dev/

2024-07-21 23:50 UTC, Yunexiz commented on domains/catro.json
> +        "CNAME": "catrophie.github.io"
> 404 website

github wants to use CNAME directly to the users github.io (which you cant reach). the actual ones are hosted with /repo-name

2024-07-23 13:21 UTC, orxngc commented
Closing as stale.

2024-07-23 13:21 UTC, closed without merging