Register phv.is-a.dev
is-a-dev/register pull request #15034
Opened 2024-07-21 15:18 UTC by PHV08

Register phv.is-a.dev with TXT record pointing to Hello, Myself PHV, a Dedicated developer.

2024-07-21 18:07 UTC, CuteDog5695 requested changes

2024-07-21 18:07 UTC, CuteDog5695 commented on domains/phv.json
> +            "TXT": "hello, myself phv, a dedicated developer"
TXT doesn't do anything.

2024-07-23 13:23 UTC, orxngc commented
Closing as stale.

2024-07-23 13:23 UTC, closed without merging

2024-07-23 13:26 UTC, orxngc commented
Closing as stale.