Create _github-pages-challenge-daglaroglou.dag.json
is-a-dev/register pull request #15048
Opened 2024-07-22 13:33 UTC by daglaroglou

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-07-22 13:36 UTC, Stef-00012 requested changes

2024-07-22 13:36 UTC, Stef-00012 commented on domains/_github-pages-challenge-daglaroglou.dag.json
> +        "email": "<christos.daglaroglou@gmail.com>"
Invalid socials, Remove the `<>` from the email field

2024-07-22 13:36 UTC, Stef-00012 commented on domains/_github-pages-challenge-daglaroglou.dag.json
the `dag` subdomain does not exist so you can not create a subdomain of that

2024-07-22 13:37 UTC, orxngc requested changes
You must own dag.is-a.dev to create a nested domain under it.

2024-07-22 13:55 UTC, daglaroglou commented
i do own it, i have it linked on discord as well but i dont have it pointing anywhere yet

2024-07-22 14:02 UTC, orxngc commented
No, you don't own it.
![image](https://github.com/user-attachments/assets/350bcf9f-7eda-4e1c-a1ed-d26ee5418a3f)
Register the subdomain first before we can merge this.

2024-07-22 14:04 UTC, daglaroglou commented
> No, you don't own it. ![image](https://private-user-images.githubusercontent.com/90866414/350993638-350bcf9f-7eda-4e1c-a1ed-d26ee5418a3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTczMDcsIm5iZiI6MTcyMTY1NzAwNywicGF0aCI6Ii85MDg2NjQxNC8zNTA5OTM2MzgtMzUwYmNmOWYtN2VkYS00ZTFjLWExZWQtZDI2ZWU1NDE4YTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE0MDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZGQ3N2ZhNGU0NWM5Mjc3MTlhYTc4ZDBhM2ZlZmVlZTA4MmM4ZjUxMmRjZTJjNTNiY2Y0NDQxZjA3NmI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZCvC4xL-vBPofIOIZcAspzXii3VJfOAPlxxanmaiYg) Register the subdomain first before we can merge this.

i have it linked in discord, i did the steps in the docs to link it there and i made a _discord........json file
![image](https://github.com/user-attachments/assets/f9fc52bb-4a95-4855-8db6-d2fd2c6a1aae)

2024-07-22 15:08 UTC, Stef-00012 commented
> > No, you don't own it. ![image](https://private-user-images.githubusercontent.com/90866414/350993638-350bcf9f-7eda-4e1c-a1ed-d26ee5418a3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTczMDcsIm5iZiI6MTcyMTY1NzAwNywicGF0aCI6Ii85MDg2NjQxNC8zNTA5OTM2MzgtMzUwYmNmOWYtN2VkYS00ZTFjLWExZWQtZDI2ZWU1NDE4YTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE0MDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZGQ3N2ZhNGU0NWM5Mjc3MTlhYTc4ZDBhM2ZlZmVlZTA4MmM4ZjUxMmRjZTJjNTNiY2Y0NDQxZjA3NmI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZCvC4xL-vBPofIOIZcAspzXii3VJfOAPlxxanmaiYg) Register the subdomain first before we can merge this.
> 
> i have it linked in discord, i did the steps in the docs to link it there and i made a _discord........json file ![image](https://private-user-images.githubusercontent.com/70488503/350994285-f9fc52bb-4a95-4855-8db6-d2fd2c6a1aae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTc0NDAsIm5iZiI6MTcyMTY1NzE0MCwicGF0aCI6Ii83MDQ4ODUwMy8zNTA5OTQyODUtZjlmYzUyYmItNGE5NS00ODU1LThkYjYtZDJmZDJjNmExYWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE0MDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNDA1Njc3N2I0M2NhYmY5OTIwNjZmOTNhMTI4NzFjY2RiNjYyNGI3YmFkYzIzZjRmNWM1ZGFlOTE3OWM2N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ARrd9kR1o6tPgODvtl38Z2BVm7SdtCG6cehmeN2_DkA)
> 
> can i make a dag.json file as well even if i have it for discord? if yes what should i include?

are you sure that it's verified? discord will still show the domain to yourself but if it isn't verified others won't see it (also you'll get a message in the connections)

2024-07-22 20:29 UTC, daglaroglou commented
![image](https://github.com/user-attachments/assets/0c00f1bd-a5e5-4bee-bb66-cc5bbada3af2)
i see this in connections

2024-07-22 20:45 UTC, CuteDog5695 commented
You know that wasn't supposed to be merged, right?
If you don't want us to remove the domain which has the discord txt then please make dag.json (with your website's records)

2024-07-22 20:59 UTC, daglaroglou commented
> You know that wasn't supposed to be merged, right? If you don't want us to remove the domain which has the discord txt then please make dag.json (with your website's records)

i dont have a website right now, i host it in github pages, so how can i link that there without the special guide of gh pages?

2024-07-24 12:23 UTC, orxngc commented
Closing this PR as stale for now. If you want to know how to register your site with Github Pages, follow the [documentation](https://www.is-a.dev/docs/github-pages/).

2024-07-24 12:23 UTC, closed without merging