Register lsmithx2.is-a.dev
is-a-dev/register pull request #15052
Opened 2024-07-22 15:36 UTC by lsmithx2

Register lsmithx2.is-a.dev with A record pointing to 109.169.71.157.

2024-07-22 15:51 UTC, DEV-DIBSTER requested changes

2024-07-22 15:51 UTC, DEV-DIBSTER commented on domains/admin.json
Domain name has the potential to be abused, this will be held in reserve.

2024-07-22 15:51 UTC, DEV-DIBSTER commented on domains/lsmithx2.json
> +            "A": ["109.169.71.157"]
Unable to view site, are you able to send a preview?

2024-07-24 12:17 UTC, orxngc commented
Closing as stale.

2024-07-24 12:17 UTC, closed without merging