Register shaxzodbek.is-a.dev
is-a-dev/register pull request #15130
Opened 2024-07-27 13:02 UTC by shaxCoder

Register shaxzodbek.is-a.dev with CNAME record pointing to shakhzodbekDev.github.io.

2024-07-27 13:21 UTC, Stef-00012 requested changes

2024-07-27 13:21 UTC, Stef-00012 commented on domains/shakhzodbek.json
> +            "A": ["109.95.212.121"]
can you show a preview of your website?

2024-07-27 13:21 UTC, Stef-00012 commented on domains/shaxzodbek.json
> +            "CNAME": "shakhzodbekdev.github.io"
404 not found

2024-07-29 01:17 UTC, orxngc commented
Closing as stale.

2024-07-29 01:17 UTC, closed without merging