Create shivam27
is-a-dev/register pull request #15151
Opened 2024-07-28 13:26 UTC by shiv1819

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-07-28 13:49 UTC, CuteDog5695 requested changes

2024-07-28 13:49 UTC, CuteDog5695 commented on domains/shivam27
> +    "TXT": "79ac9ab8571f3432e2ba77d0709fa9"
TXT doesn't do anything. Was this by any chance a Github Pages TXT verification? Because if so thats not how you do it.

2024-07-28 13:49 UTC, CuteDog5695 commented on domains/shivam27
File isn't a json file, please add .json after shivam27

2024-07-29 00:31 UTC, orxngc requested changes
TXT records alone don't do anything.

2024-07-29 09:10 UTC, shiv1819 commented
so what should i do? for my domain can u provide steps


On Mon, 29 Jul 2024 at 06:01, orangc ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> TXT records alone don't do anything.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/15151#pullrequestreview-2203647566>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5QOV7MVRKEPLAMYLVUTA3LZOWEPFAVCNFSM6AAAAABLSZ446WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBTGY2DONJWGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-01 17:10 UTC, CuteDog5695 commented
Read this doc for github pages https://www.is-a.dev/docs/github-pages/

2024-08-02 02:05 UTC, closed without merging