Register Janco.is-a.dev
is-a-dev/register pull request #15158
Opened 2024-07-28 17:05 UTC by JancoNel

Register Janco.is-a.dev with CNAME record pointing to https://janconel.github.io/Personalwebsite/.

2024-07-29 00:19 UTC, orxngc requested changes

2024-07-29 00:19 UTC, orxngc commented on domains/janco.json
> +            "CNAME": "https://janconel.github.io/personalwebsite/"
```suggestion
            "CNAME": "https://janconel.github.io"
```
CNAME records cannot contain slashes (`/`).

2024-07-29 00:19 UTC, orxngc commented
And your site is incomplete. Please add some content.

2024-07-29 16:46 UTC, JancoNel commented
Hi 

- I made the changes to record , was unsure about the what I should put in it becuae the last couple of times I also messed it up.

- About the incomplete website , I thought I would sort the domain/subdomain out before I start focusing on that

- Does the fact that it is incomplete cause any problems? @orxngc

2024-07-29 17:56 UTC, CuteDog5695 requested changes

2024-07-29 17:56 UTC, CuteDog5695 commented on domains/janco.json
> +            "CNAME": "https://janconel.github.io"
```suggestion
            "CNAME": "janconel.github.io"
```

2024-07-29 17:59 UTC, CuteDog5695 commented
Also about your website, at the moment its just a simple "Hello World!" with just some plain text. As from the comment you send, I understand that you first wanted the domain and then work on the websites, but we usually don't merge PRs which aren't "complete". If you want for this PR to be merged, you can add like a about me and then I'll merge the PR.

2024-07-30 17:00 UTC, JancoNel commented
Alright , I made the chanhges to janco.json , going to make some improvements to the site to make it look more complete now

2024-07-30 17:23 UTC, JancoNel commented
Done , the website looks a lot more complete now after a bit of work on it 

https://janconel.github.io/Personalwebsite/

2024-08-01 16:58 UTC, JancoNel commented
Screw it yall are taking your time im oppening a new PR

2024-08-01 16:58 UTC, closed without merging