Register z.is-a.dev
is-a-dev/register pull request #15231
Opened 2024-07-30 04:29 UTC by ZenZoyaUDR

Register z.is-a.dev with CNAME record pointing to vortres.netlify.app.

2024-07-30 06:29 UTC, wdhdev requested changes
I cannot reach your website.

2024-07-30 06:37 UTC, ZenZoyaUDR commented
wired i can access the site

2024-08-01 17:15 UTC, CuteDog5695 requested changes

2024-08-01 17:15 UTC, CuteDog5695 commented on domains/z.json
> +            "CNAME": "vortres.netlify.app"
Site works for me, but could you add more stuff to the website?

2024-08-03 17:35 UTC, orxngc commented
Closing as stale.

2024-08-03 17:35 UTC, closed without merging