Create h3lmcserver.json
is-a-dev/register pull request #15259
Opened 2024-07-30 23:55 UTC by gvalue-04

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview
*insert minecraft world here*

2024-07-30 23:58 UTC, gvalue-04 commented
This is for a minecraft server, so it does not have an accessible website. You can however connect to the server using Minecraft Java Edition 1.12.2

2024-07-31 01:50 UTC, DEV-DIBSTER requested changes, later dismissed

2024-07-31 01:50 UTC, DEV-DIBSTER commented on domains/h3lmcserver.json
> +    "CNAME": "on-clan.gl.at.ply.gg:25565"
CNAME cannot have port number.

2024-07-31 12:48 UTC, EducatedSuddenBucket commented
> on-clan.gl.at.ply.gg

hey you dont need cname with port , if you set your cname to on-clan.gl.at.ply.gg all ports on on-clan.gl.at.ply.gg will be accesible from your subdomain

2024-07-31 17:11 UTC, gvalue-04 commented
Updated

2024-07-31 17:17 UTC, gvalue-04 commented
the domain should be mc.h3l.is-a.dev

2024-07-31 19:08 UTC, CuteDog5695 requested changes

2024-07-31 19:08 UTC, CuteDog5695 commented on domains/mc.h3l.is-a.dev.json
remove .is-a.dev from the name

2024-07-31 19:13 UTC, gvalue-04 commented
Fixed

2024-07-31 19:20 UTC, CuteDog5695 approved these changes
Seems fine to me ig

2024-07-31 19:20 UTC, merged