Create and Merge snbhowmik.json
is-a-dev/register pull request #15282
Opened 2024-08-01 07:30 UTC by snbhowmik

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-08-01 17:22 UTC, CuteDog5695 requested changes

2024-08-01 17:22 UTC, CuteDog5695 commented on domains/snbhowmik.json
> +            "75.2.60.5"
Please give your site preview.

2024-08-01 18:04 UTC, snbhowmik commented on domains/snbhowmik.json
> +            "75.2.60.5"
![image](https://github.com/user-attachments/assets/b47ec96c-9725-4838-9b2f-d9eb17677229)

2024-08-02 08:38 UTC, CuteDog5695 requested changes

2024-08-02 08:38 UTC, CuteDog5695 commented on domains/snbhowmik.json
> +        "linkedin": "https://www.linkedin.com/in/snbhowmik/",
You need to add email line, though you can leave it blank if you don't want to give your email.

2024-08-02 10:14 UTC, CuteDog5695 requested changes, later dismissed

2024-08-02 10:14 UTC, CuteDog5695 commented on domains/snbhowmik.json
> +        "email": "snbhowmikac@proton.me",
```suggestion
        "email": "snbhowmikac@proton.me"
```

2024-08-02 16:26 UTC, orxngc approved these changes

2024-08-02 16:26 UTC, merged