Create _discord.meywy.is-a.dev
is-a-dev/register pull request #15314
Opened 2024-08-02 20:57 UTC by Meywy

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-08-02 20:58 UTC, Meywy commented
i dont know if it is required to send the web even when this is for discord, but here it is: https://meywy.is-a.dev

2024-08-02 22:28 UTC, Stef-00012 requested changes, later dismissed

2024-08-02 22:28 UTC, Stef-00012 commented on domains/_discord.meywy.is-a.dev
remove `.is-a.dev` and add `.json`

2024-08-02 22:30 UTC, Meywy commented on domains/_discord.meywy.is-a.dev
done

2024-08-03 04:51 UTC, MaskDuck approved these changes

2024-08-03 04:51 UTC, merged