Register mashrafi.is-a.dev
is-a-dev/register pull request #15355
Opened 2024-08-05 11:13 UTC by MashrafiYT

Register mashrafi.is-a.dev with CNAME record pointing to www.mashrafi.is-a.dev.

2024-08-05 12:40 UTC, Stef-00012 requested changes

2024-08-05 12:40 UTC, Stef-00012 commented on domains/_discord.example.json
> +        "username": "github-username",
You should replace `github-username` with your github username

2024-08-05 12:40 UTC, Stef-00012 commented on domains/_discord.example.json
> +        "email": "email@address"
You should replace `email@address` with your email address (or keep as empty string, `""`)

2024-08-07 13:29 UTC, orxngc commented
Closing as stale.

2024-08-07 13:29 UTC, closed without merging