Register xohcloud.is-a.dev
is-a-dev/register pull request #15366
Opened 2024-08-05 19:19 UTC by aysko-discord

Register xohcloud.is-a.dev with TXT record pointing to xohcloud.fr.

2024-08-05 19:21 UTC, CuteDog5695 requested changes

2024-08-05 19:21 UTC, CuteDog5695 commented on domains/aysko.json
> +            "CNAME": "relaxed-sable-26f2ce.netlify.app."
Site not found, also technically CNAME is invalid
```suggestion
            "CNAME": "relaxed-sable-26f2ce.netlify.app"
```

2024-08-05 19:21 UTC, CuteDog5695 commented on domains/ayskobtw.json
> +        "CNAME": "guns.lol/aysko"
```suggestion
        "CNAME": "guns.lol"
```

2024-08-05 19:21 UTC, CuteDog5695 commented on domains/ayskobtww.json
> +        "URL": "guns.lol/aysko"
URL records need to have protocol
```suggestion
        "URL": "https://guns.lol/aysko"
```

2024-08-05 19:21 UTC, CuteDog5695 commented on domains/xohcloud.json
> +            "TXT": "xohcloud.fr"
TXT doesn't do anything technically

2024-08-07 13:29 UTC, orxngc commented
Closing as stale.

2024-08-07 13:29 UTC, closed without merging