Add fame.is-a-dev
is-a-dev/register pull request #15421
Opened 2024-08-08 00:23 UTC by TheRealFame

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [✓ ] The file is in the `domains` folder and is in the JSON format.
- [✓ ] The file's name is all lowercased and alphanumeric. 
- [ ✓] You have completed your website. 
- [ ✓] The website is reachable.  
- [ ✓] You're not using Vercel.  
- [ ✓] The CNAME record doesn't contain `https://` or `/`.  
- [ ✓] There is sufficient information at the `owner` field.  

## Website Link/Preview

[cutefame.net](https://cutefame.net)

2024-08-08 12:43 UTC, Stef-00012 requested changes

2024-08-08 12:43 UTC, Stef-00012 commented on domains/fame.json
> +        "username": "<TheRealFame>",
Remove <>
```suggestion
        "username": "TheRealFame",
```

2024-08-08 12:43 UTC, Stef-00012 commented on domains/fame.json
> +        "twitter": "<The_RealFame>"
Remove <>
```suggestion
        "twitter": "The_RealFame"
```

2024-08-08 12:43 UTC, Stef-00012 commented on domains/fame.json
Invalid JSON
Missing records

2024-08-08 18:54 UTC, TheRealFame commented on domains/fame.json
Records?

2024-08-09 02:11 UTC, orxngc requested changes
???
You don't have any records. Read the documentation: https://is-a.dev/docs
Invalid file & JSON.

2024-08-10 17:33 UTC, closed without merging

2024-08-12 01:40 UTC, TheRealFame commented
The requested cname for an .is-a-dev domain should be there now, I just don't know if my current json on my branch is invalid, or the one i made through documentation is.

2024-08-12 01:40 UTC, TheRealFame commented
@Stef-00012