Register visualhc.is-a.dev
is-a-dev/register pull request #15515
Opened 2024-08-12 10:20 UTC by max96git

Register visualhc.is-a.dev with CNAME record pointing to apex-loadbalancer.netlify.com.

2024-08-12 15:46 UTC, Stef-00012 requested changes

2024-08-12 15:46 UTC, Stef-00012 commented on domains/visualhc.json
> +            "CNAME": "apex-loadbalancer.netlify.com"
I cannot reach your website, netlify says "Site Not Found"

2024-08-12 15:46 UTC, MaskDuck submitted a review, later dismissed

2024-08-14 08:12 UTC, orxngc commented
Closing as stale.

2024-08-14 08:12 UTC, closed without merging