Register tahag.is-a.dev
is-a-dev/register pull request #15526
Opened 2024-08-13 07:22 UTC by TahaGorme

Register tahag.is-a.dev with A record pointing to 68.65.123.44.

2024-08-13 15:02 UTC, DEV-DIBSTER requested changes

2024-08-13 15:02 UTC, DEV-DIBSTER commented on domains/tahagorme.json
> +        "TXT": ""
Invalid record, TXT records alone don't do anything.

2024-08-13 15:02 UTC, DEV-DIBSTER commented on domains/tahag.json
> +            "A": ["68.65.123.44"]
I get a 403 forbidden page, please send a preview of the site.

2024-08-15 09:38 UTC, orxngc commented
Closing as stale.

2024-08-15 09:38 UTC, closed without merging