Add fictiveds.is-a.dev subdomain
is-a-dev/register pull request #15562
Opened 2024-08-14 11:10 UTC by fictiveds

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-08-14 13:17 UTC, CuteDog5695 requested changes

2024-08-14 13:17 UTC, CuteDog5695 commented on fictiveds.json
> +    "subdomain": "is-a",
please remove this

2024-08-14 13:17 UTC, CuteDog5695 commented on fictiveds.json
file needs to be in domains directory

2024-08-15 10:06 UTC, orxngc approved these changes, later dismissed

2024-08-15 10:06 UTC, orxngc approved these changes

2024-08-15 10:07 UTC, orxngc requested changes
Inaccessible website, please provide a preview.

2024-08-16 04:32 UTC, closed without merging