Update ehab.json
is-a-dev/register pull request #15566
Opened 2024-08-14 11:52 UTC by ehabmansour1

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-08-14 13:15 UTC, CuteDog5695 requested changes

2024-08-14 13:15 UTC, CuteDog5695 commented on domains/ehab.json
> +        "A": ["128.204.223.115"],
You can't use CNAME with A records.

2024-08-14 13:15 UTC, CuteDog5695 commented on domains/ehab.json
>              "dns2.serv00.com"
Uh we don't support NS records currently (since we don't even have them)

2024-08-15 09:41 UTC, orxngc commented
Closing as duplicate.

2024-08-15 09:41 UTC, closed without merging