Please review my PR
is-a-dev/register pull request #15601
Opened 2024-08-16 00:57 UTC by wweziza

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://lsrp.world

2024-08-16 04:30 UTC, DEV-DIBSTER requested changes

2024-08-16 04:30 UTC, DEV-DIBSTER commented on domains/weziza.json
> +    "CNAME": "dev.lsrp.world"
Cannot reach your site.

2024-08-16 04:30 UTC, DEV-DIBSTER commented on domains/weziza.json
> +    "CNAME": "dev.lsrp.world"
Cannot reach your site.

2024-08-18 07:24 UTC, orxngc commented
Closing as stale.

2024-08-18 07:24 UTC, closed without merging