project
is-a-dev/register pull request #15620
Opened 2024-08-17 09:18 UTC by KarmaAI-soldat

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-08-17 11:52 UTC, CuteDog5695 requested changes

2024-08-17 11:52 UTC, CuteDog5695 commented on domains/soldat.json
File is empty.

2024-08-17 11:52 UTC, CuteDog5695 commented on domains/soldat.is-a.dev
File is empty and also isn't in json format.

2024-08-17 11:52 UTC, CuteDog5695 commented on domains/subway.json
> +    },
You need to add your github username here.

2024-08-17 11:52 UTC, CuteDog5695 commented on domains/subway.json
I don't think we can merge this since Subway is technically trade-marked.

2024-08-17 12:09 UTC, KarmaAI-soldat commented on domains/subway.json
let me fix it

2024-08-17 16:05 UTC, DEV-DIBSTER requested changes

2024-08-17 16:05 UTC, DEV-DIBSTER commented on domains/soldat.is-a.dev
Empty file.

2024-08-17 16:05 UTC, DEV-DIBSTER commented on domains/soldat.json
Empty file.

2024-08-18 08:18 UTC, KarmaAI-soldat commented on domains/soldat.is-a.dev
how?

2024-08-18 14:17 UTC, omsenjalia commented
Please fix your stuff and then re open the pr. It's far away from being accepted.

2024-08-18 14:17 UTC, closed without merging