my domain name and details
is-a-dev/register pull request #15663
Opened 2024-08-20 15:32 UTC by keviiixaviiii

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-08-20 17:18 UTC, Stef-00012 requested changes

2024-08-20 17:18 UTC, Stef-00012 commented on domains/kevin-xavier.is-a.dev
Remove `.is-a.dev` and add `.json`

2024-08-20 17:18 UTC, Stef-00012 commented on domains/kevin-xavier.is-a.dev
> +  "subdomain": "kevin-xavier",
`subdomain` is not a valid key in is-a.dev

2024-08-20 17:18 UTC, Stef-00012 commented on domains/kevin-xavier.is-a.dev
> +    "CNAME": "keviiixaviiii.github.io"
I cannot reach your website, 404 page

2024-08-22 07:42 UTC, orxngc commented
Closing as stale.

2024-08-22 07:42 UTC, closed without merging