Create elyagoubi.json
is-a-dev/register pull request #15689
Opened 2024-08-21 23:26 UTC by abdessattar23

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

### https://abdessattar23.github.io
![Website Screenshot](https://github.com/user-attachments/assets/ac52cb44-cd08-471e-844e-6e07a74c4a88)

2024-08-21 23:35 UTC, DEV-DIBSTER requested changes

2024-08-21 23:35 UTC, DEV-DIBSTER commented on domains/elyagoubi.json
> +        "CNAME": "abdessattar23.github.io",
Cannot have CNAME in conjunction with other records as per DNS rules.

2024-08-22 00:09 UTC, abdessattar23 commented
@DEV-DIBSTER OK thanks for noticing that brother, I have fixed the records by changing the CNAME record into A record pointing on the IP Address

2024-08-22 00:10 UTC, DEV-DIBSTER approved these changes, later dismissed

2024-08-22 00:11 UTC, DEV-DIBSTER commented
Actually wait, you'll need to put them in an array as GitHub wants all of those IPs, there should be 4.

2024-08-22 00:24 UTC, abdessattar23 commented
@DEV-DIBSTER Ohhh I missed that too, sorry lmao can you check now if it is valid

2024-08-22 01:00 UTC, DEV-DIBSTER approved these changes

2024-08-22 01:02 UTC, merged