Update zayaanar.is-a.dev to allow for Zoho Mail usage, and GitHub, Discord connections
is-a-dev/register pull request #15706
Opened 2024-08-22 20:11 UTC by userandaname

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] The file's name is all lowercased and alphanumeric. 
- [X] You have completed your website. 
- [X] The website is reachable.  
- [X] You're not using Vercel.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-08-22 20:15 UTC, userandaname commented
let me know if i need to change anything or if there are any issues preventing this to be merged! :)

2024-08-23 11:14 UTC, CuteDog5695 requested changes

2024-08-23 11:14 UTC, CuteDog5695 commented on domains/zayaanar.json
> +            "TXT": ["v=spf1 include:zohomail.com ~all"]
You cannot use CNAME with MX and TXT records, also CNAME isn't supposed to be in a array

2024-08-23 12:54 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-08-23 12:54 UTC, merged