Register frndshostel.is-a.dev
is-a-dev/register pull request #15778
Opened 2024-08-26 17:42 UTC by kakarot-dev

Register frndshostel.is-a.dev with A record pointing to 100.72.127.43.

2024-08-26 17:44 UTC, DEV-DIBSTER requested changes

2024-08-26 17:44 UTC, DEV-DIBSTER commented on domains/frndshostel.json
> +            "A": ["100.72.127.43"]
Unable to access the site.

2024-08-26 17:44 UTC, DEV-DIBSTER commented on domains/frndshosteldrive.json
> +            "A": ["45.8.201.208"]
Unable to access the site.

2024-08-27 11:52 UTC, orxngc requested changes

2024-08-27 11:52 UTC, orxngc commented on domains/frndshostel.json
This site is still inaccessible.

2024-08-28 05:41 UTC, closed without merging