Register mr-julus.is-a.dev
is-a-dev/register pull request #15821
Opened 2024-08-29 17:07 UTC by BougSoon-Studio

Register mr-julus.is-a.dev with CNAME record pointing to mr-julus.web.app.

2024-08-29 18:24 UTC, Stef-00012 requested changes, later dismissed

2024-08-29 18:24 UTC, Stef-00012 commented on domains/mr-julus
The file should be a JSON fil (end with `.json`)

2024-08-29 18:37 UTC, BougSoon-Studio commented on domains/mr-julus
it's done

2024-08-30 14:18 UTC, orxngc approved these changes

2024-08-30 14:19 UTC, merged