Update minhphan.json
is-a-dev/register pull request #15888
Opened 2024-09-02 14:40 UTC by MinhPhan1203

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-09-02 15:13 UTC, DEV-DIBSTER requested changes

2024-09-02 15:13 UTC, DEV-DIBSTER commented on domains/minhphan.json
> +            "216.24.57.1"
Unable to access site, are you able to send a preview?

2024-09-02 15:41 UTC, MaskDuck requested changes
duplicate PR. please address it (details in DMs)

2024-09-03 06:50 UTC, orxngc commented
closing as duplicate of #15891

2024-09-03 06:50 UTC, closed without merging