Add jalaj.json
is-a-dev/register pull request #1589
Opened 2022-01-21 03:00 UTC by jalajcodes

2022-01-23 15:45 UTC, phenax requested changes
Unfortunately, netlify doesn't support is-a-dev cnames. You can use URL redirection or a different hosting service like railway.app

2022-02-26 04:27 UTC, jalajcodes commented
> Unfortunately, netlify doesn't support is-a-dev cnames. You can use URL redirection or a different hosting service like railway.app

@phenax Changed to Vercel

2022-02-26 05:23 UTC, jalajcodes commented
Nvm just found that vercel is also not supported.

Still figuring out how to deploy gatsby site to railway.

2022-02-26 16:46 UTC, phenax approved these changes

2022-02-26 16:47 UTC, merged