Register gabrigode.is-a.dev
is-a-dev/register pull request #15937
Opened 2024-09-06 01:31 UTC by gabrigode

Register gabrigode.is-a.dev with CNAME record pointing to https://github.com/gabrigode.

2024-09-06 04:18 UTC, DEV-DIBSTER requested changes

2024-09-06 04:18 UTC, DEV-DIBSTER commented on domains/gabrigode.json
> +            "CNAME": "https://github.com/gabrigode"
CNAME should be just a hostname.

2024-09-06 07:02 UTC, gabrigode commented on domains/gabrigode.json
> +            "CNAME": "https://github.com/gabrigode"
Sorry! Changed!

2024-09-06 07:02 UTC, gabrigode reviewed
Changed!

2024-09-06 07:20 UTC, orxngc submitted a review, later dismissed

2024-09-06 07:20 UTC, orxngc commented on domains/gabrigode.json
> +            "CNAME": "github.com/gabrigode"
CNAMEs cannot contain slashes `/`. If you want this to redirect to your Github profile, I recommend using https://redirect.pizza and following their instructions; or you can use our (unstable) URL records like this:

```suggestion
            "URL": "https://github.com/gabrigode"
```

2024-09-07 03:47 UTC, DEV-DIBSTER approved these changes

2024-09-07 03:48 UTC, merged