Create crvt
is-a-dev/register pull request #15939
Opened 2024-09-06 09:19 UTC by slovakians

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

link : http://181.215.58.8:1993/
Fixes #

2024-09-06 09:32 UTC, CuteDog5695 requested changes

2024-09-06 09:32 UTC, CuteDog5695 commented on domains/crvt
File isn't in json format.

2024-09-06 09:35 UTC, slovakians commented on domains/crvt
oh...
sorry i didnt see it

2024-09-08 05:07 UTC, orxngc requested changes
This site is inaccessible, please provide a preview.

2024-09-08 05:09 UTC, closed without merging

2024-09-08 05:09 UTC, orxngc commented
Closing as duplicate of #15941.