Create prozt.json
is-a-dev/register pull request #1600
Opened 2022-01-22 03:28 UTC by Techpro709

Add prozt domain

2022-01-22 03:38 UTC, prabincankod requested changes
CNAME record cannot be a link with directory, it must me plain. or you can use 'URL' key instead of 'CNAME' to redirect your subdomain to the destination of yours.

2022-01-22 03:47 UTC, prabincankod commented on domains/prozt.json
> +    "CNAME": "https://www.proz.tk/prozt709/"
either change the 'CNAME' key to 'URL' or make the 'CNAME' key value valid of some sort.

2022-01-22 03:59 UTC, Techpro709 reviewed
I Changed it

2022-01-22 04:09 UTC, Techpro709 commented
https://github.com/is-a-dev/register/pull/1600/files/a8a2a7a9ffe151dabaaf97baf3ffeff3e3bfcda6#diff-9d1213b2617ef9d99060005f5fd9195760a9de1e5a5fe725651a8c67361b9631.patch

2022-01-22 04:09 UTC, Techpro709 commented
https://github.com/is-a-dev/register/pull/1600/files/a8a2a7a9ffe151dabaaf97baf3ffeff3e3bfcda6#diff-9d1213b2617ef9d99060005f5fd9195760a9de1e5a5fe725651a8c67361b9631.diff

2022-01-22 15:53 UTC, Techpro709 commented
https://patch-diff.githubusercontent.com/raw/is-a-dev/register/pull/1600.patch

2022-01-22 15:53 UTC, Techpro709 commented
https://patch-diff.githubusercontent.com/raw/is-a-dev/register/pull/1600.patch

2022-01-23 15:48 UTC, phenax approved these changes

2022-01-23 15:48 UTC, merged