Register xeh.is-a.dev
is-a-dev/register pull request #16024
Opened 2024-09-10 11:58 UTC by Saulencijus10

Register xeh.is-a.dev with A record pointing to 129.151.255.81.

2024-09-10 12:45 UTC, DEV-DIBSTER requested changes

2024-09-10 12:45 UTC, DEV-DIBSTER commented on domains/your-domain-name.json
This file should be deleted.

2024-09-13 07:32 UTC, orxngc requested changes
This site is inaccessible, please provide a preview.

2024-09-13 07:32 UTC, orxngc commented
Closing as stale.

2024-09-13 07:32 UTC, closed without merging