mnethegamer@gmail.com
is-a-dev/register pull request #16049
Opened 2024-09-12 08:44 UTC by MNEzone

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://emenee-ht4vnrn.gamma.site/

2024-09-12 16:51 UTC, Stef-00012 requested changes, later dismissed

2024-09-12 16:51 UTC, Stef-00012 commented on domains/emenee.json
> +    "username": "emenee",
Username must match your github username

2024-09-12 18:31 UTC, emeneekw commented
Done ✅

On Thu, 12 Sept 2024, 7:51 pm Stef_DP, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In domains/emenee.json
> <https://github.com/is-a-dev/register/pull/16049#discussion_r1757243818>:
>
> > @@ -0,0 +1,11 @@
> +{
> +  "description": "Emenee's design portfolio",
> +  "repo": "https://github.com/is-a-dev/docs",
> +  "owner": {
> +    "username": "emenee",
>
> Username must match your github username
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/16049#pullrequestreview-2300905438>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BHHM2EYHJQVKNCYXYXC2NGLZWHBCXAVCNFSM6AAAAABOCVMZQCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMBQHEYDKNBTHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-14 15:22 UTC, orxngc approved these changes

2024-09-14 15:23 UTC, merged