Create haianh.json
is-a-dev/register pull request #16053
Opened 2024-09-12 12:43 UTC by hungwt

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-09-12 13:41 UTC, EducatedSuddenBucket commented
A record should be an array

2024-09-12 16:56 UTC, Stef-00012 commented
> A record should be an array

I can fix that directly

2024-09-12 16:56 UTC, Stef-00012 requested changes

2024-09-12 16:56 UTC, Stef-00012 commented on domains/haianh.json
> +            "A": ["31.186.83.254"]
Can you show a preview of your website?

2024-09-12 17:01 UTC, Stef-00012 requested changes

2024-09-12 17:01 UTC, Stef-00012 commented on domains/haianh.json
> +           "username": "haianh",
also username should be your github username

2024-09-12 17:03 UTC, Stef-00012 commented
this same file is also in #16057

2024-09-14 15:22 UTC, orxngc commented
Closing as stale.

2024-09-14 15:22 UTC, closed without merging