Register haianh.is-a.dev
is-a-dev/register pull request #16057
Opened 2024-09-12 15:35 UTC by hungwt

Register haianh.is-a.dev with A record pointing to 31.186.83.254.

2024-09-12 17:03 UTC, Stef-00012 requested changes

2024-09-12 17:03 UTC, Stef-00012 commented on domains/haianh.json
> +            "A": ["31.186.83.254"]
Can you show a preview of your website?

2024-09-12 17:03 UTC, Stef-00012 commented on domains/xn--duyhng-6zb.json
> +        "A": ["31.186.83.254"]
Can you show a preview of your website?

2024-09-14 15:21 UTC, orxngc commented
Closing as stale.

2024-09-14 15:21 UTC, closed without merging