Update artaabedi.json
is-a-dev/register pull request #16093
Opened 2024-09-14 12:40 UTC by artaabedi

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-09-14 12:41 UTC, artaabedi commented
I had a typo in the record text that I fixed. Please check this file again.

2024-09-14 15:23 UTC, Stef-00012 requested changes

2024-09-14 15:23 UTC, Stef-00012 commented on domains/artaabedi.json
> +    ],
remove this comma
```suggestion
    ]
```

2024-09-15 03:51 UTC, DEV-DIBSTER approved these changes

2024-09-16 16:27 UTC, closed without merging