Update CNAME in azer.json
is-a-dev/register pull request #1623
Opened 2022-01-26 20:36 UTC by Sadykhzadeh

2022-01-28 14:04 UTC, phenax approved these changes

2022-01-28 14:06 UTC, phenax requested changes
I missed this in your last pr but please enter your email address. We need a way to contact you if we need to inform you about any changes to the service. Twitter/Discord will do too. Please refer to our documentation for information regarding what fields are required.

2022-01-28 17:26 UTC, Sadykhzadeh commented
> We need a way to contact you if we need to inform you about any changes to the service.

Done! Thank you a lot for this awesome domain ^_^

2022-01-29 08:43 UTC, phenax submitted a review, later dismissed

2022-01-29 08:44 UTC, merged