Create kachi.json
is-a-dev/register pull request #16254
Opened 2024-09-23 07:43 UTC by joshex150

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x ] The file is in the `domains` folder and is in the JSON format.
- [x ] The file's name is all lowercased and alphanumeric. 
- [x ] You have completed your website. 
- [x ] The website is reachable.  
- [x ] The CNAME record doesn't contain `https://` or `/`.  
- [x ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-09-23 20:45 UTC, Stef-00012 approved these changes

2024-09-23 20:45 UTC, Stef-00012 requested changes, later dismissed

2024-09-23 20:45 UTC, Stef-00012 commented on kachi.json
wait nevermind, file has to be in the domains folder

2024-09-23 23:40 UTC, joshex150 commented on kachi.json
it isn't ?

2024-09-24 12:48 UTC, orxngc submitted a review, later dismissed

2024-09-24 12:48 UTC, orxngc commented on kachi.json
no it wasn't, i'll move it for you, do it properly next time

2024-09-24 12:49 UTC, orxngc approved these changes

2024-09-24 12:50 UTC, merged