Create create yesnielx.json
is-a-dev/register pull request #16257
Opened 2024-09-23 18:45 UTC by YesnielX

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://yesnielx.github.io/portfolio

2024-09-23 20:41 UTC, Stef-00012 requested changes, later dismissed

2024-09-23 20:41 UTC, Stef-00012 commented on domains/yesnielx.json
> +        "CNAME": "yesnielx.github.io/portfolio"
CNAME can not contain `/`

2024-09-23 22:29 UTC, YesnielX commented on domains/yesnielx.json
> +        "CNAME": "yesnielx.github.io/portfolio"
Solved!

2024-09-23 23:16 UTC, YesnielX commented
Now https://yesnielx.github.io

2024-09-24 01:01 UTC, DEV-DIBSTER approved these changes
LGTM.

2024-09-24 01:01 UTC, merged