Update _github-pages-challenge-clay990.suraj.json
is-a-dev/register pull request #16253
Opened 2024-09-23 07:20 UTC by Clay990

Mail is not verifying 
![Screenshot_20240923-120835_1](https://github.com/user-attachments/assets/e82252c3-def2-4b20-86d4-3c9c27b48eae)

2024-09-23 17:05 UTC, DEV-DIBSTER requested changes

2024-09-23 17:05 UTC, DEV-DIBSTER commented on domains/_github-pages-challenge-clay990.suraj.json
> +  "TXT": [
Array should contain just strings and not objects.

2024-09-23 17:11 UTC, DEV-DIBSTER commented on domains/_github-pages-challenge-clay990.suraj.json
> +  "TXT": [
@Clay990 Arrays I was referring to was the TXT records.

2024-09-23 17:29 UTC, Clay990 commented
![Screenshot_20240923-225711_1](https://github.com/user-attachments/assets/7eea3569-4f1c-43c1-a54f-27befa568657)

2024-09-24 01:02 UTC, DEV-DIBSTER commented
> ![Screenshot_20240923-225711_1](https://private-user-images.githubusercontent.com/83020021/369983999-7eea3569-4f1c-43c1-a54f-27befa568657.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDAwMjksIm5iZiI6MTcyNzEzOTcyOSwicGF0aCI6Ii84MzAyMDAyMS8zNjk5ODM5OTktN2VlYTM1NjktNGYxYy00M2MxLWE1NGYtMjdiZWZhNTY4NjU3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAxMDIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZDAyM2U3OTY1OWM5ZjJhNjVkNWI0ZTUzMWE3MWIyNjAwNDQ3NzBjOTVjMzE5NzJkYTEzZjAyOTNiOTEzNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Tb_NXYVW7GvV1AMzXxG-Ho9iQ-IoX1rNiyaCAMipOd0)

If this is the file, then you would have to create a folder with that TXT name, as that's not under this file. File names directly determine the subdomain you are requesting.

2024-09-24 01:38 UTC, Clay990 commented
![Screenshot_20240924-070659_1](https://github.com/user-attachments/assets/64e514b9-3410-4cd0-bb7c-8ae58b4510c9)
------------------
![Screenshot_20240924-065610_1](https://github.com/user-attachments/assets/9f6e2ab9-5861-48db-954a-0581c5710c2c)
--------------------
![Screenshot_20240924-065708_1](https://github.com/user-attachments/assets/04e90771-5a48-4299-8141-87ffda70834d)
--------------------
![Screenshot_20240924-065718_1](https://github.com/user-attachments/assets/b5695939-2349-4785-9a25-cdc588b647c5)
--------------------
So the thing is I have created a mail name (official@suraj.is-a.dev) So, Zoho mail service want me to verify that 3 things MX, SPF and DKIM.
Now, what I do? I have to create 3 txt file or something else? Tell me!

2024-09-24 02:45 UTC, DEV-DIBSTER commented
> So the thing is I have created a mail name ([official@suraj.is-a.dev](mailto:official@suraj.is-a.dev)) So, Zoho mail service want me to verify that 3 things MX, SPF and DKIM.
Now, what I do? I have to create 3 txt file or something else? Tell me!

You would need to create 3 different .json files with the corresponding names that matches your records, and then for each of those files, have the correct TXT record value.

2024-09-24 06:14 UTC, Clay990 commented
Ok I set this file as it before.

2024-09-24 12:59 UTC, DEV-DIBSTER requested changes

2024-09-24 12:59 UTC, DEV-DIBSTER commented on domains/mx.json
Double check this is for the actual domain you're requesting (like mx.dibster.json as opposed to mx.json).

2024-09-24 12:59 UTC, DEV-DIBSTER commented on domains/spf.json
Double check this is for the actual domain you're requesting (like mx.dibster.json as opposed to mx.json).

2024-09-24 12:59 UTC, DEV-DIBSTER commented on domains/zmail._domainkey.json
Double check this is for the actual domain you're requesting (like mx.dibster.json as opposed to mx.json).

2024-09-24 13:32 UTC, Clay990 commented on domains/mx.json
the mail service actually give Malti MX record I don't add it because I don't know JSON, if u know can u add it, I provided the picture in up comment.

2024-09-24 13:36 UTC, Clay990 commented on domains/spf.json
Verification for suraj.is-a.dev (zoho mail service) mail official@suraj.is-a.dev checked

2024-09-26 06:26 UTC, closed without merging