Create craete arifintajul4.json
is-a-dev/register pull request #16256
Opened 2024-09-23 12:21 UTC by arifintajul4

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://www.tajul.my.id/

2024-09-23 17:07 UTC, DEV-DIBSTER requested changes

2024-09-23 17:07 UTC, DEV-DIBSTER commented on domains/craete arifintajul4.json
Invalid file, it cannot have spaces in it's name.

2024-09-24 02:46 UTC, DEV-DIBSTER requested changes

2024-09-24 02:46 UTC, DEV-DIBSTER commented on domains/arifintajul4.json
> +    "RECORDTYPE": "tajul.my.id"
RECORDTYPE should be an actual record type and not a placeholder.

Please refer to the docs: https://docs.is-a.dev/

2024-09-24 12:31 UTC, DEV-DIBSTER approved these changes

2024-09-24 12:32 UTC, merged

2024-10-13 10:47 UTC, arifintajul4 commented
still cant access

2024-10-13 10:59 UTC, CuteDog5695 commented
Did you connect the domain to the hosting provider?

2024-10-13 11:06 UTC, arifintajul4 commented
<img width="809" alt="Screenshot 2024-10-13 at 18 05 20" src="https://github.com/user-attachments/assets/090e8acb-5d9b-406d-ab2c-11159f66188e">


> Did you connect the domain to the hosting provider?