Power DNS pipeline
is-a-dev/register pull request #16287
Opened 2024-09-25 02:17 UTC by andrewstech

DNSCONTROL

2024-09-25 02:44 UTC, wdhdev requested changes
Can you add support for NS records

2024-09-25 02:47 UTC, andrewstech commented
> Can you add support for NS records

done

2024-09-25 02:50 UTC, wdhdev requested changes

2024-09-25 02:50 UTC, wdhdev commented on dnsconfig.js
> +        NS('', domainData.record.NS + ".")
```suggestion
        NS('', `${domainData.record.NS}.`)
```

2024-09-25 02:50 UTC, wdhdev commented on dnsconfig.js
> +          NS('', domainData.record.NS[ns] + ".")
```suggestion
          NS('', `${domainData.record.NS}.`)
```

2024-09-25 02:50 UTC, wdhdev commented on dnsconfig.js
> +        MX('', 10, domainData.record.MX[mx] + ".") // Default priority is set to 10
```suggestion
        MX('', 10, `${domainData.record.MX[mx]}.`) // Default priority is set to 10
```

2024-09-25 02:50 UTC, wdhdev commented on dnsconfig.js
> +      CNAME('', domainData.record.CNAME + ".")
```suggestion
      CNAME('', `${domainData.record.CNAME}.`)
```

2024-09-25 02:51 UTC, wdhdev commented
Also, `Validation / DNS` checks are failing, is there a reason for this?

2024-09-25 03:02 UTC, andrewstech commented
> Also, `Validation / DNS` checks are failing, is there a reason for this?

Probably but it’s 4am I will fix it later

2024-09-25 04:12 UTC, wdhdev requested changes
Can we also add support for SRV records, that would be good. If possible set SRV records to be in an object like this:
```json
"SRV": {
  "priority": 10,
  "weight": 1,
  // ...
}
```

Here are the DNSControl docs on it: https://github.com/StackExchange/dnscontrol/blob/main/documentation/language-reference/domain-modifiers/SRV.md

2024-09-27 15:25 UTC, EducatedSuddenBucket commented
@wdhdev for support of srv u need to add many underscores to be valid like for eg
For minecraft there is _minecraft._tcp.sub.json

2024-10-16 09:27 UTC, closed without merging