Update to change link
is-a-dev/register pull request #1631
Opened 2022-01-27 22:59 UTC by MrShoeShoe66

update to new url from user website to org website

2022-01-28 04:44 UTC, MrShoeShoe66 commented
Please to this as soon as possible, due to migrating my website repo the site is invalid. I moved the repo account and repository!

2022-01-28 14:10 UTC, phenax requested changes
CNAME has to be a host name and not a url. Please check the documentation for more information. If you want a URL redirection, use URL instead of CNAME. If you want a CNAME record, remove everything but the host name.

2022-01-28 18:06 UTC, MrShoeShoe66 commented
one sec

2022-01-29 08:45 UTC, phenax approved these changes

2022-01-29 08:45 UTC, merged