Delete akborana.is-a.dev
is-a-dev/register pull request #16528
Opened 2024-10-12 07:17 UTC by akborana3

Delete akborana.is-a.dev via Discord

2024-10-12 10:05 UTC, Stef-00012 requested changes
Please resolve the merge conflicts

2024-10-12 17:39 UTC, DEV-DIBSTER submitted a review, later dismissed

2024-10-13 07:50 UTC, orxngc requested changes

2024-10-13 07:50 UTC, orxngc commented on domains/akay.json
This site is inaccessible, please provide a preview.

2024-10-13 07:50 UTC, orxngc commented on domains/akborana1.json
This site is inaccessible, please provide a preview.

2024-10-13 08:30 UTC, akborana3 commented on domains/akborana1.json
akborana.tech here is preview

2024-10-15 06:44 UTC, closed without merging