add ryan.json
is-a-dev/register pull request #16573
Opened 2024-10-13 22:10 UTC by epic-person-on

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [✅ ] The file is in the `domains` folder and is in the JSON format.
- [ ✅] The file's name is all lowercased and alphanumeric. 
- [✅] You have completed your website. 
- [✅] The website is reachable.  
- [✅] The CNAME record doesn't contain `https://` or `/`.  
- [✅] There is sufficient information at the `owner` field.  

## Website Link/Preview

ec2-3-12-165-61.us-east-2.compute.amazonaws.com

2024-10-13 22:11 UTC, epic-person-on commented
note I will get ssl cert later

2024-10-13 22:49 UTC, DEV-DIBSTER requested changes
Please read the docs: https://docs.is-a.dev/

2024-10-13 22:49 UTC, DEV-DIBSTER commented on domains/ryan
File needs to end in .json.

2024-10-13 22:49 UTC, DEV-DIBSTER commented on domains/ryan
> +    "discord": "epic.person"
You're missing the email field.

2024-10-13 23:20 UTC, epic-person-on commented
Fixed

2024-10-13 23:32 UTC, epic-person-on commented
I added my email

2024-10-14 00:45 UTC, DEV-DIBSTER approved these changes

2024-10-14 00:46 UTC, merged