Register earth.is-a.dev
is-a-dev/register pull request #16584
Opened 2024-10-14 15:58 UTC by imdakiki

Register earth.is-a.dev with CNAME record pointing to imdakiki.github.io/earth.

2024-10-14 16:25 UTC, CuteDog5695 requested changes, later dismissed

2024-10-14 16:25 UTC, CuteDog5695 commented on domains/earth.json
> +            "CNAME": "imdakiki.github.io/earth"
Also please add more stuff to your website
```suggestion
            "CNAME": "imdakiki.github.io"
```

2024-10-14 16:42 UTC, imdakiki commented
Done I added more content

2024-10-14 20:40 UTC, imdakiki commented
anyone there

2024-10-15 06:44 UTC, orxngc requested changes

2024-10-15 06:44 UTC, orxngc commented on domains/qefw.json
This site is inaccessible, please provide a preview.

2024-10-15 07:35 UTC, imdakiki commented on domains/qefw.json
i dont wanna do the qefw one

2024-10-15 11:49 UTC, imdakiki commented on domains/qefw.json
can you do it now since i deleted the qefw file

2024-10-15 12:24 UTC, orxngc approved these changes

2024-10-15 12:25 UTC, merged