Create celsojr.json
is-a-dev/register pull request #16678
Opened 2024-10-19 08:20 UTC by celsojr

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-10-19 10:37 UTC, Satindar31 commented
This is probably going to be declined because your website has very little content. Add more stuff like maybe an about me for it to be accepted.

2024-10-19 10:49 UTC, celsojr commented
I have added some content before migrating the full website over here: https://celsojr.com

2024-10-19 10:53 UTC, Satindar31 commented
Looks good now!

2024-10-19 11:50 UTC, CuteDog5695 requested changes, later dismissed

2024-10-19 11:50 UTC, CuteDog5695 commented on domains/celsojr.json
> +    "CNAME": "celsojr.github.io/celsojr"
```suggestion
    "CNAME": "celsojr.github.io"
```

2024-10-20 11:30 UTC, orxngc approved these changes

2024-10-20 11:30 UTC, merged