Register randheimer.is-a.dev
is-a-dev/register pull request #16727
Opened 2024-10-21 16:01 UTC by JohnDoeIsBag

Register randheimer.is-a.dev with TXT record pointing to dh=a92d529306d598504174c8a39737b46d89cbe0c2.

2024-10-22 15:31 UTC, CuteDog5695 requested changes

2024-10-22 15:31 UTC, CuteDog5695 commented on domains/deutschlanddermacher.json
> +            "CNAME": "burt.ns.cloudflare.com"
Wrong way to add NS records

2024-10-22 15:31 UTC, CuteDog5695 commented on domains/randheimer.json
> +            "TXT": "dh=a92d529306d598504174c8a39737b46d89cbe0c2"
TXT doesn't do anything

2024-10-23 06:20 UTC, orxngc commented
All PRs adding NS records will be closed as per the README.

2024-10-23 06:20 UTC, closed without merging