Create aetinx.json
is-a-dev/register pull request #1680
Opened 2022-02-08 13:54 UTC by aetinx

2022-02-09 13:18 UTC, phenax requested changes
CNAME has to be a host name and not a url. In this case you'll have to remove `http://` and the trailing `/`.

2022-02-22 04:34 UTC, malbouy requested changes
```
{
    "owner": {
      "username": "aetinx",
      "twitter": "aetinx",
      "discord": "aetinx#8300",
      "note": "amogus"
    },
    "description": "Aetinx's domain. https://aetinx.glitch.me",
    "record": {
      "URL": "http://glitch.edgeapp.net/"
    }
}
```
OR
```
{
    "owner": {
      "username": "aetinx",
      "twitter": "aetinx",
      "discord": "aetinx#8300",
      "note": "amogus"
    },
    "description": "Aetinx's domain. https://aetinx.glitch.me",
    "record": {
      "CNAME": "glitch.edgeapp.net"
    }
}
```

2022-02-22 11:32 UTC, aetinx commented
Alright

2022-02-22 16:45 UTC, phenax approved these changes

2022-02-22 16:45 UTC, merged