Create kartikshriwas.json
is-a-dev/register pull request #16828
Opened 2024-10-26 03:51 UTC by kartikshriwas

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-10-26 14:32 UTC, Stef-DP requested changes

2024-10-26 17:47 UTC, kartikshriwas commented on domains/_github-pages-challenge-kartikshriwas.json
i followed all steps properly.

2024-10-26 19:34 UTC, Stef-00012 commented on domains/_github-pages-challenge-kartikshriwas.json
You didn't as the file name is not correct

it has to be `_github-pages-challenge-USERNAME.DOMAIN.json`
and you also have to make a file `DOMAIN.json` with the IP (A) record or CNAME of github pages

2024-10-27 03:30 UTC, kartikshriwas commented on domains/_github-pages-challenge-kartikshriwas.json
check i jave renamed that file, i haven't created 2 files, at first i created a file as name `domain.json` but after sometime i just renamed it as `_github-pages-challenge-USERNAME.DOMAIN.json`

2024-10-28 22:57 UTC, closed without merging