Register reaverstudio.is-a.dev
is-a-dev/register pull request #16909
Opened 2024-10-30 16:04 UTC by playreaver

Register reaverstudio.is-a.dev with CNAME record pointing to https://playreaver.github.io/website/.

2024-10-31 07:15 UTC, JustDeveloper1 reviewed
you need to delete playreaver.is-a.dev file

2024-10-31 07:15 UTC, JustDeveloper1 commented on domains/playreaver.is-a.dev
you should delete this file

2024-10-31 07:16 UTC, JustDeveloper1 reviewed
cname must be `playreaver.github.io`

2024-10-31 07:16 UTC, JustDeveloper1 commented on domains/playreaver.json
cname must be playreaver.github.io

2024-10-31 07:16 UTC, JustDeveloper1 commented on domains/reaverstudio.json
cname must be playreaver.github.io

2024-10-31 15:03 UTC, CuteDog5695 requested changes
Heads up that you can't connect 2 domains to one github repo, please choose one of them.

2024-11-01 17:42 UTC, playreaver commented
> Heads up that you can't connect 2 domains to one github repo, please choose one of them.

done

2024-11-01 17:46 UTC, CuteDog5695 approved these changes
Seems good to me (used translator and didn't find any weird parts)

2024-11-01 17:47 UTC, merged