Fix some outdated info.
is-a-dev/register pull request #1690
Opened 2022-02-10 07:59 UTC by aduckuwu

2022-02-10 17:16 UTC, phenax requested changes
CNAME has to be a host name and not a url. If you want a URL redirection, use URL instead of CNAME. If you want a CNAME record, remove everything but the host name.

2022-02-11 00:13 UTC, aduckuwu commented
Fixed =))

2022-02-11 00:27 UTC, TheBotlyNoob approved these changes, later dismissed
that is not a very popular opinion ngl

![image](https://user-images.githubusercontent.com/72417807/153519621-e5fdd214-2d22-45af-affc-3ee5c4cb57a9.png)

2022-02-11 00:28 UTC, TheBotlyNoob approved these changes

2022-02-11 15:29 UTC, phenax approved these changes

2022-02-11 15:29 UTC, merged