Register ams.is-a.dev
is-a-dev/register pull request #16908
Opened 2024-10-30 15:47 UTC by ibodyms

Register ams.is-a.dev with CNAME record pointing to www CNAME amms.netlify.app..

2024-10-31 17:24 UTC, Stef-00012 requested changes

2024-10-31 17:24 UTC, Stef-00012 commented on domains/ams.json
> +            "CNAME": "www cname amms.netlify.app."
CNAME should be a domain name

2024-11-03 18:29 UTC, Stef-00012 requested changes

2024-11-03 18:29 UTC, Stef-00012 commented on domains/ams.json
> +            "CNAME": "amms.netlify.app"
You should complete your website first

2024-11-08 05:30 UTC, orangci commented
stale

2024-11-08 05:30 UTC, closed without merging