Register aryanpatel.is-a.dev
is-a-dev/register pull request #16913
Opened 2024-10-30 21:56 UTC by aryanpatel142006

Register aryanpatel.is-a.dev with CNAME record pointing to cname.vercel-dns.com..

2024-10-31 20:20 UTC, Stef-00012 requested changes

2024-10-31 20:20 UTC, Stef-00012 commented on domains/aryanpatel.json
> +            "CNAME": "cname.vercel-dns.com."
CNAME can not end with `.`
```suggestion
            "CNAME": "cname.vercel-dns.com"
```

2024-10-31 20:21 UTC, Stef-00012 commented
> Hey, so I read some of the comments in the previous PRs and turns out I'll have to finish the website, before getting the domain, and I'm a beginner I just learnt hosting a website, so I'm creating my portfolio rn, so it's ok if you just close the PR, I really like it cause I'm getting my full name in the subdomain, which I never get anywhere,but I'm afraid someone might take the subdomain, so it'd be great if you could merge the PR and I'll update the website ASAP, but I totally understand if you cant't :)

I don't think ur name is that common that might be taken by anyone else

2024-11-09 14:39 UTC, CuteDog5695 requested changes
Can you provide a preview of your website?

2024-11-09 14:40 UTC, CuteDog5695 commented
I'll leave this PR up until Monday, then I'll close it

2024-11-11 07:23 UTC, orangci commented
> I'll leave this PR up until Monday, then I'll close it

no me

2024-11-11 07:23 UTC, closed without merging