Super Skibidi
is-a-dev/register pull request #16947
Opened 2024-11-01 17:40 UTC by 3TERN4LF1R3

![fpsc-sample-2 aa0939b8](https://github.com/user-attachments/assets/70ed5506-022a-43bc-b82f-15a2fd5c0d7f)

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-11-02 11:13 UTC, cupglassDEV commented
@3TERN4LF1R3 
nah you think you want to fool us? you dumbass

it still 404 btw, please provide a content, ok?

![image](https://github.com/user-attachments/assets/eaeb9312-411d-4940-89fb-8a88fccd7e99)

2024-11-05 15:23 UTC, Stef-00012 requested changes

2024-11-05 15:23 UTC, Stef-00012 commented on domains/superskibidi
> +    "CNAME": "3TERN4LF1R3.github.io"
Your site is a 404 page and I don't see any repository on your profile which has the contents of the picture

2024-11-05 15:24 UTC, Stef-00012 requested changes

2024-11-05 15:24 UTC, Stef-00012 commented on domains/superskibidi
> +    "CNAME": "3TERN4LF1R3.github.io"
Your site is a 404 page and I don't see any repository on your profile which has the contents of the picture

2024-11-08 05:28 UTC, orangci commented
stale

2024-11-08 05:28 UTC, closed without merging