Create sophiapp.json
is-a-dev/register pull request #16942
Opened 2024-11-01 14:09 UTC by apposophy

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
[](https://oauth-ssr-apposophys-projects.vercel.app/signin)

2024-11-01 17:54 UTC, CuteDog5695 requested changes

2024-11-01 17:54 UTC, CuteDog5695 commented on domains/sophiapp.json
> +    "RECORDTYPE": "CNAME"
?????

2024-11-01 21:43 UTC, apposophy commented on domains/sophiapp.json
> +    "RECORDTYPE": "CNAME"
hello I made the necessary changes

2024-11-07 15:03 UTC, CuteDog5695 requested changes
PR doesn't have any file changes.

2024-11-09 14:03 UTC, closed without merging