Register daki.is-a.dev
is-a-dev/register pull request #16972
Opened 2024-11-03 01:22 UTC by Mai1ii

Register daki.is-a.dev with TXT record pointing to _vercel.daki.is-a.dev to use daki.is-a.dev.

2024-11-03 09:50 UTC, cupglassDEV commented
You can't do it like this. You need to make a website first, even though you are trying to register it ASAP to vercel

In the directory for example, if you want the scenario to be like this. Add both `_vercel.daki.json` AND `daki.json`. Add `daki.json` as a cname to `cname.vercel-dns.com`.
and on the `_vercel.daki.json`, add the TXT value like in the screenshot (may be vary on your account)
![image](https://github.com/user-attachments/assets/705a581a-9fb2-4277-97fa-c968745657f8)

2024-11-05 15:04 UTC, Stef-DP requested changes

2024-11-05 15:04 UTC, Stef-00012 commented on domains/daki.json
> +            "TXT": "_vercel.daki.is-a.dev to use daki.is-a.dev"
this is not how you make a TXT record, make another file `_vercel.daki.json` and put the TXT there

also see https://is-a.dev/docs/vercel

2024-11-08 06:07 UTC, orangci commented
stale

2024-11-08 06:07 UTC, closed without merging