Register petey.is-a.dev
is-a-dev/register pull request #16989
Opened 2024-11-03 20:23 UTC by peteypocalypse

Register petey.is-a.dev with CNAME record pointing to https://peteypocalypse.github.io/website/.

2024-11-03 23:47 UTC, cupglassDEV commented
did you read these docs???
CNAME cannot contain any slashes

https://is-a.dev/docs/domain-structure
https://is-a.dev/docs/github-pages/

2024-11-04 22:33 UTC, Stef-DP requested changes

2024-11-04 22:33 UTC, Stef-00012 commented on domains/petey.json
> +            "CNAME": "https://peteypocalypse.github.io/website/"
CNAME can not contain `https://` or `/`

2024-11-08 06:07 UTC, orangci commented
stale

2024-11-08 06:07 UTC, closed without merging