Update TXT record for huygd.is-a.dev
is-a-dev/register pull request #16995
Opened 2024-11-04 06:41 UTC by huygmdvn

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-11-04 06:45 UTC, huygmdvn commented
Register a new domain and Up a domain

2024-11-04 10:39 UTC, Satindar31 commented
Merge conflicts have to be fixed

2024-11-04 22:25 UTC, Stef-00012 requested changes
please resolve the merge conflict

2024-11-04 22:25 UTC, Stef-00012 commented on domains/huygd.json
> +      "103.77.240.59",
remove this comma
```suggestion
      "103.77.240.59"
```

2024-11-04 22:25 UTC, Stef-00012 commented on domains/huygmd.json
> +      "103.77.240.59",
remove this comma
```suggestion
      "103.77.240.59"
```

2024-11-04 22:27 UTC, Stef-00012 requested changes

2024-11-04 22:27 UTC, Stef-00012 commented on domains/huygd.json
> +    ]
add a comma here
```suggestion
    ],
```

2024-11-04 22:27 UTC, Stef-00012 commented on domains/huygmd.json
> +    ]
add a comma here
```suggestion
    ],
```

2024-11-05 13:23 UTC, huygmdvn commented
> please resolve the merge conflict

Have resolve,can you check it again?

2024-11-06 13:31 UTC, Satindar31 commented
> > please resolve the merge conflict
> 
> Have resolve,can you check it again?

The merge conflicts are still there. If you don't know how to resolve them, the easiest way is to probably just delete your fork, refork it, make the changes and then make a new pr

2024-11-06 15:28 UTC, closed without merging