Create nomena.json
is-a-dev/register pull request #16998
Opened 2024-11-04 11:40 UTC by Shiro-cha

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview
[My Web Site] (https://shiro-cha.github.io/)

2024-11-04 11:41 UTC, Shiro-cha commented
Dear,
Hope this PR find you well.

I want to register a subdomain if it doesn't matter.

Thank you and best regards

2024-11-04 22:23 UTC, Stef-00012 requested changes, later dismissed

2024-11-04 22:23 UTC, Stef-00012 commented on domains/nomena.json
> +    "username": "nomena",
username should be your github username

2024-11-05 02:38 UTC, Shiro-cha commented on domains/nomena.json
> +    "username": "nomena",
change done

Best regards

2024-11-08 06:40 UTC, orangci approved these changes

2024-11-08 06:41 UTC, merged