Register Galaxyfounded.is-a.dev
is-a-dev/register pull request #17005
Opened 2024-11-04 17:17 UTC by Peppe12367

Register Galaxyfounded.is-a.dev with TXT record pointing to Wallet.

2024-11-04 22:01 UTC, Stef-00012 requested changes

2024-11-04 22:01 UTC, Stef-00012 commented on domains/galaxy.json
> +            "TXT": "wallet"
TXT records alone do nothing

2024-11-04 22:01 UTC, Stef-00012 commented on domains/galaxyfounded.json
> +            "TXT": "wallet"
TXT records alone do nothing

2024-11-08 06:39 UTC, orangci commented
stale

2024-11-08 06:39 UTC, closed without merging