Create dankamigos.json
is-a-dev/register pull request #17000
Opened 2024-11-04 13:44 UTC by mokshdk

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ `dankamigos.json` ] The file is in the `domains` folder and is in the JSON format.
- [  yes ] The file's name is all lowercased and alphanumeric.
- [  yes  ] You have completed your website.
- [  yes ] The website is reachable.
- [  yes ] The CNAME record doesn't contain `https://` or `/`. 
- [ yes ] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://dankamigos-baapekd9aua9esh2.eastus-01.azurewebsites.net/

2024-11-04 22:16 UTC, Stef-00012 requested changes, later dismissed

2024-11-04 22:16 UTC, Stef-00012 commented on domains/dankamigos.json
> +    "CNAME": "dankamigos-baapekd9aua9esh2.eastus-01.azurewebsites.net"
You can't have CNAME along with other records

2024-11-05 12:20 UTC, mokshdk commented
okie

2024-11-05 12:20 UTC, mokshdk commented
bymistake i closed it 🤦

2024-11-08 06:40 UTC, orangci submitted a review, later dismissed

2024-11-09 14:47 UTC, CuteDog5695 requested changes

2024-11-09 14:47 UTC, CuteDog5695 commented on domains/dankamigos.json
> +    "TXT": ["562965D131E7C913D1796476301A86A148A2B64B52D99FC316724B0B785FAAB1"],
```suggestion
    "TXT": ["562965D131E7C913D1796476301A86A148A2B64B52D99FC316724B0B785FAAB1"]
```

2024-11-09 14:48 UTC, CuteDog5695 approved these changes
Now it was fine, dunno why it took 4 days to actually merge it.

2024-11-09 14:49 UTC, merged