Register devabh.is-a.dev
is-a-dev/register pull request #17004
Opened 2024-11-04 15:48 UTC by devabh96

Register devabh.is-a.dev with A record pointing to 69.30.249.53.

2024-11-04 22:05 UTC, Stef-00012 requested changes

2024-11-04 22:05 UTC, Stef-00012 commented on domains/devabh.json
> +            "A": ["69.30.249.53"]
Can you show a preview of your website?

2024-11-04 23:24 UTC, devabh96 commented
Still being developed but here it is
http://dono-01.danbot.host:2085

On Tue, 5 Nov, 2024, 3:36 am Stef_DP, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In domains/devabh.json
> <https://github.com/is-a-dev/register/pull/17004#discussion_r1828450016>:
>
> > @@ -0,0 +1,13 @@
> +{
> +        "owner": {
> +           "username": "devabh96",
> +           "email": "",
> +           "discord": "760049962544791562",
> +           "OWL": "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiUlNBLU9BRVAiLCJraWQiOiJaa1VsRmRqVThiUEstLXVVM2JJR09PVHFYYVFFS1ZINFVXOW53MTR6WTJnIn0.ElT9DhII1rufR0gYynme9pdGI3SfSTl2Zmd9-EyY5E9Ps1iZ4N91swCb0ysjljq1GAqbH6Va1diLHYewyFERJ-Vsh4dj808DbId8GIF_8vzVBZTcuXnSr-FkKaN1v0_47AROdJp_VYSgQRMO72YwzvhOp1tPlZE_vuZl4HU80iEpdiXrf-V0G3byVRWiCKOh8NV7L3nvl_qTtZgKvHZ9fSLXGGFMaqiklT1WP0sLL_HCff1AP-G9c_iYFRio_lxX9XIuhKu8yhdF1KczlqBBCznvDmt6bNDZAnSg16ps5ewM90lLhXpbRNjMXYOdo53NgN3F5YlvatM71yb1P45Beg.ZwhjDQtTOA_lTklJzQTJUQ.BHQG3HvdAlSSIX9KpdeMFDT9j-31zS1Kw-LJ-wxXI0VaOg3HK49IKolePQOjzoGL40GTzlYy9VFjNszCB5dA5hntUqjTbO-1vtX0SI15sno.oERYSO8ZdE1J9oI4jfGumw"
> +        },
> +
> +        "record": {
> +            "A": ["69.30.249.53"]
>
> Can you show a preview of your website?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/17004#pullrequestreview-2414212676>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUBBUU53PN2DIVL6FFL7OC3Z67VVJAVCNFSM6AAAAABRERYWYGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMJUGIYTENRXGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-05 14:59 UTC, Stef-DP requested changes

2024-11-05 14:59 UTC, Stef-00012 commented on domains/devabh.json
> +            "A": ["69.30.249.53"]
You should complete your website first

2024-11-08 06:02 UTC, orangci commented
stale

2024-11-08 06:02 UTC, closed without merging