Update huygd.json
is-a-dev/register pull request #17024
Opened 2024-11-06 16:01 UTC by huygmdvn

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-11-07 08:59 UTC, Stef-00012 submitted a review, later dismissed

2024-11-07 13:01 UTC, huygmdvn commented on domains/huygd.json
> +      "103.77.240.59"
https://huygd.is-a.dev/
Here sir

2024-11-08 17:49 UTC, CuteDog5695 requested changes, later dismissed
Is `huygmd.json` for a hosting service? (Judging by the link you gave in the PR description)

2024-11-08 17:49 UTC, CuteDog5695 commented on domains/huygd.json
> +      "103.77.240.59"
Seems good to me

2024-11-09 07:25 UTC, huygmdvn commented
I just understand that huygmd.json file use to register huygmd.is-a.dev.With an A record and TXT record.The link in the desc just a temp demo,When the domain approved,I will remove these

2024-11-09 13:29 UTC, wdhdev approved these changes

2024-11-09 13:30 UTC, merged