feat: update validation records
is-a-dev/register pull request #1703
Opened 2022-02-14 23:41 UTC by kyuzu

2022-02-15 16:05 UTC, phenax requested changes
A few issues here -
1. You cannot use CNAME together with any other record. It is a limitation with DNS.
2. A record has to be an array so enclose it within square braces.
3. AAAA record type is not supported

Please refer to your hosting service's docs. I couldn't find the proper docs for custom domains with dash but if it wants verification, you'll need to use A and TXT records.

2022-02-15 23:02 UTC, kyuzu commented
> A few issues here -
> 
> 1. You cannot use CNAME together with any other record. It is a limitation with DNS.
> 2. A record has to be an array so enclose it within square braces.
> 3. AAAA record type is not supported
> 
> Please refer to your hosting service's docs. I couldn't find the proper docs for custom domains with dash but if it wants verification, you'll need to use A and TXT records.

Sure thing, I'll notify you.

2022-02-15 23:10 UTC, kyuzu commented
@phenax

2022-02-16 16:10 UTC, phenax approved these changes

2022-02-16 16:10 UTC, merged