Create yashk.json
is-a-dev/register pull request #17043
Opened 2024-11-07 17:35 UTC by 0day-Yash

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ x] The file is in the `domains` folder and is in the JSON format.
- [ x] The file's name is all lowercased and alphanumeric. 
- [ x] You have completed your website. 
- [x ] The website is reachable.  
- [ x] The CNAME record doesn't contain `https://` or `/`.  
- [x ] There is sufficient information at the `owner` field.  

## Website Link/Preview

yashk.app
However, this webpage is going to be set up to redirect to the main website

2024-11-07 18:05 UTC, DEV-DIBSTER requested changes

2024-11-09 14:52 UTC, CuteDog5695 requested changes

2024-11-09 14:52 UTC, CuteDog5695 commented on domains/yashk.json
> +    ]
The hell? This is **NOT** how you do it. Please read our documentation on how to add MX and TXT records.

2024-11-09 14:52 UTC, CuteDog5695 commented on domains/yashk.json
> +  "proxied": true //for cloudflare
Not fixed, don't know why this conversation was resolved.

2024-11-11 07:24 UTC, orangci commented
stale. user didn't fix anything, come back wen you rtfm

2024-11-11 07:24 UTC, closed without merging