register subdomain
is-a-dev/register pull request #17054
Opened 2024-11-08 16:16 UTC by CreepyTheCat

# Pull Request Template

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

[My Website](creepycat.pythonanywhere.com)

2024-11-08 17:42 UTC, CuteDog5695 requested changes

2024-11-08 17:42 UTC, CuteDog5695 commented on domains/creepycat.json
> +    "TXT": "zoho-verification=zb99586085.zmverify.zoho.com"
Can't use CNAME with other records

2024-11-11 07:25 UTC, orangci requested changes
This site is incomplete and an empty template, please add some content. E.g. a "Hi, I'm orangc" will suffice as complete.

2024-11-11 07:25 UTC, orangci commented on domains/creepycat.json
> +    "username": "creepycat",
```suggestion
    "username": "CreepyTheCat",
```
This must be your GitHub username.

2024-11-12 21:47 UTC, closed without merging