Update ronalds1398.json
is-a-dev/register pull request #17060
Opened 2024-11-08 19:24 UTC by Ronalds13424

I have created this PR to add my TXT record for google indexing.

2024-11-09 14:54 UTC, CuteDog5695 requested changes

2024-11-09 14:54 UTC, CuteDog5695 commented on domains/ronalds1398.json
> +    "TXT": "google-site-verification=YcDGuXFRPF2Udyt8BMXCE7RrQ9wFgvPx1hYAEDFfow8"
CNAME can't be with other records.

2024-11-09 15:00 UTC, Ronalds13424 commented on domains/ronalds1398.json
> +    "TXT": "google-site-verification=YcDGuXFRPF2Udyt8BMXCE7RrQ9wFgvPx1hYAEDFfow8"
what should i do then?
remove txt?

2024-11-10 12:22 UTC, cupglassDEV commented on domains/ronalds1398.json
> +    "TXT": "google-site-verification=YcDGuXFRPF2Udyt8BMXCE7RrQ9wFgvPx1hYAEDFfow8"
> what should i do then? remove txt?

yes.

2024-11-10 13:42 UTC, Ronalds13424 commented on domains/ronalds1398.json
> +    "TXT": "google-site-verification=YcDGuXFRPF2Udyt8BMXCE7RrQ9wFgvPx1hYAEDFfow8"
so theres no way i can index my site?

2024-11-11 07:26 UTC, orangci commented
stale

2024-11-11 07:26 UTC, closed without merging