notjunar.is-a.dev
is-a-dev/register pull request #17084
Opened 2024-11-09 20:04 UTC by NotJunar

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [Yes] The file is in the `domains` folder and is in the JSON format.
- [Yes] The file's name is all lowercased and alphanumeric. 
- [Yes] You have completed your website. 
- [Yes] The website is reachable.  
- [Yes] The CNAME record doesn't contain `https://` or `/`.  
- [Yes] There is sufficient information at the `owner` field.  

## Website Link/Preview

![image](https://github.com/user-attachments/assets/d9d6a2cc-195b-4d1b-856d-41d27cebd94a)

2024-11-10 11:05 UTC, Stef-00012 approved these changes

2024-11-10 11:09 UTC, Stef-00012 requested changes, later dismissed

2024-11-10 11:09 UTC, Stef-00012 commented on domains/notjunar.json
> +        "username": "NotJunar"
nvm, missing a comma here
```suggestion
        "username": "NotJunar",
```

2024-11-10 21:48 UTC, NotJunar commented
Fixed. @Stef-00012

2024-11-11 07:28 UTC, orangci approved these changes

2024-11-11 07:29 UTC, merged