Register `anto.is-a.dev`
is-a-dev/register pull request #17096
Opened 2024-11-10 06:57 UTC by hardianto01

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [done ] The file is in the `domains` folder and is in the JSON format.
- [done ] The file's name is all lowercased and alphanumeric. 
- [done ] You have completed your website. 
- [done ] The website is reachable.  
- [done ] The CNAME record doesn't contain `https://` or `/`.  
- [done ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://hardianto.vercel.app

2024-11-10 11:28 UTC, cupglassDEV commented
Wih keren, lanjutin mas 👍
---
TRANSLATION: Thats cool, keep going 👍

2024-11-10 11:39 UTC, Stef-00012 approved these changes

2024-11-10 11:44 UTC, Stef-00012 requested changes, later dismissed

2024-11-10 11:44 UTC, Stef-00012 commented on domains/_vercel.anto.json
> +    }
Missing closing `}`
```suggestion
    }
}
```

2024-11-10 11:44 UTC, hardianto01 commented on domains/_vercel.anto.json
> +    }
Ah sorry

2024-11-11 07:33 UTC, orangci approved these changes

2024-11-11 07:34 UTC, merged