Update mariano-avila.json
is-a-dev/register pull request #17091
Opened 2024-11-09 23:36 UTC by DxRavage

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-11-10 06:33 UTC, cupglassDEV commented
i cant find the specific subdomain for https://mariano.avila.vercel.app/ bcs it says not found

![image](https://github.com/user-attachments/assets/912a716e-a389-4142-a969-45a5a9258d27)

And when i go to https://avila.vercel.app/, the preview dosent actually the same as your old one (`dxravage.github.io`)

![image](https://github.com/user-attachments/assets/6cf3832e-71ff-42dd-b2da-7a7d2082d822)

It weirdly just a file uploader? and no other menu on there???

2024-11-10 11:24 UTC, Stef-00012 requested changes

2024-11-10 11:24 UTC, Stef-00012 commented on domains/mariano-avila.json
> +    "CNAME": "mariano.avila.vercel.app"
I can not reach your website, 404

2024-11-12 06:15 UTC, orangci commented
stale

2024-11-12 06:15 UTC, closed without merging