Create voided.json
is-a-dev/register pull request #17095
Opened 2024-11-10 06:40 UTC by iHategithub9000

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [-] The file is in the `domains` folder and is in the JSON format.
- [-] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [-] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [-] There is sufficient information at the `owner` field.  

i am not the author of this site, i am simply creating a domain for my friend

## Website Link/Preview

2024-11-10 11:34 UTC, Stef-00012 requested changes, later dismissed
You can not create a domain for another user

2024-11-11 07:30 UTC, orangci commented
> You can not create a domain for another user

yes, you can, we just need proof that that user gave you consent

2024-11-11 14:59 UTC, iHategithub9000 commented
well voided isn't responding rn, ill give proof when he responds on discord

2024-11-12 13:37 UTC, iHategithub9000 commented
![obraz](https://github.com/user-attachments/assets/c873a10b-e803-4616-9934-d787cc3b98d4)
here's the proof

2024-11-13 07:15 UTC, orangci approved these changes

2024-11-13 07:15 UTC, merged