Create chiller.json
is-a-dev/register pull request #1710
Opened 2022-02-16 13:25 UTC by Code19Master

2022-02-16 16:13 UTC, phenax requested changes
CNAME has to be a host name and not a url. If you want a URL redirection, use URL instead of CNAME. If you want a CNAME record, remove everything but the host name.

Also, netlify doesn't support is-a.dev cnames. You can use alternative platforms like railway.app

2022-02-16 16:25 UTC, Code19Master commented
Okay, Thanx For the Reply.

2022-03-24 13:45 UTC, MaskDuck requested changes

2022-03-24 13:45 UTC, MaskDuck commented on domains/chiller.json
> +    "CNAME": "https://chiller.netlify.app"
1. netlify doesnt work with is-a.dev, maybe try [railway](https://railway.app)?
2. cname shouldnt be a full url. (cc phenax)

2022-05-16 14:42 UTC, closed without merging