Register _vercel.encrypt0r.my.id and _atproto.encrypt0r.my.id
is-a-dev/register pull request #17196
Opened 2024-11-15 14:48 UTC by its0din-ai

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] The file's name is all lowercased and alphanumeric. 
- [X] You have completed your website. 
- [X] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://encrypt0r.my.id

2024-11-17 02:49 UTC, omsenjalia requested changes
`encrypt0r.is-a.dev` doesn't exist

2024-11-19 08:58 UTC, its0din-ai commented
> `encrypt0r.is-a.dev` doesn't exist

domain request added. please let me know if you need something.

2024-11-19 09:40 UTC, orangci requested changes

2024-11-19 09:40 UTC, orangci commented on domains/encrypt0r.json
> +    "TXT": "just_for_reservation"
```suggestion
    "TXT": "just_for_reservation"
```
You must have a complete and accessible website. A TXT record does nothing, you cannot just reserve a domain.

2024-11-19 16:21 UTC, Stef-00012 requested changes

2024-11-19 16:21 UTC, Stef-00012 commented on domains/encrypt0r.json
> +    "A": ['103.16.117.216']
invalid JSON

2024-11-19 16:27 UTC, Stef-DP requested changes

2024-11-19 16:27 UTC, Stef-00012 commented on domains/encrypt0r.json
> +    "A": "103.16.117.216"
A record should be an array, also i wouldn't consider just this as complete
![image](https://github.com/user-attachments/assets/94d1682d-6913-4477-9887-7e727fcf9bd0)

2024-11-21 02:31 UTC, closed without merging