Domain registration
is-a-dev/register pull request #17206
Opened 2024-11-15 23:22 UTC by MrBlockman

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

[mrblockman.github.io](url)

2024-11-16 04:20 UTC, DEV-DIBSTER requested changes

2024-11-16 04:20 UTC, DEV-DIBSTER commented on domains/domains.json
Think you forgot to get the actual subdomain you want.

2024-11-16 11:23 UTC, MrBlockman commented on domains/domains.json
whoops lol.  should be fixed now

2024-11-17 03:01 UTC, DEV-DIBSTER requested changes

2024-11-17 03:01 UTC, DEV-DIBSTER commented on domains/domains.json
File name still is unchanged btw, seems like you created another file that isn't in the domains directory folder. Could you double check?

2024-11-17 03:01 UTC, DEV-DIBSTER commented on mrblockman.github.io
Yeah this entire file needs to go, not in the proper directory.

2024-11-17 16:46 UTC, closed without merging