Update creeperita104.json and delete other nested subdomains
is-a-dev/register pull request #17214
Opened 2024-11-16 11:16 UTC by creeperita09

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

I'll upload a screenshot of my site in a comment since rn I'm on mobile so i cannot multitask, my reasons for using ns are that i need ddos protection and i would like my home ip address to not be public (my site is running out of nginx on a pi4), it would also make it easier for me using cloudflare's dashboard.

2024-11-16 11:46 UTC, Satindar31 commented on domains/creeperita104.json
> +  "NS":["kyrie.ns.cloudflare.com","vida.ns.cloudflare.com"]
Invalid format. Do 
```suggestion
  "record": {
    "NS":["kyrie.ns.cloudflare.com","vida.ns.cloudflare.com"]
   }
```

2024-11-16 21:28 UTC, Stef-00012 requested changes, later dismissed
what @Satindar31's said ^

2024-11-17 07:13 UTC, creeperita09 commented
Sorry my bad, apparently i was high on something

2024-11-17 07:18 UTC, creeperita09 commented
Ok, now it should be valid, sorry for wasting your time

2024-11-17 07:32 UTC, wdhdev approved these changes

2024-11-17 07:33 UTC, merged