Create _discord.computerblade.json
is-a-dev/register pull request #17246
Opened 2024-11-18 16:08 UTC by computerblade-official

for discord verification

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [*] The file is in the `domains` folder and is in the JSON format.
- [*] The file's name is all lowercased and alphanumeric. 
- [*] You have completed your website. 
- [*] The website is reachable.  
- [*] The CNAME record doesn't contain `https://` or `/`.  
- [*] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-11-18 17:58 UTC, Stef-00012 requested changes, later dismissed

2024-11-18 17:58 UTC, Stef-00012 commented on _discord.computerblade.json
file should be iin the domains folder

2024-11-19 08:46 UTC, cbladeOfficial reviewed
added to domains folder by renaming the file

2024-11-19 09:40 UTC, orangci approved these changes

2024-11-19 09:41 UTC, merged