Create whine.json
is-a-dev/register pull request #1728
Opened 2022-02-19 16:47 UTC by whinee

2022-02-19 17:40 UTC, mtgsquad approved these changes, later dismissed

2022-02-20 16:38 UTC, phenax requested changes
The structure of the json file is incorrect. Please refer to the documentation and use existing domain files as reference for the json format.

2022-02-22 04:37 UTC, malbouy requested changes
Try using ```
{
    "owner": {
    "username": "whinee",
    "twitter": "whi_nyaan"
    },
    "description": "whi_ne's personal site",
    "repo": "https://github.com/whinee/whinee.github.io",
    "record": {
        "CNAME": "whinee.github.io"
    }
}
```

2022-02-22 06:46 UTC, whinee commented
sooowwwwy, I'm dumb, I've done all of the editing and pull request on mobile so yea. Sorry and thanks for the suggestion.

*~~God, I can't believe I messed up twice, t'was embarassing~~*

2022-02-22 16:44 UTC, phenax approved these changes

2022-02-22 16:44 UTC, merged