Create anshu.json
is-a-dev/register pull request #17299
Opened 2024-11-21 21:14 UTC by anshu-prakash

Will be using this subdomain for personal portfolio

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-11-21 22:27 UTC, DEV-DIBSTER requested changes

2024-11-21 22:27 UTC, DEV-DIBSTER commented on domains/anshu.json
> +        "email": "your@email.address"
Please provide a valid email address.

2024-11-22 06:01 UTC, anshu-prakash commented on domains/anshu.json
> +        "email": "your@email.address"
Valid email address added. thanks

2024-11-24 02:42 UTC, DEV-DIBSTER approved these changes

2024-11-24 02:43 UTC, merged