Create hjgaming.json
is-a-dev/register pull request #17391
Opened 2024-11-28 12:42 UTC by Hjgaming

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-11-28 18:53 UTC, CuteDog5695 requested changes

2024-11-28 18:53 UTC, CuteDog5695 commented on domains/hjgaming.json
> +    "TXT": ["dh=234fc226b4f9dab9135d3a91e77d623924640e81"]
This is not supposed to be for the main file. Please read our documentation.

2024-11-28 19:50 UTC, Hjgaming reviewed
new added pls re review

2024-11-29 02:15 UTC, DEV-DIBSTER requested changes

2024-11-29 02:15 UTC, DEV-DIBSTER commented on domains/hjgaming.json
> +    "TXT": ["vc-domain-verify=hjgaming.is-a.dev,b1a85aa1f9f16d27c005"]
Vercel verification records should be under a file called _vercel.domain.json, this file should be the actual A or CNAME records.

2024-11-29 16:41 UTC, DEV-DIBSTER approved these changes

2024-11-29 16:42 UTC, DEV-DIBSTER requested changes

2024-11-29 16:42 UTC, DEV-DIBSTER commented on domains/_vercel.hjgaming.json
> +            "vc-domain-verify=hjgaming.is-a.dev,b1a85aa1f9f16d27c005"
You also need to create the root file as well.

2024-11-30 04:33 UTC, Hjgaming commented
close

2024-11-30 04:33 UTC, closed without merging