Create aeyika.json
is-a-dev/register pull request #17415
Opened 2024-11-29 20:14 UTC by aeyika

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://portfolio-aeyikas-projects.vercel.app/

2024-11-29 20:20 UTC, DEV-DIBSTER requested changes

2024-11-29 20:20 UTC, DEV-DIBSTER commented on domains/aeyika.json
> +    "TXT": "_vercel.aeyika.is-a.dev"
This TXT should be a domain name file, and a verification TXT value should be placed.

Refer to the docs: https://is-a.dev/docs/vercel/

2024-11-30 17:01 UTC, CuteDog5695 requested changes, later dismissed

2024-11-30 17:01 UTC, CuteDog5695 commented on domains/aeyika-vercel.json
File should be `_vercel.aeyika.json`

2024-11-30 17:01 UTC, CuteDog5695 commented on domains/aeyika-vercel.json
> +  }
```suggestion
    "description": "Domain for my portfolio website"
```

2024-11-30 18:29 UTC, DEV-DIBSTER approved these changes

2024-11-30 18:30 UTC, merged