Create DangVuQuangHuy.json
is-a-dev/register pull request #17489
Opened 2024-12-01 06:26 UTC by qhuyqhuy

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ X ] The file is in the `domains` folder and is in the JSON format.
- [ X ] The file's name is all lowercased and alphanumeric. 
- [ X ] You have completed your website. 
- [ X ] The website is reachable.  
- [ X ] The CNAME record doesn't contain `https://` or `/`.  
- [ X ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-01 16:31 UTC, Stef-00012 requested changes

2024-12-01 16:31 UTC, Stef-00012 commented on domains/DangVuQuangHuy.json
> +        "RECORDTYPE": "CNAME"
read https://docs.is-a.dev and make proper record

2024-12-04 02:25 UTC, DEV-DIBSTER requested changes

2024-12-04 02:25 UTC, DEV-DIBSTER commented on domains/DangVuQuangHuy.json
> +        "TXT": ["667494e9b3478e8b62e9e1b175e23a"]
TXT records alone don't do anything.

2024-12-05 04:38 UTC, closed without merging