Update julianwe17.json
is-a-dev/register pull request #17492
Opened 2024-12-01 09:39 UTC by Julianwe17

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://julianwe17.is-a.dev

2024-12-01 16:38 UTC, Stef-00012 requested changes

2024-12-01 16:38 UTC, Stef-00012 commented on domains/julianwe17.json
> +            "TXT": "v=spf1 include:spf.improvmx.com ~all"
You can have CNAME with other records

2024-12-01 16:38 UTC, Stef-00012 commented on domains/julianwe17.json
> +            "mx2.improvmx.com." ],
remove trailing dot
```suggestion
            "mx1.improvmx.com",
            "mx2.improvmx.com" ],
```

2024-12-04 02:26 UTC, DEV-DIBSTER requested changes

2024-12-04 02:26 UTC, DEV-DIBSTER commented on domains/julianwe17.json
> +
Records are still not valid as CNAME cannot be used in conjunction with other records.

2024-12-05 04:38 UTC, closed without merging