Create Chrisbase12.json
is-a-dev/register pull request #17517
Opened 2024-12-02 00:59 UTC by OverCharred

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-02 21:59 UTC, Stef-00012 approved these changes

2024-12-02 22:00 UTC, Stef-00012 submitted a review, later dismissed

2024-12-02 22:00 UTC, Stef-00012 commented on domains/_vercel.chrisbase12.json
> +    "username": "insert-github-username-here"
this should be your github username

2024-12-04 17:57 UTC, CuteDog5695 requested changes

2024-12-04 17:57 UTC, CuteDog5695 commented on domains/_vercel.chrisbase12.json
> +    "username": "insert-github-username-here"
```suggestion
    "username": "OverCharred"
```

2024-12-04 17:57 UTC, CuteDog5695 commented on domains/chrisbase12.json
> +    "username": "overcharred"
```suggestion
    "username": "OverCharred"
```

2024-12-04 17:58 UTC, CuteDog5695 approved these changes
Seems good to me now

2024-12-04 17:58 UTC, merged