Create wussnow.json
is-a-dev/register pull request #17537
Opened 2024-12-02 10:14 UTC by sondeptraicute

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x ] The file is in the `domains` folder and is in the JSON format.
- [x ] The file's name is all lowercased and alphanumeric. 
- [x ] You have completed your website. 
- [x ] The website is reachable.  
- [x ] The CNAME record doesn't contain `https://` or `/`.  
- [x ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-02 21:45 UTC, Stef-00012 requested changes

2024-12-02 21:45 UTC, Stef-00012 commented on wussnow.json
> +        "RECORDTYPE": "A"
this is not how you register a record

2024-12-02 21:45 UTC, Stef-00012 commented on wussnow.json
file should be in the domains folder

2024-12-04 18:00 UTC, CuteDog5695 commented
Closing PR. Please make a new PR with the correct file format.

2024-12-04 18:00 UTC, closed without merging