Create luuminh.json
is-a-dev/register pull request #17538
Opened 2024-12-02 10:40 UTC by Zicc2005

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] The file's name is all lowercased and alphanumeric. 
- [X] You have completed your website. 
- [X] The website is reachable.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-02 21:44 UTC, Stef-00012 requested changes

2024-12-02 21:44 UTC, Stef-00012 commented on luuminh.json
> +        "RECORDTYPE": "CNAME"
This not how you register a record

2024-12-02 21:44 UTC, Stef-00012 commented on luuminh.json
file should be in the domains folder

2024-12-04 17:59 UTC, CuteDog5695 commented
Closing PR. Please open a new PR with the actual json format.

2024-12-04 17:59 UTC, closed without merging