Create hongson.json & GitHub Pages Domain Verification
is-a-dev/register pull request #17540
Opened 2024-12-02 12:22 UTC by hongson209

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-02 21:42 UTC, Stef-00012 requested changes

2024-12-02 21:42 UTC, Stef-00012 commented on hongson.json
this should be in the domains folder, also see https://is-a.dev/docs/github-pages-verification/ for github pages verification

2024-12-06 22:26 UTC, Stef-00012 requested changes

2024-12-06 22:26 UTC, Stef-00012 commented on hongson.json
the file still isn't in the domains folder

2024-12-09 13:32 UTC, orangci commented
stale

2024-12-09 13:32 UTC, closed without merging