Create cursedscrubdaddygang.json
is-a-dev/register pull request #17565
Opened 2024-12-03 23:11 UTC by QuantumMapleQC

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

![image](https://github.com/user-attachments/assets/d98c0b1f-98d4-4c27-bec5-eb74f9d39ff7)

## Website Link/Preview
![image](https://github.com/user-attachments/assets/5e4fd790-1ac6-4b32-82eb-cc5fad43320f)

2024-12-04 02:33 UTC, DEV-DIBSTER submitted a review, later dismissed

2024-12-04 02:33 UTC, DEV-DIBSTER commented on domains/cursedscrubdaddygang.json
> +        "CNAME": "quantummapleqc.github.io/CursedScrubDaddyGang/"
CNAME is invalid. CNAME should be a hostname without any additional components like protocols or file paths.

2024-12-04 02:41 UTC, QuantumMapleQC commented
Github does not let me make a domain thats like

example.github.io

Instead it just gives me an used one along with the filepath

On Tue, Dec 3, 2024, 21:33 DIBSTER ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In domains/cursedscrubdaddygang.json
> <https://github.com/is-a-dev/register/pull/17565#discussion_r1868634082>:
>
> > @@ -0,0 +1,10 @@
> +{
> +    "owner": {
> +        "repo": "https://github.com/QuantumMapleQC/CursedScrubDaddyGang"
> +        "username": "quantummapleqc"
> +        "Discord": "herricksom"
> +    },
> +    "record": {
> +        "CNAME": "quantummapleqc.github.io/CursedScrubDaddyGang/"
>
> CNAME is invalid. CNAME should be a hostname without any additional
> components like protocols or file paths.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/17565#pullrequestreview-2477164968>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BL3OFJELG3ZSLYZ2T6ONYU32DZSXPAVCNFSM6AAAAABS63BNXKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINZXGE3DIOJWHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-04 02:47 UTC, DEV-DIBSTER commented
@QuantumMapleQC You can set your hostname to be just `quantummapleqc.github.io`, which then you could access that URL at 
`https://cursedscrubdaddygang/CursedScrubDaddyGang/`

2024-12-04 02:48 UTC, QuantumMapleQC commented
Thats strange cause github does not let me do this normally

On Tue, Dec 3, 2024, 21:47 DIBSTER ***@***.***> wrote:

> @QuantumMapleQC <https://github.com/QuantumMapleQC> You can set your
> hostname to be just quantummapleqc.github.io, which then you could access
> that URL at
> https://cursedscrubdaddygang/CursedScrubDaddyGang/
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/17565#issuecomment-2516051816>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BL3OFJFIGKLTWVDOWJDAXCT2DZUMHAVCNFSM6AAAAABS63BNXKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMJWGA2TCOBRGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-04 17:30 UTC, CuteDog5695 requested changes

2024-12-04 17:30 UTC, CuteDog5695 commented on domains/cursedscrubdaddygang.json
> +        "CNAME": "https://quantummapleqc.github.io/"
```suggestion
        "CNAME": "quantummapleqc.github.io"
```

2024-12-04 17:46 UTC, CuteDog5695 approved these changes
Seems good to me

2024-12-04 17:46 UTC, CuteDog5695 requested changes
NEVERMIND

2024-12-04 17:46 UTC, CuteDog5695 commented on domains/cursedscrubdaddygang.json
> +        "Discord": "herricksom"
```suggestion
        "repo": "https://github.com/QuantumMapleQC/quantummapleqc.github.io",
        "username": "quantummapleqc",
        "Discord": "herricksom"
```

2024-12-04 17:54 UTC, CuteDog5695 approved these changes
Now its fine

2024-12-04 17:54 UTC, merged

2025-08-10 02:18 UTC, QuantumMapleQC commented
so its been a couple months and i came back to the project but when i put the domain back in the dns it works just fine however i cant navigate the domain it drags me back to the is-a.dev website 

https://quantummapleqc.github.io/cursedscrubdaddygang/