Create dyikes.json
is-a-dev/register pull request #17587
Opened 2024-12-05 10:42 UTC by dyikes

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-05 14:06 UTC, DEV-DIBSTER requested changes

2024-12-05 14:06 UTC, DEV-DIBSTER commented on domains/dyikes.json
> +        "A": "dyikes.synology.me"
A records should be an array of IPs. If you're using a hostname that should be a CNAME record.

2024-12-06 22:28 UTC, Stef-00012 requested changes

2024-12-06 22:28 UTC, Stef-00012 commented on domains/dyikes.json
> +        "CNAME": "z.dyikes.cloudns.be"
you should complete your website first, i only see "This website is working properly!"

2024-12-07 22:07 UTC, closed without merging