Create dash.bernardonogueira8.is-a.dev.json
is-a-dev/register pull request #17612
Opened 2024-12-06 23:15 UTC by Samuraiflamesf

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-06 23:21 UTC, Samuraiflamesf commented
New test

2024-12-07 10:11 UTC, Stef-00012 requested changes

2024-12-07 10:11 UTC, Stef-00012 commented on dash.bernardonogueira8.json
this file should be in the domains folder

2024-12-07 10:11 UTC, Stef-00012 commented on domains/cdn.bernardonogueira8.json
> +    "A": ["100.42.189.124"]
i cannot reach your website
> 404 page not found

2024-12-07 10:11 UTC, Stef-00012 commented on dash.bernardonogueira8.json
> +    "A": ["100.42.189.124"]
i cannot reach your website
> 404 page not found

2024-12-07 10:41 UTC, Samuraiflamesf commented on dash.bernardonogueira8.json
Thanks, I will solve it

2024-12-07 22:42 UTC, closed without merging