i create json
is-a-dev/register pull request #1763
Opened 2022-02-27 17:54 UTC by tanilayagirlar

add domain list

2022-02-27 17:57 UTC, tanilayagirlar commented on domains/tanilay.json
> +    "username": "tanilay",
"username": "tanilayagirlar",

2022-02-28 00:34 UTC, MaskDuck requested changes

2022-02-28 00:34 UTC, MaskDuck commented on domains/tanilay.json
> +    "username": "tanilay",
```suggestion
    "username": "tanilayagirlar",
```

2022-02-28 04:26 UTC, MaskDuck commented
@tanilayagirlar can you fix the json?

2022-03-03 08:31 UTC, closed without merging