Create loverboy-ent
is-a-dev/register pull request #17694
Opened 2024-12-12 19:37 UTC by Skyy09

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-12 19:38 UTC, Skyy09 commented
I made sure it's in /domains/

2024-12-12 20:19 UTC, CuteDog5695 requested changes

2024-12-12 20:19 UTC, CuteDog5695 commented on domains/loverboy-ent
File needs to be in json format.

2024-12-12 20:22 UTC, Skyy09 commented on domains/loverboy-ent
It is

2024-12-12 20:23 UTC, Skyy09 commented on domains/loverboy-ent
{
  "owner": {
    "username": "skyy09",
    "organization": "Loverboy Website Manager",
    "enterprise": "Loverboy Enterprise",
    "email": "29686@ghaps.org",
    "description": "Loverboy Enterprise is a development enterprise organization dedicated to creating programs under special circumstances for specific businesses, teams, individuals, and organizations."
  },
  "record": {
    "CNAME": "lb-ent.github.io"
  }
}

2024-12-13 16:00 UTC, CuteDog5695 commented on domains/loverboy-ent
The actual file isn't in json format. You need to add `.json` at the end of the file's name

2024-12-13 21:52 UTC, Skyy09 commented on domains/loverboy-ent
Oh!

2024-12-13 21:52 UTC, Skyy09 commented on domains/loverboy-ent
I apologize, I completely forgot about that.

2024-12-13 21:55 UTC, Skyy09 commented on domains/loverboy-ent
Finished. I apologize about that.

2024-12-14 21:14 UTC, Skyy09 commented
Are you guys going to merge it?

2024-12-14 21:22 UTC, CuteDog5695 requested changes
Site wasn't accessible, but I went to the sites repo and if its the correct one its not complete. I would like you to add more to your website.
I could be wrong here, so if you think I made a mistake here, please give a preview of the website.

2024-12-14 22:20 UTC, Skyy09 commented
> Site wasn't accessible, but I went to the sites repo and if its the correct one its not complete. I would like you to add more to your website. I could be wrong here, so if you think I made a mistake here, please give a preview of the website.

It's for email.

2024-12-15 07:53 UTC, CuteDog5695 commented
Then why didn't you add MX records for the main file? If I merged this right now it would only be pointed to a website, not a email service.

2024-12-16 23:26 UTC, Skyy09 commented
Done! <3

2024-12-17 20:02 UTC, CuteDog5695 requested changes

2024-12-17 20:02 UTC, CuteDog5695 commented on domains/loverboy-ent.json
> +    ]
wtf?
Read docs please

2024-12-18 15:10 UTC, orangci commented
wth is this cursed tomfoolery
closing, come back when you've read the docs

2024-12-18 15:19 UTC, closed without merging