Minecraft server domain
is-a-dev/register pull request #17709
Opened 2024-12-13 17:45 UTC by 3geETR

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

Domain for the server i play with my friends.

2024-12-14 00:53 UTC, omsenjalia requested changes, later dismissed
Bunch of grey spaces in here and commenting for the first file: that's now how mc records work.

2024-12-14 07:28 UTC, 3geETR commented
> Bunch of grey spaces in here and commenting for the first file: that's now how mc records work.

I updated the file, should I do it like this?

2024-12-14 08:35 UTC, wdhdev requested changes

2024-12-14 08:35 UTC, wdhdev commented on domains/mc.3gee.json
You don't need this file if you're using Minecraft.

2024-12-14 17:34 UTC, 3geETR commented on domains/mc.3gee.json
If the port is different from 25565, it must be done through the srv record.

2024-12-14 17:38 UTC, 3geETR reviewed
If the port is different from 25565, it must be done through the srv record.

2024-12-14 17:39 UTC, 3geETR commented on domains/mc.3gee.json
Ok

2024-12-15 00:16 UTC, wdhdev approved these changes

2024-12-15 00:16 UTC, merged

2024-12-15 00:16 UTC, wdhdev commented
> If the port is different from 25565, it must be done through the srv record.

That is correct.