Create abhinav.josn
is-a-dev/register pull request #17761
Opened 2024-12-18 17:05 UTC by abhinavshyju

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-19 07:01 UTC, orangci requested changes
Filename must end in `.json`.

This site is inaccessible.

2024-12-19 07:07 UTC, abhinavshyju commented
Sorry for the typo error plz check this

2024-12-23 21:26 UTC, DEV-DIBSTER requested changes

2024-12-23 21:26 UTC, DEV-DIBSTER commented on domains/abhinav.json
> +        "CNAME": "portfolio-6ns.pages.dev"
Little content provided.

2024-12-25 11:39 UTC, closed without merging

2024-12-25 11:39 UTC, orangci commented
stale