Delete snowy.is-a.dev
is-a-dev/register pull request #17806
Opened 2024-12-22 07:18 UTC by HayBael

Delete snowy.is-a.dev via Discord

2024-12-22 14:13 UTC, CuteDog5695 requested changes
You are making a nested subdomain on a subdomain which you want to delete.

2024-12-23 01:40 UTC, HayBael commented
I want to delete snowy.is-a.dev, can i?

2024-12-23 22:01 UTC, HayBael commented
I forgot I can't change it directly 🙏

2024-12-25 11:40 UTC, orangci commented
stale

2024-12-25 11:40 UTC, closed without merging