CNAME subdomain
is-a-dev/register pull request #17818
Opened 2024-12-23 06:41 UTC by aadltya

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] The file's name is all lowercased and alphanumeric. 
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

[website-link](https://portfolio-sec.vercel.app/)

2024-12-23 07:16 UTC, wdhdev requested changes
We don't tend to allow templated websites that have not been modified from the template. (You have links linking to other people, and have projects listed that do not appear to be run by you.)

2024-12-23 13:52 UTC, aadltya commented
That's wrong one, I messed up I'll create new PR with my own website

2024-12-23 13:52 UTC, aadltya commented
> We don't tend to allow templated websites that have not been modified from the template. (You have links linking to other people, and have projects listed that do not appear to be run by you.)


That's wrong one, I messed up I'll create new PR with my own website

2024-12-24 06:54 UTC, wdhdev approved these changes

2024-12-24 06:56 UTC, merged