register clarenisme.is-a.dev
is-a-dev/register pull request #17833
Opened 2024-12-24 04:12 UTC by razelleclaren

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-24 19:20 UTC, Stef-00012 submitted a review, later dismissed

2024-12-24 19:20 UTC, Stef-00012 commented on domains/clarenisme.json
> +    "username": "clarenisme",
username should be your github username

2024-12-25 11:37 UTC, orangci approved these changes

2024-12-25 12:00 UTC, Stef-00012 requested changes

2024-12-25 12:00 UTC, Stef-00012 commented on domains/clarenisme.json
> +  }
replace the unknown space-like characters with actual spaces

one before `~` and 2 before `}`

2024-12-27 22:47 UTC, closed without merging