Create s1ow.json
is-a-dev/register pull request #17845
Opened 2024-12-25 07:12 UTC by akk1to

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://h4iph0ngm1enb4c.github.io/Web

2024-12-25 11:25 UTC, orangci requested changes, later dismissed
if you're registering a domain on behalf of another user you must provide evidence as such

2024-12-26 10:19 UTC, akk1to commented
I'll ask the author to prove that I register for him hehe

2024-12-26 10:29 UTC, H4iPh0ngM1enB4c commented
Yup I'm H4iPh0ngM1enB4c here. I asked akk1to to register the domain for me because I don't know how to make one lmao

2024-12-27 12:31 UTC, iostpa requested changes

2024-12-27 12:31 UTC, iostpa commented on domains/s1ow.json
> +          "185.199.109.153"
You forgot one A record.
```suggestion
          "185.199.108.153",
          "185.199.110.153",
          "185.199.109.153",
          "185.199.111.153"
```

2024-12-27 12:33 UTC, iostpa approved these changes
Seems good to me now

2024-12-27 12:34 UTC, merged