Register rhv.is-a.dev
is-a-dev/register pull request #17850
Opened 2024-12-25 09:06 UTC by Houloude9IOfficial

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://rhv.pages.dev
![image](https://github.com/user-attachments/assets/9326bae5-aebb-4632-a08a-742628248143)

2024-12-25 11:24 UTC, orangci approved these changes, later dismissed

2024-12-25 11:24 UTC, orangci commented on domains/rhv.json
> +    "username": "Human Verification",
```suggestion
```
you cant have two username fields

2024-12-25 15:00 UTC, Houloude9IOfficial reviewed
Now there's only 1 username

2024-12-27 12:35 UTC, iostpa requested changes
1. Why does the preview only have that bot checker? Where is the actual website?
2. Actual CNAME doesn't seem to do anything,

2024-12-27 12:55 UTC, closed without merging