manish-madi
is-a-dev/register pull request #17870
Opened 2024-12-27 10:10 UTC by m-manish03

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-27 10:11 UTC, m-manish03 commented
manish-madi

2024-12-27 12:43 UTC, iostpa requested changes
Site is not accessible, please give a preview of your website.

2024-12-27 12:43 UTC, iostpa commented on manish-madi
File needs to be in the "domains" directory.

2024-12-28 18:35 UTC, iostpa commented on manish-madi
Oh, didn't notice that.

2025-01-02 05:57 UTC, orangci commented
stale

2025-01-02 05:57 UTC, closed without merging