Create oneforall.json
is-a-dev/register pull request #17918
Opened 2024-12-30 16:04 UTC by Lolgamerzsd

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-30 16:16 UTC, VinceAle7082 reviewed
You didn't write anything in the .json file, there is no reason to merge this pull request

2024-12-31 09:32 UTC, iostpa requested changes

2024-12-31 09:32 UTC, iostpa commented on domains/oneforall.json
File has nothing.

2024-12-31 09:32 UTC, closed without merging

2024-12-31 09:32 UTC, iostpa commented
Come back with a PR that actually has something in the json file.