Create ramanand.json
is-a-dev/register pull request #17933
Opened 2024-12-31 14:59 UTC by ramanandkrgupta

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2024-12-31 15:10 UTC, ramanandkrgupta commented
https://ramanandkrgupta.github.io/

Live Website 🚀

2025-01-01 13:14 UTC, iostpa requested changes

2025-01-01 13:14 UTC, iostpa commented on domains/ramanand.json
> +        "NS": ["aron.ns.cloudflare.com", "decker.ns.cloudflare.com"]
Can you give a reason as to why you want NS records?

2025-01-01 13:18 UTC, ramanandkrgupta commented on domains/ramanand.json
> +        "NS": ["aron.ns.cloudflare.com", "decker.ns.cloudflare.com"]
I don't have any domain name . And i want to use cloudflare service with my custom domain . But for starting with cloudflare i need to add a domain name first. That's why i need this.  I hope you understand .

2025-01-01 13:22 UTC, iostpa commented on domains/ramanand.json
> +        "NS": ["aron.ns.cloudflare.com", "decker.ns.cloudflare.com"]
Yea no, thats not a valid reason.

2025-01-01 13:23 UTC, closed without merging

2025-01-01 13:23 UTC, iostpa commented
Closing PR since it doesn't have a valid reason, if you want to use your github site with the domain I'd recommend going here: https://is-a.dev/docs/github-pages/.

2025-01-01 14:41 UTC, ramanandkrgupta commented
Here is a valid reason you can use for requesting the use of Cloudflare nameservers for your subdomain:

- I want to use Cloudflare's DNS services to enhance the performance and security of my subdomain.
- I need a private zone for managing devices and services behind a secure network, such as using Tailscale.
- Cloudflare's DNS management tools, including their web dashboard and API, will streamline my DNS record updates, allowing me to focus on my projects.
- Utilizing Cloudflare Tunnel will enable me to expose services securely without needing a static IP address from my ISP.