Renamed chatting.json to chattingmessenger.json because of generic domain name
is-a-dev/register pull request #17934
Opened 2024-12-31 16:06 UTC by riotoff

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] The file's name is all lowercased and alphanumeric. 
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2025-01-01 13:15 UTC, iostpa requested changes, later dismissed

2025-01-01 13:15 UTC, iostpa commented on domains/chattingmessenger.json
> +        "CNAME": "riotoff.github.io"
Uh could I get a preview of the website?

2025-01-01 14:22 UTC, riotoff commented on domains/chattingmessenger.json
> +        "CNAME": "riotoff.github.io"
![chrome_wfKSiaNfdW](https://github.com/user-attachments/assets/6b855c1c-17a1-4e04-b99e-8e6df6cbdfc2)

2025-01-02 06:02 UTC, orangci approved these changes

2025-01-02 06:03 UTC, merged