Add emails for fake.is-a.dev
is-a-dev/register pull request #1810
Opened 2022-03-07 21:27 UTC by YEEETT

2022-03-07 22:36 UTC, hackermondev approved these changes

2022-03-07 22:38 UTC, hackermondev requested changes, later dismissed
IIRC you cannot use ``CNAME`` record with MX record, only an A record with MX record is allowed.

2022-03-08 21:42 UTC, YEEETT commented
Hopefully that works. (I modified my fork and I think I saw it updated here, but I may be wrong because I don't have much experience with pull requests)

2022-03-11 04:08 UTC, icancodebeauty requested changes
Remove CNAME & Add Array Of A Records For Github Pages
![image](https://user-images.githubusercontent.com/90105839/157800241-c2cb9352-4263-4ffb-9d75-ee6867933b68.png)

Look At This PR For Reference :- https://github.com/is-a-dev/register/pull/1409

2022-03-11 04:36 UTC, MaskDuck requested changes

2022-03-11 04:36 UTC, MaskDuck commented on domains/fake.json
> +    "A": "185.199.108.153",
```suggestion
    "A": ["185.199.108.153"],
```

2022-03-11 22:27 UTC, YEEETT commented
> Remove CNAME & Add Array Of 'A' Records For Github Pages ![image](https://user-images.githubusercontent.com/90105839/157800241-c2cb9352-4263-4ffb-9d75-ee6867933b68.png)
> 
> Look At This PR For Reference :- #1409

The first one was the IP address I used.

2022-03-12 02:10 UTC, MaskDuck approved these changes
not sus

2022-03-12 02:11 UTC, TheBotlyNoob approved these changes
yep

2022-03-12 02:12 UTC, merged