nischay.is-a.dev | Add file nischay.json
is-a-dev/register pull request #1814
Opened 2022-03-08 03:17 UTC by nischay02

2022-03-08 03:25 UTC, MaskDuck requested changes

2022-03-08 03:25 UTC, MaskDuck commented on domains/nischay.json
> +    "snapchat": "https://snapchat.com/add/nischay_02",
```suggestion
    "snapchat": "nischay_02",
```

2022-03-08 03:25 UTC, MaskDuck commented on domains/nischay.json
> +    "instagram": "https://www.instagram.com/nischay_02/",
```suggestion
    "instagram": "nischay_02",
```

2022-03-08 15:41 UTC, MaskDuck commented
do you see our comments

2022-03-08 19:45 UTC, nischay876 commented
> do you see our comments
yes but i don 't understand that is there something that i need to edit or the PR is just on hold from your side?

2022-03-10 17:54 UTC, TheBotlyNoob approved these changes

2022-03-10 17:54 UTC, merged

2022-03-13 11:04 UTC, MaskDuck commented
@nischay876 we will remove one of your txt record

2022-03-14 10:54 UTC, nischay876 commented
ok remove the google verification one bcz it got reset