Update roxza.json
is-a-dev/register pull request #1857
Opened 2022-03-12 20:27 UTC by Roxza

2022-03-12 21:08 UTC, TheBotlyNoob requested changes, later dismissed

2022-03-12 21:08 UTC, TheBotlyNoob commented on domains/roxza.json
> +    "CNAME": "https://roxza.me"
The `CNAME` cannot have any slashes, if you want the domain to just redirect to your website, you can use a `URL` record instead.

```
```

2022-03-13 11:00 UTC, hackermondev approved these changes

2022-03-13 11:01 UTC, hackermondev approved these changes

2022-03-16 12:42 UTC, MaskDuck approved these changes
uh ok

2022-03-17 00:19 UTC, merged