Create ceon.json
is-a-dev/register pull request #1919
Opened 2022-03-18 16:35 UTC by Ceonnn

2022-03-18 17:14 UTC, AbubakarKang requested changes
I recommend changing the URL record format to a more uniformed format: https://www.ceon.tech/

2022-03-19 01:48 UTC, MaskDuck requested changes

2022-03-19 01:48 UTC, MaskDuck commented on domains/ceon.json
> +    "email": "ceon.tech"
uh this is not a valid email

2022-03-19 01:57 UTC, MaskDuck commented
> I recommend changing the URL record format to a more uniformed format: https://www.ceon.tech/

uh imo an url record like that is perfectly fine.

2022-05-08 14:40 UTC, closed without merging