update zerotwo.json to use new config
is-a-dev/register pull request #1920
Opened 2022-03-18 19:18 UTC by ConnorDoesDev

2022-03-19 01:55 UTC, MaskDuck requested changes

2022-03-19 01:55 UTC, MaskDuck commented on domains/zerotwo.json
> +    "email": "[redacted] send me a dm on discord instead."
uh left email an empty string and add an discord pls (discord = Connor!#0800, id 744603004493365330 i suppose)

2022-03-19 01:55 UTC, MaskDuck commented on domains/zerotwo.json
> +    "username": "Connor",
github username pls?

2022-03-19 01:55 UTC, MaskDuck commented on domains/zerotwo.json
> +    "CNAME": "zerotwodiscord.github.io/website"
cname cant have slash

2022-03-21 06:43 UTC, ConnorDoesDev commented
your english was giving me internal bleeding, but thanks i suppose

2022-03-21 06:45 UTC, MaskDuck commented
i dont really think im speaking english rn

2022-03-21 06:46 UTC, MaskDuck approved these changes
sussy

2022-03-21 06:46 UTC, merged