Create ziue.json
is-a-dev/register pull request #1982
Opened 2022-03-26 21:29 UTC by ziuee

2022-03-26 22:15 UTC, hackermondev requested changes
That's not how you do CNAME with GitHub pages.
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

2022-03-27 09:49 UTC, MaskDuck requested changes

2022-03-27 09:49 UTC, MaskDuck commented on domains/ziue.json
> +    "username": "ziue",
rly your gh username?

2022-03-27 09:49 UTC, MaskDuck commented on domains/ziue.json
> +    "discord": "ziue#8495"
email pls? if not leave email as an empty string

2022-03-27 10:44 UTC, ziuee commented on domains/ziue.json
> +    "username": "ziue",
does it gotta be github name?

2022-03-27 10:46 UTC, ziuee commented
have a look at new file

2022-03-27 11:15 UTC, MaskDuck commented on domains/ziue.json
> +    "username": "ziue",
yes.

2022-03-27 11:15 UTC, MaskDuck approved these changes
sus power uninjected

2022-03-27 11:17 UTC, merged

2022-03-27 11:18 UTC, MaskDuck commented
@ziuee 
now go config github pages, see how [here](https://github.com/is-a-dev/register/blob/main/docs/hosted-at/github-pages.md).

**[optional]** star the repo pls