Create svloog.json
is-a-dev/register pull request #2019
Opened 2022-03-31 16:30 UTC by slvoog

2022-03-31 16:36 UTC, MaskDuck requested changes

2022-04-02 10:29 UTC, slvoog commented on domains/svloog.json
> +    "CNAME": "slvoog.github.io"
Fixed

2022-04-02 10:29 UTC, slvoog commented
Fixed the 404

2022-04-02 10:30 UTC, MaskDuck approved these changes
nice

2022-04-02 10:31 UTC, merged

2022-04-02 10:31 UTC, MaskDuck commented
@slvoog go config github pages (you can find how in the docs) and optionally star the repo

2022-04-02 10:32 UTC, MaskDuck commented
also feel free to join discord/open gh issue if youve ever need help