Create burandby.json
is-a-dev/register pull request #2084
Opened 2022-04-09 07:45 UTC by BurAndBY

2022-04-09 08:09 UTC, MaskDuck requested changes

2022-04-09 08:09 UTC, MaskDuck commented on domains/burandby.json
> +    "CNAME": "burandby.github.io/PicoPi/"
no cname with slash

2022-04-11 13:42 UTC, BurAndBY commented
@MaskDuck Sorry. done!

2022-04-11 13:58 UTC, MaskDuck approved these changes

2022-04-14 20:17 UTC, merged