Add domains
is-a-dev/register pull request #2110
Opened 2022-04-12 14:43 UTC by ThisMe124

Nice days

2022-04-12 15:41 UTC, MaskDuck requested changes

2022-04-16 08:00 UTC, ThisMe124 commented on domains/raw-kirito.json
> +    "CNAME": "thisme124.github.io"
Fixed🙂🙂

2022-04-16 08:00 UTC, ThisMe124 commented on domains/raw-kirito.json
> +    "CNAME": "thisme124.github.io"
> 404?

Fixed🙂🙂🙂

2022-04-16 08:00 UTC, MaskDuck commented on domains/raw-kirito.json
> +    "CNAME": "thisme124.github.io"
okay

2022-04-16 08:00 UTC, MaskDuck approved these changes

2022-04-16 08:01 UTC, merged