Update noma.json
is-a-dev/register pull request #2113
Opened 2022-04-12 21:11 UTC by Noma4321

I am the domain owner and I want to add an email to my domain
Thanks :)

2022-04-13 11:05 UTC, MaskDuck requested changes
cname cant be used with other domain record. sorry.

2022-04-14 01:59 UTC, Noma4321 commented
> cname cant be used with other domain record. sorry.

Ok, so can I make another file called 'Noma4321.is-a.dev' with the other records?

2022-04-14 05:09 UTC, Noma4321 commented
> > cname cant be used with other domain record. sorry.
> 
> Ok, so can I make another file called 'Noma4321.is-a.dev' with the other records?

I made the new file but the parse do not work
Can you check and say what’s wrong?

2022-04-15 13:31 UTC, hackermondev approved these changes

2022-04-17 08:31 UTC, closed without merging