Create dev101.json
is-a-dev/register pull request #2151
Opened 2022-04-17 20:28 UTC by GitCat12

2022-04-18 00:34 UTC, omxpro requested changes
In the "repo" section you are supposed to put your GitHub repo's link. Not the web's link

2022-04-18 10:06 UTC, MaskDuck requested changes

2022-04-18 10:06 UTC, MaskDuck commented on domains/dev101.json
> +    "twitter": "no_twitter"
if you don't have a twitter just leave that blank.

2022-04-18 10:06 UTC, MaskDuck commented on domains/dev101.json
> +    "email": "not_public@np.org",
if you don't want to share your email, leave `""` as your email and share more of your social medias. we require at least 1 valid social media link beside github.

2022-04-18 10:06 UTC, MaskDuck commented on domains/dev101.json
> +    "CNAME": "https://infrapay.github.io/"
cname cant have slash

2022-05-08 01:06 UTC, cyberdev101 commented
Sorry, realized I dont need the domain anymore. Thank you for your time!

2022-05-08 01:06 UTC, closed without merging