request to add my domain
is-a-dev/register pull request #2159
Opened 2022-04-18 11:40 UTC by Muppidathi-sys

2022-04-18 11:42 UTC, MaskDuck requested changes

2022-04-18 11:42 UTC, MaskDuck commented on domains/sathish.json
> +    "CNAME": "Muppidathi-sys.github.io"
404?

2022-04-18 11:43 UTC, omxpro commented
![Screenshot_20220418-171244_Brave](https://user-images.githubusercontent.com/69719569/163803436-4e38337a-ca6b-4217-84e7-9ca3b779f330.png)

Btw aren't repo supposed to end with username.github.io

2022-04-18 12:33 UTC, MaskDuck commented
theres a trick to name the repo whatever you like :)

2022-04-19 05:25 UTC, Muppidathi-sys commented
Sorry, there was a mistake in mapping the repo to domain. It works now.
https://muppidathi-sys.github.io/

2022-04-19 15:04 UTC, MaskDuck submitted a review, later dismissed

2022-04-21 08:13 UTC, Muppidathi-sys commented
please verify. and merge quickly.

2022-04-21 10:58 UTC, MaskDuck commented
why are you constantly closing and re-opening?

2022-04-21 11:13 UTC, Muppidathi-sys commented
sorry bro, by mistake!!!

2022-04-25 09:38 UTC, MaskDuck approved these changes

2022-04-25 09:38 UTC, merged