initial
is-a-dev/register pull request #2172
Opened 2022-04-19 16:00 UTC by SumirSeth

2022-04-19 16:01 UTC, MaskDuck requested changes

2022-04-19 16:01 UTC, MaskDuck commented on domains/sumir.json
> +    "username": "Sumir Seth",
gh username pls?

2022-04-19 16:08 UTC, MaskDuck requested changes

2022-04-19 16:08 UTC, MaskDuck commented on domains/sumir.json
> +    "CNAME": "sumirseth.github.io"
404?

2022-04-19 16:08 UTC, SumirSeth commented on domains/sumir.json
> +    "username": "Sumir Seth",
cool now?

2022-04-20 15:18 UTC, MaskDuck requested changes

2022-04-20 15:18 UTC, MaskDuck commented on domains/sumir.json
> +    "CNAME": "sumirseth.github.io/sumir"
no cname at slash

2022-06-11 14:38 UTC, closed without merging