Create polopro.json
is-a-dev/register pull request #2173
Opened 2022-04-19 19:16 UTC by polo-1245-oficial

2022-04-20 10:21 UTC, AbubakarKang approved these changes, later dismissed

2022-04-21 13:00 UTC, MaskDuck requested changes

2022-04-21 13:00 UTC, MaskDuck commented on domains/polopro.json
> +    "username": "polo",
your gh username?

2022-04-21 13:11 UTC, MaskDuck approved these changes

2022-04-21 13:57 UTC, merged