hi
is-a-dev/register pull request #2185
Opened 2022-04-21 19:57 UTC by 5rq

hi

2022-04-22 01:13 UTC, omxpro commented
Why there is no repo url?

2022-04-22 03:34 UTC, 5rq commented
> Why there is no repo url?

good question
I forgot it 🤷‍♂️

2022-04-23 01:52 UTC, MaskDuck requested changes

2022-04-23 01:52 UTC, MaskDuck commented on domains/syz.json
> +      "username":"Syz",
your gh username?

2022-04-23 01:52 UTC, MaskDuck commented on domains/syz.json
> +      "repo":"https://github.com/5rq/5rq.github.io"
repo should be a dedicated field instead

2022-06-13 14:44 UTC, closed without merging

2022-06-14 09:31 UTC, omxpro commented
F