Create api.arman.json
is-a-dev/register pull request #2223
Opened 2022-04-29 02:39 UTC by ItzArman09

2022-04-29 21:11 UTC, hackermondev approved these changes

2022-04-29 21:12 UTC, hackermondev requested changes, later dismissed
CNAME record in ``foxie.arman`` cannot have slash.

2022-04-30 01:35 UTC, ItzArman09 commented
but thats my cname, got it from gh pages... What do i do. Now

2022-04-30 01:57 UTC, MaskDuck requested changes

2022-04-30 01:57 UTC, MaskDuck commented on domains/api.arman.json
> +    "github": "ItzArman09"
```suggestion
    "username": "ItzArman09",
    "email": "contact@mail.arman.is-a.dev"
```

2022-04-30 01:57 UTC, MaskDuck commented on domains/arman.json
> +    "github": "ItzArman09"
```suggestion
    "email": "contact@mail.arman.is-a.dev"
```

2022-04-30 01:57 UTC, MaskDuck commented on domains/foxie.arman.json
> +    "github": "ItzArman09"
```suggestion
    "username": "ItzArman09",
    "email": "contact@mail.arman.is-a.dev"
```

2022-04-30 02:15 UTC, ItzArman09 commented
commited

2022-04-30 02:18 UTC, MaskDuck requested changes

2022-04-30 02:18 UTC, MaskDuck commented on domains/foxie.arman.json
> +    "CNAME": "itzarman09.github.io"
404?

2022-04-30 02:19 UTC, ItzArman09 commented
1 min

2022-04-30 02:22 UTC, ItzArman09 commented
check?

2022-04-30 02:26 UTC, MaskDuck approved these changes

2022-04-30 02:27 UTC, merged