Create l.alpha.json
is-a-dev/register pull request #2401
Opened 2022-05-20 20:07 UTC by YouFoundAlpha

2022-05-20 20:56 UTC, hackermondev approved these changes

2022-05-20 20:57 UTC, hackermondev requested changes
It cannot be ``l``, it must have more than two characters.

2022-05-21 06:19 UTC, YouFoundAlpha commented
@hackermondev I renamed l.alpha.json to link.alpha.json, I hope it works now.

2022-05-21 06:24 UTC, YouFoundAlpha commented
> It cannot be `l`, it must have more than two characters.
I have renamed it to link.

2022-05-21 11:10 UTC, hackermondev approved these changes

2022-05-21 11:10 UTC, merged