Create vikrant.json
is-a-dev/register pull request #2540
Opened 2022-06-06 09:43 UTC by 150207

A Subdomain For Me

2022-06-08 15:30 UTC, MaskDuck requested changes

2022-06-08 15:30 UTC, MaskDuck commented on domains/vikrant.json
> +    "username": "TheMalware",
insert your gh username.

2022-06-08 22:17 UTC, shrinetojha reviewed
Changed gh username

2022-06-09 06:25 UTC, MaskDuck requested changes

2022-06-09 06:25 UTC, MaskDuck commented on domains/vikrant.json
> +    "CNAME": "https://themalware.tk"
cname cant contain slash

2022-06-11 18:15 UTC, shrinetojha reviewed
Update CNAME

2022-06-13 04:56 UTC, MaskDuck requested changes

2022-06-13 04:56 UTC, MaskDuck commented on domains/vikrant.json
> +    "username": "shrinetojha",
this is the line for your github username.

2022-06-13 18:41 UTC, 150207 commented
yeah ofc, i changed my gh username

2022-06-14 12:14 UTC, MaskDuck approved these changes

2022-06-14 12:14 UTC, MaskDuck approved these changes

2022-06-14 12:15 UTC, merged