Created rohith.json
is-a-dev/register pull request #256
Opened 2020-10-14 11:24 UTC by rohithp7777

2020-10-14 14:02 UTC, shajanjp requested changes
Is https://rohithp7777.github.io/ working?
Refer https://pages.github.com/ to make one.

2020-10-15 18:44 UTC, rohithp7777 commented
> Is https://rohithp7777.github.io/ working?
> Refer https://pages.github.com/ to make one.

is firebase okay

> Is https://rohithp7777.github.io/ working?
> Refer https://pages.github.com/ to make one.

sorry for the trouble firebase is okay ig ?

2020-10-15 18:51 UTC, rohithp7777 commented
> Is https://rohithp7777.github.io/ working?
> Refer https://pages.github.com/ to make one.

Oh sorry, is firebase hosted one fine?

2020-10-15 19:51 UTC, phenax requested changes

2020-10-15 19:51 UTC, phenax commented on domains/rohith.json
> +        "URL": "https://rohith-1c974.web.app/"
Please make sure firebase supports custom domains. If not, you can use github pages.

```suggestion
        "CNAME": "rohith-1c974.web.app"
```

2020-10-16 18:02 UTC, phenax approved these changes

2020-10-16 18:02 UTC, merged