Create huseyin.json
is-a-dev/register pull request #2652
Opened 2022-06-20 06:17 UTC by Huseyin-Cinar

To make our job easier, please spend time to review your application before submitting. 

- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.

2022-06-21 06:32 UTC, Huseyin-Cinar commented on domains/huseyin.json
> +  }
a

2022-06-27 05:54 UTC, Huseyin-Cinar commented
Birleştirmem neden onaylanmadı?

2022-06-29 07:19 UTC, MaskDuck requested changes
this website wasn't written in english, right? can you elaborate on what does the content in this website means? and also can you fix the `description` field to use english?

thanks.

2022-06-29 08:00 UTC, Huseyin-Cinar commented
sure

2022-06-29 11:54 UTC, Huseyin-Cinar commented
This web site redirecting to futuree.netlify.app adress. Want you futuree.netlify.app's means?

2022-06-29 14:03 UTC, Huseyin-Cinar commented
@MaskDuck

2022-06-30 07:54 UTC, MaskDuck commented
yes

2022-06-30 08:07 UTC, Huseyin-Cinar commented
This website, from many parts of the world; was established to gather people with different purposes such as software, coding, programming, domain acpuisition, and opening a website on a single website.

2022-07-04 06:08 UTC, MaskDuck approved these changes, later dismissed

2022-07-04 06:08 UTC, MaskDuck commented
acceptable ig idk

2022-07-04 06:10 UTC, MaskDuck commented
will have to look into this further sorry

2022-08-13 02:19 UTC, TheBotlyNoob submitted a review, later dismissed
:+1:

2022-09-16 12:39 UTC, MaskDuck approved these changes
we're sorry for late reply :(

2022-09-16 12:39 UTC, merged