feat: add she.json as she.is-a.dev
is-a-dev/register pull request #2770
Opened 2022-07-05 15:30 UTC by yuzhigang33

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-07-06 13:46 UTC, MaskDuck requested changes
can you escalate on what does the website means?

2022-07-06 14:34 UTC, yuzhigang33 commented
> can you escalate on what does the website means?

be my personal homepage

2022-07-08 03:17 UTC, omxpro commented
> > can you escalate on what does the website means?
> 
> be my personal homepage

**Be** my personal homepage?

2022-07-10 12:17 UTC, MaskDuck approved these changes

2022-07-10 12:17 UTC, merged