create bimal.json
is-a-dev/register pull request #2806
Opened 2022-07-09 11:35 UTC by bimal-inc

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-07-11 16:29 UTC, bimal-inc commented
Its been 2 days and my PR is still in pending...;(

2022-07-11 16:30 UTC, bimal-inc commented
Its been 2 days and my PR is still in pending...;(

2022-07-13 03:28 UTC, MaskDuck commented
dw i waited 1 month :)

2022-07-13 03:29 UTC, MaskDuck requested changes

2022-07-13 03:29 UTC, MaskDuck commented on domains/bimal.json
> +    "CNAME": "bimal-inc.github.io/myportfolio/"
no slash in cname

2022-07-13 04:39 UTC, bimal-inc commented on domains/bimal.json
> +    "CNAME": "bimal-inc.github.io/myportfolio/"
Fixed now

2022-07-13 04:41 UTC, bimal-inc commented
Fixed the CNAME , username and repo link @MaskDuck and thankyou for your  service

2022-07-13 04:44 UTC, bimal-inc reviewed
Fixed it should be working now

2022-07-13 06:53 UTC, MaskDuck approved these changes
my ancestor's feeling good

welcome https://bimal.is-a.dev !

(will be accesible in bimal.is-a.dev/myportfolio )

2022-07-13 06:55 UTC, merged