mc.dainfloop.is-a.dev
is-a-dev/register pull request #2811
Opened 2022-07-09 21:39 UTC by DaInfLoop

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [ ] ~~You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**~~
  - Link to website: (minecraft server)
- [x] The website is reachable. (Currently using Aternos as a test, will move onto a different hosting platform when finished.)
- [ ] ~~The CNAME record doesn't contain any slash.~~
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ
 

Mostly depends on #2810.

2022-07-09 22:33 UTC, andrewstech requested changes
Sorry we do not support name servers.

2022-07-10 09:11 UTC, DaInfLoop commented
> Sorry we do not support NS records.
Alright, is there any way I could link my minecraft server with an .is-a.dev domain then?

2022-07-13 10:34 UTC, MouseMoosz commented
> > Sorry we do not support NS records.
> 
> Alright, is there any way I could link my minecraft server with an .is-a.dev domain then?

Add a [`A`](https://docs.is-a.dev/domain_structure/#record-required) record pointing to the IPv4 address of your minecraft server

2022-07-13 12:21 UTC, MaskDuck requested changes

2022-09-02 17:46 UTC, closed without merging