Change my mail and create new subdomain
is-a-dev/register pull request #2843
Opened 2022-07-14 14:06 UTC by gornostay25

- [X] You're not using Vercel or Netlify.
- [X] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [X] The website is reachable.
- [X] The CNAME record doesn't contain any slash.
- [X] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.

2022-07-14 14:17 UTC, gornostay25 commented
??? Where's my mistake

2022-07-16 03:49 UTC, MaskDuck requested changes

2022-07-16 08:09 UTC, gornostay25 commented on domains/gornostay25.json
> +    ]
Thanks 🙏

2022-07-17 11:53 UTC, MaskDuck approved these changes

2022-07-17 11:53 UTC, merged