Redirect to my blog instead of being an email domain
is-a-dev/register pull request #2859
Opened 2022-07-15 18:45 UTC by DaInfLoop

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [X] You're not using Vercel or Netlify.
- [X] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: https://haroon.repl.co/
- [X] The website is reachable.
- [X] The CNAME record doesn't contain any slash.
- [X] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-07-16 04:26 UTC, MaskDuck requested changes

2022-07-16 10:57 UTC, DaInfLoop commented on domains/dainfloop.json
> +    "TXT": "replit-verify=ea1ab2ec-071c-45d5-8455-bfdecf9fb1b1"
Removed the TXT record then

2022-07-23 11:18 UTC, DaInfLoop commented
Forgot to request a review again, sorry

2022-07-24 01:08 UTC, MaskDuck approved these changes

2022-07-24 01:08 UTC, merged