pleas start my website immediately
is-a-dev/register pull request #2933
Opened 2022-07-21 15:11 UTC by SatyamV7

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-07-21 15:17 UTC, MouseMoosz commented on domains/00001.json
> +    "twitter": "your-twitter-username"
You could drop this

2022-07-21 15:28 UTC, MouseMoosz requested changes

2022-07-21 15:28 UTC, MouseMoosz commented on satyamv7.json
> +    "twitter": "your-twitter-username"
You can drop the twitter field if you are not entering anything in it.

2022-07-24 01:18 UTC, MaskDuck requested changes

2022-07-24 01:18 UTC, MaskDuck approved these changes

2022-07-24 01:19 UTC, merged