Change to form type
is-a-dev/register pull request #2964
Opened 2022-07-24 16:04 UTC by andrewstech

Change abuse template to form template

2022-07-24 16:10 UTC, andrewstech commented
Example: https://github.com/is-a-dev/test-project/issues/new/choose

2022-07-26 10:54 UTC, MaskDuck requested changes

2022-08-05 12:50 UTC, MaskDuck approved these changes

2022-08-21 14:10 UTC, hackermondev approved these changes

2022-08-29 11:01 UTC, andrewstech commented
@phenax thoughts?

2022-09-28 23:49 UTC, WilliamDavidHarrison approved these changes

2022-09-29 13:17 UTC, andrewstech commented
Not stale

2022-10-17 13:31 UTC, closed without merging