zarwin.is-a.dev
is-a-dev/register pull request #3031
Opened 2022-07-29 20:53 UTC by zarwin

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: https://zarwin.github.io/zarwin.is-a.dev
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-07-30 09:44 UTC, VaibhavSys requested changes

2022-07-30 09:44 UTC, VaibhavSys commented on domains/zarwin.json
> +  }
A `,` is missing.

2022-07-30 16:14 UTC, zarwin reviewed
Done the Suggested changes Please re-review my PR

2022-07-30 16:14 UTC, zarwin commented on domains/zarwin.json
> +  }
Where ?? I coudn't get that

2022-07-30 19:25 UTC, VaibhavSys approved these changes
Now wait for a maintainer to review and merge.

2022-08-07 07:08 UTC, academicgit commented
Please Merge this PR

2022-08-07 08:27 UTC, mtgsquad commented
Hi, i'm incredibly sorry for the long wait times. I apologise for the wait.

2022-08-07 08:29 UTC, mtgsquad approved these changes

2022-08-07 08:29 UTC, merged

2022-12-18 07:49 UTC, zarwin commented
> Hi, i'm incredibly sorry for the long wait times. I apologise for the wait.

No Problem and keep up the good work!