Register Subdomain: tusharhero
is-a-dev/register pull request #3086
Opened 2022-08-05 18:19 UTC by tusharhero

Added the domain: tusharhero

2022-08-07 10:53 UTC, omxpro approved these changes, later dismissed
wait for a maintiner to merge this

2022-08-07 11:52 UTC, MaskDuck requested changes
can you also elaborate on what will this domain be used for?

2022-08-08 06:45 UTC, tusharhero commented on domains/tusharhero.json
> +        "TXT": "c84447185947a39adfb909ef58b9e4"
It will be used for github pages

2022-08-08 12:17 UTC, tusharhero commented on domains/tusharhero.json
> +        "TXT": "c84447185947a39adfb909ef58b9e4"
then how do i use it for github pages?

2022-08-08 12:23 UTC, tusharhero commented on domains/tusharhero.json
> +        "TXT": "c84447185947a39adfb909ef58b9e4"
https://www.is-a.dev/github_pages

2022-08-12 02:58 UTC, tusharhero commented on domains/tusharhero.json
> +        "TXT": "c84447185947a39adfb909ef58b9e4"
Hello?

2022-08-13 13:50 UTC, tusharhero commented
Please resolve

2022-09-23 17:52 UTC, tusharhero commented
When u approve it

2022-09-23 17:52 UTC, tusharhero commented
I have been waiting for like a month

2022-09-23 18:20 UTC, mtgsquad commented
Hi, I'm sorry but at the moment, we're unable to merge any PRs, due to issues from our provider "Namecheap". For further information please join our discord server here: [https://s.molai.dev/is-a-dev](https://s.molai.dev/is-a-dev) (Shortened Redirect)

2022-09-23 22:28 UTC, WilliamDavidHarrison approved these changes

2022-10-04 03:26 UTC, tusharhero commented
I  don't want to index my site but It is a personal site. What information do I need to add to my site?

2022-11-08 06:54 UTC, tusharhero commented
Ok I will do that

2022-11-30 22:06 UTC, TheBotlyNoob commented
I'm closing this because of the large amounts of pull requests. You can make another PR later with fixes if you want.

2022-11-30 22:06 UTC, closed without merging