Register Subdomain: lknows
is-a-dev/register pull request #3144
Opened 2022-08-12 09:32 UTC by lknows

Added the domain: lknows

2022-08-13 01:01 UTC, hum-an requested changes
wheres the website? and this isn't the correct json

2022-08-13 02:13 UTC, MaskDuck requested changes

2022-08-13 03:26 UTC, lknows commented
> wheres the website? and this isn't the correct json

Is this json correct now or am I editing wrong entirely wrong directory?

2022-08-13 05:28 UTC, hum-an commented
this is good just wait for other people to approve and merge :)

2022-08-14 03:46 UTC, MaskDuck submitted a review, later dismissed

2022-08-14 03:47 UTC, MaskDuck approved these changes

2022-08-14 03:48 UTC, merged