Update koshikkumar17.json
is-a-dev/register pull request #3165
Opened 2022-08-14 08:27 UTC by KoshikKumar17

Hello @MaskDuck 
https://github.com/is-a-dev/register/pull/2864
You merged but it shows error
This:- https://telegra.ph/file/e13593a5f62145c2f92c5.jpg

2022-08-14 11:02 UTC, MaskDuck requested changes
cname shouldnt contain slash

2022-08-15 16:15 UTC, KoshikKumar17 commented
@MaskDuck done.

2022-09-30 01:37 UTC, WilliamDavidHarrison approved these changes

2022-10-03 12:26 UTC, MaskDuck approved these changes

2022-10-03 12:26 UTC, merged