Register Subdomain: microbot
is-a-dev/register pull request #3270
Opened 2022-08-25 19:52 UTC by MicroBotCodes

Added the domain: microbot

2022-09-18 08:54 UTC, MaskDuck requested changes

2022-10-11 10:11 UTC, WilliamDavidHarrison commented on domains/micro.json
> +        "CNAME": "https://website-one-bice.vercel.app/"
@MaskDuck I think you meant to say we do not support *vercel* not railway

2022-10-11 10:12 UTC, WilliamDavidHarrison requested changes

2022-10-11 10:12 UTC, WilliamDavidHarrison commented on domains/micro.json
> +        "CNAME": "https://website-one-bice.vercel.app/"
Invalid CNAME. CNAME cannot contain `https://` or `/`. Also, we don't support Vercel unfortunately :(

2022-11-16 01:14 UTC, closed without merging