Register Subdomain: lxance
is-a-dev/register pull request #3323
Opened 2022-08-30 20:14 UTC by LxaNce-Hacker

Added the domain: lxance

2022-09-27 11:58 UTC, MaskDuck requested changes

2022-09-28 19:45 UTC, LxaNce-Hacker commented
I have edit cname
Please see

On Tue, 27 Sep, 2022, 5:28 pm MaskDuck, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In domains/lxance.json
> <https://github.com/is-a-dev/register/pull/3323#discussion_r981145429>:
>
> > @@ -0,0 +1,12 @@
> +
> +    {
> +      "owner": {
> +        "username": "LxaNce-Hacker",
> +        "email": ***@***.***"
> +      },
> +
> +      "record": {
> +        "URL": "4404"
>
> please have some actual records here.
> ------------------------------
>
> In domains/lxanceee.json
> <https://github.com/is-a-dev/register/pull/3323#discussion_r981145713>:
>
> > @@ -0,0 +1,12 @@
> +
> +    {
> +      "owner": {
> +        "username": "LxaNce-Hacker",
> +        "email": ***@***.***"
> +      },
> +
> +      "record": {
> +        "CNAME": "172.16.0.3"
>
> i think you wanted an A record?
> ------------------------------
>
> In domains/lxancehacker.json
> <https://github.com/is-a-dev/register/pull/3323#discussion_r981145911>:
>
> > @@ -0,0 +1,13 @@
> +
> +    {
> +        "repo": "https://github.com/LxaNce-Hacker/LxaNce-Hacker.github.io",
> +      "owner": {
> +        "username": "LxaNce-Hacker",
> +        "email": ***@***.***"
> +      },
> +
> +      "record": {
> +        "CNAME": "lxancehacker.github.io"
>
> 404
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/3323#pullrequestreview-1121844579>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXCPV53LR7O5GSA44JIOEL3WALONVANCNFSM6AAAAAAQAXTKDM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-28 23:41 UTC, WilliamDavidHarrison approved these changes

2022-10-08 08:46 UTC, LxaNce-Hacker commented on domains/lxanceee.json
> +        "CNAME": "172.16.0.3"
yes

2022-11-28 14:37 UTC, closed without merging