Create sarfaraz.json
is-a-dev/register pull request #3330
Opened 2022-08-31 11:36 UTC by sarfarazstark

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-09-01 11:34 UTC, sarfarazstark commented
> To make our job easier, please spend time reviewing your application before submitting it.
> 
> #### Add a x between [] if you meet that requirement example `[x]`
> * [x]  You're not using Vercel or Netlify.
> * [x]  You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
>   
>   * Link to website:
> * [x]  The website is reachable.
> * [x]  The CNAME record doesn't contain any slash.
> * [x]  There's enough information in the `owner` field.
>   
>   * You should have your email presented. If you don't want to share an email, you can leave the email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
> 
> #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

I reviewed my repo and I meet your given requirement.
Kindly please merge my request
Thank You

2022-09-16 00:55 UTC, WilliamDavidHarrison commented
> I reviewed my repo and I meet your given requirement. Kindly please merge my request Thank You

Please wait, there are other PR's, not just yours.

2022-09-27 12:05 UTC, MaskDuck requested changes

2022-09-27 12:06 UTC, sarfarazstark commented on domains/sarfaraz.json
> +        "CNAME": "sarfarazstark.github.io"
I didn't understand what?

2022-09-27 12:08 UTC, sarfarazstark commented on domains/sarfaraz.json
> +        "CNAME": "sarfarazstark.github.io"
Ohhh you mean a web page 
I am working on it 
Please approve so I can share my website using this domain

2022-09-27 12:11 UTC, sarfarazstark commented on domains/sarfaraz.json
> +        "CNAME": "sarfarazstark.github.io"
Ok then 🙂

2022-11-17 14:41 UTC, closed without merging

2022-12-06 17:21 UTC, sarfarazstark commented
Hello please recheck and merge this commit 
i completed my portfolio