Register Subdomain: son
is-a-dev/register pull request #3332
Opened 2022-08-31 13:07 UTC by sonphantrung

Added the domain: son

2022-09-27 12:05 UTC, MaskDuck approved these changes

2022-09-27 12:06 UTC, MaskDuck requested changes
sorry, didn't mean to approve it :(((

2022-11-13 05:09 UTC, sonphantrung commented
Uhm, I've updated my website, is it ok now?

2022-12-11 09:06 UTC, MaskDuck approved these changes
fine, sorry for the late response

2022-12-11 09:07 UTC, merged