updated portfolio endpoint
is-a-dev/register pull request #337
Opened 2020-10-21 08:39 UTC by X3NOSIZ

2020-10-21 20:09 UTC, phenax commented
@X3NOSIZ, I'm not sure you can configure `.js.org` to work with this subdomain. You can use github pages.

2020-10-22 07:02 UTC, X3NOSIZ commented
Umm like I can't use gh pages for some personal reasons, but I guess if this works on `.js.org` then it should also work here.

2020-10-22 09:39 UTC, phenax commented
@X3NOSIZ, The problem is I'm not sure how you will configure the ssl certificate to include this subdomain. Let me know if you still want to try it out. I'll merge it in.

2020-10-23 18:24 UTC, X3NOSIZ commented
@phenax I can do one thing which might fix this issue. I can deploy my site to Vercel & this might fix the issue. I'm pasting the link over here, can you let me know if it is working or not please?

2020-10-23 18:32 UTC, X3NOSIZ commented
Here you go -> https://neilblaz3.vercel.app/

2020-10-23 19:09 UTC, phenax commented
Oooof. Bad news man. Vercel has restrictions for subdomains (#249). I think for now, you should make it a URL redirection instead of a CNAME record. You can change it later if you want.

```js
  "URL": "https://neilblaz3.vercel.app",
```

2020-10-24 07:18 UTC, X3NOSIZ commented
Let's do onething, I'm creating my new blog site, which will be ready by Nov. So let's keep `pratyay.is-a.dev` on hold. I'll be deploying the site on gh-pages soon & I'll let you know then ok?

2020-10-24 17:34 UTC, X3NOSIZ commented
Here you go -> https://neilblaze.github.io/Neoblog/

2020-10-24 18:20 UTC, phenax requested changes

2020-10-24 18:20 UTC, phenax commented on domains/pratyay.json
> +    "CNAME": "https://neilblaze.github.io/Neoblog"
```suggestion
    "CNAME": "neilblaze.github.io"
```

2020-10-24 18:21 UTC, phenax approved these changes

2020-10-24 18:22 UTC, merged