Register Subdomain: jeros
is-a-dev/register pull request #3438
Opened 2022-09-11 10:20 UTC by Ascript89

Added the domain: jeros

2022-09-12 23:23 UTC, MaskDuck requested changes

2022-09-16 00:31 UTC, WilliamDavidHarrison commented on domains/jeros.json
> +        "TXT": "yes"
@MaskDuck I think this is a spam domain.

2022-09-16 01:26 UTC, Ascript89 commented on domains/jeros.json
> +        "TXT": "yes"
No, sorry, it's just I haven't got that much time now, I'll look into it this weekend, sorry.

2022-09-23 15:56 UTC, Ascript89 commented
I already modified it, what now?

2022-09-23 22:28 UTC, WilliamDavidHarrison approved these changes

2022-10-04 10:20 UTC, MaskDuck approved these changes

2022-10-04 10:23 UTC, merged