Register Subdomain: borris
is-a-dev/register pull request #3473
Opened 2022-09-13 21:58 UTC by linkb15

Added the domain: borris

2022-09-13 23:57 UTC, WilliamDavidHarrison commented
@linkb15 An A record only has numbers, for example: `8.8.8.8`

2022-09-15 22:33 UTC, WilliamDavidHarrison commented
We don't support Netlify sorry.

2022-09-16 09:39 UTC, linkb15 commented
how about vercel?

2022-09-16 23:41 UTC, WilliamDavidHarrison commented
> how about vercel?

No. We do support Railway though.

2022-10-13 01:39 UTC, TheBotlyNoob requested changes

2022-10-13 01:39 UTC, TheBotlyNoob commented on domains/borris.json
> +        "CNAME": ["https://borris.netlify.app/"]
We don't support netlify

2022-12-03 14:37 UTC, closed without merging