MrEnder website
is-a-dev/register pull request #3486
Opened 2022-09-16 15:17 UTC by MrEnder0

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-09-18 02:13 UTC, WilliamDavidHarrison requested changes
Website can't be a coming soon page.

2022-10-13 01:43 UTC, TheBotlyNoob requested changes

2022-10-13 01:43 UTC, TheBotlyNoob commented on domains/mrender.json
> +        "CNAME": "MrEnder0.github.io"
As said above, the website cannot be a "coming soon" page. If you want to can change it to 
```suggestion
        "URL": "https://github.com/MrEnder0"
```
Which will redirect to your GitHub profile.

2022-10-14 00:29 UTC, WilliamDavidHarrison approved these changes

2022-10-17 03:21 UTC, MrEnder0 commented
Hey I don't have much experience with pull requests. Am I supposed to be doing something or just leave the rest up to you guys?

2022-10-17 03:27 UTC, WilliamDavidHarrison commented
> Hey I don't have much experience with pull requests. Am I supposed to be doing something or just leave the rest up to you guys?

Leave the rest up to us 😃

2022-12-15 14:38 UTC, closed without merging

2023-03-30 15:49 UTC, MrEnder0 reviewed
re-submit