Register Subdomain: _vercel
is-a-dev/register pull request #3539
Opened 2022-09-24 06:40 UTC by priyanshdotxyz

Added the domain: _vercel

2022-09-24 06:45 UTC, priyanshdotxyz commented
...

2022-09-24 06:46 UTC, priyanshdotxyz commented
..........................

2022-09-24 07:59 UTC, WilliamDavidHarrison requested changes
Sorry we don't support Vercel.

2022-09-29 13:53 UTC, andrewstech requested changes
Spam

2022-09-29 13:53 UTC, closed without merging