Add files via upload
is-a-dev/register pull request #3545
Opened 2022-09-25 03:44 UTC by AkumaX1

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-09-25 23:35 UTC, WilliamDavidHarrison requested changes
Please remove `<` and `>` they are not needed.

2022-09-27 02:29 UTC, WilliamDavidHarrison approved these changes

2022-09-27 03:04 UTC, AkumaX1 commented on domains/shl.json
> +    "CNAME": "go.tldr.ml"
go.tldr.ml is THE website .

2022-09-27 03:04 UTC, AkumaX1 commented on domains/shl.json
> +    "CNAME": "go.tldr.ml"
it just has passoword .

2022-09-27 03:28 UTC, WilliamDavidHarrison commented on domains/shl.json
> +    "CNAME": "go.tldr.ml"
@AkumaX1 Please provide the password, so we can check the content of your site.

2022-09-27 04:28 UTC, closed without merging