added anish.is-a.dev
is-a-dev/register pull request #3552
Opened 2022-09-25 16:34 UTC by anish-mandal

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: https://anishdeveloper.netlify.app/
- [x] The website is reachable.
- [x] The CNAME record doesn't contain any slash.
- [x] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-09-25 23:32 UTC, WilliamDavidHarrison approved these changes, later dismissed

2022-10-03 12:45 UTC, MaskDuck submitted a review, later dismissed

2022-10-04 05:30 UTC, WilliamDavidHarrison commented on domains/anish.json
> +    "CNAME": "anishdeveloper.netlify.app"
just realised that, i shouldnt have approved those changes 🤦

2022-10-06 06:11 UTC, anish-mandal commented on domains/anish.json
> +    "CNAME": "anishdeveloper.netlify.app"
oh ok I am changing that CNAME to a github page

2022-10-06 06:13 UTC, WilliamDavidHarrison requested changes
not enough content

2022-10-07 13:27 UTC, anish-mandal commented
> not enough content

I will redesign the website soon and will add some content about my projects and works.

2022-10-07 23:23 UTC, WilliamDavidHarrison commented
> > not enough content
> 
> I will redesign the website soon and will add some content about my projects and works.

We can't give you a domain until then.

2022-10-08 01:31 UTC, anish-mandal commented
> > > not enough content
> > 
> > 
> > I will redesign the website soon and will add some content about my projects and works.
> 
> We can't give you a domain until then.

Ok that's understandable I will redesign my website and will soon come back to get the domain. Thanks for your time.

2022-10-11 10:05 UTC, WilliamDavidHarrison reviewed
Awaiting website redesign

2022-11-11 08:08 UTC, anish-mandal commented
> This pull request has been marked as stale due to inactivity and will be closed. Comment anything on this PR to prevent it

Don't close it

2022-11-14 15:21 UTC, anish-mandal commented
My site is ready.

2022-11-14 21:38 UTC, WilliamDavidHarrison approved these changes

2022-12-14 09:22 UTC, anish-mandal commented
When will the pr be merged ? @WilliamDavidHarrison

2022-12-14 22:07 UTC, WilliamDavidHarrison commented
> When will the pr be merged ? @WilliamDavidHarrison

Just wait for a mainter too

2022-12-15 14:10 UTC, anish-mandal commented
> > When will the pr be merged ? @WilliamDavidHarrison
> 
> Just wait for a mainter too

Ok

2022-12-26 13:18 UTC, WilliamDavidHarrison approved these changes

2022-12-26 13:19 UTC, WilliamDavidHarrison commented
Fix checks not running

2022-12-26 13:20 UTC, WilliamDavidHarrison requested changes
Fix json

2022-12-26 13:20 UTC, WilliamDavidHarrison commented on domains/anish.json
> +    "twitter": "anishsay",
```suggestion
    "twitter": "anishsay"
```

2022-12-26 13:21 UTC, WilliamDavidHarrison approved these changes

2022-12-26 13:22 UTC, merged

2022-12-26 13:22 UTC, WilliamDavidHarrison commented
Sorry for late merge 😅

2022-12-27 19:02 UTC, anish-mandal commented
> Sorry for late merge sweat_smile

Thanks for merging