Register Subdomain: click.node
is-a-dev/register pull request #3562
Opened 2022-09-28 06:31 UTC by node0505

Added the domain: click.node

2022-09-28 23:48 UTC, WilliamDavidHarrison approved these changes, later dismissed
Nevermind, I didn't see the other commits.

2022-09-28 23:48 UTC, WilliamDavidHarrison commented on domains/click.node.json
> +        "CNAME": "cname.github.com"
Invalid CNAME

2022-09-30 01:08 UTC, WilliamDavidHarrison requested changes
404

2022-09-30 06:23 UTC, node0505 commented
It's not a 404, it's a URL forwarder. Go to /google and it should resolve

2022-09-30 07:00 UTC, WilliamDavidHarrison approved these changes, later dismissed
/google resolves. You should add a main page though.

2022-09-30 07:02 UTC, node0505 commented
Will do in the next few days 👍

2022-10-01 01:40 UTC, merged