Register Subdomain: mac
is-a-dev/register pull request #3574
Opened 2022-09-30 14:36 UTC by macthetoaster

Added the domain: mac

2022-09-30 22:58 UTC, WilliamDavidHarrison requested changes

2022-09-30 22:58 UTC, WilliamDavidHarrison commented on domains/mac.json
> +        "CNAME": "https://floofy.info"
CNAME cannot have `https://`. Change this to a url if you want it to redirect.

2022-10-04 05:31 UTC, WilliamDavidHarrison requested changes
404

2022-10-04 10:26 UTC, MaskDuck requested changes
website is inaccessible :(((

2022-11-24 14:39 UTC, closed without merging