Create aliSabry.json
is-a-dev/register pull request #3597
Opened 2022-10-03 09:14 UTC by ali-sabry

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-10-04 05:29 UTC, WilliamDavidHarrison requested changes

2022-10-04 05:29 UTC, WilliamDavidHarrison commented on domains/alisabry.json
> +    "CNAME": "alisabry.is-a.dev"
You cannot use this as your CNAME.

2022-10-04 23:02 UTC, WilliamDavidHarrison requested changes
Invalid CNAME

2022-10-06 05:54 UTC, WilliamDavidHarrison requested changes

2022-10-06 05:54 UTC, WilliamDavidHarrison commented on domains/alisabry.json
> +        "URL": "https://alisabryofficial.is-a.dev"
Invalid URL

2022-10-06 23:27 UTC, WilliamDavidHarrison requested changes
You cannot redorect to an is-a.dev subdomain.

2022-10-07 23:22 UTC, WilliamDavidHarrison approved these changes

2022-10-09 02:57 UTC, MaskDuck approved these changes

2022-10-09 02:57 UTC, merged