Add kevin.json to domains
is-a-dev/register pull request #36
Opened 2020-10-07 21:29 UTC by ikevin

2020-10-08 05:19 UTC, phenax requested changes

2020-10-08 05:19 UTC, phenax commented on domains/kevin.json
> +    "URL": "https://ikevin.is-a.dev"
The domain in the URL has to match the file name to redirect

2020-10-08 05:19 UTC, phenax commented on domains/kevin.json
> +{
There is a conflict with the subdomain you are trying to register as another `kevin.json` was just added to the repo. You will have to change the name of the file.

2021-04-13 07:21 UTC, Codeize commented
Hey! @ikevin !  Please let us know if you still would like to proceed with the domain registration process. Thanks!

2021-04-19 17:05 UTC, closed without merging