Update CNAME and Repo based on Documentation
is-a-dev/register pull request #361
Opened 2020-10-25 06:42 UTC by b-hexsoul

2020-10-25 07:01 UTC, phenax requested changes

2020-10-25 07:01 UTC, phenax commented on domains/brandon.json
> +    "CNAME": "https://b-hexsoul.github.io/portfolio/",
CNAME records cannot be a full url. It has to be a host name. I'd suggest you rename your repo to `b-hexsoul.github.io`.

You can take a look at the [github pages guide](https://guides.github.com/features/pages/).

2020-10-25 11:44 UTC, b-hexsoul reviewed
Ok!

2020-10-26 19:25 UTC, phenax approved these changes

2020-10-26 19:25 UTC, phenax commented on domains/brandon.json
> +  "repo": "https://github.com/b-hexsoul/b-hexsoul.github.io",
You don't have the repo created. If you are having any trouble with github pages you can check out [their docs](https://guides.github.com/features/pages/)

2020-10-26 19:26 UTC, merged