Create red.json
is-a-dev/register pull request #3612
Opened 2022-10-05 00:18 UTC by StandRed

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [x ] You're not using Vercel or Netlify.
- [x ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [x ] The website is reachable.
- [ x] The CNAME record doesn't contain any slash.
- [x ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-10-05 04:31 UTC, WilliamDavidHarrison requested changes

2022-10-05 04:31 UTC, WilliamDavidHarrison commented on domains/red.json
> +    "web": "standred.dev"
Invalid record type.

2022-10-05 04:31 UTC, WilliamDavidHarrison commented on domains/standred.json
> +    "CNAME": "glitch.edgeapp.net"
Please provide a website link.

2022-10-07 04:58 UTC, WilliamDavidHarrison requested changes

2022-10-07 04:58 UTC, WilliamDavidHarrison commented on domains/red.json
> +    "web": "www.standred.dev"
Please change this to `"URL": "https://www.strandred.dev"` if you want it to redirect.

2022-10-07 23:21 UTC, WilliamDavidHarrison requested changes

2022-10-07 23:21 UTC, WilliamDavidHarrison commented on domains/red.json
> +    "URL": "www.standred.dev"
Please add `https://` before www

2022-10-08 03:37 UTC, WilliamDavidHarrison submitted a review, later dismissed

2022-10-09 02:59 UTC, MaskDuck approved these changes

2022-10-09 03:00 UTC, MaskDuck requested changes
sorry, didn't mean to approve

2022-10-09 22:23 UTC, StandRed commented
@MaskDuck @WilliamDavidHarrison i changed it for email forwarding

2022-10-09 22:25 UTC, WilliamDavidHarrison submitted a review, later dismissed

2022-10-09 22:31 UTC, StandRed commented
@WilliamDavidHarrison does it work now? im confused

2022-10-09 22:32 UTC, WilliamDavidHarrison commented
> @WilliamDavidHarrison does it work now? im confused

Since it is now only email forwarding it's fine.

2022-10-09 22:32 UTC, StandRed commented
> > @WilliamDavidHarrison does it work now? im confused
> 
> Since it is now only email forwarding it's fine.

so does the email work now?

2022-10-09 22:34 UTC, WilliamDavidHarrison commented
> > > @WilliamDavidHarrison does it work now? im confused
> > 
> > 
> > Since it is now only email forwarding it's fine.
> 
> so is the email supposed to work now?

The email will work, but since you don't have a A record, there will be no website. So the domain will purely be for emails.

2022-10-09 22:38 UTC, StandRed commented
i updated it @WilliamDavidHarrison may you merge please?

2022-10-09 22:39 UTC, WilliamDavidHarrison commented
Sorry, I can't merge PR's, since I'm only a helper, you'll need to wait for a maintainer to merge it.

2022-10-09 22:40 UTC, closed without merging

2022-10-09 22:40 UTC, StandRed commented
> Sorry, I can't merge PR's, since I'm only a helper, you'll need to wait for a maintainer to merge it.

oh ok who are maintainers?

2022-10-09 22:41 UTC, StandRed commented
also it closed randomly

2022-10-09 23:51 UTC, WilliamDavidHarrison commented
> > Sorry, I can't merge PR's, since I'm only a helper, you'll need to wait for a maintainer to merge it.
> 
> oh ok who are maintainers?

Just be patient and they will eventually merge your pr.

2022-10-22 04:11 UTC, WilliamDavidHarrison commented
> also it closed randomly

Just reopen it.