Register Subdomain: YashejShah
is-a-dev/register pull request #3614
Opened 2022-10-05 04:08 UTC by YashejShah

Added the domain: YashejShah

2022-10-05 04:27 UTC, WilliamDavidHarrison requested changes

2022-10-05 04:27 UTC, WilliamDavidHarrison commented on domains/YashejShah.json
> +        "CNAME": "YashejShah.github.io"
404

2022-10-05 13:31 UTC, MaskDuck requested changes

2022-10-06 05:54 UTC, WilliamDavidHarrison requested changes

2022-10-06 05:54 UTC, WilliamDavidHarrison commented on domains/YashejShah.json
> +    "CNAME": "yashejshah.github.io/yashej.github.io/"
CNAME cannot contain `/`. Please change it to just `yashejshah.github.io`

2022-10-06 11:28 UTC, WilliamDavidHarrison requested changes

2022-10-06 11:28 UTC, WilliamDavidHarrison commented on domains/YashejShah.json
> +    "CNAME": "yashej.github.io"
This GitHub account doesn't exist

2022-10-23 00:20 UTC, closed without merging