Create CCRP.json
is-a-dev/register pull request #3644
Opened 2022-10-09 14:41 UTC by PatrickDevelopr

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-10-09 20:27 UTC, p0lygun requested changes

2022-10-09 20:27 UTC, p0lygun commented on domains/CCRP.json
> +    "CNAME": "572ca600-be84-4a76-8cf9-986690eaf03b.id.repl.co"
this CNAME is not reachable

2022-10-09 22:26 UTC, WilliamDavidHarrison approved these changes, later dismissed
CNAME is reachable.

2022-10-16 06:43 UTC, MaskDuck approved these changes

2022-10-16 06:43 UTC, merged