Register Subdomain: rlewsley
is-a-dev/register pull request #3666
Opened 2022-10-11 21:17 UTC by lewsley-r

Added the domain: rlewsley

2022-10-12 22:03 UTC, WilliamDavidHarrison requested changes

2022-10-12 22:03 UTC, WilliamDavidHarrison commented on domains/rlewsley.json
> +        "CNAME": ["https://lewsley-r.github.io"]
CNAME cannot be an array or have `https://`.

2022-10-14 00:34 UTC, WilliamDavidHarrison requested changes

2022-10-14 00:34 UTC, WilliamDavidHarrison commented on domains/rlewsley.json
> +        "name": "Ronan Lewsley",
You don't need this field.

2022-10-14 00:34 UTC, WilliamDavidHarrison commented on domains/rlewsley.json
> +        "role": "junior full stack dev"
You don't need this field.

2022-10-14 00:34 UTC, WilliamDavidHarrison commented on domains/rlewsley.json
> +        "github-link": "https://github.com/lewsley-r"
You don't need this field.

2022-10-14 15:30 UTC, lewsley-r commented on domains/rlewsley.json
> +        "name": "Ronan Lewsley",
removed.

2022-10-14 15:30 UTC, lewsley-r commented on domains/rlewsley.json
> +        "role": "junior full stack dev"
removed.

2022-10-15 04:09 UTC, WilliamDavidHarrison submitted a review, later dismissed

2022-10-16 06:54 UTC, MaskDuck approved these changes

2022-10-16 06:57 UTC, merged