Create cdn.aayush
is-a-dev/register pull request #3694
Opened 2022-10-14 09:05 UTC by OpAayush

To make our job easier, please spend time to review your application before submitting. 

#### Add a x between [] if you meet that requirement example `[x]`
- [ ] You're not using Vercel or Netlify.
- [ ] You have completed your website, there's no type of placeholder at the website. **This requirement can be raised if the domain you're registering is for emails**
  - Link to website: 
- [ ] The website is reachable.
- [ ] The CNAME record doesn't contain any slash.
- [ ] There's enough information at the `owner` field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.
 
 #### Feel free to join our discord server for more updates or any help related to the service :D - https://discord.gg/PZCGHz4RhQ

2022-10-15 03:56 UTC, WilliamDavidHarrison requested changes
Please rename your file to: `cdn.aayush.json` and add an homepage.

2022-10-16 09:55 UTC, OpAayush commented
yo accept

2022-10-16 10:00 UTC, WilliamDavidHarrison requested changes

2022-10-16 10:00 UTC, WilliamDavidHarrison commented on domains/cdn.aayush.json
> +    "CNAME": "opaayush.github.io"
Please add a homepage.

2022-10-17 09:21 UTC, OpAayush commented
Can you merge?

2022-10-18 09:51 UTC, OpAayush commented
but its actual website is aayush.is-a.dev who has a homepage for cdn bro...

2022-10-19 09:19 UTC, OpAayush commented
Kk

2022-10-19 10:44 UTC, OpAayush commented
what about now? accept?

2022-10-20 00:10 UTC, WilliamDavidHarrison approved these changes

2022-10-20 08:55 UTC, andrewstech approved these changes

2022-10-20 08:55 UTC, merged