Create rojan.json
is-a-dev/register pull request #3725
Opened 2022-10-18 12:58 UTC by RojanGamingYT

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-10-19 01:20 UTC, WilliamDavidHarrison requested changes

2022-10-19 01:20 UTC, WilliamDavidHarrison commented on domains/rojan.json
> +        "CNAME": "rojangamingyt.github.io"
404?

2022-10-23 04:14 UTC, RojanGamingYT commented
> question, since link to website is .../is-a-dev-portfolio, your website won't be accessible in https://rojan.is-a.dev but https://rojan.is-a.dev/is-a-dev-portfolio, confirm?

I want it accessible in https://rojan.is-a.dev

2022-10-29 15:02 UTC, RojanGamingYT commented
> > > question, since link to website is .../is-a-dev-portfolio, your website won't be accessible in https://rojan.is-a.dev but https://rojan.is-a.dev/is-a-dev-portfolio, confirm?
> > 
> > 
> > I want it accessible in https://rojan.is-a.dev
> 
> uuuuuuhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh then i don't think that it's possible you can try rename the repository containing ur files to rojangamingyt.github.io and then remove the part after the slash in the CNAME record

I have fixed it and its now available at https://rojangamingyt.github.io/

2022-10-29 22:55 UTC, WilliamDavidHarrison approved these changes

2022-11-13 12:14 UTC, RojanGamingYT commented
Why isnt it merged?

2022-11-23 07:32 UTC, closed without merging