Update aryamaan.json
is-a-dev/register pull request #3729
Opened 2022-10-18 17:56 UTC by HalalJadeja

added mx and txt records

### Requirements
- [✅] You're not using Vercel or Netlify.
- [✅] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [✅] The website is reachable.
- [✅] The CNAME record doesn't contain `https://` or `/`.  
- [✅] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

https://aryamaan.is-a.dev

2022-10-19 03:57 UTC, wdhdev approved these changes

2022-10-19 03:58 UTC, WilliamDavidHarrison requested changes

2022-10-19 03:58 UTC, WilliamDavidHarrison commented on domains/aryamaan.json
> +              "mx1.improvmx.com.",
Please remove the `.` at the end of the line.

2022-10-19 03:58 UTC, WilliamDavidHarrison commented on domains/aryamaan.json
> +              "mx2.improvmx.com."
Please remove the `.` at the end of the line.

2022-10-19 03:58 UTC, WilliamDavidHarrison commented on domains/notjadeja.json
> +          "TXT:" "v=spf1 include:spf.improvmx.com ~all"
Please change it to `"TXT":`

2022-10-19 03:58 UTC, WilliamDavidHarrison commented on domains/aryamaan.json
> +          "TXT:" "v=spf1 include:spf.improvmx.com ~all"
Please change it to `"TXT":`

2022-10-19 03:58 UTC, WilliamDavidHarrison commented on domains/notjadeja.json
> +              "mx1.improvmx.com.",
Please remove the `.`

2022-10-19 03:58 UTC, WilliamDavidHarrison commented on domains/notjadeja.json
> +              "mx2.improvmx.com."
Please remove the `.`

2022-10-23 03:36 UTC, MaskDuck requested changes
oops wait, seems like CNAME records can't be combined with MX records nor any other types of records, sorry :(((((

2022-10-25 11:26 UTC, HalalJadeja commented
> then how shall i add mx and txt records?

2022-10-28 03:12 UTC, hackermondev commented
@HalalJadeja You can only use MX and TXT records with A records.

2022-10-29 22:52 UTC, WilliamDavidHarrison requested changes

2022-10-29 22:52 UTC, WilliamDavidHarrison commented on domains/aryamaan.json
> +        "CNAME": "halaljadeja.github.io",
You need to use an A record here.

2022-11-07 03:05 UTC, WilliamDavidHarrison requested changes

2022-11-07 03:05 UTC, WilliamDavidHarrison commented on domains/aryamaan.json
> +        "CNAME": "halaljadeja.github.io",
Please remove the CNAME.

2022-11-07 10:56 UTC, closed without merging