Update lthon09.json
is-a-dev/register pull request #3735
Opened 2022-10-19 15:06 UTC by lthon09

2022-10-20 00:11 UTC, WilliamDavidHarrison requested changes

2022-10-20 00:11 UTC, WilliamDavidHarrison commented on domains/lthon09.json
> +    "A": ["75.2.69.226"]
404?

2022-10-20 14:58 UTC, lthon09 commented on domains/lthon09.json
> +    "A": ["75.2.69.226"]
idrk, i just got it from my hosting

2022-10-21 13:02 UTC, lthon09 commented
im pretty sure this a record is valid

2022-10-23 03:37 UTC, MaskDuck approved these changes

2022-10-23 03:37 UTC, merged