Register Subdomain: amr.elrefaiec
is-a-dev/register pull request #3746
Opened 2022-10-21 06:28 UTC by amour86

Added the domain: amr.elrefaiec

2022-10-22 00:27 UTC, WilliamDavidHarrison requested changes
404? Also, what do you intend to use on the amr subdomain?

2022-10-22 05:26 UTC, amour86 commented
I will point them to my VMs on AWS which I'm using to automate some things with the help of Automation Anywhere RPA and these VMs will create some APIs on them to play with it

2022-10-22 06:54 UTC, WilliamDavidHarrison commented
> I will point them to my VMs on AWS which I'm using to automate some things with the help of Automation Anywhere RPA and these VMs will create some APIs on them to play with it

We cannot allow you to register the amr subdomain if we don't know specifically what you're doing with them.

2022-10-28 03:10 UTC, hackermondev approved these changes

2022-10-28 03:11 UTC, merged