Create zjfc.json
is-a-dev/register pull request #3774
Opened 2022-10-24 11:25 UTC by Endermanbugzjfc

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website
https://endermanbugzjfc.github.io

2022-10-25 05:56 UTC, WilliamDavidHarrison requested changes

2022-10-25 05:56 UTC, WilliamDavidHarrison commented on domains/zjfc.json
> +        "CNAME": "endermanbugzjfc.github.io"
404?

2022-10-25 23:11 UTC, WilliamDavidHarrison submitted a review, later dismissed

2022-10-28 02:53 UTC, hackermondev approved these changes, later dismissed

2022-10-28 03:06 UTC, hackermondev approved these changes

2022-10-28 03:07 UTC, merged