Register Subdomain: fengkch
is-a-dev/register pull request #3775
Opened 2022-10-24 11:57 UTC by sohokay

Added the domain: fengkch

2022-10-25 05:57 UTC, WilliamDavidHarrison requested changes

2022-10-25 05:57 UTC, WilliamDavidHarrison commented on domains/fengkch.json
> +        "A": ["https://github.com/sohokay"]
Please change this to a `URL` record and not use an array.

Like this: `"URL": "https://github.com/sohokay"`

2022-10-25 07:27 UTC, WilliamDavidHarrison requested changes

2022-10-25 07:27 UTC, WilliamDavidHarrison commented on domains/fengkch.json
> +        "A": "https://github.com/sohokay"
Please change this to a URL record.

2022-10-28 02:54 UTC, hackermondev approved these changes

2022-10-28 03:06 UTC, merged