Register Subdomain: eliask
is-a-dev/register pull request #3812
Opened 2022-10-29 01:12 UTC by eliaskyt

Added the domain: eliask

2022-10-29 13:13 UTC, MaskDuck requested changes

2022-10-29 14:05 UTC, eliaskyt commented on domains/eliask.json
> +        "CNAME": "eliaskrueckeberg.de"
I can access :)

2022-10-30 00:54 UTC, akshayans commented on domains/eliask.json
> +        "CNAME": "eliaskrueckeberg.de"
I can, but no files are uploaded on the server it says. And, the site is not in English, so it still doesn't qualify. If your site is in a different language, add a translation.

2022-10-30 01:35 UTC, eliaskyt commented on domains/eliask.json
> +        "CNAME": "eliaskrueckeberg.de"
Yes, im working on my site and want it to release on my is-a.dev Domain :)

2022-10-30 03:31 UTC, WilliamDavidHarrison commented on domains/eliask.json
> +        "CNAME": "eliaskrueckeberg.de"
@eliaskyt Your website needs to completed before we can give you a domain.

2022-12-29 10:28 UTC, WilliamDavidHarrison commented
PR been open for over 2 months with no changes, still a default webpage.

2022-12-29 10:28 UTC, closed without merging