Register Subdomain: Megalith
is-a-dev/register pull request #3815
Opened 2022-10-29 19:51 UTC by MegalithOffical

Added the domain: Megalith

2022-10-29 22:56 UTC, WilliamDavidHarrison requested changes

2022-10-29 22:56 UTC, WilliamDavidHarrison commented on domains/Megalith.json
> +        "CNAME": "https://profile-megalithoffical.vercel.app/"
Sorry, we don't support Vercel, but you can change the record type to `URL` and have it redirect to the vercel app.

2022-10-31 20:54 UTC, MegalithOffical commented
Ok i edit it

2022-10-31 22:22 UTC, WilliamDavidHarrison requested changes
Please delete the file `megalith.is-a.dev` and change the file name of `Megalith.json` to all lower-case and change the record to a `URL`

2022-12-29 10:30 UTC, WilliamDavidHarrison approved these changes

2022-12-29 10:31 UTC, merged