Register Subdomain: max
is-a-dev/register pull request #3818
Opened 2022-10-29 23:55 UTC by ItzMaxxi

Added the domain: max

2022-10-30 03:29 UTC, WilliamDavidHarrison requested changes
Sorry, the website has to be in English.

2022-10-30 20:54 UTC, ItzMaxxi commented
I added a button to change the language. 
![image](https://user-images.githubusercontent.com/94728544/198901028-8987e8a7-2acc-4bcd-a4e4-b396e6a3cd8c.png)

2022-10-30 23:32 UTC, WilliamDavidHarrison approved these changes

2022-11-19 10:26 UTC, MaskDuck approved these changes

2022-11-19 10:27 UTC, merged