Register Subdomain: zarcabout
is-a-dev/register pull request #3820
Opened 2022-10-30 02:52 UTC by ZarcDev21

Added the domain: zarcabout

2022-10-30 03:32 UTC, WilliamDavidHarrison submitted a review, later dismissed

2022-11-05 03:14 UTC, WilliamDavidHarrison requested changes

2022-11-05 03:14 UTC, WilliamDavidHarrison commented on domains/zarcdev.json
> +        "CNAME": "zarcdev21.github.io"
I can't seem to reach this site.

2022-11-05 07:46 UTC, ZarcDev21 commented on domains/zarcdev.json
> +        "CNAME": "zarcdev21.github.io"
I already change the cname

2022-11-05 21:49 UTC, WilliamDavidHarrison approved these changes

2022-11-07 11:40 UTC, closed without merging