Create vapedevv
is-a-dev/register pull request #3837
Opened 2022-10-31 21:10 UTC by jadjasjafsafasfasfsa

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-10-31 22:14 UTC, WilliamDavidHarrison requested changes

2022-10-31 22:14 UTC, WilliamDavidHarrison commented on domains/vapedevv.json
> +        "CNAME": "jadjasjafsafasfasfsa.github.io/gkdgskgkskgksbbsdbsgsd"
Please remove the `/` and everything after it.

2022-11-02 04:08 UTC, WilliamDavidHarrison approved these changes

2022-11-26 02:27 UTC, MaskDuck approved these changes

2022-11-26 02:31 UTC, merged