Register Subdomain: maxximum
is-a-dev/register pull request #3886
Opened 2022-11-05 20:47 UTC by xMaxximum

Added the domain: maxximum

2022-11-05 21:54 UTC, WilliamDavidHarrison requested changes

2022-11-05 21:54 UTC, WilliamDavidHarrison commented on domains/maxximum.json
> +        "A": "["130.61.245.198"]"
Please remove the quotation marks around the array.

2022-11-06 00:07 UTC, WilliamDavidHarrison commented
@xMaxximum On the IP I just get the default Nginx page.

2022-11-06 10:40 UTC, xMaxximum commented
sorry @WilliamDavidHarrison I am in the process of rewriting the website so I didn't host it yet. But check again now I uploaded the current state of it.

2022-11-07 02:58 UTC, WilliamDavidHarrison approved these changes, later dismissed

2022-11-09 23:05 UTC, merged