Create jishnupsamal.json
is-a-dev/register pull request #3890
Opened 2022-11-06 06:50 UTC by jishnu-prasad-s

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website
https://jishnupsamal.ml

2022-11-07 02:58 UTC, WilliamDavidHarrison requested changes

2022-11-07 02:58 UTC, WilliamDavidHarrison commented on domains/jishnupsamal.json
> +    "TXT": "yandex-verification: 993af4b67b219d80"
Sorry, we don't support TXT verification

2022-11-08 00:10 UTC, WilliamDavidHarrison approved these changes, later dismissed

2022-11-30 22:00 UTC, TheBotlyNoob submitted a review, later dismissed

2022-11-30 22:02 UTC, TheBotlyNoob submitted a review, later dismissed

2022-11-30 22:06 UTC, TheBotlyNoob approved these changes

2022-11-30 22:07 UTC, merged