Register Subdomain: thered
is-a-dev/register pull request #3897
Opened 2022-11-06 16:42 UTC by TheRedXD

Added the domain: thered

2022-11-07 03:07 UTC, WilliamDavidHarrison requested changes

2022-11-07 03:07 UTC, WilliamDavidHarrison commented on domains/thered.json
> +        "URL": ""thered.sh""
Please remove the extra quotations.

2022-11-07 03:08 UTC, WilliamDavidHarrison commented on domains/thered.json
> +        "URL": ""thered.sh""
And add `https://` to the link.

2022-11-30 21:56 UTC, TheBotlyNoob commented
I'm closing this because of the large amounts of pull requests. You can make another PR later with fixes if you want.

2022-11-30 21:56 UTC, closed without merging