Register Subdomain: gabriel.almeida
is-a-dev/register pull request #3901
Opened 2022-11-06 20:39 UTC by gabriellukke

Added the domain: gabriel.almeida

2022-11-07 03:11 UTC, WilliamDavidHarrison requested changes
You need to register the domain `almeida.is-a.dev` before you can get a nested subdomain.

Please also refer to the review comments below.

2022-11-07 03:11 UTC, WilliamDavidHarrison commented on domains/gabriel.almeida.json
> +        "URL": ""gabriellukke.github.io""
Please remove the extra quotations and add `https://` infront of the URL.

2022-11-08 08:10 UTC, WilliamDavidHarrison requested changes

2022-11-08 08:10 UTC, WilliamDavidHarrison commented on domains/gabrielalmeida.json
> +        "URL": "https://gabriellukke.github.io"
Please create a website.

2022-11-30 22:04 UTC, TheBotlyNoob commented
I'm closing this because of the large amounts of pull requests. You can make another PR later with fixes if you want.

2022-11-30 22:04 UTC, closed without merging