Create Subdomain: mc1.notjadeja.json
is-a-dev/register pull request #3905
Opened 2022-11-07 11:00 UTC by HalalJadeja

Re-did the file with email.

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-11-08 00:12 UTC, WilliamDavidHarrison requested changes

2022-11-08 00:12 UTC, WilliamDavidHarrison commented on domains/mc1.notjadeja.json
> +  "A": "147.185.221.180"
A records need to be an array.

2022-11-11 18:35 UTC, HalalJadeja commented on domains/mc1.notjadeja.json
> +  "A": "147.185.221.180"
Done.

2022-11-12 03:59 UTC, WilliamDavidHarrison approved these changes

2022-12-10 05:56 UTC, MaskDuck approved these changes

2022-12-10 05:56 UTC, merged