Update almightynan.json
is-a-dev/register pull request #3917
Opened 2022-11-08 09:27 UTC by AlmightyNan

2022-11-08 09:32 UTC, WilliamDavidHarrison requested changes

2022-11-08 09:32 UTC, WilliamDavidHarrison commented on domains/almightynan.json
> +		"CNAME": "https://a88a0a2a-4e01-4d66-845c-db47023b86c3.id.repl.co/"
```suggestion
                "CNAME": "a88a0a2a-4e01-4d66-845c-db47023b86c3.id.repl.co"
```

2022-11-08 23:35 UTC, WilliamDavidHarrison approved these changes

2022-11-10 08:24 UTC, andrewstech approved these changes

2022-11-10 08:24 UTC, merged