Register Subdomain: didntpot
is-a-dev/register pull request #3918
Opened 2022-11-08 14:19 UTC by xDidntPot

Added the domain: didntpot

2022-11-08 23:37 UTC, WilliamDavidHarrison requested changes

2022-11-08 23:37 UTC, WilliamDavidHarrison commented on domains/didntpot.json
> +        "URL": ""https://github.com/xdidntpot""
Please remove the extra quotations.

```suggestion
        "URL": "https://github.com/xdidntpot"
```

2022-11-09 04:02 UTC, WilliamDavidHarrison approved these changes

2022-11-10 08:22 UTC, andrewstech approved these changes

2022-11-10 08:22 UTC, merged