hyperhacker.json
is-a-dev/register pull request #3919
Opened 2022-11-08 19:10 UTC by HyperGithubForm

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. This requirement is optional if you are registering a domain for emails.
- [x] The website is reachable.
- [x] The CNAME record doesn't contain https:// or /.  
- [x] There is sufficient information at the owner field.
   - You should have your email presented. If you don't want to share email, you can leave email an empty string ("") and add any other social such as Discord/Twitter/etc.

### Link to Website
https://hyperhacker.repl.co

2022-11-08 23:34 UTC, WilliamDavidHarrison approved these changes

2022-11-10 08:20 UTC, andrewstech approved these changes, later dismissed

2022-11-10 08:23 UTC, WilliamDavidHarrison requested changes

2022-11-10 08:23 UTC, WilliamDavidHarrison commented on domains/hyperhacker.json
> +    "username": "HyperGithubForm",
```suggestion
    "username": "HyperGithubForm",
    "email": "",
```

2022-11-26 02:18 UTC, MaskDuck approved these changes

2022-11-26 02:19 UTC, merged