Register Subdomain: mdbesoain
is-a-dev/register pull request #3922
Opened 2022-11-09 03:03 UTC by mdbesoain

Added the domain: mdbesoain

2022-11-09 04:01 UTC, WilliamDavidHarrison requested changes

2022-11-09 04:01 UTC, WilliamDavidHarrison commented on domains/mdbesoain.json
> +        "URL": ""mdbesoain.cl""
```suggestion
        "URL": "https://mdbesoain.cl"
```

2022-11-10 08:18 UTC, andrewstech approved these changes

2022-11-10 08:18 UTC, merged

2022-11-10 08:22 UTC, WilliamDavidHarrison commented on domains/mdbesoain.json
> +        "URL": "https://mdbesoain.cl"
Sorry, the website needs to be in English.