Register Subdomain: joabutt
is-a-dev/register pull request #3925
Opened 2022-11-09 07:13 UTC by Joabutt

Added the domain: joabutt

2022-11-09 10:15 UTC, WilliamDavidHarrison requested changes

2022-11-09 10:15 UTC, WilliamDavidHarrison commented on domains/eis.json
> +        "CNAME": ""https://e-4w8.pages.dev""
```suggestion
        "CNAME": "https://e-4w8.pages.dev"
```

2022-11-09 10:15 UTC, WilliamDavidHarrison commented on domains/joabutt.json
> +        "CNAME": ""joabuttisadev.pages.dev""
```suggestion
        "CNAME": "joabuttisadev.pages.dev"
```

2022-11-09 10:15 UTC, WilliamDavidHarrison commented on domains/atom
> +
Please rename this file to `atom.json` and add content to it.

2022-11-10 08:21 UTC, WilliamDavidHarrison requested changes

2022-11-10 08:21 UTC, WilliamDavidHarrison commented on domains/eis.json
> +        "CNAME": "https://e-4w8.pages.dev"
Please add content to your website.

2022-11-10 12:24 UTC, Joabutt commented
I have updated. eis.json is not supposed to be there.

2022-11-18 02:24 UTC, closed without merging