Created dhruvil.json
is-a-dev/register pull request #3936
Opened 2022-11-10 18:16 UTC by DhruvilMoradiya

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-11-11 00:19 UTC, WilliamDavidHarrison approved these changes

2022-11-11 00:23 UTC, WilliamDavidHarrison requested changes

2022-11-11 00:23 UTC, WilliamDavidHarrison commented on domains/dhruvil.json
> +        "email": "dhruvil1808@gmail.com",
```suggestion
        "email": "dhruvil1808@gmail.com"
```

2022-11-11 04:13 UTC, WilliamDavidHarrison approved these changes

2022-12-10 06:00 UTC, MaskDuck approved these changes

2022-12-10 06:06 UTC, merged