Create alokik.json
is-a-dev/register pull request #3947
Opened 2022-11-14 14:24 UTC by OpAayush

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

https://alokik-here.github.io/devloper-alokik

2022-11-16 14:27 UTC, OpAayush commented
Please merge 🧛🏻‍♂️

2022-11-16 23:41 UTC, WilliamDavidHarrison commented
> Please merge 🧛🏻‍♂️

Please fix the JSON

2022-11-17 14:38 UTC, OpAayush commented
What about now

2022-11-17 23:55 UTC, WilliamDavidHarrison requested changes

2022-11-17 23:55 UTC, WilliamDavidHarrison commented on domains/alokik.json
> +        "username": "alokik-here",
Sorry, you can't register domains in other peoples names.

2022-11-17 23:55 UTC, WilliamDavidHarrison commented on domains/alokik.json
> +        "CNAME": "alokik-here.github.io"
404 and also please see the review comment above.

2022-11-17 23:55 UTC, WilliamDavidHarrison commented on domains/alokik.json
> +                "repo": "https://github.com/alokik-here/devloper-alokik
Fixed

2022-11-19 06:09 UTC, OpAayush commented
Bro he is my brother :/

2022-11-20 01:48 UTC, WilliamDavidHarrison requested changes

2022-11-20 01:48 UTC, WilliamDavidHarrison commented on domains/alokik.json
> +        "CNAME": "alokik-here.github.io"
404?

2022-11-20 07:46 UTC, OpAayush commented
The website is https://alokik-here.github.io/devloper-alokik

2022-11-21 09:26 UTC, OpAayush commented
??

2022-12-29 10:48 UTC, WilliamDavidHarrison approved these changes

2022-12-29 10:48 UTC, merged