prettier
is-a-dev/register pull request #3959
Opened 2022-11-16 01:47 UTC by WilliamDavidHarrison

2022-11-16 02:36 UTC, WilliamDavidHarrison commented
@phenax What do you think?

(I spent like an hour doing this since prettier was being stupid lol)

2022-11-23 03:50 UTC, TheBotlyNoob requested changes, later dismissed
Quoting @phenax (https://github.com/is-a-dev/register/pull/2664#pullrequestreview-1048149693):
> We can add prettier just for the script files but let's leave the json files alone. Ideally, the subdomain json files must only have commit logs authored by the owner. I used to run a simple formatter in the initial stages of the project but stopped because of this reason.

2022-11-23 03:51 UTC, WilliamDavidHarrison commented
It doesn't include JSON files

2022-11-23 03:51 UTC, TheBotlyNoob commented
ah, I didn't see the file diff, sorry.

2022-11-23 03:51 UTC, TheBotlyNoob approved these changes, later dismissed

2022-11-23 03:51 UTC, WilliamDavidHarrison commented
> ah, I didn't see the file diff, sorry.

Np

2022-11-23 03:52 UTC, WilliamDavidHarrison commented
Oh, we need Phenax to review as well

2022-11-23 03:52 UTC, TheBotlyNoob commented
yeah...

2022-11-23 03:53 UTC, WilliamDavidHarrison commented
@phenax

2022-11-23 03:53 UTC, WilliamDavidHarrison commented
It's because I was modifying script files, I think.

2022-11-23 06:11 UTC, phenax requested changes
Please add a `format` command in package.json scripts so that we have one consistent method for formatting

2022-11-23 06:11 UTC, phenax commented on scripts/certbot.sh
> -#!/usr/bin/env bash
Shebang needs to be here

2022-11-23 07:50 UTC, WilliamDavidHarrison commented
> Please add a `format` command in package.json scripts so that we have one consistent method for formatting

I was using prettier online, not a desktop version. Also, prettier isn't installed in `package.json`.

2022-12-27 17:42 UTC, phenax requested changes
This and there's a merge conflict in README

2022-12-27 17:42 UTC, phenax commented on scripts/verify-record.sh
> -#!/usr/bin/env sh
Needs the shbang

2023-01-01 02:08 UTC, closed without merging