New registration
is-a-dev/register pull request #3982
Opened 2022-11-18 05:31 UTC by AnujMutha

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-11-18 05:48 UTC, WilliamDavidHarrison requested changes

2022-11-18 05:48 UTC, WilliamDavidHarrison commented on domains/anuj.json
> +    "CNAME": "anujmutha.github.io/Portfolio/"
Please remove the `/Portfolio/` part of the record.
```suggestion
    "CNAME": "anujmutha.github.io"
```

2022-11-18 05:59 UTC, WilliamDavidHarrison approved these changes

2022-12-11 04:34 UTC, MaskDuck approved these changes

2022-12-11 04:35 UTC, merged