For getting is-a.dev domain for portfolio website
is-a-dev/register pull request #3993
Opened 2022-11-19 07:40 UTC by ajachintya

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-11-20 01:51 UTC, WilliamDavidHarrison approved these changes

2022-11-20 01:57 UTC, WilliamDavidHarrison requested changes
Didn't mean to approve

2022-11-20 01:57 UTC, WilliamDavidHarrison commented on domains/achintya.json
> +    "URL": "portfolio-app-production.up.railway.app"
```suggestion
    "URL": "https://portfolio-app-production.up.railway.app"
```

2022-11-20 04:04 UTC, ajachintya reviewed
added "https://" in the url

2022-11-20 05:51 UTC, WilliamDavidHarrison submitted a review, later dismissed

2022-11-22 06:59 UTC, ajachintya commented
How long can it take to get approved by a maintainer?

2022-11-23 00:21 UTC, WilliamDavidHarrison commented
> How long can it take to get approved by a maintainer?

Hopefully not too long.

@andrewstech

2022-12-01 03:33 UTC, ajachintya commented
Could it be possible to speed up the review process? Thank you in advance :)

2022-12-01 05:30 UTC, WilliamDavidHarrison commented
> Could it be possible to speed up the review process? Thank you in advance :)

Sorry that is not possible.

2022-12-11 09:01 UTC, MaskDuck approved these changes

2022-12-11 09:05 UTC, merged