Added hlodansmssmmsVia is-a-dev-cli
is-a-dev/register pull request #4043
Opened 2022-11-25 13:57 UTC by Affumii

Added hlodansmssmmsvia the CLI

2022-11-26 03:06 UTC, WilliamDavidHarrison requested changes

2022-11-26 03:06 UTC, WilliamDavidHarrison commented on domains/hlodansmssmms.json
> +        "A": ["38.242.243.93"]
I can't reach this IP address.

2022-12-24 09:47 UTC, MaskDuck requested changes

2022-12-29 11:17 UTC, WilliamDavidHarrison requested changes
Please add a website on your server

2023-01-01 11:40 UTC, WilliamDavidHarrison commented
No website + email.

2023-01-01 11:40 UTC, closed without merging