Register Subdomain: worm
is-a-dev/register pull request #4052
Opened 2022-11-27 03:39 UTC by kornls

Added the domain: worm

2022-11-27 04:15 UTC, WilliamDavidHarrison requested changes
Also I can't reach the website.

2022-11-27 04:15 UTC, WilliamDavidHarrison commented on domains/worm.json
> +        "CNAME": "https://arq091.github.io/worm"
```suggestion
        "CNAME": "arq091.github.io"
```

2022-11-27 05:47 UTC, kornls commented on domains/worm.json
> +        "CNAME": "https://arq091.github.io/worm"
Ah sorry, incorrect link.

2022-11-27 06:02 UTC, WilliamDavidHarrison requested changes

2022-11-27 06:02 UTC, WilliamDavidHarrison commented on domains/worm.json
> +        "CNAME": "arq091.github.io/wiggly-worm"
```suggestion
        "CNAME": "arq091.github.io"
```

The wriggly worm website will still show up even when the `CNAME` doesn't have the URL.

2022-11-27 06:18 UTC, kornls commented
Changes have been done accordingly.

2022-11-27 06:39 UTC, WilliamDavidHarrison approved these changes

2022-12-24 09:50 UTC, MaskDuck approved these changes

2022-12-24 09:50 UTC, merged