Register Subdomain: thepatik
is-a-dev/register pull request #4056
Opened 2022-11-27 11:54 UTC by patik123

Added the domain: thepatik

2022-11-28 00:47 UTC, WilliamDavidHarrison requested changes
I can't seem to reach your website

2022-11-29 06:00 UTC, patik123 commented
I update my CNAME record.

2022-11-29 06:06 UTC, WilliamDavidHarrison approved these changes

2022-12-24 09:51 UTC, MaskDuck approved these changes

2022-12-24 09:58 UTC, merged