Register Subdomain: cyan
is-a-dev/register pull request #4068
Opened 2022-11-28 15:41 UTC by ArslanDoesDev

Added the domain: cyan

2022-11-28 23:01 UTC, WilliamDavidHarrison requested changes
I can't reach your website

2022-11-30 11:23 UTC, ArslanDoesDev commented
I couldn't specify one, this PR was created via register.is-a.dev. Will apply changes as soon as possible.

2022-11-30 11:48 UTC, ArslanDoesDev commented
Changes made, site is now reachable.

2022-11-30 22:18 UTC, WilliamDavidHarrison approved these changes

2022-12-10 06:10 UTC, closed without merging