Register Subdomain: pekly
is-a-dev/register pull request #4101
Opened 2022-12-03 20:20 UTC by Pekly

Added the domain: pekly

2022-12-05 01:27 UTC, WilliamDavidHarrison requested changes

2022-12-05 01:27 UTC, WilliamDavidHarrison commented on domains/pekly.json
> +        "URL": "dsc.gg/pekly"
```suggestion
        "URL": "https://dsc.gg/pekly"
```

2022-12-06 00:34 UTC, wdhdev approved these changes

2022-12-24 10:15 UTC, MaskDuck approved these changes

2022-12-24 10:18 UTC, merged