Register Subdomain: gstudiosx
is-a-dev/register pull request #4142
Opened 2022-12-08 05:34 UTC by GStudiosX2

Added the domain: gstudiosx

2022-12-08 05:45 UTC, GStudiosX2 commented
is it URL or CNAME ?

2022-12-08 05:51 UTC, WilliamDavidHarrison requested changes

2022-12-08 05:51 UTC, WilliamDavidHarrison commented on domains/gstudiosx.json
> +        "CNAME": "https://discord.gg/dV2M2HsH3F"
```suggestion
        "URL": "https://discord.gg/dV2M2HsH3F"
```

2022-12-08 05:55 UTC, WilliamDavidHarrison approved these changes

2022-12-09 11:52 UTC, MaskDuck approved these changes

2022-12-09 11:56 UTC, merged