For new subdomain registration
is-a-dev/register pull request #4149
Opened 2022-12-08 18:32 UTC by vyshuks

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-12-08 23:29 UTC, WilliamDavidHarrison requested changes

2022-12-08 23:29 UTC, WilliamDavidHarrison commented on domains/vysakh.json
> +        "twitter": ""
```suggestion
```

2022-12-08 23:29 UTC, WilliamDavidHarrison commented on domains/vysakh.json
> +        "email": "vyshuks@gmail.com",
```suggestion
        "email": "vyshuks@gmail.com"
```

2022-12-09 03:01 UTC, vyshuks reviewed
update suggestion changes

2022-12-09 03:12 UTC, WilliamDavidHarrison approved these changes

2022-12-09 11:48 UTC, MaskDuck approved these changes

2022-12-09 11:55 UTC, merged