Added zuntieVia is-a-dev-cli
is-a-dev/register pull request #4156
Opened 2022-12-09 17:38 UTC by Zuntie

Added zuntievia the CLI

2022-12-09 22:53 UTC, WilliamDavidHarrison requested changes

2022-12-09 22:53 UTC, WilliamDavidHarrison commented on domains/zuntie.json
> +        "CNAME": "https://zuntie.github.io/portfolio/"
```suggestion
        "CNAME": "zuntie.github.io"
```

2022-12-09 23:18 UTC, WilliamDavidHarrison requested changes
404

2022-12-09 23:32 UTC, Zuntie commented
> 404
Fixed 👍

2022-12-10 02:44 UTC, WilliamDavidHarrison approved these changes

2022-12-14 18:50 UTC, andrewstech approved these changes

2022-12-14 18:50 UTC, merged