Create tejas-luthra.json
is-a-dev/register pull request #4158
Opened 2022-12-09 19:31 UTC by tejas-luthra

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-12-09 22:53 UTC, WilliamDavidHarrison approved these changes

2022-12-10 22:49 UTC, tejas-luthra commented
Am I missing something?

2022-12-10 23:41 UTC, WilliamDavidHarrison commented
> Am I missing something?

Just wait for a maintainer to merge the pr

2022-12-15 01:13 UTC, tejas-luthra commented
I checked the format of the file and I did not see any errors. Can someone tell me what I missed anything? Any help will be appreciated.

2022-12-15 03:28 UTC, WilliamDavidHarrison requested changes

2022-12-15 03:28 UTC, WilliamDavidHarrison commented on domains/tejas-luthra.json
> +        "email": "tejasluthra3008@gmail.com",
```suggestion
        "email": "tejasluthra3008@gmail.com"
```

Found the issue

2022-12-15 03:28 UTC, WilliamDavidHarrison commented
> I checked the format of the file and I did not see any errors. Can someone tell me what I missed anything? Any help will be appreciated.

https://github.com/is-a-dev/register/pull/4158#pullrequestreview-1218537267

2022-12-16 22:56 UTC, WilliamDavidHarrison approved these changes

2022-12-25 01:50 UTC, MaskDuck approved these changes

2022-12-25 02:06 UTC, merged