Create TheHackerDude1083.json
is-a-dev/register pull request #4161
Opened 2022-12-10 02:28 UTC by TheHackerDude1083

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-12-10 02:43 UTC, WilliamDavidHarrison requested changes

2022-12-10 02:43 UTC, WilliamDavidHarrison commented on domains/TheHackerDude1083.json
> +        "twitter": "<n/a>"
```suggestion
```

2022-12-10 02:43 UTC, WilliamDavidHarrison commented on domains/TheHackerDude1083.json
> +        "email": "shaheeransari57@gmail.com",
```suggestion
        "email": "shaheeransari57@gmail.com"
```

2022-12-11 00:43 UTC, TheHackerDude1083 commented
Fixed

2022-12-11 03:36 UTC, WilliamDavidHarrison requested changes
404

2022-12-11 16:39 UTC, TheHackerDude1083 commented
What do I need to fix?

2022-12-12 01:04 UTC, WilliamDavidHarrison commented
> What do I need to fix?

Can you provide a link yo your website?

2022-12-12 03:14 UTC, TheHackerDude1083 commented
https://thehackerdude1083.github.io/My-Website/

2022-12-12 04:56 UTC, WilliamDavidHarrison submitted a review, later dismissed

2022-12-12 20:15 UTC, TheHackerDude1083 commented
When I add a custom domain it says "Your site's DNS settings are using a custom subdomain, thehackerdude1083.is-a.dev, that is set up as an A record. We recommend you change this to a CNAME record pointing to thehackerdude1083.github.io. " How do I fix this?

2022-12-12 23:27 UTC, WilliamDavidHarrison commented
> When I add a custom domain it says "Your site's DNS settings are using a custom subdomain, thehackerdude1083.is-a.dev, that is set up as an A record. We recommend you change this to a CNAME record pointing to thehackerdude1083.github.io. " How do I fix this?

It says that as your changes haven't been merged yet.  Just wait for this PR to be merged and the message should go away

2022-12-14 18:46 UTC, andrewstech approved these changes

2022-12-14 18:46 UTC, merged