Update aditya.json
is-a-dev/register pull request #4174
Opened 2022-12-11 14:43 UTC by adityaasyadav

changed my github username, so changing records :)

2022-12-12 01:00 UTC, WilliamDavidHarrison requested changes
404

2022-12-13 13:03 UTC, adityaasyadav commented
domain is activ, just wanna change cname records!

2022-12-14 00:39 UTC, WilliamDavidHarrison approved these changes

2022-12-14 18:26 UTC, andrewstech approved these changes

2022-12-14 18:26 UTC, merged