Register Subdomain: yuphie
is-a-dev/register pull request #4179
Opened 2022-12-12 07:51 UTC by yuphiedev

Added the domain: yuphie

2022-12-12 23:40 UTC, WilliamDavidHarrison requested changes

2022-12-12 23:40 UTC, WilliamDavidHarrison commented on domains/yuphie.json
> +        "URL": "yuphie.vercel.app"
```suggestion
        "URL": "https://yuphie.vercel.app"
```

2022-12-12 23:40 UTC, WilliamDavidHarrison commented on domains/yuphiee.json
> +        "URL": "yuphie.vercel.app"
```suggestion
        "URL": "https://yuphie.vercel.app"
```

2022-12-25 01:53 UTC, MaskDuck approved these changes

2022-12-25 02:06 UTC, merged