Register Subdomain: vion
is-a-dev/register pull request #4195
Opened 2022-12-15 13:31 UTC by VIONYT

Added the domain: vion

2022-12-15 22:13 UTC, WilliamDavidHarrison requested changes

2022-12-15 22:13 UTC, WilliamDavidHarrison commented on domains/vion.json
> +        "URL": "vion.moe"
```suggestion
        "URL": "https://vion.moe"
```

2022-12-16 06:07 UTC, WilliamDavidHarrison approved these changes

2022-12-25 01:57 UTC, MaskDuck submitted a review, later dismissed

2022-12-29 11:57 UTC, WilliamDavidHarrison approved these changes
NAS type website I believe

2022-12-29 11:57 UTC, merged