Add PenguinMod
is-a-dev/register pull request #4205
Opened 2022-12-17 03:35 UTC by FreshPenguin112

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

https://penguinmod.github.io/penguinmod-gui/editor.html
Just a cool Scratch mod

2022-12-17 07:15 UTC, WilliamDavidHarrison requested changes
404

2022-12-17 14:18 UTC, FreshPenguin112 reviewed
👍
That change is fine

2022-12-17 22:34 UTC, WilliamDavidHarrison commented
> 👍 That change is fine

Why are you reviewing your own PR?

2022-12-17 22:35 UTC, WilliamDavidHarrison requested changes
404

2022-12-17 22:35 UTC, WilliamDavidHarrison commented on domains/penguinmod.json
> +   "URL": "penguinmod.github.io/penguinmod-gui/editor.html"
```suggestion
   "URL": "https://penguinmod.github.io/penguinmod-gui/editor.html"
```

2022-12-17 22:52 UTC, WilliamDavidHarrison requested changes
I cant reach your website

2022-12-17 23:08 UTC, FreshPenguin112 commented
Fixed
Forgot some capitalization lol

2022-12-18 00:00 UTC, WilliamDavidHarrison requested changes
Still a 404

2022-12-18 00:04 UTC, FreshPenguin112 commented
fixed forgot capital M lmao

2022-12-18 01:10 UTC, WilliamDavidHarrison approved these changes

2022-12-25 02:02 UTC, MaskDuck approved these changes
scratch clone? :eyes:

2022-12-25 02:06 UTC, merged