Added cattoVia is-a-dev-cli
is-a-dev/register pull request #4213
Opened 2022-12-18 10:00 UTC by HF1016

Added cattovia the CLI

2022-12-18 11:28 UTC, WilliamDavidHarrison requested changes
502

2022-12-25 02:05 UTC, MaskDuck submitted a review, later dismissed

2023-01-07 10:02 UTC, WilliamDavidHarrison commented
@HF1016 please provide an email and website.

2023-01-07 13:22 UTC, HF1016 commented
Email: harrowfung1016@gmail.com
For website, the server I provided will handle the requests.

2023-01-07 23:02 UTC, WilliamDavidHarrison approved these changes

2023-01-07 23:03 UTC, merged