Register Subdomain: bachwumpus
is-a-dev/register pull request #4219
Opened 2022-12-19 12:14 UTC by BachLe2000

Added the domain: bachwumpus

2022-12-19 12:40 UTC, WilliamDavidHarrison requested changes

2022-12-19 12:40 UTC, WilliamDavidHarrison commented on domains/bachwumpus.json
> +        "CNAME": "https://web.frawgnu.tk"
```suggestion
        "CNAME": "web.frawgnu.tk"
```

2022-12-19 23:15 UTC, WilliamDavidHarrison approved these changes

2022-12-23 11:29 UTC, BachLe2000 commented
Sorry but when will this domain get approve?

2022-12-23 12:39 UTC, WilliamDavidHarrison commented
> Sorry but when will this domain get approve?

Most of the maintainers are on leave

2022-12-25 02:17 UTC, MaskDuck approved these changes

2022-12-25 02:18 UTC, merged