Arsdorint.GitHub.io
is-a-dev/register pull request #4242
Opened 2022-12-22 01:50 UTC by arsdorintbp2003

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-12-22 03:51 UTC, WilliamDavidHarrison requested changes

2022-12-22 03:51 UTC, WilliamDavidHarrison commented on domains/arsdorint.json
> +        "URL": "https://github.com/arsdorintbp2003",
```suggestion
```

2022-12-22 04:13 UTC, WilliamDavidHarrison requested changes
404

2022-12-22 04:20 UTC, arsdorintbp2003 commented
I have followed the instruction in this link, https://www.is-a.dev/docs/github_pages/, but when I paste the arsdorint.is-a.dev into the custom domain it is as follow:
![image](https://user-images.githubusercontent.com/88639992/209054795-26b61ed5-34c4-4471-9c6d-0db39892aa2a.png)

2022-12-22 04:32 UTC, WilliamDavidHarrison commented
> I have followed the instruction in this link, https://www.is-a.dev/docs/github_pages/, but when I paste the arsdorint.is-a.dev into the custom domain it is as follow:
> ![image](https://user-images.githubusercontent.com/88639992/209054795-26b61ed5-34c4-4471-9c6d-0db39892aa2a.png)

Please wait for this PR to be merged

2022-12-22 04:35 UTC, arsdorintbp2003 commented
Oh you mean this? And who would review those things? 
![image](https://user-images.githubusercontent.com/88639992/209056940-11da088d-595a-42eb-843c-02a02653b788.png)

2022-12-22 04:35 UTC, WilliamDavidHarrison commented
> Oh you mean this? And who would review those things?
> ![image](https://user-images.githubusercontent.com/88639992/209056940-11da088d-595a-42eb-843c-02a02653b788.png)

A maintainer

2022-12-22 04:37 UTC, arsdorintbp2003 commented
So normally how long does it takes?

2022-12-22 04:56 UTC, WilliamDavidHarrison commented
> So normally how long does it takes?

it can take a few days

2022-12-26 12:57 UTC, WilliamDavidHarrison requested changes
I can't reach your website

2022-12-26 12:57 UTC, MaskDuck submitted a review, later dismissed

2022-12-28 03:26 UTC, arsdorintbp2003 commented
I have resolve the conflict by changing the content in arsdorintbp2003:arsdorint.github.io

2022-12-28 04:38 UTC, WilliamDavidHarrison requested changes
Please update your username and verify the records.

Also, where is your website located?

2022-12-28 06:52 UTC, WilliamDavidHarrison commented
Newer PR: #4290

2022-12-28 06:52 UTC, closed without merging