Register Subdomain: gavinferdinandchee.github.io
is-a-dev/register pull request #4244
Opened 2022-12-22 08:22 UTC by GavinFerdinandChee

Added the domain: gavinferdinandchee.github.io

2022-12-23 06:42 UTC, WilliamDavidHarrison requested changes
Please delete [this file](https://github.com/GavinFerdinandChee/register/blob/main/domains/gavinferdinandchee.github.io.json)

2022-12-23 07:04 UTC, GavinFerdinandChee commented
> Please delete [this file](https://github.com/GavinFerdinandChee/register/blob/main/domains/gavinferdinandchee.github.io.json)

its done, thanks btw

2022-12-23 10:24 UTC, WilliamDavidHarrison approved these changes

2022-12-26 12:59 UTC, WilliamDavidHarrison requested changes
Resolves failing checks

2022-12-26 12:59 UTC, WilliamDavidHarrison commented on domains/gavin.json
> +    "email_personal": "gavin.ferdinand@proton.me",
```suggestion
    "email": "gavin.ferdinand@proton.me",
```

2022-12-26 13:00 UTC, WilliamDavidHarrison approved these changes

2022-12-26 13:00 UTC, merged