Register Subdomain: reizy
is-a-dev/register pull request #4254
Opened 2022-12-23 22:32 UTC by P0rc0D10

Added the domain: reizy

2022-12-24 00:08 UTC, WilliamDavidHarrison requested changes, later dismissed

2022-12-24 00:08 UTC, WilliamDavidHarrison commented on domains/reizy.json
> +        "URL": "reizy.eu"
```suggestion
        "URL": "https://reizy.eu"
```

2022-12-24 00:08 UTC, WilliamDavidHarrison commented on domains/thispc.json
> +
Delete this file

2022-12-26 12:55 UTC, MaskDuck approved these changes

2022-12-26 12:55 UTC, WilliamDavidHarrison approved these changes

2022-12-26 12:55 UTC, merged