Register Subdomain: tarun
is-a-dev/register pull request #4266
Opened 2022-12-26 08:56 UTC by Tarun2468

Added the domain: tarun

2022-12-26 12:42 UTC, WilliamDavidHarrison requested changes

2022-12-26 12:42 UTC, WilliamDavidHarrison commented on domains/tarun.json
> +        "URL": "0"
Please specify a valid URL.

2022-12-27 13:28 UTC, MaskDuck requested changes

2022-12-29 11:31 UTC, WilliamDavidHarrison commented
Invalid URL after 2 comments.

2022-12-29 11:31 UTC, closed without merging