Create Pancakes.is-a.dev.json
is-a-dev/register pull request #4286
Opened 2022-12-27 22:39 UTC by pancak3boy

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

https://k.pancakeboy.repl.co

2022-12-27 23:02 UTC, WilliamDavidHarrison requested changes
Please read the [docs](https://www.is-a.dev/docs) and update your file with the valid format.

2022-12-28 11:33 UTC, pancak3boy commented
![image](https://user-images.githubusercontent.com/82325516/209805857-14401304-f926-4fcc-b7e9-f0dbbda5d5de.png)

2022-12-28 11:41 UTC, WilliamDavidHarrison commented
> ![image](https://user-images.githubusercontent.com/82325516/209805857-14401304-f926-4fcc-b7e9-f0dbbda5d5de.png)

Oh uh, I'll just do it for you.

2022-12-28 11:45 UTC, WilliamDavidHarrison requested changes

2022-12-28 11:45 UTC, WilliamDavidHarrison commented on domains/pancakes.json
> +        "email": ""
Can you put your email here

2022-12-29 17:01 UTC, pancak3boy commented on domains/pancakes.json
> +        "email": ""
done sorry for late reply

2022-12-29 23:42 UTC, WilliamDavidHarrison requested changes
Sorry, you need to finish your website before I can merge :(

2023-01-04 15:57 UTC, pancak3boy commented
will that do now? (I made a site)

2023-01-04 22:34 UTC, WilliamDavidHarrison requested changes
Sorry you need to finish your website

2023-01-05 17:46 UTC, pancak3boy commented
I did tho? what else do I need to do now

2023-01-06 00:21 UTC, WilliamDavidHarrison commented
> I did tho? what else do I need to do now

The website can't be under development it needs to be finished.

2023-01-08 19:51 UTC, pancak3boy commented
I DID THO

2023-01-08 22:57 UTC, WilliamDavidHarrison commented
> I DID THO
![Screenshot_20230109_065615_Chrome](https://user-images.githubusercontent.com/87287585/211223252-d24cf5a0-be11-443e-a215-e0babe6b7ab4.jpg)

2023-01-15 19:51 UTC, pancak3boy commented
I hate my life.... REPLIT DIDNT PUBLISH MY UPDATE FOR SOME REASON but it should be fixed now

2023-01-15 23:48 UTC, WilliamDavidHarrison approved these changes

2023-01-15 23:50 UTC, merged