Update repo link
is-a-dev/register pull request #4290
Opened 2022-12-28 06:36 UTC by arsdorintbp2003

### Requirements
- [x] You're not using Vercel or Netlify.
- [x] You have completed your website, there's no type of placeholder at the website. *This requirement is optional if you are registering a domain for emails.*
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.
   - *You should have your email presented. If you don't want to share email, you can leave email an empty string (`""`) and add any other social such as Discord/Twitter/etc.*

### Link to Website

2022-12-28 06:46 UTC, WilliamDavidHarrison requested changes

2022-12-28 06:46 UTC, WilliamDavidHarrison commented on domains/arsdorint.json
> +      "description": Arsdorint
```suggestion
      "description": "Arsdorint"
```

2022-12-28 06:46 UTC, WilliamDavidHarrison commented on domains/arsdorint.json
> +        "CNAME": "arsdorint.gitHub.io"
```suggestion
        "CNAME": "arsdorintbp2003.github.io"
```

2022-12-28 06:46 UTC, WilliamDavidHarrison commented on domains/arsdorint.json
> +      "description": Arsdorint
```suggestion
      "description": "Arsdorint"
```

2022-12-28 06:49 UTC, WilliamDavidHarrison requested changes
I can't reach your website

2022-12-28 06:58 UTC, arsdorintbp2003 commented
Oh sorry, I forgot, my repo is private, have changed to public already

2022-12-28 08:57 UTC, WilliamDavidHarrison commented
> Oh sorry, I forgot, my repo is private, have changed to public already

Uhh, you don't have any files?

2022-12-29 11:27 UTC, WilliamDavidHarrison requested changes
404

2023-01-04 02:26 UTC, arsdorintbp2003 commented
I have updated files in my repo:
![image](https://user-images.githubusercontent.com/88639992/210473260-8cd8c3c3-4c84-44ee-b2b2-0a67127c072d.png)

2023-01-04 03:26 UTC, WilliamDavidHarrison requested changes
I still can't seem to access it.

2023-01-04 06:09 UTC, arsdorintbp2003 commented
This repo: https://github.com/arsdorintbp2003/arsodrintbp2003.github.io

2023-01-04 06:20 UTC, WilliamDavidHarrison commented
> This repo: https://github.com/arsdorintbp2003/arsodrintbp2003.github.io

There is a typo in the repo name that's why. You need to change the repo name to `arsdorintbp2003.github.io`.

2023-02-10 02:57 UTC, closed without merging