Create closed-pr.yml
is-a-dev/register pull request #4350
Opened 2023-01-02 02:25 UTC by WilliamDavidHarrison

This will send a message when a PR is closed on various conditions.

2023-01-02 02:26 UTC, TerraPlayz commented
Being worked by Me and William

2023-01-02 02:44 UTC, WilliamDavidHarrison commented
**This PR isn't for merged PRs!**

2023-01-02 03:46 UTC, MaskDuck submitted a review, later dismissed
can the file be in MD form?

2023-01-02 03:55 UTC, WilliamDavidHarrison commented
> can the file be in MD form?

Yes, I think so. I'll try.

2023-01-02 05:09 UTC, WilliamDavidHarrison commented
Opened Preview: https://william.pics/qTjn4LKl/direct
Closed Preview: https://william.pics/Yw3skacT/direct
Merged Preview: https://william.pics/N0Y5xPpj/direct

2023-01-02 05:12 UTC, TerraPlayz commented
👍👍👍

2023-01-02 06:30 UTC, MaskDuck requested changes
note that the main reason for closing PR is for no change implemented over a long time, not for such reason like that

2023-01-02 06:31 UTC, WilliamDavidHarrison commented on .github/comments/opened.md
> +<a href="https://www.buymeacoffee.com/phenax" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/default-orange.png" alt="Buy Me a Coffee" height="28" width="119"></a> <a href="https://li
Because it helps the service

2023-01-02 06:32 UTC, WilliamDavidHarrison commented on .github/comments/closed.md
> +Your pull request was most likely closed for one of the following reasons:
If stale bot closes it this sends as well. Also, I think 45 days is way too long.

2023-01-02 06:34 UTC, WilliamDavidHarrison commented on .github/comments/opened.md
> +<a href="https://www.buymeacoffee.com/phenax" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/default-orange.png" alt="Buy Me a Coffee" height="28" width="119"></a> <a href="https://li
It's only 2 buttons and it's not like a dedicated section either.

2023-01-02 06:35 UTC, MaskDuck submitted a review, later dismissed

2023-01-02 06:37 UTC, WilliamDavidHarrison commented on .github/workflows/pr.yml
> +name: "PR"
All of the other workflows use them, so format.

2023-01-02 06:38 UTC, WilliamDavidHarrison commented on .github/workflows/pr.yml
> +    branches: ["main", "master"]
Not sure. I'll remove it.
```suggestion
    branches: ["main"]
```

2023-01-02 06:38 UTC, WilliamDavidHarrison commented on .github/comments/closed.md
> +Your pull request was most likely closed for one of the following reasons:
?

2023-01-02 06:43 UTC, WilliamDavidHarrison commented on .github/workflows/pr.yml
> +name: "PR"
Nevermind, I thought they did.
```suggestion
name: PR
```

2023-01-03 06:46 UTC, TerraPlayz commented
@WilliamDavidHarrison can you please dismiss mask's requested changes?

2023-01-03 07:00 UTC, TerraPlayz commented
## Here are the previews!!
<details>
<summary>Opened PR Preview</summary>
<p><img src="https://user-images.githubusercontent.com/87287585/210196747-b7851d87-e083-4d7a-9c3a-1fb64f0c7cce.png" alt="image"></p>
</details>

---

<details>
<summary>Merged PR Preview</summary>
<p><img src="https://user-images.githubusercontent.com/87287585/210196763-5c1ae4ac-57ca-44ca-827a-35311808b64b.png" alt="image"></p>
</details>

---

<details>
<summary>Closed PR Preview</summary>
<p><img src="https://user-images.githubusercontent.com/87287585/210196757-51130ad9-a608-4d30-975a-de4abb4f1082.png" alt="image"></p>
</details>

2023-01-03 08:14 UTC, WilliamDavidHarrison commented
> @WilliamDavidHarrison can you please dismiss mask's requested changes?

Done

2023-01-06 12:02 UTC, WilliamDavidHarrison commented on .github/workflows/bot.yml
It used to be the bit that sent the messages. But now it just sends a notification to an API.

2023-02-10 02:26 UTC, WilliamDavidHarrison commented
@TerraPlayz @MaskDuck Closing this as Andrew has implemented in the notify api.

2023-02-10 02:26 UTC, closed without merging