Register Subdomain: midlaj
is-a-dev/register pull request #4351
Opened 2023-01-02 07:00 UTC by whoismidlaj

Added the domain: midlaj

2023-01-02 07:08 UTC, TerraPlayz requested changes
Your website cannot have Lorem Ispum or any type of place holders

2023-01-02 07:10 UTC, WilliamDavidHarrison requested changes
Your website cannot contain any placeholders.

2023-01-02 18:28 UTC, whoismidlaj commented
can you pls review now. i just updated my site. and removed lorem ipsum now. sorry to request without reading terms properly.

2023-01-03 05:41 UTC, WilliamDavidHarrison approved these changes

2023-01-03 05:42 UTC, merged