Added analogsombraVia is-a-dev-cli
is-a-dev/register pull request #4392
Opened 2023-01-04 07:18 UTC by analog-sombra

Added analogsombravia the CLI

2023-01-04 08:23 UTC, WilliamDavidHarrison requested changes
404 and please provide an email.

2023-01-04 08:37 UTC, analog-sombra commented
@WilliamDavidHarrison  email address is added, please kindly check it again sir.

2023-01-04 10:47 UTC, WilliamDavidHarrison requested changes
I can't reach your website

2023-01-04 11:06 UTC, analog-sombra commented
@WilliamDavidHarrison  https://analog-sombra.github.io/MyPortfolio

2023-01-04 11:14 UTC, TerraPlayz approved these changes, later dismissed
👍👍

2023-01-04 11:18 UTC, WilliamDavidHarrison requested changes

2023-01-04 11:18 UTC, WilliamDavidHarrison commented on domains/analogsombra.json
> +        "CNAME": "analogsombra.dev"
I can't reach this address though. If you want to use GitHub Pages please change this to `analog-sombra.github.io`.
```suggestion
        "CNAME": "analog-sombra.github.io"
```

2023-02-17 08:02 UTC, WilliamDavidHarrison approved these changes

2023-02-17 08:02 UTC, merged