Register subdomain: bnyro
is-a-dev/register pull request #4506
Opened 2023-01-12 16:07 UTC by Bnyro

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] You have completed your website. 
- [X] The website is reachable.  
- [X] You're not using Vercel or Netlify.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.  

## Website Link/Preview

<https://bnyro.github.io>

Thanks in advance!

2023-01-13 00:17 UTC, WilliamDavidHarrison requested changes
I can't reach your website

2023-01-13 12:16 UTC, Bnyro commented
Sorry for the inconvenience, the CNAME I used before had some issues, I removed it and now it should be accessible!

2023-01-14 02:43 UTC, WilliamDavidHarrison approved these changes, later dismissed

2023-01-14 02:44 UTC, WilliamDavidHarrison approved these changes

2023-01-14 02:45 UTC, merged

2023-01-14 07:01 UTC, Bnyro commented
Thanks!