Register Subdomain: quydang
is-a-dev/register pull request #4531
Opened 2023-01-14 15:51 UTC by quydang04

Added the domain: quydang

2023-01-14 15:52 UTC, quydang04 commented
Thanks you very much

2023-01-14 23:21 UTC, WilliamDavidHarrison requested changes
If you want to use GitHub Pages, commit the suggestion below.

2023-01-14 23:21 UTC, WilliamDavidHarrison commented on domains/quydang.json
> +        "CNAME": "github.io"
```suggestion
        "CNAME": "quydang04.github.io"
```

2023-01-15 00:52 UTC, quydang04 commented
> If you want to use GitHub Pages, commit the suggestion below.

I have just updated, please check for me. Thank you very much.

2023-01-15 01:13 UTC, WilliamDavidHarrison requested changes
Sorry you need to create a website

2023-01-15 02:09 UTC, quydang04 reviewed
Yes, i have fixed this. Check for me again, please.

2023-01-15 05:14 UTC, WilliamDavidHarrison approved these changes

2023-01-15 05:15 UTC, merged