Register Subdomain shiv
is-a-dev/register pull request #4742
Opened 2023-02-08 14:40 UTC by shivasharanappaBiradar

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-02-08 23:31 UTC, WilliamDavidHarrison requested changes
Please use a valid record

2023-02-09 08:52 UTC, shivasharanappaBiradar commented
I have done the changes.

2023-02-09 08:55 UTC, WilliamDavidHarrison requested changes
I can't reach your website

2023-02-09 22:36 UTC, WilliamDavidHarrison approved these changes

2023-02-09 22:37 UTC, merged