Register arch.is-a.dev
is-a-dev/register pull request #4748
Opened 2023-02-09 19:14 UTC by Arch881010

Added `arch` via the registration website.

2023-02-09 22:39 UTC, WilliamDavidHarrison requested changes
Please use a valid record.

2023-02-11 00:20 UTC, WilliamDavidHarrison requested changes
Please finish your website

2023-03-02 16:00 UTC, Arch881010 commented
Website has been worked on. If it still is deemed incomplete, please let me know. [Quick Link].(https://arch881010.github.io/Arch881010/)

2023-03-03 03:06 UTC, WilliamDavidHarrison approved these changes

2023-03-03 03:06 UTC, merged