Added ohcrazy via is-a-dev-cli
is-a-dev/register pull request #5091
Opened 2023-03-17 16:17 UTC by mrcrazii

Added ohcrazy via the CLI

2023-03-17 22:24 UTC, WilliamDavidHarrison requested changes
Please finish your website.

2023-03-18 10:23 UTC, mrcrazii commented
Done.

2023-03-18 23:37 UTC, WilliamDavidHarrison requested changes
Please use a valid email.

2023-03-19 01:23 UTC, WilliamDavidHarrison approved these changes

2023-03-19 01:25 UTC, merged