Create pixyshare.json
is-a-dev/register pull request #5095
Opened 2023-03-18 05:59 UTC by emmu123

All done

Requesting SSL secure

2023-03-18 23:36 UTC, WilliamDavidHarrison requested changes
What is this website used for?

2023-03-19 12:36 UTC, emmu123 commented
> What is this website used for?

used for ordering codes

2023-03-19 12:55 UTC, emmu123 commented
This website not abuse because this site not using any login or register method. This site asking some Data if can give only they need to use.
Data means not high value data's
Only Asking Discord user name, tag and user id.

2023-03-19 22:39 UTC, WilliamDavidHarrison approved these changes

2023-03-19 22:40 UTC, merged