Add files via upload
is-a-dev/register pull request #5257
Opened 2023-04-10 17:48 UTC by andrealicheri

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

https://windfarms.github.io/index.html

2023-04-12 06:39 UTC, WilliamDavidHarrison requested changes

2023-04-12 06:39 UTC, WilliamDavidHarrison commented on domains/windfarms.json
> +        "twitter": "i don't have twitter"
```suggestion
```

2023-04-12 06:39 UTC, WilliamDavidHarrison commented on domains/windfarms.json
> +        "email": "windfarms@andrealicheri.anonaddy.com",
```suggestion
        "email": "windfarms@andrealicheri.anonaddy.com"
```

2023-04-12 12:48 UTC, andrealicheri commented
I removed the useless twitter field

2023-04-13 09:13 UTC, WilliamDavidHarrison approved these changes

2023-04-13 09:14 UTC, merged