Register daflixy.is-a.dev
is-a-dev/register pull request #5277
Opened 2023-04-13 17:15 UTC by daflixy

Added `daflixy.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

2023-04-13 23:14 UTC, WilliamDavidHarrison requested changes
Please add more content to your website(s).

2023-04-22 10:04 UTC, daflixy commented
done

2023-04-22 10:56 UTC, WilliamDavidHarrison commented
You can't have a coming soon page, you need a complete website.

2023-04-27 23:36 UTC, WilliamDavidHarrison approved these changes

2023-04-28 00:27 UTC, merged