Create talinsharma.json
is-a-dev/register pull request #5548
Opened 2023-05-04 19:08 UTC by TalinTheDev

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [X] You're not using Vercel or Netlify.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-05-06 09:45 UTC, WilliamDavidHarrison requested changes
I can't reach your website

2023-05-10 19:13 UTC, TalinTheDev commented
Yes, I opened a post about it and you said that's okay as long as I get it done which I will start soon.
![image](https://github.com/is-a-dev/register/assets/97065122/691531c7-d076-42d0-ae5f-1617f5099dd3)

2023-05-11 01:14 UTC, WilliamDavidHarrison approved these changes

2023-05-11 01:14 UTC, merged

2023-05-11 01:14 UTC, WilliamDavidHarrison commented
Sorry, I forgot about that.