Register mudrika.is-a.dev
is-a-dev/register pull request #5625
Opened 2023-05-16 17:54 UTC by aktgram

Added `mudrika.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

2023-05-17 00:16 UTC, WilliamDavidHarrison requested changes
Please use a valid record.

2023-05-17 08:27 UTC, WilliamDavidHarrison approved these changes

2023-05-17 08:28 UTC, merged

2023-10-03 10:11 UTC, aktgram commented
Hey my domain now shows certificate expired

2023-10-03 10:16 UTC, aktgram commented
My issue is similar to #3602 @WilliamDavidHarrison please guide me how to get it back