Add files via upload
is-a-dev/register pull request #5733
Opened 2023-05-30 10:01 UTC by linuxforall3

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-05-30 10:10 UTC, VaibhavSys requested changes
The website has nothing but a placeholder. Please add some content to your website before submitting a PR.
![image](https://github.com/is-a-dev/register/assets/76240678/00c08c32-1669-4374-83d3-3ce54b1aef6b)

2023-05-30 10:22 UTC, linuxforall3 reviewed
Thanks for the reply. Content has been added. Please review. 
![o](https://github.com/is-a-dev/register/assets/135006946/7b5ae1b3-5d6a-4d32-b6a6-8b079bbcc85e)

2023-05-31 08:58 UTC, WilliamDavidHarrison approved these changes

2023-05-31 09:00 UTC, merged

2023-10-03 07:23 UTC, linuxforall3 commented
Hey @WilliamDavidHarrison @VaibhavSys @tonetheman @frozzare, my site does not seem to be working. And also, I had few questions on what basis the name (prefix before .is-dev.to) will be assigned. 

{
    "description": "Linux For All",
    "repo": "https://github.com/linuxforall3/linuxforall3.github.io",
    "owner": {
        "username": "linux",
        "email": "linuxforall32@proton.me"
    },
    "record": {
        "CNAME": "linuxforall3.github.io"
    }
}

This is what I submitted. I thought either the name would be assigned `linuxforall.is-a.dev` (based on description) or `linux.is-a.dev`(this is what I preferred, that's in username), or at least `linuxforall3.is-a.dev`(GitHub address). None of them are working. I have tried and tested changing my CNAME with all three. Could you please give me more insights on how we can rectify this?