Register collin.is-a.dev
is-a-dev/register pull request #5822
Opened 2023-06-07 17:05 UTC by Hanyaku-Chan

Added `collin.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

2023-06-07 23:24 UTC, WilliamDavidHarrison commented on domains/sunshine.json
> +        "A": ["192.168.0.101"]
You cannot use a private IP address.

2023-06-07 23:25 UTC, WilliamDavidHarrison requested changes

2023-06-07 23:25 UTC, WilliamDavidHarrison commented on domains/sunshine.json
> +        "A": ["192.168.0.101"]
You cannot use a private IP address.

2023-06-07 23:36 UTC, Hanyaku-Chan commented on domains/sunshine.json
> +        "A": ["192.168.0.101"]
My bad

2023-06-08 07:18 UTC, WilliamDavidHarrison approved these changes

2023-06-08 07:19 UTC, merged