Register cdn.zerow.is-a.dev
is-a-dev/register pull request #5830
Opened 2023-06-08 17:59 UTC by DevZerow

Added `cdn.zerow.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

2023-06-08 22:56 UTC, WilliamDavidHarrison approved these changes

2023-06-08 22:56 UTC, WilliamDavidHarrison commented
Please note: I removed the www.zerow.json file since we do not allow domains starting with `www`.

2023-06-08 22:58 UTC, WilliamDavidHarrison requested changes

2023-06-08 22:58 UTC, WilliamDavidHarrison commented on domains/_spf.google.com.zerow.json
> +        "TXT": "v=spf1 include:_spf.google.com ~all"
The file name of this file is invalid.

2023-06-10 01:01 UTC, WilliamDavidHarrison requested changes

2023-06-10 01:01 UTC, WilliamDavidHarrison commented on domains/default._domainkey.zerow.json
> +        "TXT": "v=dkim1; p=migfma0gcsqgsib3dqebaquaa4gnadcbiqkbgqdcjg/af7z9z137q+wammo7swvqsegrqtewzqbv9xmtr80i18edp4jpb37ljxlrv2hkfinmqvbs5l8smi80lmz2flm78nmmgw/vnjqytsepjocoisafpanqbqgmtr1kjtexzjtp
We don't support `._domainkey` subdomains.

2023-06-10 01:01 UTC, WilliamDavidHarrison commented on domains/57fvjjcng24i.zerow.json
> +        "CNAME": "gv-zsnibvk6cnv5er.dv.googlehosted.com"
We don't support domain verification.

2023-06-10 07:02 UTC, DevZerow commented
Good now ?

2023-06-10 07:58 UTC, WilliamDavidHarrison approved these changes
I've removed `_dmarc` and `_domainkey` since we don't support them.

2023-06-10 07:58 UTC, merged