Create gamerzam.json
is-a-dev/register pull request #6030
Opened 2023-06-30 19:02 UTC by GamerTheDev

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-07-02 07:47 UTC, WilliamDavidHarrison requested changes
I can't reach your site.

2023-07-06 07:47 UTC, GamerTheDev commented
wait uhm i will send new link i never got a notification of ur mail my bad

On Thu, Jul 6, 2023 at 1:01 PM William Harrison ***@***.***>
wrote:

> Closed #6030 <https://github.com/is-a-dev/register/pull/6030>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/6030#event-9740405585>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXPS2XWNWZCLVH4WINAZFZLXOZSUTANCNFSM6AAAAAAZ2GP5FI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-06 13:46 UTC, GamerTheDev commented
lividevergreenengineers-2.bitohofo.repl.co here is the new link repl just
goes down sometimes

On Thu, Jul 6, 2023 at 1:17 PM Gamers_Streak ***@***.***>
wrote:

> wait uhm i will send new link i never got a notification of ur mail my bad
>
> On Thu, Jul 6, 2023 at 1:01 PM William Harrison ***@***.***>
> wrote:
>
>> Closed #6030 <https://github.com/is-a-dev/register/pull/6030>.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/is-a-dev/register/pull/6030#event-9740405585>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AXPS2XWNWZCLVH4WINAZFZLXOZSUTANCNFSM6AAAAAAZ2GP5FI>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2023-07-06 22:59 UTC, WilliamDavidHarrison submitted a review, later dismissed

2023-07-06 22:59 UTC, WilliamDavidHarrison approved these changes

2023-07-06 23:00 UTC, merged