BETA: Register gigwanoob.is-a.dev
is-a-dev/register pull request #6091
Opened 2023-07-06 17:48 UTC by gigwanoobstudios

Added `gigwanoob.is-a.dev` using the Discord bot.

2023-07-07 01:50 UTC, WilliamDavidHarrison requested changes
Please use a valid record.

2023-07-07 05:38 UTC, gigwanoobstudios commented
Duplicate of #

2023-07-07 05:38 UTC, gigwanoobstudios commented
@WilliamDavidHarrison fixed

2023-07-08 06:37 UTC, WilliamDavidHarrison approved these changes

2023-07-08 06:40 UTC, merged