Register yassine.is-a.dev
is-a-dev/register pull request #6105
Opened 2023-07-07 22:56 UTC by yassine20011

Added `yassine.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

2023-07-08 07:36 UTC, WilliamDavidHarrison requested changes
I can't reach your website.

2023-07-08 13:52 UTC, yassine20011 commented
> I can't reach your website.

I change it to https://amjad.pages.dev/

2023-07-08 13:57 UTC, yassine20011 reviewed
update yassine.json

2023-07-09 02:14 UTC, WilliamDavidHarrison approved these changes

2023-07-09 02:20 UTC, merged