clau.json
is-a-dev/register pull request #622
Opened 2021-03-15 19:55 UTC by iClaudette

2021-03-22 12:59 UTC, phenax requested changes

2021-03-22 12:59 UTC, phenax commented on domains/clau.json
> +    "CNAME": "claudette.github.io"
This is an invalid cname. Seems like there is a mismatch between your username and the name of the repo.
```suggestion
    "CNAME": "iClaudette.github.io"
```

I'd also reccommend renaming your repo to `iClaudette.github.io` but it'll work either way.

2021-03-22 13:09 UTC, phenax commented
You have 2 pr's open for the same subdomain. Can you keep the one you want and close the other? #622 and #632

2021-04-30 06:42 UTC, Codeize commented
Hi @iClaudette . Are you still wanting to continue with this subdomain? Thanks

2021-05-01 20:00 UTC, TheBotlyNoob commented
Closing because of inactivity

2021-05-01 20:00 UTC, closed without merging