BETA: Register duyeric.is-a.dev
is-a-dev/register pull request #6229
Opened 2023-07-17 00:34 UTC by duyeric

Added `duyeric.is-a.dev` using the site.

2023-07-18 06:07 UTC, WilliamDavidHarrison requested changes
Please use a valid record.

2023-07-23 06:17 UTC, WilliamDavidHarrison requested changes

2023-07-23 06:17 UTC, WilliamDavidHarrison commented on domains/duyeric.json
> +            "CNAME": "www"
Please use a valid record.

2023-07-23 10:07 UTC, duyeric commented on domains/duyeric.json
> +            "CNAME": "www"
"A": 172.245.139.131

2023-07-23 10:23 UTC, duyeric commented
"A": 172.245.139.131
Thanks

Vào CN, 23 thg 7, 2023 vào lúc 13:17 William Harrison <
***@***.***> đã viết:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In domains/duyeric.json
> <https://github.com/is-a-dev/register/pull/6229#discussion_r1271388422>:
>
> > @@ -0,0 +1,10 @@
> +{
> +        "owner": {
> +           "username": "duyeric",
> +           "email": ***@***.***"
> +        },
> +        "record": {
> +            "CNAME": "www"
>
> Please use a valid record.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/6229#pullrequestreview-1542190972>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2GLLIBUY4PBI5KLQNTAWM3XRS6ZBANCNFSM6AAAAAA2MILE2E>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-26 10:01 UTC, WilliamDavidHarrison approved these changes

2023-07-26 10:03 UTC, merged