BETA: Register shuawe.is-a.dev
is-a-dev/register pull request #6812
Opened 2023-08-06 08:14 UTC by shuawe

Added `shuawe.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-08-06 08:22 UTC, WilliamDavidHarrison requested changes
Please use a valid record. We also don't support Vercel.

2023-08-07 11:33 UTC, WilliamDavidHarrison requested changes
I cannot reach your website.

2023-08-07 11:55 UTC, shuawe commented
> I cannot reach your website.

Done, check now

2023-08-08 08:54 UTC, WilliamDavidHarrison approved these changes

2023-08-08 08:55 UTC, merged