Create _github-pages-challenge-rubinskiy.bob
is-a-dev/register pull request #6823
Opened 2023-08-06 10:51 UTC by Rubinskiy

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

![image](https://github.com/is-a-dev/register/assets/62457878/ab47c2d1-0c42-41aa-8019-5b5f0217bc66)

2023-08-06 16:03 UTC, vj-abishek requested changes
@Rubinskiy add `.json` file extension
```diff
+ domains/_github-pages-challenge-rubinskiy.bob.json

2023-08-07 04:49 UTC, vj-abishek requested changes

2023-08-07 04:49 UTC, vj-abishek commented on domains/_github-pages-challenge-rubinskiy.bob.json
> +        "discord": "rubinskiy#5258"
![Screenshot_2023-08-07-10-17-22-80](https://github.com/is-a-dev/register/assets/43115551/e017795f-4a33-4dba-994c-29f3c6ac10c4)

There is a validation issue. U need to have a valid username and a email.

2023-08-10 00:59 UTC, WilliamDavidHarrison approved these changes

2023-08-10 01:00 UTC, merged