BETA: Register vaibhv.is-a.dev
is-a-dev/register pull request #7002
Opened 2023-08-11 06:53 UTC by vaibhavharsoda

Added `vaibhv.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-08-12 03:57 UTC, WilliamDavidHarrison requested changes
Please use a valid record.

2023-08-13 09:11 UTC, vaibhavharsoda commented
Add valid record

2023-08-14 00:16 UTC, WilliamDavidHarrison requested changes

2023-08-14 00:16 UTC, WilliamDavidHarrison commented on domains/Vaibhv.json
> +{
Please delete this file

2023-08-18 06:50 UTC, WilliamDavidHarrison approved these changes

2023-08-18 06:52 UTC, merged