BETA: Register o.is-a.dev
is-a-dev/register pull request #7094
Opened 2023-08-14 08:34 UTC by lxntagram

Added `o.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-08-16 15:36 UTC, andrewstech requested changes
Sorry we are unable to reach your site can you verify that you have provided the correct IP for your `mydog` domain

2023-08-18 06:53 UTC, WilliamDavidHarrison requested changes

2023-08-18 06:53 UTC, WilliamDavidHarrison commented on domains/o.json
> +        "URL": "dicord.xyz"
Please provide a valid URL

2023-08-18 06:53 UTC, WilliamDavidHarrison commented on domains/o.json
Your file name needs to be 2 characters or longer.

2023-08-25 00:10 UTC, closed without merging