Didier is-a-dev request
is-a-dev/register pull request #712
Opened 2021-04-18 19:49 UTC by didiermunezero

2021-04-18 19:51 UTC, hackermondev requested changes
the json is wrong. please remove the comma after the email that you added.

2021-04-18 20:02 UTC, hackermondev approved these changes, later dismissed

2021-04-18 21:34 UTC, TheBotlyNoob submitted a review, later dismissed
👍

2021-04-19 01:06 UTC, mtgsquad commented
Seems Good!

2021-04-19 10:08 UTC, closed without merging