BETA: Update shept.is-a.dev
is-a-dev/register pull request #7311
Opened 2023-08-24 04:11 UTC by mcshept

Updated `shept.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-08-24 05:00 UTC, WilliamDavidHarrison requested changes

2023-08-24 05:00 UTC, WilliamDavidHarrison commented on domains/shept.json
> +        "CNAME": "mcshept.github.io",
You need to use GitHub Pages A records instead of a CNAME.

2023-08-24 10:06 UTC, mcshept commented
Is my website going to be available now as well?

2023-08-25 03:49 UTC, WilliamDavidHarrison approved these changes

2023-08-25 03:50 UTC, merged

2023-08-25 03:50 UTC, WilliamDavidHarrison commented
> Is my website going to be available now as well?

Yes.