BETA: Register magdi.is-a.dev
is-a-dev/register pull request #7408
Opened 2023-08-27 18:07 UTC by coeur85

Added `magdi.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-08-28 02:51 UTC, WilliamDavidHarrison requested changes

2023-08-28 02:51 UTC, WilliamDavidHarrison commented on domains/d.json
Your file name must be 2 characters or longer.

2023-08-28 07:44 UTC, coeur85 commented on domains/d.json
done

2023-08-30 00:31 UTC, WilliamDavidHarrison approved these changes

2023-08-30 00:32 UTC, merged