BETA: Register amanthakur.is-a.dev
is-a-dev/register pull request #7537
Opened 2023-09-01 08:59 UTC by aman7thakurr

Added `amanthakur.is-a.dev` using the Discord bot.

2023-09-02 01:11 UTC, WilliamDavidHarrison requested changes

2023-09-02 01:11 UTC, WilliamDavidHarrison commented on domains/amanthakur.json
> +        "CNAME": "aman7thakurr"
Please use a valid record.

2023-09-02 01:11 UTC, WilliamDavidHarrison commented on domains/aman.json
Please add records to this domain.

2023-09-02 14:58 UTC, aman7thakurr commented on domains/amanthakur.json
CNAME Updated

2023-09-02 15:05 UTC, aman7thakurr commented
please review record added

2023-09-07 10:05 UTC, WilliamDavidHarrison approved these changes

2023-09-07 10:05 UTC, WilliamDavidHarrison commented on domains/aman_thakur.json
We do not allow underscores in subdomain names.

2023-09-07 10:07 UTC, merged