BETA: Register gpchn.is-a.dev
is-a-dev/register pull request #7544
Opened 2023-09-01 16:19 UTC by gpchn

Added `gpchn.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-02 00:59 UTC, WilliamDavidHarrison requested changes
We don't support Vercel or TXT verification.

2023-09-02 14:13 UTC, gpchn commented
Change to Cloudflare Pages now.

2023-09-03 09:34 UTC, gpchn commented
Excuse me, is there any problem with my file? If there is, I'll correct it.

2023-09-07 10:13 UTC, WilliamDavidHarrison approved these changes

2023-09-07 10:13 UTC, merged