Create neealdon3.json
is-a-dev/register pull request #7549
Opened 2023-09-02 01:04 UTC by neealdon3

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-09-02 01:06 UTC, neealdon3 reviewed
good

2023-09-02 07:04 UTC, Lukas-Batema requested changes

2023-09-02 07:04 UTC, Lukas-Batema commented on domains/neealdon3.json
Where is the stuff for the domain?

2023-09-02 07:18 UTC, WilliamDavidHarrison requested changes
Please refer to @Lukas-Batema's review.

2023-09-07 10:10 UTC, WilliamDavidHarrison submitted a review, later dismissed
I cannot reach your website.

2023-09-07 23:55 UTC, neealdon3 commented
> I cannot reach your website.

dang nab it the url is eternal-network.github.io/public

2023-09-10 15:06 UTC, DEV-DIBSTER approved these changes

2023-09-10 15:08 UTC, merged

2023-09-10 17:05 UTC, neealdon3 commented
it doesn't work