delete unwanted domains that i don't need rn & update information
is-a-dev/register pull request #7567
Opened 2023-09-02 10:23 UTC by dedomil

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-09-05 09:38 UTC, WilliamDavidHarrison requested changes
You don't own any of these domains, so you cannot modify them.

2023-09-05 12:22 UTC, dedomil commented
that @adityaasyadav account is me myself only!

2023-09-05 23:08 UTC, WilliamDavidHarrison commented
You will need to comment on this PR with that account to confirm that.

2023-09-06 04:44 UTC, adityaasyadav commented
hey @dedomil & @adityaasyadav both accounts are mine!

On Wed, 6 Sep, 2023, 04:39 William Harrison, ***@***.***>
wrote:

> You will need to comment on this PR with that account to confirm that.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/7567#issuecomment-1707423952>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVPOP32UAHKD34WFUYVCGITXY6WJBANCNFSM6AAAAAA4IQE26M>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-07 15:36 UTC, dedomil commented
please look into it, i commented from my alt account

2023-09-07 22:55 UTC, WilliamDavidHarrison approved these changes

2023-09-07 22:58 UTC, WilliamDavidHarrison requested changes

2023-09-07 22:58 UTC, WilliamDavidHarrison commented on domains/l.aditya.json
Each part of your subdomain name must be 2 characters or more.

2023-09-09 05:54 UTC, WilliamDavidHarrison approved these changes

2023-09-09 05:55 UTC, merged