BETA: Register saurabh-kirve.is-a.dev
is-a-dev/register pull request #7669
Opened 2023-09-07 13:53 UTC by BerzCode

Added `saurabh-kirve.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-10 13:14 UTC, DEV-DIBSTER requested changes, later dismissed

2023-09-10 13:14 UTC, DEV-DIBSTER commented on domains/saurabh-kirve.json
> +        "CNAME": "berzcode.github.io"
404 site. Please have something displayed.

2023-09-10 14:24 UTC, DEV-DIBSTER commented
You didn't change anything, I have nothing to review... @BerzCode

2023-09-11 08:46 UTC, WilliamDavidHarrison approved these changes

2023-09-11 08:47 UTC, merged