Create alanitd.json
is-a-dev/register pull request #771
Opened 2021-05-09 13:00 UTC by AlanCh4n

2021-05-09 16:12 UTC, TheBotlyNoob approved these changes, later dismissed

2021-05-09 20:10 UTC, hackermondev requested changes
You need to read the docs https://github.com/is-a-dev/register/tree/main/docs

2021-05-14 02:25 UTC, TheBotlyNoob commented
Would You Like To Proceed With The Domain?

2021-05-16 18:54 UTC, TheBotlyNoob commented
closed because of inactivity

2021-05-16 18:54 UTC, closed without merging