BETA: Register firedemon.is-a.dev
is-a-dev/register pull request #7713
Opened 2023-09-09 06:26 UTC by ShadowPlayzYT22

Added `firedemon.is-a.dev` using the Discord bot.

2023-09-09 10:02 UTC, WilliamDavidHarrison requested changes

2023-09-09 10:02 UTC, WilliamDavidHarrison commented on domains/firedemon.json
> +        "CNAME": "demon-briefly.github.io"
I cannot reach this website, are you sure the CNAME is correct?

2023-09-09 10:11 UTC, ShadowPlayzYT22 commented
yeah, im pretty sure thats the correct Cname

On Sat, 9 Sep 2023, 6:02 pm William Harrison ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In domains/firedemon.json
> <https://github.com/is-a-dev/register/pull/7713#discussion_r1320530410>:
>
> > @@ -0,0 +1,11 @@
> +{
> +    "owner": {
> +       "username": "ShadowPlayzYT22",
> +       "email": ***@***.***",
> +       "discord": "1038747272701292584"
> +    },
> +
> +    "record": {
> +        "CNAME": "demon-briefly.github.io"
>
> I cannot reach this website, are you sure the CNAME is correct?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/7713#pullrequestreview-1618608181>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2LWBO5VQMLZNCCBCTVYPJTXZQ5DPANCNFSM6AAAAAA4RHXBEY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-11 08:42 UTC, WilliamDavidHarrison commented
Well, I can't reach your website.

2023-09-11 08:42 UTC, WilliamDavidHarrison approved these changes

2023-09-11 08:44 UTC, merged