BETA: Register e.is-a.dev
is-a-dev/register pull request #7823
Opened 2023-09-14 01:20 UTC by Peaqcy

Added `e.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-14 04:50 UTC, WilliamDavidHarrison approved these changes

2023-09-14 04:51 UTC, WilliamDavidHarrison requested changes

2023-09-14 04:51 UTC, WilliamDavidHarrison commented on domains/e.json
Subdomain names must be 2 characters or longer.

2023-09-15 12:38 UTC, DEV-DIBSTER submitted a review, later dismissed

2023-09-16 16:56 UTC, VaibhavSys commented
Why do you need 31 domains? That looks like reserving domains.
Reopen the PR or open a new one if this is actually for a legit reason.

2023-09-16 16:56 UTC, closed without merging