BETA: Register web3.is-a.dev
is-a-dev/register pull request #7835
Opened 2023-09-14 16:07 UTC by kramiikk

Added `web3.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-15 12:28 UTC, DEV-DIBSTER submitted a review, later dismissed

2023-09-18 02:24 UTC, WilliamDavidHarrison requested changes

2023-09-18 02:24 UTC, WilliamDavidHarrison commented on domains/sex.json
We cannot allow you to register this domain as it violates our guidelines.

2023-09-18 02:24 UTC, WilliamDavidHarrison commented on domains/web3.json
We also cannot allow this due to abuse risks.

2023-09-18 02:24 UTC, closed without merging