Create _discord.mohamad.json
is-a-dev/register pull request #7861
Opened 2023-09-15 18:20 UTC by mjnaous

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-09-15 19:22 UTC, DEV-DIBSTER approved these changes

2023-09-15 19:22 UTC, DEV-DIBSTER requested changes, later dismissed

2023-09-15 19:22 UTC, DEV-DIBSTER commented on domains/_discord.mohamad.json
For some reason the file name is not valid.

2023-09-18 02:17 UTC, WilliamDavidHarrison approved these changes
I have removed the `_discord.mohamad.json` file as we do not support Discord verification yet. I have opened the issue #7933 for this. You can also verify via HTTPS if you would like to connect your domain to Discord in the mean time.

2023-09-18 02:17 UTC, merged