BETA: Register rakibahmed.is-a.dev
is-a-dev/register pull request #7916
Opened 2023-09-17 14:36 UTC by rafsaaanrakib

Added `rakibahmed.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-17 14:44 UTC, rafsaaanrakib commented
I just signed up for the beta registration at rakibahmed.is-a.dev. Can't wait to see what amazing projects or features are in store. Rakib, your work always delivers, and I'm eager to be a part of this journey. Let's beta-test the future together! 🚀💻 #BetaRegistration #Innovation"

2023-09-17 15:39 UTC, DEV-DIBSTER requested changes, later dismissed

2023-09-17 15:39 UTC, DEV-DIBSTER commented on domains/rakibahmed.json
> +        "CNAME": "rakibahmed"
Invalid CNAME record.

2023-09-17 16:06 UTC, rafsaaanrakib commented
how can i change the record?

On Sun, Sep 17, 2023 at 9:39 PM DIBSTER ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In domains/rakibahmed.json
> <https://github.com/is-a-dev/register/pull/7916#discussion_r1328108994>:
>
> > @@ -0,0 +1,9 @@
> +{
> +    "owner": {
> +        "username": "rafsaaanrakib",
> +        "email": ***@***.***"
> +    },
> +    "record": {
> +        "CNAME": "rakibahmed"
>
> Invalid CNAME record.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/7916#pullrequestreview-1630095640>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCULOSDTXOCHYWOGO6T2CATX24KTRANCNFSM6AAAAAA43VBXEY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-17 16:07 UTC, rafsaaanrakib commented on domains/rakibahmed.json
> +        "CNAME": "rakibahmed"
how can i change the record?

2023-09-18 02:20 UTC, WilliamDavidHarrison approved these changes

2023-09-18 02:20 UTC, merged