BETA: Register phuc.is-a.dev
is-a-dev/register pull request #7962
Opened 2023-09-18 14:47 UTC by phucbm

Added `phuc.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-18 14:55 UTC, VaibhavSys requested changes

2023-09-18 14:55 UTC, VaibhavSys commented on domains/phuc.json
> +        "URL": "buiminhphuc.com"
Invalid URL

2023-09-19 14:22 UTC, phucbm commented on domains/phuc.json
> +        "URL": "buiminhphuc.com"
I changed the URL.

2023-09-19 14:39 UTC, VaibhavSys approved these changes

2023-09-19 14:39 UTC, merged