BETA: Register celestialai.is-a.dev
is-a-dev/register pull request #7984
Opened 2023-09-19 10:38 UTC by Luongzz

Added `celestialai.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-22 01:46 UTC, DEV-DIBSTER submitted a review, later dismissed

2023-09-23 03:32 UTC, WilliamDavidHarrison requested changes
We don't support TXT verification.

2023-09-24 01:35 UTC, WilliamDavidHarrison requested changes

2023-09-24 01:35 UTC, WilliamDavidHarrison commented on domains/celestialai.json
> +        "TXT": "replit-verify=06aa0b03-94af-4382-9f9d-8bcdaf765152"
We do not support TXT verification

2023-09-24 11:19 UTC, closed without merging