BETA: Register mirozr.is-a.dev
is-a-dev/register pull request #8006
Opened 2023-09-20 09:28 UTC by Miroslavchen

Added `mirozr.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-20 12:10 UTC, DEV-DIBSTER requested changes

2023-09-20 12:10 UTC, DEV-DIBSTER commented on domains/mirozr.json
> +        "CNAME": "miroslavchen.github.io"
404 CNAME record.

2023-09-23 03:16 UTC, WilliamDavidHarrison requested changes

2023-09-23 03:16 UTC, WilliamDavidHarrison commented on domains/mirozr.json
> +        "CNAME": "miroslavchen.github.io"
Please explain what your website does and please add more content.

2023-09-30 23:16 UTC, closed without merging