BETA: Register lcded.is-a.dev
is-a-dev/register pull request #8028
Opened 2023-09-21 02:11 UTC by PHYT90DitYT

Added `lcded.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-21 14:18 UTC, VaibhavSys requested changes

2023-09-21 14:18 UTC, VaibhavSys commented on domains/mcio.json
Invalid CNAME

2023-10-08 01:01 UTC, DEV-DIBSTER requested changes

2023-10-08 01:01 UTC, DEV-DIBSTER commented on domains/mcio.json
> +        "CNAME": ""[{"type":"CNAME","value":"i-think-i.lol","allowMultiple":false}]""
No changes seen, CNAME still is invalid.

2023-10-12 23:53 UTC, closed without merging