BETA: Register anshp.is-a.dev
is-a-dev/register pull request #8085
Opened 2023-09-22 17:38 UTC by Ansh-cloud11

Added `anshp.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-23 03:29 UTC, DEV-DIBSTER requested changes

2023-09-23 03:29 UTC, DEV-DIBSTER commented on domains/anshp.json
> +        "TXT": "google-site-verification=w7acqghnujqfmv7yuwhh8p6vqs0xcv693j55nsghn_w"
This TXT record doesn't do anything as it's not with any other records.

2023-09-23 03:29 UTC, DEV-DIBSTER commented on domains/harsheyssyrup.json
> +        "CNAME": "harsheyssyrup.github.io"
404 GitHub page. Please display content.

2023-09-30 06:40 UTC, WilliamDavidHarrison requested changes

2023-09-30 06:40 UTC, WilliamDavidHarrison commented on domains/anshp.json
> +        "CNAME": "gv-rrogb46mfdmtcr.dv.googlehosted.com"
We do not support domain verification.

2023-10-08 01:08 UTC, closed without merging