BETA: Register nassro.is-a.dev
is-a-dev/register pull request #8096
Opened 2023-09-23 00:46 UTC by nassro199

Added `nassro.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-23 03:20 UTC, DEV-DIBSTER requested changes, later dismissed

2023-09-23 03:20 UTC, DEV-DIBSTER commented on domains/nassro.json
> +        "CNAME": "nassro"
Invalid CNAME record.

2023-09-23 12:53 UTC, nassro199 commented on domains/nassro.json
> +        "CNAME": "nassro"
> Invalid CNAME record.

i edit it sorry i was a typo

2023-09-23 18:25 UTC, nassro199 reviewed
i fixed the cname sorry for the mistake

2023-09-24 01:34 UTC, WilliamDavidHarrison requested changes
Please add content to your website.

2023-09-24 20:20 UTC, nassro199 reviewed
changed the cname

2023-09-25 06:26 UTC, WilliamDavidHarrison approved these changes

2023-09-25 06:26 UTC, merged