Register satvikg7.is-a.dev
is-a-dev/register pull request #8135
Opened 2023-09-23 13:31 UTC by SatvikG7

## Website Link/Preview
<a href="https://satvikg7-is-a-dev.netlify.app">satvikg7-is-a-dev.netlify.app</a>

2023-09-23 16:21 UTC, DEV-DIBSTER requested changes, later dismissed

2023-09-23 16:21 UTC, DEV-DIBSTER commented on domains/satvikg7.json
> +        "CNAME": "satvikg7-is-a-dev.netlify.app"
We do not support netlify.

2023-09-24 09:48 UTC, SatvikG7 commented on domains/satvikg7.json
> +        "CNAME": "satvikg7-is-a-dev.netlify.app"
I have made the changes

2023-09-25 06:24 UTC, WilliamDavidHarrison approved these changes

2023-09-25 06:25 UTC, merged