Added ImproveMX configs
is-a-dev/register pull request #8137
Opened 2023-09-23 14:10 UTC by JadeBetty

2023-09-23 16:22 UTC, DEV-DIBSTER requested changes, later dismissed

2023-09-23 16:22 UTC, DEV-DIBSTER commented on domains/jadebetty.json
> +        "MX": ["mx1.improvmx.com.", "mx2.improvmx.com."],
Cannot have CNAME with MX records.

2023-09-23 23:32 UTC, WilliamDavidHarrison requested changes

2023-09-23 23:32 UTC, WilliamDavidHarrison commented on domains/jadebetty.json
> +        "MX": ["mx1.improvmx.com.", "mx2.improvmx.com."],
```suggestion
        "MX": ["mx1.improvmx.com", "mx2.improvmx.com"],
```

2023-09-24 03:38 UTC, JadeBetty commented on domains/jadebetty.json
> +        "MX": ["mx1.improvmx.com.", "mx2.improvmx.com."],
what should i do then?

2023-09-24 05:44 UTC, WilliamDavidHarrison approved these changes

2023-09-24 05:44 UTC, merged