BETA: Register radsteve.is-a.dev
is-a-dev/register pull request #8213
Opened 2023-09-25 04:49 UTC by radstevee

Added `radsteve.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-09-25 06:28 UTC, WilliamDavidHarrison requested changes
I cannot reach your website.

2023-09-25 08:36 UTC, sahmed011 commented
your servers ports rad
L

2023-09-25 14:36 UTC, radstevee commented
> I cannot reach your website.

Ah, didn't know you already had to set up a webserver. Set up a basic homer page with traefik routed to `radsteve.is-a.dev`, so hopefully that should work now.

2023-10-01 02:57 UTC, WilliamDavidHarrison approved these changes

2023-10-01 02:57 UTC, merged