BETA: Register ja_3.is-a.dev
is-a-dev/register pull request #8368
Opened 2023-10-01 09:56 UTC by Ja3mamtora

Added `ja_3.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-10-01 09:59 UTC, Ja3mamtora commented
@WilliamDavidHarrison Please can you review this

2023-10-06 01:52 UTC, DEV-DIBSTER requested changes

2023-10-06 01:52 UTC, DEV-DIBSTER commented on domains/ja_3.json
Invalid file name, sub domains cannot contain _.

2023-10-06 02:04 UTC, Ja3mamtora commented
@DEV-DIBSTER I have removed for ja_3 and added for Ja3mamtora can you please review it

2023-10-08 01:35 UTC, DEV-DIBSTER requested changes

2023-10-08 01:35 UTC, DEV-DIBSTER commented on domains/ja3mamtora.json
> +        "CNAME": "ja3mamtora.github.io"
CNAME returns 404 record.

2023-10-08 05:34 UTC, Ja3mamtora reviewed
Check it now

2023-10-08 05:34 UTC, Ja3mamtora commented on domains/ja3mamtora.json
> +        "CNAME": "ja3mamtora.github.io"
check it now

2023-10-08 16:46 UTC, DEV-DIBSTER requested changes

2023-10-08 16:46 UTC, DEV-DIBSTER commented on domains/ja3mamtora.json
> +        "CNAME": "ja3mamtora.github.io/Resume-Portfolio/"
CNAME cannot contain /.

2023-10-17 10:46 UTC, closed without merging