BETA: Register avversion.is-a.dev
is-a-dev/register pull request #8393
Opened 2023-10-02 08:40 UTC by AVVERSION

Added `avversion.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-10-02 23:42 UTC, DEV-DIBSTER requested changes

2023-10-02 23:42 UTC, DEV-DIBSTER commented on domains/avversion.json
> +        "CNAME": "avversion.github.io"
Redirect loop.

2023-10-03 10:19 UTC, AVVERSION commented on domains/avversion.json
> +        "CNAME": "avversion.github.io"
Fixed the Redirect loop!

2023-10-08 01:34 UTC, DEV-DIBSTER approved these changes

2023-10-08 01:35 UTC, merged