BETA: Register chiso.is-a.dev
is-a-dev/register pull request #8416
Opened 2023-10-03 05:20 UTC by raeeceip

Added `chiso.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-10-03 12:46 UTC, DEV-DIBSTER requested changes

2023-10-03 12:46 UTC, DEV-DIBSTER commented on domains/chiso.json
> +        "CNAME": "idk"
Invalid CNAME record.

2023-10-08 01:36 UTC, DEV-DIBSTER requested changes

2023-10-08 01:36 UTC, DEV-DIBSTER commented on domains/chiso.json
> +        "CNAME": "chiso.is-a-dev"
CNAME is just loop of requested domain.

2023-10-12 02:43 UTC, DEV-DIBSTER requested changes

2023-10-12 02:43 UTC, DEV-DIBSTER commented on domains/chiso.json
> +        "CNAME": "chiso.is-a.dev"
CNAME is just a loop to domain being requested.

2023-10-12 02:45 UTC, raeeceip commented
What does this mean?

On Wed, Oct 11, 2023 at 10:43 PM DIBSTER ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In domains/chiso.json
> <https://github.com/is-a-dev/register/pull/8416#discussion_r1355980619>:
>
> > @@ -0,0 +1,9 @@
> +{
> +    "owner": {
> +        "username": "raeeceip",
> +        "email": ***@***.***"
> +    },
> +    "record": {
> +        "CNAME": "chiso.is-a.dev"
>
> CNAME is just a loop to domain being requested.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/is-a-dev/register/pull/8416#pullrequestreview-1672927870>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXNBWQ63JPXDWZBDWNZV4OLX65KODANCNFSM6AAAAAA5QNEVMI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-22 15:38 UTC, closed without merging