Create xmdb.json
is-a-dev/register pull request #847
Opened 2021-06-10 12:41 UTC by xMdb

2021-06-10 17:33 UTC, iop3 requested changes
add your email

2021-06-10 21:35 UTC, xMdb commented
> add your email

But the docs say Twitter is just fine? I don't rlly want to share my email

2021-06-10 21:50 UTC, TheBotlyNoob approved these changes
> > add your email
> 
> But the docs say Twitter is just fine? I don't rlly want to share my email

An email is not required.

2021-06-11 02:00 UTC, hackermondev approved these changes

2021-06-11 02:01 UTC, merged