BETA: Register xchillds.is-a.dev
is-a-dev/register pull request #8523
Opened 2023-10-08 00:49 UTC by XChillDS

Added `xchillds.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-10-08 01:13 UTC, DEV-DIBSTER requested changes

2023-10-08 01:13 UTC, DEV-DIBSTER commented on domains/xchillds.json
> +        "CNAME": "xchillds.github.io"
Redirect loop.

2023-10-08 16:47 UTC, DEV-DIBSTER commented
@XChillDS The CNAME still redirects loop, fix this to get this merged.

2023-10-08 22:59 UTC, XChillDS commented
> @XChillDS The CNAME still redirects loop, fix this to get this merged.

what redirect loop, I don't understand 🥲

2023-10-09 00:47 UTC, DEV-DIBSTER commented
> > @XChillDS The CNAME still redirects loop, fix this to get this merged.
> 
> what redirect loop, I don't understand 🥲

Go the the value you gave of xchillds.github.io. It then redirects to xchillds.is-a.dev, which is what you're trying to register. xchillds.is-a.dev with the CNAME you provide would go back to the GitHub. Endless loop cycle. Nothing is being displayed.

2023-10-09 01:24 UTC, XChillDS commented
saya sudah melakukan nya

2023-10-09 01:25 UTC, XChillDS commented
> > > @XChillDS The CNAME still redirects loop, fix this to get this merged.
> > 
> > 
> > what redirect loop, I don't understand 🥲
> 
> Go the the value you gave of xchillds.github.io. It then redirects to xchillds.is-a.dev, which is what you're trying to register. xchillds.is-a.dev with the CNAME you provide would go back to the GitHub. Endless loop cycle. Nothing is being displayed.

I Will do it

2023-10-09 04:44 UTC, closed without merging