Create adigen.json
is-a-dev/register pull request #854
Opened 2021-06-12 16:34 UTC by mradigen

Thanks a lot for such a service! I currently don't use twitter, I hope my Discord tag shall suffice.

2021-06-12 17:21 UTC, hackermondev requested changes, later dismissed
We don't support discord tag, sorry about that. Do you have an email you can put?

2021-06-12 18:07 UTC, mradigen commented
I would prefer to refrain from including an email, but looks like that's the only option.
I'm not sure how can I edit my pull request, do I just edit the file and commit it on my fork? I hope that would incorprate the neccesary changes in this pull request. Sorry, I'm new to git and Github. :D

2021-06-14 12:03 UTC, TheBotlyNoob approved these changes

2021-06-14 12:13 UTC, mradigen commented
Thanks for taking a look and approving!

2021-06-14 14:47 UTC, hackermondev approved these changes

2021-06-14 14:47 UTC, merged