BETA: Register mackrz.is-a.dev
is-a-dev/register pull request #8735
Opened 2023-10-16 08:27 UTC by mackrz

Added `mackrz.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-10-16 11:48 UTC, DEV-DIBSTER requested changes

2023-10-16 11:48 UTC, DEV-DIBSTER commented on domains/mackrz.json
> +        "CNAME": "mackrz.github.io"
404 CNAME record.

2023-10-17 08:07 UTC, mackrz commented
I removed the domain that i requested now and modified first one in terms of GH Pages usage and validation

2023-10-18 21:20 UTC, DEV-DIBSTER approved these changes

2023-10-18 21:20 UTC, merged