Removable Application
is-a-dev/register pull request #8824
Opened 2023-10-19 16:37 UTC by dimaaac

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

I want to remove my domain file, thank you.

2023-10-19 16:37 UTC, dimaaac commented
I would like yo remove my domain file, thank you.

2023-10-19 17:03 UTC, oyepriyansh requested changes
You can simply delete the JSON file instead of keeping an empty JSON file.

2023-10-19 19:02 UTC, dimaaac commented
omg im dumb ok sorry 😁😁😁

2023-10-20 00:02 UTC, WilliamDavidHarrison approved these changes

2023-10-20 00:07 UTC, merged