Register 2 domains
is-a-dev/register pull request #8831
Opened 2023-10-19 20:54 UTC by leon332157

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X ] The file is in the `domains` folder and is in the JSON format.
- [X ] You have completed your website. 
- [ X] The website is reachable.  
- [ X] You're not using Vercel or Netlify.  
- [ X] The CNAME record doesn't contain `https://` or `/`.  
- [ X] There is sufficient information at the `owner` field.  

## Website Link/Preview

My GitHub pages isn't done yet, but I would like to register for the is-dev domain beforehand.

2023-10-20 04:32 UTC, oyepriyansh requested changes

2023-10-20 04:32 UTC, oyepriyansh commented on domains/leon3321.json
> +        "CNAME": "leon332157.is-a.dev"
invalid CNAME record

2023-10-22 15:40 UTC, DEV-DIBSTER requested changes

2023-10-22 15:40 UTC, DEV-DIBSTER commented on domains/leon332157.json
> +        "CNAME":"leon332157.github.io"
404 GitHub page.

2023-10-24 20:38 UTC, leon332157 commented on domains/leon332157.json
> +        "CNAME":"leon332157.github.io"
Fixed now!

2023-11-01 04:36 UTC, closed without merging