lykcloud.json
is-a-dev/register pull request #8834
Opened 2023-10-20 00:18 UTC by YashRawat911

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You have completed your website. 
- [x] The website is reachable.  
- [x] You're not using Vercel or Netlify.  
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

lykcloud.zc.al

2023-10-20 04:35 UTC, oyepriyansh approved these changes
LGTM

2023-10-20 11:19 UTC, YashRawat911 reviewed
Ok

2023-10-20 11:22 UTC, YashRawat911 commented
Update

2023-10-20 11:22 UTC, YashRawat911 reviewed
Update

2023-10-21 03:56 UTC, oyepriyansh requested changes

2023-10-21 03:56 UTC, oyepriyansh commented on domains/lykcloud.json
> +        "username": "LykCloud",
The username must be the same as your GitHub username.

2023-10-27 09:03 UTC, WilliamDavidHarrison requested changes

2023-10-27 09:03 UTC, WilliamDavidHarrison commented on domains/lykcloud.json
> +        "TXT": "replit-verify=f5023159-9ff2-4823-9493-d8eae763f6dd"
We do not support TXT verification.

2023-10-27 09:03 UTC, WilliamDavidHarrison commented on domains/lykhost.json
> +        "CNAME": "lykcloud.zc.al"
We do not allow free hosting services to use our subdomains.

2023-11-04 04:54 UTC, closed without merging