BETA: Register rinat.is-a.dev
is-a-dev/register pull request #8855
Opened 2023-10-20 19:41 UTC by notrinat

Added `rinat.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-10-20 20:31 UTC, DEV-DIBSTER requested changes

2023-10-20 20:31 UTC, DEV-DIBSTER commented on domains/rinat.json
> +        "CNAME": "notrinat.github.io"
404 GitHub page.

2023-10-20 21:16 UTC, notrinat commented on domains/rinat.json
> +        "CNAME": "notrinat.github.io"
> 404 GitHub page.

test now

2023-10-27 09:01 UTC, WilliamDavidHarrison commented on domains/rinat.json
> +        "CNAME": "notrinat.github.io"
@notrinat Still not accessible.

2023-10-27 09:01 UTC, closed without merging