Register csur.is-a.dev
is-a-dev/register pull request #8856
Opened 2023-10-21 00:12 UTC by ocoke

Added `csur.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

2023-10-21 00:13 UTC, ocoke commented
CranSurvey is an open-source tool for collecting survey data, it is written in Vue & TypeScript, and `csur` is the short of it.

The page file of the site is in [ocoke/csur-site](https://github.com/ocoke/csur-site), the main code of CranSurvey is in [ocoke/CranSurvey](https://github.com/ocoke/CranSurvey).

Thank you.

2023-10-21 03:58 UTC, oyepriyansh reviewed
is-a-dev doesn't support vercel

2023-10-21 05:57 UTC, ocoke commented
well, let me change the record to netlify later, thx.

2023-10-21 06:22 UTC, oyepriyansh commented
They don't support both Vercel and Netlify due to TXT verification. Instead, you can use Cloudflare Pages.

2023-10-26 03:29 UTC, DEV-DIBSTER requested changes

2023-10-26 03:29 UTC, DEV-DIBSTER commented on domains/csur.json
> +        "CNAME": "csur-site.netlify.app"
We do not support netlify.

2023-10-26 19:36 UTC, closed without merging