Create gokul6350.github.io.json
is-a-dev/register pull request #9017
Opened 2023-10-28 15:41 UTC by gokul6350

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [ ] The file is in the `domains` folder and is in the JSON format.
- [ ] You have completed your website. 
- [ ] The website is reachable.  
- [ ] You're not using Vercel or Netlify.  
- [ ] The CNAME record doesn't contain `https://` or `/`.  
- [ ] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-10-28 15:41 UTC, gokul6350 commented
i guss it will work

2023-10-28 15:42 UTC, gokul6350 commented
wdwd

2023-10-28 20:59 UTC, DEV-DIBSTER requested changes

2023-10-28 20:59 UTC, DEV-DIBSTER commented on domains/gokulbarath.json
> +        "CNAME": "gokul6350.github.io"
Little content provided.

2023-11-04 04:54 UTC, closed without merging

2024-02-25 18:15 UTC, gokul6350 commented on domains/gokulbarath.json
> +        "CNAME": "gokul6350.github.io"
what content u need more ?