BETA: Register dave9123.is-a.dev
is-a-dev/register pull request #9255
Opened 2023-11-08 12:27 UTC by dave9123

Added `dave9123.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-11-12 17:07 UTC, DEV-DIBSTER requested changes

2023-11-12 17:07 UTC, DEV-DIBSTER commented on domains/dave9123.json
> +        "CNAME": "dave9123-isadev.netlify.app"
We do not support netlify.

2023-11-12 22:33 UTC, dave9123 commented
What should I use then?

2023-11-12 22:50 UTC, dave9123 commented
I think I messed up

2023-11-12 23:02 UTC, dave9123 commented
![Screenshot_2023-11-13-06-01-46-89_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/is-a-dev/register/assets/91056752/40ad1ca5-142b-415e-9010-27fa4314a625)

Can I use this?

2023-11-12 23:37 UTC, DEV-DIBSTER requested changes

2023-11-12 23:37 UTC, DEV-DIBSTER commented on domains/dave9123.json
> +        "CNAME": "dave9123.github.io/dave9123_page"
Invalid CNAME, cannot store / within CNAME.

2023-11-13 21:25 UTC, DEV-DIBSTER requested changes

2023-11-13 21:25 UTC, DEV-DIBSTER commented on domains/dave9123.json
> +        "CNAME": "dave9123.github.io"
CNAME still redirects to this domain, which would redirect back to your GitHub page, creating a loop.

2023-11-13 22:43 UTC, dave9123 commented
![Screenshot_2023-11-14-05-42-53-36_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/is-a-dev/register/assets/91056752/09dd6039-77a7-41de-95e7-218a5bd96135)

2023-11-14 02:23 UTC, DEV-DIBSTER commented
Yes, but your site content doesn't exist. All it's doing is redirecting.

2023-11-14 02:23 UTC, DEV-DIBSTER commented
Infact I don't see your site repository, are you sure you made that public?

2023-11-14 07:55 UTC, dave9123 commented
Because it's waiting for CNAME record
________________________________
From: DIBSTER ***@***.***>
Sent: Tuesday, November 14, 2023 9:23:15 AM
To: is-a-dev/register ***@***.***>
Cc: Dave ***@***.***>; Author ***@***.***>
Subject: Re: [is-a-dev/register] BETA: Register dave9123.is-a.dev (PR #9255)


Yes, but your site content doesn't exist. All it's doing is redirecting.

—
Reply to this email directly, view it on GitHub<https://github.com/is-a-dev/register/pull/9255#issuecomment-1809439982>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVWWU4DMNZ2W3LT3B3ZSWNTYELIZHAVCNFSM6AAAAAA7CZM2HGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBZGQZTSOJYGI>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-11-14 07:55 UTC, dave9123 commented
I have GitHub Pro, it's made private
________________________________
From: DIBSTER ***@***.***>
Sent: Tuesday, November 14, 2023 9:23:48 AM
To: is-a-dev/register ***@***.***>
Cc: Dave ***@***.***>; Author ***@***.***>
Subject: Re: [is-a-dev/register] BETA: Register dave9123.is-a.dev (PR #9255)


Infact I don't see your site repository, are you sure you made that public?

—
Reply to this email directly, view it on GitHub<https://github.com/is-a-dev/register/pull/9255#issuecomment-1809440335>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVWWU4CSHROU5LCLOZ2DLYLYELI3JAVCNFSM6AAAAAA7CZM2HGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBZGQ2DAMZTGU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-11-14 07:56 UTC, dave9123 commented
![Screenshot_2023-11-14-14-55-54-58_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/is-a-dev/register/assets/91056752/da2aaa63-6780-47a5-8dbd-c7674b5b24ce)

:)

2023-11-14 22:38 UTC, DEV-DIBSTER approved these changes

2023-11-14 22:38 UTC, merged

2023-11-14 22:45 UTC, dave9123 commented
Thanks so much![Screenshot_2023-11-15-05-45-20-91_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/is-a-dev/register/assets/91056752/96a9518e-b8c0-4e48-8a20-163bf59ab807)