Update MX and TXT records
is-a-dev/register pull request #9325
Opened 2023-11-12 16:36 UTC by toastyyyxd

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] You have completed your website. 
- [X] The website is reachable.  
- [X] You're not using Vercel or Netlify.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.  

## Website Link/Preview
https://toasty.is-a.dev

2023-11-12 21:22 UTC, DEV-DIBSTER requested changes

2023-11-12 21:22 UTC, DEV-DIBSTER commented on domains/toasty.json
> +        "CNAME": "toasty.pages.dev",
CNAME record cannot be used in conjunction with other records.

2023-11-13 14:41 UTC, toastyyyxd commented
Moved MX and TXT records to mail.toasty.json

2023-11-13 21:33 UTC, DEV-DIBSTER approved these changes

2023-11-13 21:33 UTC, merged