BETA: Register vo.is-a.dev
is-a-dev/register pull request #9349
Opened 2023-11-13 12:35 UTC by YoruAkio

Added `vo.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-11-13 21:34 UTC, DEV-DIBSTER requested changes

2023-11-13 21:34 UTC, DEV-DIBSTER commented on domains/vo.json
> +        "CNAME": "voids.pages.dev"
Unable to access CNAME.

2023-11-13 21:34 UTC, DEV-DIBSTER commented on domains/v0.json
> +        "CNAME": "vo-kio.pages.dev"
Little content displayed.

2023-11-14 12:43 UTC, YoruAkio reviewed
Please review this changes!

2023-11-14 17:19 UTC, YoruAkio commented
> # 🔍 ReviewMate Analysis
> File: [domains/v0.json](https://github.com/is-a-dev/register/blob/7ef10705002d44696100e15c45688f751105d164/domains%2Fv0.json) Content URL: http://vo-kio.pages.dev Description: N/A Repository: N/A
> 
> ## 📸 Screenshot
> ![Screenshot of domains/v0.json](https://camo.githubusercontent.com/741f885783d3d42154a32ca61aabc2246ee331823812fd91767e44a9540f1e1e/68747470733a2f2f692e6962622e636f2f514e635a3678682f3938373838613362313539382e706e67)

**Fix**: Added more content to displayed!

2023-11-14 22:33 UTC, DEV-DIBSTER approved these changes

2023-11-14 22:33 UTC, merged