BETA: Register loganpaxton.is-a.dev
is-a-dev/register pull request #9457
Opened 2023-11-18 16:57 UTC by LoganPaxton

Added `loganpaxton.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-11-22 17:25 UTC, DEV-DIBSTER requested changes

2023-11-22 17:25 UTC, DEV-DIBSTER commented on CNAME
This file should be deleted.

2023-11-22 21:19 UTC, LoganPaxton commented on CNAME
fixed.

2023-11-22 23:39 UTC, DEV-DIBSTER commented on CNAME
Has not been fixed, as the file is still here in the PR.

2023-11-24 02:10 UTC, LoganPaxton commented on CNAME
Sorry, I didn't hit the "Commit Changes..." button

2023-11-24 04:00 UTC, DEV-DIBSTER approved these changes

2023-11-24 04:00 UTC, merged