added subdomains
is-a-dev/register pull request #946
Opened 2021-07-18 09:40 UTC by LellisV2

2021-07-18 12:02 UTC, TheBotlyNoob commented
You cannot have `panel.lellis.json`, sorry.

2021-07-18 13:12 UTC, TheBotlyNoob requested changes

2021-07-18 13:12 UTC, TheBotlyNoob commented on domains/panel.lellis.json
> +{
You cannot have this filename

2021-07-20 16:46 UTC, TheBotlyNoob approved these changes

2021-07-20 19:20 UTC, hackermondev approved these changes

2021-07-20 19:20 UTC, merged