Yep, Another commit. It didn't work properly
is-a-dev/register pull request #9570
Opened 2023-11-23 19:43 UTC by MrDaPoyo

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [X] The file is in the `domains` folder and is in the JSON format.
- [X] You have completed your website. 
- [X] The website is reachable.  
- [X] You're not using Vercel or Netlify.  
- [X] The CNAME record doesn't contain `https://` or `/`.  
- [X] There is sufficient information at the `owner` field.  

## Website Link/Preview

2023-11-23 21:31 UTC, mtgsquad commented
@MrDaPoyo would like to ask you to temporarily delete your domain since the site isn't ready yet.

2023-11-23 22:05 UTC, DEV-DIBSTER requested changes

2023-11-23 22:05 UTC, DEV-DIBSTER commented on domains/poyo.json
> +        "CNAME": "mrdapoyo.github.io"
Invalid CNAME record. This just redirects back to this domain.

2023-11-24 11:10 UTC, MrDaPoyo commented
How can I remove it?

2023-11-24 11:10 UTC, closed without merging