Create sharath.json
is-a-dev/register pull request #97
Opened 2020-10-09 05:31 UTC by thesct22

2020-10-09 14:52 UTC, phenax requested changes

2020-10-09 14:52 UTC, phenax commented on domains/sharath.json
> +
Please add the required information to register the subdomain

2020-10-09 17:33 UTC, thesct22 reviewed
Added necessary changes hopefully

2020-10-09 17:40 UTC, thesct22 reviewed
CNAME changed

2020-10-12 12:23 UTC, phenax requested changes

2020-10-12 12:23 UTC, phenax commented on domains/sharath.json
> +    "CNAME":"http://34.67.228.107.xip.io"
This is not a valid cname.

Maybe this is what you wanted to do?

```suggestion
    "CNAME":"34.67.228.107.xip.io"
```

2020-10-12 18:52 UTC, phenax requested changes

2020-10-12 18:52 UTC, phenax commented on domains/sharath.json
> +    "CNAME": "https://thesct22.github.io/",
```suggestion
    "CNAME": "thesct22.github.io",
```

2020-10-12 18:55 UTC, phenax approved these changes

2020-10-12 18:55 UTC, merged