BETA: Register ggio.is-a.dev
is-a-dev/register pull request #9717
Opened 2023-11-29 17:09 UTC by dusiadudusia

Added `ggio.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-11-30 02:13 UTC, DEV-DIBSTER requested changes

2023-11-30 02:13 UTC, DEV-DIBSTER commented on domains/gg.io.json
> +        "Hosting By Is-a.dev": "gg.io.is-a.dev"
Invalid record type.

2023-11-30 03:33 UTC, dusiadudusia commented on domains/gg.io.json
> +        "Hosting By Is-a.dev": "gg.io.is-a.dev"
Please remove gg.io.json

2023-12-01 00:44 UTC, DEV-DIBSTER approved these changes

2023-12-01 00:44 UTC, merged