BETA: Register bitter_130.is-a.dev
is-a-dev/register pull request #9785
Opened 2023-12-02 14:57 UTC by Bitter130

Added `bitter_130.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-12-02 16:46 UTC, DEV-DIBSTER requested changes

2023-12-02 16:46 UTC, DEV-DIBSTER commented on domains/bitter_130.json
Invalid domain name cannot contain _

2023-12-02 18:33 UTC, Bitter130 commented on domains/bitter_130.json
Great question, how can I edit it to just be "bitter130" or "bitter-130", I don't usually work with Github.

2023-12-03 03:27 UTC, DEV-DIBSTER submitted a review, later dismissed

2023-12-03 03:28 UTC, DEV-DIBSTER approved these changes

2023-12-03 03:28 UTC, merged