BETA: Register shayan.is-a.dev
is-a-dev/register pull request #9835
Opened 2023-12-04 00:15 UTC by Lightshayan

Added `shayan.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-12-10 03:51 UTC, WilliamDavidHarrison approved these changes

2023-12-10 03:52 UTC, WilliamDavidHarrison requested changes

2023-12-10 03:52 UTC, WilliamDavidHarrison commented on domains/codershayan.is-a.dev.json
This domain already exists, you cannot register it.

2023-12-19 22:38 UTC, Lightshayan commented on domains/codershayan.is-a.dev.json
I have it, but I want to link it to my Gituhb Pages

2023-12-20 23:29 UTC, closed without merging