Create astra.json
is-a-dev/register pull request #9847
Opened 2023-12-04 13:13 UTC by LilyMusic

domain

2023-12-04 13:29 UTC, VaibhavSys requested changes
Ports cannot be added in A or AAAA records and AAAA are for IPv76 not IPv4

2023-12-04 13:29 UTC, VaibhavSys commented on domains/astra.json
> +        "AAAA": ["167.86.83.49:6210"]
```suggestion
        "A": ["167.86.83.49"]
```

2023-12-10 17:01 UTC, DEV-DIBSTER requested changes

2023-12-10 17:01 UTC, DEV-DIBSTER commented on domains/astra.json
> +        "CNAME": ["proxy.private.danbot.host"]
CNAME should be only a string, no array.

2023-12-20 23:29 UTC, closed without merging