BETA: Register cfp.is-a.dev
is-a-dev/register pull request #9917
Opened 2023-12-07 18:29 UTC by cfpwastaken

Added `cfp.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-12-07 18:32 UTC, cfpwastaken commented
I changed the files manually, cos the dashboard didnt give me the option to customize the owner object.

The screenshots are blank because my nginx automatically redirects to cfp.is-a.dev.

2023-12-10 04:00 UTC, DEV-DIBSTER requested changes

2023-12-10 04:00 UTC, DEV-DIBSTER commented on domains/cfp.json
> +        "CNAME": "cfp.gotdns.ch"
Unable to access CNAME.

2023-12-13 07:35 UTC, YouFoundAlpha requested changes
Please add your Discord username + Discord tag in the Discord info or add your Discord user id

2023-12-20 16:01 UTC, cfpwastaken commented
Added discord id

2023-12-21 02:32 UTC, DEV-DIBSTER approved these changes

2023-12-21 02:32 UTC, merged