BETA: Register jasmeetsingh.is-a.dev
is-a-dev/register pull request #9923
Opened 2023-12-08 04:51 UTC by jasmeetsinghbhatia

Added `jasmeetsingh.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-12-10 03:57 UTC, DEV-DIBSTER requested changes

2023-12-10 03:57 UTC, DEV-DIBSTER commented on domains/jasmeetsingh.json
> +        "CNAME": "jasmeetsingh"
Invalid CNAME record should be valid hostname.

2023-12-18 07:11 UTC, jasmeetsinghbhatia commented
fixing it now

2023-12-21 02:32 UTC, DEV-DIBSTER approved these changes

2023-12-21 02:33 UTC, merged