BETA: Register mostafizur+rahman.is-a.dev
is-a-dev/register pull request #9939
Opened 2023-12-09 04:34 UTC by gigwanoobstudios

Added `mostafizur+rahman.is-a.dev` using the [dashboard](https://manage.is-a.dev).

2023-12-09 04:59 UTC, gigwanoobstudios commented
Had to use "+" for email and my old domain without"+" is not showing😑
Is there any way to fix it

2023-12-09 12:21 UTC, WilliamDavidHarrison commented
> Had to use "+" for email and my old domain without"+" is not showing😑 Is there any way to fix it

That domain seems to have been deleted in the recent domain cleanup #9887

2023-12-10 16:50 UTC, DEV-DIBSTER requested changes, later dismissed

2023-12-10 16:50 UTC, DEV-DIBSTER commented on domains/mostafizur+rahman.json
Invalid domain name.

2023-12-11 16:41 UTC, gigwanoobstudios commented on domains/mostafizur+rahman.json
Changed to mostafizur-rahman.is-a.dev

2023-12-16 22:40 UTC, WilliamDavidHarrison approved these changes

2023-12-16 22:41 UTC, merged