Add MX and TXT records for didotb.is-a.dev
is-a-dev/register pull request #9966
Opened 2023-12-10 02:54 UTC by didotb

## Requirements
Unless explicitly specified otherwise by a **maintainer** or in the requirement description, your domain must pass **ALL** the indicated requirements above.

Please note that we reserve the rights not to accept any domain at our own discretion.

- [x] The file is in the `domains` folder and is in the JSON format.
- [x] You're not using Vercel or Netlify.  
- [x] There is sufficient information at the `owner` field.  

## Website Link/Preview

Website does not exist, records used for email

2023-12-10 03:42 UTC, DEV-DIBSTER approved these changes, later dismissed

2023-12-10 03:43 UTC, DEV-DIBSTER commented
Appears our validation cannot verify this. Will have the team investigate.

2023-12-10 03:52 UTC, didotb commented
in-case you need sources from where the TXT record requirement is from, the website is `https://resend.com`

2023-12-16 11:46 UTC, WilliamDavidHarrison requested changes

2023-12-16 11:46 UTC, WilliamDavidHarrison commented on domains/resend._domainkey.didotb.json
We do not support these kind of records.

2023-12-17 03:44 UTC, closed without merging